import type { AccommodationType, RouteId, ServiceId } from '@/lib/i18n/routes';
import type { TermsSectionId } from '@/lib/legal/terms';

export type FaqItem = { q: string; a: string };

export type ProductStatus = 'available' | 'roadmap';

/** Short commercial service page: hero → opportunity → do → get → cross-sell → CTA. */
export type ServicePitchContent = {
  support: string;
  concepts: string[];
  primaryCta: string;
  talkCta: string;
  opportunityTitle: string;
  opportunityBody: string;
  opportunityPoints: string[];
  doTitle: string;
  doItems: { title: string; body: string }[];
  getTitle: string;
  getItems: string[];
  crossSellBody: string;
  crossSellCta: string;
  crossSellRoute: RouteId;
  finalTitle: string;
  finalBody: string;
  diagnosisCta: string;
  finalNote: string;
};

export type VisibilityContent = {
  support: string;
  concepts: string[];
  primaryCta: string;
  talkCta: string;
  heroImage: string;
  heroAlt: string;
  searchLabel: string;
  searchQuery: string;
  searchResultName: string;
  searchResultMeta: string;
  searchCaption: string;
  journeyTitle: string;
  journeyBody: string;
  journey: { title: string; image: string }[];
  whatEyebrow: string;
  whatTitle: string;
  whatBody: string;
  whatImage: string;
  whatAlt: string;
  whatItems: { title: string; body: string }[];
  benefitsEyebrow: string;
  benefitsTitle: string;
  benefits: { title: string; body: string; image: string }[];
  compareTitle: string;
  scatteredTitle: string;
  scatteredPoints: string[];
  workedTitle: string;
  workedPoints: string[];
  ecosystemTitle: string;
  ecosystemBody: string;
  ecosystem: {
    id: 'andario-visibility' | 'andario-web' | 'andario-connect' | 'andario-booking-engine';
    name: string;
    role: string;
  }[];
  finalImage: string;
  finalAlt: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type ConnectContent = {
  support: string;
  concepts: string[];
  primaryCta: string;
  talkCta: string;
  heroImage: string;
  heroAlt: string;
  chatGuestLabel: string;
  chatGuestMessage: string;
  chatPropertyLabel: string;
  chatPropertyMessage: string;
  chatOptions: string[];
  chatCaption: string;
  opportunityTitle: string;
  opportunityBody: string;
  floatingMessages: string[];
  problems: { title: string; body: string }[];
  whatEyebrow: string;
  whatTitle: string;
  whatBody: string;
  whatImage: string;
  whatAlt: string;
  whatChecklist: string[];
  whatItems: { title: string; body: string }[];
  demoTitle: string;
  demoBody: string;
  demoSteps: {
    label: string;
    title: string;
    body: string;
    options?: string[];
    cta?: string;
    actions?: string[];
  }[];
  benefitsEyebrow: string;
  benefitsTitle: string;
  benefits: { title: string; body: string; image: string }[];
  balanceTitle: string;
  balanceBody: string;
  balanceRepetitiveTitle: string;
  balanceRepetitive: string[];
  balanceCenterTitle: string;
  balanceCenterBody: string;
  balanceHumanTitle: string;
  balanceHuman: string[];
  balanceHumanNote: string;
  bridgeTitle: string;
  bridgeBody: string;
  bridgeNote: string;
  bridge: { title: string; role: string }[];
  finalImage: string;
  finalAlt: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type ContentPage = {
  support: string;
  concepts: string[];
  primaryCta: string;
  talkCta: string;
  heroImage: string;
  heroAlt: string;
  heroCards: { label: string; image: string }[];
  journeyTitle: string;
  journeyBody: string;
  journey: { title: string; image: string }[];
  compareTitle: string;
  improvisedTitle: string;
  improvisedPoints: string[];
  improvisedImages: string[];
  polishedTitle: string;
  polishedPoints: string[];
  polishedImages: string[];
  whatTitle: string;
  whatBody: string;
  whatItems: { title: string; body: string }[];
  mosaicTitle: string;
  mosaicBody: string;
  mosaic: { label: string; image: string; alt: string; span?: 'wide' | 'tall' | 'normal' }[];
  channelsTitle: string;
  channelsBody: string;
  channels: { title: string; body: string; image: string }[];
  experienceTitle: string;
  experienceBody: string;
  experienceHighlight: string;
  experienceImage: string;
  experienceAlt: string;
  experienceMoments: { label: string; image: string }[];
  benefitsTitle: string;
  benefits: { title: string; body: string }[];
  bridgeTitle: string;
  bridgeLead: string;
  bridge: { title: string; role: string }[];
  finalImage: string;
  finalAlt: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type GrowthContent = {
  support: string;
  concepts: string[];
  primaryCta: string;
  talkCta: string;
  dashboardLabel: string;
  dashboardNav: string[];
  dashboardMetrics: { label: string; value: string; trend: string }[];
  dashboardChannelsTitle: string;
  dashboardChannels: { label: string; value: number }[];
  dashboardDevicesTitle: string;
  dashboardDevices: { label: string; value: number }[];
  loopTitle: string;
  loop: { title: string; body: string }[];
  loopNote: string;
  doTitle: string;
  doItems: { title: string; body: string }[];
  getTitle: string;
  getSupport: string;
  getItems: { title: string; body: string }[];
  editorialEyebrow: string;
  editorialTitle: string;
  editorialBody: string;
  editorialCta: string;
  editorialImage: string;
  editorialAlt: string;
  heroAtmosphere: string;
  heroAtmosphereAlt: string;
  finalImage: string;
  finalAlt: string;
  finalTitle: string;
  finalBody: string;
  diagnosisCta: string;
  finalNote: string;
};

export type SolutionsCard = {
  category: string;
  problem: string;
  body: string;
  cta: string;
};

export type SolutionsHubContent = {
  eyebrow: string;
  h1: string;
  support: string;
  assist: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  heroAlt: string;
  problemTitle: string;
  problemIntro: string;
  problems: string[];
  whereTitle: string;
  whereIntro: string;
  resultLabel: string;
  solutionLabel: string;
  whereAlt: string;
  scenarios: { title: string; summary: string; result: string; cta: string; placement: string; service: ServiceId }[];
  cardsTitle: string;
  cardsSupport: string;
  checkPrompt: string;
  checkNote: string;
  portfolioTitle: string;
  portfolioBody: string;
  unsureTitle: string;
  unsureBody: string;
  unsureCta: string;
  cards: Record<ServiceId, SolutionsCard>;
  ownTech: string;
  paceEyebrow: string;
  paceTitle: string;
  paceBody: string;
  paths: { need: string; support: string; service: ServiceId }[];
  paceCloseTitle: string;
  paceCloseBody: string;
  paceCta: string;
  trustTitle: string;
  trustSupport: string;
  pillars: { title: string; body: string }[];
  trustNoteTitle: string;
  trustNoteBody: string;
  finalTitle: string;
  finalBody: string;
  finalPrimary: string;
  finalSecondary: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type HomePageContent = {
  h1: string;
  support: string;
  trust: string;
  primaryCta: string;
  secondaryCta: string;
  forLine: string;
  heroAlt: string;
  heroBadge: string;
  checkAlt: string;
  checkNote: string;
  checkItems: { label: string; tone: 'steady' | 'attention' }[];
  knownAlt: string;
  mockProperty: string;
  mockDates: string;
  mockGuests: string;
  mockUnit: string;
  mockPrice: string;
  mockAction: string;
  mockNote: string;
  bookingAlt: string;
  bridge: string;
  bridgeBody: string;
  bridgeMark: string;
  bridgePoints: { title: string; tags: string; body: string }[];
  checkLead: string;
  situationsTitle: string;
  situations: { title: string; body: string }[];
  situationClose: string;
  situationCta: string;
  boardTitle: string;
  boardStatus: string;
  boardAreas: string;
  boardOpportunities: string;
  boardNext: string;
  opportunities: string[];
  nextSteps: string[];
  offerHeading: string;
  offerTitle: string;
  offerSupport: string;
  cards: Record<ServiceId, { role: string; title: string; body: string; cta: string; points: string[] }>;
  solutionsCta: string;
  roadmapTitle: string;
  roadmapIntro: string;
  roadmap: string[];
  knownTitle: string;
  knownBody: string[];
  audienceTitle: string;
  audiences: string[];
  audienceCta: string;
  processCta: string;
  differentiatorsTitle: string;
  differentiators: { title: string; body: string }[];
  bookingTitle: string;
  booking: string[];
  bookingCta: string;
  bookingBranches: { title: string; body: string }[];
  bookingResult: string;
  bookingNote: string;
  bookingOta: string;
  bookingPoints: string[];
  finalTitle: string;
  finalBody: string[];
  finalPrimary: string;
  finalSecondary: string;
  faqs: FaqItem[];
};

export type AccommodationsPageContent = {
  eyebrow: string;
  h1: string;
  support: string;
  complement: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  heroAlt: string;
  typesTitle: string;
  typesSupport: string;
  types: { id: string; title: string; body: string }[];
  improveTitle: string;
  improveSupport: string;
  situations: { title: string; body: string }[];
  checkLabel: string;
  checkTitle: string;
  checkSupport: string;
  checkBody: string;
  checkBoardTitle: string;
  checkStatus: string;
  checkItems: { label: string; tone: 'steady' | 'attention' }[];
  checkAreasTitle: string;
  checkAreas: string[];
  checkOpportunitiesTitle: string;
  checkOpportunities: string[];
  checkNextTitle: string;
  checkNext: string;
  checkCta: string;
  checkDisclaimer: string;
  checkMark: string;
  checkNote: string;
  solutionsTitle: string;
  solutionsSupport: string;
  solutions: { id: ServiceId; title: string; body: string }[];
  unsureTitle: string;
  unsureBody: string;
  bookingTitle: string;
  bookingBody: string;
  bookingPhrase: string;
  bookingCta: string;
  bookingNote: string;
  humanTitle: string;
  humanBody: string[];
  humanMark: string;
  humanAlt: string;
  startTitle: string;
  steps: { title: string; body: string }[];
  baruchEyebrow: string;
  baruchTitle: string;
  baruchPlace: string;
  baruch: string;
  finalTitle: string;
  finalBody: string;
  finalPrimary: string;
  finalSecondary: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type AboutViewContent = {
  eyebrow: string;
  h1: string;
  support: string;
  tags: string;
  talkCta: string;
  howCta: string;
  originTitle: string;
  originBody: string[];
  originPlace: string;
  whyTitle: string;
  whyBody: string[];
  purposeTitle: string;
  purposeBody: string;
  purposeItems: { title: string; detail: string }[];
  beliefsTitle: string;
  beliefs: { title: string; body: string }[];
  finalTitle: string;
  finalBody: string[];
  finalTalkCta: string;
  diagnosisCta: string;
  finalNote: string;
};

export type HowWeWorkPageContent = {
  eyebrow: string;
  h1: string;
  support: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  heroAlt: string;
  businessTitle: string;
  businessBody: string;
  businessAlt: string;
  methodTitle: string;
  method: { title: string; body: string }[];
  checkTitle: string;
  checkBody: string;
  checkName: string;
  checkRows: { label: string; mark: string; status: string }[];
  checkLabel: string;
  reviewTitle: string;
  questions: { title: string; body: string }[];
  receiveTitle: string;
  receive: { title: string; body: string }[];
  deliverableTitle: string;
  deliverableItems: string[];
  deliverableLabel: string;
  roadmapTitle: string;
  roadmapBody: string;
  roadmapLabel: string;
  roadmap: string[];
  approveTitle: string;
  approveBody: string;
  approveTrust: string;
  approveResultLabel: string;
  approveClose: string;
  approveSteps: { label: string; title: string; body: string; result: string; mark?: string }[];
  knownTitle: string;
  knownBody: string;
  knownAlt: string;
  principlesTitle: string;
  principles: { title: string; body: string }[];
  principlesMark: string;
  solutionsBody: string;
  solutionsCta: string;
  bookingBody: string;
  bookingCta: string;
  pioneerTitle: string;
  pioneerBody: string;
  pioneerPlace: string;
  pioneerCta: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type AndarioWebContent = {
  support: string;
  concepts: string[];
  primaryCta: string;
  talkCta: string;
  mockProperty: string;
  mockNav: string[];
  mockReserve: string;
  mockLabel: string;
  personalizeTitle: string;
  personalizeBody: string;
  personalizeItems: { title: string; body: string }[];
  personalizeImage: string;
  personalizeAlt: string;
  findTitle: string;
  findBody: string;
  findItems: { title: string; body: string; image?: string }[];
  experienceEyebrow: string;
  experienceTitle: string;
  experienceBody: string;
  experienceItems: { title: string; body: string }[];
  experienceImage: string;
  experienceAlt: string;
  bookingTitle: string;
  bookingSteps: string[];
  bookingCta: string;
  finalImage: string;
  finalAlt: string;
  finalTitle: string;
  finalBody: string;
  diagnosisCta: string;
  finalNote: string;
};

export type DigitalCheckContent = {
  support: string;
  primaryCta: string;
  talkCta: string;
  benefits: string[];
  dashboardLabel: string;
  dashboardScoreLabel: string;
  dashboardScoreNote: string;
  dashboardAreas: { label: string; value: number }[];
  heroAtmosphere: string;
  heroAtmosphereAlt: string;
  problemTitle: string;
  problemBody: string;
  problemSteps: { title: string; body: string; image: string }[];
  whatEyebrow: string;
  whatTitle: string;
  whatBody: string;
  whatImage: string;
  whatAlt: string;
  lenses: { title: string; body: string }[];
  whatNote: string;
  receiveEyebrow: string;
  receiveTitle: string;
  receiveBody: string;
  receive: { title: string; body: string }[];
  resultTitle: string;
  resultBody: string;
  resultFlow: string[];
  actionTitle: string;
  actionBody: string;
  actionFlow: string[];
  finalImage: string;
  finalAlt: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type BookingEngineContent = {
  support: string;
  primaryCta: string;
  talkCta: string;
  capabilities: string[];
  heroImage: string;
  heroAlt: string;
  webTitle: string;
  webBody: string;
  presentCard: { title: string; role: string; points: string[] };
  reserveCard: { title: string; role: string; points: string[] };
  guestTitle: string;
  guestBody: string;
  guestSteps: string[];
  guestImage: string;
  guestAlt: string;
  channelsEyebrow: string;
  channelsTitle: string;
  channelsBody: string;
  channels: { id: 'web' | 'facebook' | 'instagram' | 'tiktok' | 'whatsapp' | 'google' | 'other'; label: string }[];
  channelDestination: string;
  channelOutcomes: string[];
  compareTitle: string;
  compareBody: string;
  beforeTitle: string;
  beforePoints: string[];
  afterTitle: string;
  afterPoints: string[];
  adminTitle: string;
  adminBody: string;
  adminImage: string;
  adminAlt: string;
  conceptualNote: string;
  adminPoints: { title: string; body: string }[];
  analyticsTitle: string;
  analyticsBody: string;
  analyticsImage: string;
  analyticsAlt: string;
  analyticsPoints: string[];
  typesTitle: string;
  typesBody: string;
  types: { name: string; image: string; alt: string }[];
  ecosystemTitle: string;
  ecosystemBody: string;
  ecosystem: { id: 'andario-web' | 'andario-visibility' | 'andario-booking-engine' | 'andario-connect' | 'andario-growth'; label: string }[];
  processTitle: string;
  processBody: string;
  processSteps: string[];
  finalTitle: string;
  finalBody: string;
  finalCta: string;
  finalImage: string;
  finalAlt: string;
};

export type ServiceContent = {
  name: string;
  subtitle: string;
  summary: string;
  cardCta: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  problemTitle: string;
  problem: string;
  solutionTitle: string;
  solution: string;
  includedTitle: string;
  included: string[];
  howTitle: string;
  steps: { title: string; body: string }[];
  ecosystem: string;
  note?: string;
  futureTitle?: string;
  future: string[];
  faqs: FaqItem[];
  ctaTitle: string;
  ctaLabel: string;
};

export type TermsBlock =
  | { kind: 'p'; text: string }
  | { kind: 'list'; items: string[] }
  | { kind: 'h3'; text: string }
  | { kind: 'privacy' }
  | { kind: 'channels' }
  | { kind: 'identity' };

export type TermsViewContent = {
  h1: string;
  lead: string;
  note: string;
  updatedLabel: string;
  tocLabel: string;
  sections: { id: TermsSectionId; title: string; blocks: TermsBlock[] }[];
  closerTitle: string;
  closerBody: string;
};

export type Dictionary = {
  meta: {
    htmlLang: string;
    pages: Record<RouteId, { title: string; description: string }>;
  };
  chrome: {
    skip: string;
    primaryCta: string;
    secondaryCta: string;
    ctaSteps: readonly string[];
    ctaNote: string;
    menu: string;
    close: string;
    language: string;
    footerTagline: string;
    footerDescription: string;
    footerLine: string;
    footerCtaTitle: string;
    footerCtaBody: string;
    footerGroupDiagnosis: string;
    footerGroupPresence: string;
    footerGroupTechnology: string;
    footerTalkCta: string;
    footerWhatsappLabel: string;
    solutionsTitle: string;
    companyTitle: string;
    legalTitle: string;
    contactTitle: string;
    rights: string;
    map: string;
    analyticsTitle: string;
    analyticsBody: string;
    analyticsAccept: string;
    analyticsReject: string;
  };
  nav: Record<
    | 'home'
    | 'solutions'
    | 'products'
    | 'accommodations'
    | 'how-we-work'
    | 'andario-booking-engine'
    | 'cases'
    | 'about'
    | 'contact'
    | 'faq'
    | 'privacy'
    | 'terms',
    string
  >;
  home: {
    eyebrow: string;
    h1: string;
    lead: string;
    micro: string;
    secondaryCta: string;
    problemTitle: string;
    problem: string[];
    problemClose: string;
    solutionTitle: string;
    solution: string[];
    solutionKey: string;
    portfolioTitle: string;
    portfolioIntro: string;
    diffTitle: string;
    diffLead: string;
    diffBody: string;
    highlights: { title: string; body: string }[];
    audienceTitle: string;
    audienceIntro: string;
    audiences: { title: string; body: string }[];
    processTitle: string;
    processIntro: string;
    process: { title: string; body: string }[];
    trustTitle: string;
    trust: string[];
    aboutTitle: string;
    about: string[];
    aboutCta: string;
    casesTitle: string;
    cases: string[];
    casesCta: string;
    finalTitle: string;
    final: string;
  };
  servicesIntro: { h1: string; lead: string; metaTitle: string; metaDescription: string };
  services: Record<ServiceId, ServiceContent>;
  bookingEngine: BookingEngineContent;
  digitalCheck: DigitalCheckContent;
  andarioWeb: AndarioWebContent;
  visibility: VisibilityContent;
  connect: ConnectContent;
  contentPage: ContentPage;
  growth: GrowthContent;
  solutionsHub: SolutionsHubContent;
  homePage: HomePageContent;
  accommodationsPage: AccommodationsPageContent;
  howWeWorkPage: HowWeWorkPageContent;
  aboutView: AboutViewContent;
  accommodations: {
    h1: string;
    lead: string;
    body: string[];
    types: { title: string; body: string }[];
    close: string;
  };
  processPage: {
    h1: string;
    lead: string;
    close: string;
  };
  casesPage: {
    h1: string;
    lead: string;
    name: string;
    place: string;
    label: string;
    body: string[];
    pending: string;
  };
  aboutPage: {
    h1: string;
    lead: string;
    body: string[];
    visionTitle: string;
    vision: string;
    missionTitle: string;
    mission: string;
  };
  faqPage: { h1: string; lead: string; items: FaqItem[] };
  contactPage: {
    h1: string;
    lead: string;
    micro: string;
    whatsappTitle: string;
    whatsappCta: string;
    orForm: string;
    progress: string;
    continueLabel: string;
    backLabel: string;
    stepOne: string;
    stepTwo: string;
    unavailable: string;
    fields: {
      name: string;
      establishment: string;
      location: string;
      type: string;
      whatsapp: string;
      whatsappHint: string;
      email: string;
      emailHint: string;
      note: string;
      noteHint: string;
      needs: string;
      consent: string;
      submit: string;
      sending: string;
    };
    types: Record<AccommodationType, string>;
    needs: Record<'bookings' | 'web' | 'google' | 'otas' | 'organize' | 'whatsapp' | 'unsure', string>;
    afterTitle: string;
    after: { title: string; body: string }[];
    afterNote: string;
    unsureTitle: string;
    unsureBody: string;
    checkCta: string;
    requiredNote: string;
    errors: { required: string; emailRequired: string; emailInvalid: string; consent: string };
    result: { success: string; invalid: string; rate_limited: string; unavailable: string; error: string };
    honeypot: string;
  };
  legal: {
    privacy: { h1: string; lead: string; sections: { title: string; body: string[] }[] };
    review: string;
  };
  termsView: TermsViewContent;
  notFound: { title: string; body: string; cta: string };
  error: { title: string; body: string; retry: string };
};
