import type { AccommodationType, RouteId, ServiceId } from '@/lib/i18n/routes';
import type { TermsSectionId } from '@/lib/legal/terms';

export type FaqItem = { q: string; a: string };

export type ProductStatus = 'available' | 'roadmap';

export type VisibilityContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  problemCta: string;
  talkCta: string;
  reviewCta: string;
  infoCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  heroCaption: string;
  heroQuery: string;
  problems: { title: string; body: string }[];
  systemTitle: string;
  systemParts: string[];
  systemEquals: string;
  systemNote: string;
  chain: string[];
  whatTitle: string;
  whatBody: string;
  whatNote: string;
  technicalTitle: string;
  technicalBody: string;
  technicalDo: string[];
  technicalWhy: string;
  localTitle: string;
  localBody: string;
  localSteps: string[];
  localNote: string;
  googleTitle: string;
  googleBody: string;
  googleParts: { title: string; body: string }[];
  googleNote: string;
  consoleTitle: string;
  consoleBody: string;
  consoleRows: string[];
  contentTitle: string;
  contentBody: string;
  contentSteps: string[];
  intentTitle: string;
  intentIntro: string;
  intents: { query: string; intent: string }[];
  intentNote: string;
  destinationTitle: string;
  destinationBody: string;
  destinationPoints: string[];
  ecosystemCaption: string;
  ecosystemColumns: { title: string; points: string[] }[];
  discoveryTitle: string;
  discoverySteps: string[];
  discoveryNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  groups: { title: string; what: string; purpose: string }[];
  matrixTitle: string;
  matrixCenter: string;
  matrixPoints: string[];
  matrixNote: string;
  processTitle: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receive: string[];
  receiveNote: string;
  structureTitle: string;
  structureBefore: string[];
  structureAfter: string[];
  finding: { label: string; value: string }[];
  webTitle: string;
  webBody: string;
  webNote: string;
  checkTitle: string;
  checkBody: string;
  checkNote: string;
  bookingTitle: string;
  bookingBody: string;
  growthTitle: string;
  growthBody: string;
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  whenTitle: string;
  when: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  adsTitle: string;
  adsIntro: string;
  organicTitle: string;
  organicPoints: string[];
  paidTitle: string;
  paidPoints: string[];
  adsNote: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type ConnectContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  problemCta: string;
  bookingCta: string;
  talkCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  roadmapLabel: string;
  heroCaption: string;
  heroGuest: string;
  heroGuestMsg: string;
  heroReply: string;
  heroReplyMsg: string;
  heroAction: string;
  heroEngine: string;
  heroAvailability: string;
  heroReserve: string;
  questions: string[];
  problems: { title: string; body: string }[];
  problemNote: string;
  journeyTitle: string;
  journeySteps: string[];
  journeyNote: string;
  whatTitle: string;
  whatBody: string;
  whatNote: string;
  hubCaption: string;
  hubColumns: { title: string; points: string[] }[];
  autoTitle: string;
  autoBody: string;
  autoRepeatTitle: string;
  autoRepeat: string[];
  autoHumanTitle: string;
  autoHuman: string[];
  autoNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  exampleCardLabel: string;
  groups: { title: string; what: string; purpose: string; example: string }[];
  flowTitle: string;
  flow: { who: string; line: string }[];
  flowNote: string;
  bookingTitle: string;
  bookingBody: string;
  bookingConnect: string[];
  bookingEnginePoints: string[];
  bookingNote: string;
  webTitle: string;
  webBody: string;
  webSteps: string[];
  webNote: string;
  checkTitle: string;
  checkBody: string;
  checkSteps: string[];
  checkNote: string;
  growthTitle: string;
  growthBody: string;
  growthPoints: string[];
  growthNote: string;
  leadTitle: string;
  leadBody: string;
  leadSteps: string[];
  leadExamples: string[];
  leadNote: string;
  followTitle: string;
  followBody: string;
  followSteps: string[];
  followNote: string;
  confirmTitle: string;
  confirmBody: string;
  reminderTitle: string;
  reminderBody: string;
  messagesNote: string;
  faqLayerTitle: string;
  faqLayer: string[];
  faqLayerNote: string;
  humanTitle: string;
  humanBody: string;
  humanAuto: string[];
  humanPerson: string[];
  humanNote: string;
  aiTitle: string;
  aiBody: string;
  aiRules: string[];
  aiNote: string;
  securityTitle: string;
  securityBody: string;
  securityPoints: string[];
  securityNote: string;
  channelTitle: string;
  channelBody: string;
  channelSteps: string[];
  channelNote: string;
  otherChannelsTitle: string;
  otherChannelsBody: string;
  casesTitle: string;
  cases: { title: string; quote: string; steps: string[] }[];
  casesNote: string;
  ownerTitle: string;
  owner: { title: string; body: string }[];
  teamTitle: string;
  team: string[];
  teamNote: string;
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  whenTitle: string;
  when: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  processTitle: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receive: string[];
  receiveNote: string;
  ecosystemTitle: string;
  ecosystemSteps: string[];
  ecosystemNote: string;
  lifecycleTitle: string;
  lifecycle: string[];
  boundaryAutoTitle: string;
  boundaryAuto: string[];
  boundaryHumanTitle: string;
  boundaryHuman: string[];
  boundaryNote: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type ContentPage = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  problemCta: string;
  photoCta: string;
  scopeCta: string;
  talkCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  heroCaption: string;
  heroLayers: string[];
  questions: { q: string; a: string }[];
  decisionSteps: string[];
  decisionNote: string;
  whatTitle: string;
  whatBody: string;
  whatNote: string;
  anatomyCaption: string;
  anatomyColumns: { title: string; points: string[] }[];
  anatomyParts: string[];
  anatomyEquals: string;
  photoTitle: string;
  photoBody: string;
  photoCategories: { title: string; body: string }[];
  photoNote: string;
  coordinationTitle: string;
  coordinationBody: string;
  coordinationPoints: string[];
  coordinationNote: string;
  optimizeTitle: string;
  optimizeBody: string;
  optimizeSteps: string[];
  optimizeNote: string;
  galleryTitle: string;
  galleryBody: string;
  gallerySteps: string[];
  galleryNote: string;
  copyTitle: string;
  copyBody: string;
  copyPoints: string[];
  copyPrinciple: string;
  genericLabel: string;
  genericExample: string;
  usefulLabel: string;
  usefulExample: string;
  videoTitle: string;
  videoBody: string;
  videoPoints: string[];
  videoNote: string;
  destinationTitle: string;
  destinationBody: string;
  destinationPoints: string[];
  destinationNote: string;
  socialTitle: string;
  socialBody: string;
  socialChannels: string[];
  socialNote: string;
  editorialTitle: string;
  editorialSteps: string[];
  editorialCategories: string[];
  editorialNote: string;
  relations: { title: string; body: string; steps: string[]; note: string; hrefLabel: string }[];
  beforeLabel: string;
  before: string[];
  afterLabel: string;
  after: string[];
  beforeNote: string;
  matrixTitle: string;
  matrixCenter: string;
  matrixAround: string[];
  matrixColumns: string[];
  matrixRows: { name: string; cells: string[] }[];
  matrixNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  exampleCardLabel: string;
  groups: { title: string; what: string; purpose: string; example: string }[];
  notIncludedTitle: string;
  notIncludedBody: string;
  notIncluded: string[];
  notIncludedNote: string;
  processTitle: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receive: string[];
  receiveNote: string;
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  whenTitle: string;
  when: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  authenticTitle: string;
  authenticBody: string;
  authenticPoints: string[];
  journeyTitle: string;
  journeySteps: string[];
  journeyNote: string;
  assetTitle: string;
  assetSteps: string[];
  assetNote: string;
  ecosystemTitle: string;
  ecosystemSteps: string[];
  ecosystemNote: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type GrowthContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  talkCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  loop: string[];
  loopNote: string;
  hub: { title: string; body: string }[];
  sources: string[];
  sourceNote: string;
  guessLine: string;
  questionsTitle: string;
  questions: string[];
  questionsNote: string;
  whatTitle: string;
  whatBody: string;
  whatNote: string;
  ecosystemCaption: string;
  ecosystemColumns: { title: string; points: string[] }[];
  measureTitle: string;
  measureIntro: string;
  measureGroups: { title: string; items: string[] }[];
  measureNote: string;
  channelsTitle: string;
  channelsBody: string;
  channels: { title: string; body: string }[];
  channelsNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  groups: { title: string; what: string; purpose: string }[];
  privacyTitle: string;
  privacyPoints: string[];
  privacyNote: string;
  relations: { title: string; body: string; steps: string[]; note: string; hrefLabel: string }[];
  processTitle: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receive: string[];
  receiveNote: string;
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  ecosystemTitle: string;
  ecosystemSteps: string[];
  ecosystemNote: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type SolutionsCard = {
  category: string;
  problem: string;
  body: string;
  cta: string;
};

export type SolutionsHubContent = {
  eyebrow: string;
  h1: string;
  support: string;
  assist: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  problemTitle: string;
  problemIntro: string;
  problems: string[];
  whereTitle: string;
  whereIntro: string;
  resultLabel: string;
  solutionLabel: string;
  scenarios: { title: string; result: string; cta: string; placement: string; service: ServiceId }[];
  cardsTitle: string;
  cardsSupport: string;
  cards: Record<ServiceId, SolutionsCard>;
  ownTech: string;
  paceTitle: string;
  paceBody: string;
  paths: { need: string; service: ServiceId }[];
  paceCta: string;
  bookingTitle: string;
  bookingSupport: string;
  bookingItems: string[];
  bookingNote: string;
  bookingCta: string;
  processTitle: string;
  processMark: string;
  processNote: string;
  process: string[];
  trustTitle: string;
  pillars: { title: string; body: string }[];
  pioneer: string;
  pioneerSoon: string;
  finalTitle: string;
  finalBody: string;
  finalPrimary: string;
  finalSecondary: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type HomePageContent = {
  h1: string;
  support: string;
  trust: string;
  primaryCta: string;
  secondaryCta: string;
  forLine: string;
  heroAlt: string;
  heroBadge: string;
  checkAlt: string;
  checkNote: string;
  checkItems: { label: string; tone: 'steady' | 'attention' }[];
  knownAlt: string;
  mockProperty: string;
  mockDates: string;
  mockGuests: string;
  mockUnit: string;
  mockPrice: string;
  mockAction: string;
  mockNote: string;
  bridge: string;
  situationsTitle: string;
  situations: { title: string; body: string }[];
  situationClose: string;
  situationCta: string;
  boardTitle: string;
  boardStatus: string;
  boardAreas: string;
  boardOpportunities: string;
  boardNext: string;
  opportunities: string[];
  nextSteps: string[];
  offerTitle: string;
  offerSupport: string;
  cards: Record<ServiceId, { role: string; title: string; body: string; cta: string }>;
  solutionsCta: string;
  roadmapTitle: string;
  roadmapIntro: string;
  roadmap: string[];
  knownTitle: string;
  knownBody: string[];
  audienceTitle: string;
  audiences: string[];
  audienceCta: string;
  processCta: string;
  differentiators: { title: string; body: string }[];
  bookingTitle: string;
  booking: string[];
  bookingCta: string;
  bookingBranches: { title: string; body: string }[];
  bookingResult: string;
  bookingNote: string;
  bookingOta: string;
  bookingPoints: string[];
  pioneerTitle: string;
  pioneer: string[];
  pioneerNote: string;
  pioneerCta: string;
  finalTitle: string;
  finalBody: string[];
  finalPrimary: string;
  finalSecondary: string;
  faqs: FaqItem[];
};

export type AccommodationsPageContent = {
  eyebrow: string;
  h1: string;
  support: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  heroCenter: string;
  heroNodes: string[];
  heroMobile: string[];
  heroCaption: string;
  identifyTitle: string;
  identifyBody: string;
  identifyClose: string;
  typesTitle: string;
  typesSupport: string;
  exploreCta: string;
  relatedLabel: string;
  serviceShort: Record<ServiceId, string>;
  types: { id: string; title: string; body: string; services: ServiceId[] }[];
  recognizeTitle: string;
  recognizeSupport: string;
  scenarios: { title: string; body: string; cta: string; placement: string; services: ServiceId[] }[];
  strategyTitle: string;
  strategyBody: string;
  strategyFlow: string[];
  strategyNote: string;
  ownTech: string;
  bookingTitle: string;
  bookingSupport: string;
  bookingPhrase: string;
  bookingCta: string;
  bookingSteps: string[];
  bookingBranches: { title: string; body: string }[];
  bookingResult: string;
  bookingNote: string;
  teamTitle: string;
  teamBody: string[];
  teamPillars: { title: string; body: string }[];
  stanceTitle: string;
  stanceBody: string;
  stagesTitle: string;
  stages: { title: string; body: string; services: ServiceId[] }[];
  stagesClose: string;
  processTitle: string;
  process: { title: string; body: string }[];
  processClose: string;
  processCta: string;
  trustTitle: string;
  pillars: { title: string; body: string }[];
  casesTitle: string;
  casesPlace: string;
  casesBody: string;
  casesCta: string;
  finalTitle: string;
  finalBody: string;
  finalPrimary: string;
  finalSecondary: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type AboutViewContent = {
  eyebrow: string;
  h1: string;
  support: string;
  tags: string;
  howCta: string;
  talkCta: string;
  micro: string;
  brandCaption: string;
  brand: string;
  brandColumns: { title: string; detail: string }[];
  lodging: string;
  ideaTitle: string;
  idea: string[];
  ideaMark: string;
  whyTitle: string;
  why: string[];
  whyClose: string;
  whyCaption: string;
  whySteps: string[];
  differentTitle: string;
  different: { title: string; body: string }[];
  guideTitle: string;
  principles: { title: string; body: string }[];
  methodCta: string;
  techTitle: string;
  techBody: string;
  techClose: string;
  techCta: string;
  techCaption: string;
  techSteps: string[];
  regionTitle: string;
  region: string[];
  regionOrigin: string;
  regionHorizon: string;
  regionCaption: string;
  visionTitle: string;
  vision: string;
  missionTitle: string;
  mission: string;
  formulaParts: string[];
  formulaEquals: string;
  behindTitle: string;
  behindBody: string;
  values: { title: string; body: string }[];
  pioneerTitle: string;
  pioneerEyebrow: string;
  pioneer: string[];
  pioneerClose: string;
  pioneerCta: string;
  futureTitle: string;
  future: string[];
  futureCaption: string;
  futureSteps: string[];
  exploreTitle: string;
  stayCta: string;
  solutionsCta: string;
  companyRole: string;
  faqs: FaqItem[];
  finalTitle: string;
  finalBody: string;
  diagnosisCta: string;
  finalNote: string;
};

export type HowWeWorkPageContent = {
  eyebrow: string;
  h1: string;
  support: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  route: string[];
  lostTitle: string;
  lostBody: string;
  situations: string[];
  lostClose: string;
  lostMark: string;
  checkLabel: string;
  checkTitle: string;
  checkBody: string;
  checkMark: string;
  reviewTitle: string;
  reviews: { title: string; body: string }[];
  receiveTitle: string;
  receive: { title: string; body: string }[];
  receiveMark: string;
  receiveNote: string;
  mapTitle: string;
  mapBody: string;
  beforeLabel: string;
  before: string[];
  afterLabel: string;
  after: string[];
  goalsTitle: string;
  goalsIntro: string;
  goals: { title: string; services: ServiceId[] }[];
  unsure: string;
  processTitle: string;
  process: { title: string; body: string }[];
  processClose: string;
  paceTitle: string;
  paceBody: string;
  pace: string[];
  paceNote: string;
  solutionsTitle: string;
  solutionsBody: string;
  solutions: { id: ServiceId; body: string }[];
  knownMark: string;
  knownBody: string;
  beliefs: string[];
  bookingTitle: string;
  bookingBody: string;
  bookingNote: string;
  bookingCta: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type AndarioWebContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  talkCta: string;
  connectCta: string;
  infoCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  heroCaption: string;
  situations: string[];
  valueTitle: string;
  valueParts: string[];
  valueEquals: string;
  whatTitle: string;
  whatBody: string;
  anatomyTitle: string;
  anatomyCaption: string;
  anatomy: { title: string; body: string }[];
  journeyTitle: string;
  journey: { title: string; body: string }[];
  journeyNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  whyLabel: string;
  groups: { title: string; items: { name: string; what: string; purpose: string; why: string }[] }[];
  designTitle: string;
  designBody: string;
  designPoints: string[];
  conversionTitle: string;
  conversionNote: string;
  conversionSteps: string[];
  conversionAround: string[];
  bookingTitle: string;
  bookingBody: string;
  bookingSteps: string[];
  bookingNote: string;
  whatsappTitle: string;
  whatsappBody: string;
  whatsappNote: string;
  seoTitle: string;
  seoBody: string;
  seoPoints: string[];
  seoNote: string;
  analyticsTitle: string;
  analyticsBody: string;
  analyticsPoints: string[];
  analyticsNote: string;
  performanceTitle: string;
  performanceBody: string;
  performancePoints: string[];
  accessTitle: string;
  accessBody: string;
  accessPoints: string[];
  mockNote: string;
  mockNav: string[];
  mockHero: string;
  mockBlocks: string[];
  processTitle: string;
  processIntro: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receiveIntro: string;
  receive: string[];
  receiveNote: string;
  beforeTitle: string;
  beforeLabel: string;
  beforeItems: string[];
  afterLabel: string;
  afterItems: string[];
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  whenTitle: string;
  when: string[];
  destinationTitle: string;
  destinationBody: string;
  destinationPoints: string[];
  contentTitle: string;
  contentBody: string;
  contentWeb: string[];
  contentExtra: string[];
  contentNote: string;
  checkTitle: string;
  checkBody: string;
  checkSteps: string[];
  checkNote: string;
  visibilityTitle: string;
  visibilityBody: string;
  growthTitle: string;
  growthBody: string;
  notTitle: string;
  not: { title: string; body: string }[];
  pioneerTitle: string;
  pioneerBody: string;
  ecosystemTitle: string;
  ecosystem: string[];
  ecosystemNote: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type DigitalCheckContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  talkCta: string;
  knowCta: string;
  startCta: string;
  overviewCaption: string;
  overviewPieces: string[];
  overviewCore: string;
  overviewResult: string[];
  situations: string[];
  valueTitle: string;
  valueBody: string;
  valueSteps: string[];
  valueClose: string;
  whatTitle: string;
  whatBody: string;
  mapCaption: string;
  mapCenter: string;
  mapNodes: string[];
  reviewsLabel: string;
  whyLabel: string;
  outcomeLabel: string;
  areasTitle: string;
  areasIntro: string;
  areasNote: string;
  areas: { title: string; reviews: string[]; why: string; outcome: string }[];
  areasCta: string;
  methodTitle: string;
  methodIntro: string;
  method: { title: string; body: string }[];
  methodCta: string;
  matrixTitle: string;
  matrixIntro: string;
  matrixExample: string;
  matrixImpact: string;
  matrixEffort: string;
  matrixZones: { title: string; body: string }[];
  matrixPoints: string[];
  findingExample: string;
  finding: { label: string; value: string }[];
  receiveTitle: string;
  receiveIntro: string;
  receive: { title: string; body: string }[];
  receiveCta: string;
  reportNote: string;
  reportHeading: string;
  reportRows: { label: string; value: string }[];
  reportPrioritiesTitle: string;
  reportPriorities: string[];
  reportNextTitle: string;
  reportNext: string;
  priorityTitle: string;
  priorityBody: string;
  priorityCriteria: string[];
  priorityLevels: string[];
  decisionsTitle: string;
  decisionsIntro: string;
  decisions: string[];
  pathTitle: string;
  pathIntro: string;
  pathClose: string;
  pathServices: string[];
  whoTitle: string;
  whoTypes: string[];
  whenTitle: string;
  when: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  modelTitle: string;
  model: string[];
  modelClose: string;
  finalTitle: string;
  finalBody: string;
  finalCta: string;
  finalNote: string;
};

export type BookingEngineContent = {
  support: string;
  assist: string;
  primaryCta: string;
  talkCta: string;
  infoCta: string;
  whatsappCta: string;
  heroMicro: string;
  path: { title: string; body: string }[];
  whatTitle: string;
  whatBody: string;
  whatWeb: string;
  whatEngine: string;
  whatFlow: { title: string; body: string }[];
  contrastTitle: string;
  contrastClose: string;
  webCard: { name: string; role: string; points: string[] };
  engineCard: { name: string; role: string; points: string[] };
  manualTitle: string;
  manualSteps: string[];
  manualBody: string;
  organizedTitle: string;
  organizedSteps: string[];
  organizedBody: string;
  exampleTitle: string;
  exampleIntro: string;
  exampleSteps: string[];
  exampleClose: string;
  useTitle: string;
  uses: { title: string; body: string; result: string }[];
  resultLabel: string;
  otaTitle: string;
  otaLead: string;
  otaBody: string;
  otaExternalLabel: string;
  otaExternal: string[];
  otaOwnLabel: string;
  otaOwn: string[];
  otaSync: string;
  otaNote: string;
  organizeTitle: string;
  doesLabel: string;
  whyLabel: string;
  groups: { title: string; items: { name: string; does: string; why: string }[] }[];
  dayTitle: string;
  benefits: { audience: string; points: string[] }[];
  demandTitle: string;
  demand: string[];
  demandNote: string;
  companions: { label: string; routeId: 'andario-web' | 'andario-visibility' | 'andario-content' | 'andario-connect' | 'andario-growth' }[];
  ecosystemTitle: string;
  ecosystem: { name: string; body: string }[];
  ecosystemNote: string;
  flowTitle: string;
  flowIntro: string;
  flow: { title: string; body: string }[];
  reservationTitle: string;
  reservationNote: string;
  reservation: { label: string; value: string }[];
  todayTitle: string;
  availableLabel: string;
  roadmapLabel: string;
  todayItems: string[];
  laterItems: string[];
  honesty: string;
  trustTitle: string;
  trustBody: string;
  trustPoints: string[];
  trustHonest: string;
  whoTitle: string;
  whoBody: string;
  whoQuestion: string;
  whoAnswer: string;
  whoTypes: string[];
  whoNot: string;
  techTitle: string;
  tech: string[];
  techMark: string;
  pioneer: string;
  startTitle: string;
  startNote: string;
  startSteps: { title: string; body: string }[];
  finalTitle: string;
  finalBody: string;
  finalMicro: string;
};

export type ServiceContent = {
  name: string;
  subtitle: string;
  summary: string;
  cardCta: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  problemTitle: string;
  problem: string;
  solutionTitle: string;
  solution: string;
  includedTitle: string;
  included: string[];
  howTitle: string;
  steps: { title: string; body: string }[];
  ecosystem: string;
  note?: string;
  futureTitle?: string;
  future: string[];
  faqs: FaqItem[];
  ctaTitle: string;
  ctaLabel: string;
};

export type TermsBlock =
  | { kind: 'p'; text: string }
  | { kind: 'list'; items: string[] }
  | { kind: 'h3'; text: string }
  | { kind: 'privacy' }
  | { kind: 'channels' }
  | { kind: 'identity' };

export type TermsViewContent = {
  h1: string;
  lead: string;
  note: string;
  updatedLabel: string;
  tocLabel: string;
  sections: { id: TermsSectionId; title: string; blocks: TermsBlock[] }[];
  closerTitle: string;
  closerBody: string;
};

export type Dictionary = {
  meta: {
    htmlLang: string;
    pages: Record<RouteId, { title: string; description: string }>;
  };
  chrome: {
    skip: string;
    primaryCta: string;
    secondaryCta: string;
    ctaSteps: readonly string[];
    ctaNote: string;
    menu: string;
    close: string;
    language: string;
    footerTagline: string;
    footerDescription: string;
    footerLine: string;
    footerCtaTitle: string;
    footerCtaBody: string;
    footerGroupDiagnosis: string;
    footerGroupPresence: string;
    footerGroupTechnology: string;
    footerTalkCta: string;
    footerWhatsappLabel: string;
    solutionsTitle: string;
    companyTitle: string;
    legalTitle: string;
    contactTitle: string;
    rights: string;
    map: string;
    analyticsTitle: string;
    analyticsBody: string;
    analyticsAccept: string;
    analyticsReject: string;
  };
  nav: Record<
    | 'home'
    | 'solutions'
    | 'accommodations'
    | 'how-we-work'
    | 'andario-booking-engine'
    | 'cases'
    | 'about'
    | 'contact'
    | 'faq'
    | 'privacy'
    | 'terms',
    string
  >;
  home: {
    eyebrow: string;
    h1: string;
    lead: string;
    micro: string;
    secondaryCta: string;
    problemTitle: string;
    problem: string[];
    problemClose: string;
    solutionTitle: string;
    solution: string[];
    solutionKey: string;
    portfolioTitle: string;
    portfolioIntro: string;
    diffTitle: string;
    diffLead: string;
    diffBody: string;
    highlights: { title: string; body: string }[];
    audienceTitle: string;
    audienceIntro: string;
    audiences: { title: string; body: string }[];
    processTitle: string;
    processIntro: string;
    process: { title: string; body: string }[];
    trustTitle: string;
    trust: string[];
    aboutTitle: string;
    about: string[];
    aboutCta: string;
    casesTitle: string;
    cases: string[];
    casesCta: string;
    finalTitle: string;
    final: string;
  };
  servicesIntro: { h1: string; lead: string; metaTitle: string; metaDescription: string };
  services: Record<ServiceId, ServiceContent>;
  bookingEngine: BookingEngineContent;
  digitalCheck: DigitalCheckContent;
  andarioWeb: AndarioWebContent;
  visibility: VisibilityContent;
  connect: ConnectContent;
  contentPage: ContentPage;
  growth: GrowthContent;
  solutionsHub: SolutionsHubContent;
  homePage: HomePageContent;
  accommodationsPage: AccommodationsPageContent;
  howWeWorkPage: HowWeWorkPageContent;
  aboutView: AboutViewContent;
  accommodations: {
    h1: string;
    lead: string;
    body: string[];
    types: { title: string; body: string }[];
    close: string;
  };
  processPage: {
    h1: string;
    lead: string;
    close: string;
  };
  casesPage: {
    h1: string;
    lead: string;
    name: string;
    place: string;
    label: string;
    body: string[];
    pending: string;
  };
  aboutPage: {
    h1: string;
    lead: string;
    body: string[];
    visionTitle: string;
    vision: string;
    missionTitle: string;
    mission: string;
  };
  faqPage: { h1: string; lead: string; items: FaqItem[] };
  contactPage: {
    h1: string;
    lead: string;
    micro: string;
    whatsappTitle: string;
    whatsappCta: string;
    orForm: string;
    progress: string;
    continueLabel: string;
    backLabel: string;
    stepOne: string;
    stepTwo: string;
    unavailable: string;
    fields: {
      name: string;
      establishment: string;
      location: string;
      type: string;
      whatsapp: string;
      whatsappHint: string;
      email: string;
      emailHint: string;
      note: string;
      noteHint: string;
      needs: string;
      consent: string;
      submit: string;
      sending: string;
    };
    types: Record<AccommodationType, string>;
    needs: Record<'bookings' | 'web' | 'google' | 'otas' | 'organize' | 'whatsapp' | 'unsure', string>;
    afterTitle: string;
    after: { title: string; body: string }[];
    afterNote: string;
    unsureTitle: string;
    unsureBody: string;
    checkCta: string;
    errors: { required: string; email: string; consent: string };
    result: { success: string; invalid: string; rate_limited: string; unavailable: string; error: string };
    honeypot: string;
  };
  legal: {
    privacy: { h1: string; lead: string; sections: { title: string; body: string[] }[] };
    review: string;
  };
  termsView: TermsViewContent;
  notFound: { title: string; body: string; cta: string };
  error: { title: string; body: string; retry: string };
};
