import type { AccommodationType, RouteId, ServiceId } from '@/lib/i18n/routes';
import type { TermsSectionId } from '@/lib/legal/terms';

export type FaqItem = { q: string; a: string };

export type ProductStatus = 'available' | 'roadmap';

export type VisibilityContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  problemCta: string;
  talkCta: string;
  reviewCta: string;
  infoCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  heroCaption: string;
  heroQuery: string;
  problems: { title: string; body: string }[];
  systemTitle: string;
  systemParts: string[];
  systemEquals: string;
  systemNote: string;
  chain: string[];
  whatTitle: string;
  whatBody: string;
  whatNote: string;
  technicalTitle: string;
  technicalBody: string;
  technicalDo: string[];
  technicalWhy: string;
  localTitle: string;
  localBody: string;
  localSteps: string[];
  localNote: string;
  googleTitle: string;
  googleBody: string;
  googleParts: { title: string; body: string }[];
  googleNote: string;
  consoleTitle: string;
  consoleBody: string;
  consoleRows: string[];
  contentTitle: string;
  contentBody: string;
  contentSteps: string[];
  intentTitle: string;
  intentIntro: string;
  intents: { query: string; intent: string }[];
  intentNote: string;
  destinationTitle: string;
  destinationBody: string;
  destinationPoints: string[];
  ecosystemCaption: string;
  ecosystemColumns: { title: string; points: string[] }[];
  discoveryTitle: string;
  discoverySteps: string[];
  discoveryNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  groups: { title: string; what: string; purpose: string }[];
  matrixTitle: string;
  matrixCenter: string;
  matrixPoints: string[];
  matrixNote: string;
  processTitle: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receive: string[];
  receiveNote: string;
  structureTitle: string;
  structureBefore: string[];
  structureAfter: string[];
  finding: { label: string; value: string }[];
  webTitle: string;
  webBody: string;
  webNote: string;
  checkTitle: string;
  checkBody: string;
  checkNote: string;
  bookingTitle: string;
  bookingBody: string;
  growthTitle: string;
  growthBody: string;
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  whenTitle: string;
  when: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  adsTitle: string;
  adsIntro: string;
  organicTitle: string;
  organicPoints: string[];
  paidTitle: string;
  paidPoints: string[];
  adsNote: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type ConnectContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  problemCta: string;
  bookingCta: string;
  talkCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  roadmapLabel: string;
  heroCaption: string;
  heroGuest: string;
  heroGuestMsg: string;
  heroReply: string;
  heroReplyMsg: string;
  heroAction: string;
  heroEngine: string;
  heroAvailability: string;
  heroReserve: string;
  questions: string[];
  problems: { title: string; body: string }[];
  problemNote: string;
  journeyTitle: string;
  journeySteps: string[];
  journeyNote: string;
  whatTitle: string;
  whatBody: string;
  whatNote: string;
  hubCaption: string;
  hubColumns: { title: string; points: string[] }[];
  autoTitle: string;
  autoBody: string;
  autoRepeatTitle: string;
  autoRepeat: string[];
  autoHumanTitle: string;
  autoHuman: string[];
  autoNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  exampleCardLabel: string;
  groups: { title: string; what: string; purpose: string; example: string }[];
  flowTitle: string;
  flow: { who: string; line: string }[];
  flowNote: string;
  bookingTitle: string;
  bookingBody: string;
  bookingConnect: string[];
  bookingEnginePoints: string[];
  bookingNote: string;
  webTitle: string;
  webBody: string;
  webSteps: string[];
  webNote: string;
  checkTitle: string;
  checkBody: string;
  checkSteps: string[];
  checkNote: string;
  growthTitle: string;
  growthBody: string;
  growthPoints: string[];
  growthNote: string;
  leadTitle: string;
  leadBody: string;
  leadSteps: string[];
  leadExamples: string[];
  leadNote: string;
  followTitle: string;
  followBody: string;
  followSteps: string[];
  followNote: string;
  confirmTitle: string;
  confirmBody: string;
  reminderTitle: string;
  reminderBody: string;
  messagesNote: string;
  faqLayerTitle: string;
  faqLayer: string[];
  faqLayerNote: string;
  humanTitle: string;
  humanBody: string;
  humanAuto: string[];
  humanPerson: string[];
  humanNote: string;
  aiTitle: string;
  aiBody: string;
  aiRules: string[];
  aiNote: string;
  securityTitle: string;
  securityBody: string;
  securityPoints: string[];
  securityNote: string;
  channelTitle: string;
  channelBody: string;
  channelSteps: string[];
  channelNote: string;
  otherChannelsTitle: string;
  otherChannelsBody: string;
  casesTitle: string;
  cases: { title: string; quote: string; steps: string[] }[];
  casesNote: string;
  ownerTitle: string;
  owner: { title: string; body: string }[];
  teamTitle: string;
  team: string[];
  teamNote: string;
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  whenTitle: string;
  when: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  processTitle: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receive: string[];
  receiveNote: string;
  ecosystemTitle: string;
  ecosystemSteps: string[];
  ecosystemNote: string;
  lifecycleTitle: string;
  lifecycle: string[];
  boundaryAutoTitle: string;
  boundaryAuto: string[];
  boundaryHumanTitle: string;
  boundaryHuman: string[];
  boundaryNote: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type ContentPage = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  problemCta: string;
  photoCta: string;
  scopeCta: string;
  talkCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  heroCaption: string;
  heroLayers: string[];
  questions: { q: string; a: string }[];
  decisionSteps: string[];
  decisionNote: string;
  whatTitle: string;
  whatBody: string;
  whatNote: string;
  anatomyCaption: string;
  anatomyColumns: { title: string; points: string[] }[];
  anatomyParts: string[];
  anatomyEquals: string;
  photoTitle: string;
  photoBody: string;
  photoCategories: { title: string; body: string }[];
  photoNote: string;
  coordinationTitle: string;
  coordinationBody: string;
  coordinationPoints: string[];
  coordinationNote: string;
  optimizeTitle: string;
  optimizeBody: string;
  optimizeSteps: string[];
  optimizeNote: string;
  galleryTitle: string;
  galleryBody: string;
  gallerySteps: string[];
  galleryNote: string;
  copyTitle: string;
  copyBody: string;
  copyPoints: string[];
  copyPrinciple: string;
  genericLabel: string;
  genericExample: string;
  usefulLabel: string;
  usefulExample: string;
  videoTitle: string;
  videoBody: string;
  videoPoints: string[];
  videoNote: string;
  destinationTitle: string;
  destinationBody: string;
  destinationPoints: string[];
  destinationNote: string;
  socialTitle: string;
  socialBody: string;
  socialChannels: string[];
  socialNote: string;
  editorialTitle: string;
  editorialSteps: string[];
  editorialCategories: string[];
  editorialNote: string;
  relations: { title: string; body: string; steps: string[]; note: string; hrefLabel: string }[];
  beforeLabel: string;
  before: string[];
  afterLabel: string;
  after: string[];
  beforeNote: string;
  matrixTitle: string;
  matrixCenter: string;
  matrixAround: string[];
  matrixColumns: string[];
  matrixRows: { name: string; cells: string[] }[];
  matrixNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  exampleCardLabel: string;
  groups: { title: string; what: string; purpose: string; example: string }[];
  notIncludedTitle: string;
  notIncludedBody: string;
  notIncluded: string[];
  notIncludedNote: string;
  processTitle: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receive: string[];
  receiveNote: string;
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  whenTitle: string;
  when: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  authenticTitle: string;
  authenticBody: string;
  authenticPoints: string[];
  journeyTitle: string;
  journeySteps: string[];
  journeyNote: string;
  assetTitle: string;
  assetSteps: string[];
  assetNote: string;
  ecosystemTitle: string;
  ecosystemSteps: string[];
  ecosystemNote: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type GrowthContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  talkCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  loop: string[];
  loopNote: string;
  hub: { title: string; body: string }[];
  sources: string[];
  sourceNote: string;
  guessLine: string;
  questionsTitle: string;
  questions: string[];
  questionsNote: string;
  whatTitle: string;
  whatBody: string;
  whatNote: string;
  ecosystemCaption: string;
  ecosystemColumns: { title: string; points: string[] }[];
  measureTitle: string;
  measureIntro: string;
  measureGroups: { title: string; items: string[] }[];
  measureNote: string;
  channelsTitle: string;
  channelsBody: string;
  channels: { title: string; body: string }[];
  channelsNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  groups: { title: string; what: string; purpose: string }[];
  privacyTitle: string;
  privacyPoints: string[];
  privacyNote: string;
  relations: { title: string; body: string; steps: string[]; note: string; hrefLabel: string }[];
  processTitle: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receive: string[];
  receiveNote: string;
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  ecosystemTitle: string;
  ecosystemSteps: string[];
  ecosystemNote: string;
  pioneerTitle: string;
  pioneerBody: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type SolutionsCard = {
  category: string;
  problem: string;
  body: string;
  chain: string;
  related: string;
  cta: string;
};

export type SolutionsHubContent = {
  eyebrow: string;
  h1: string;
  support: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  heroCenter: string;
  heroNodes: string[];
  heroMobile: string[];
  heroCaption: string;
  startTitle: string;
  startBody: string;
  startSteps: string[];
  whereTitle: string;
  whereIntro: string;
  scenarios: { title: string; cta: string; placement: string; services: ServiceId[] }[];
  cardsTitle: string;
  cardsSupport: string;
  cards: Record<ServiceId, SolutionsCard>;
  ownTech: string;
  bookingTitle: string;
  bookingSupport: string;
  bookingBranches: { title: string; body: string }[];
  bookingResult: string;
  bookingNote: string;
  bookingCta: string;
  connectTitle: string;
  connectBody: string;
  connectFlow: string[];
  connectNote: string;
  beforeTitle: string;
  beforeLabel: string;
  beforeItems: string[];
  afterLabel: string;
  afterFlow: string[];
  afterNote: string;
  hopeTitle: string;
  hopeBody: string;
  hopeSteps: string[];
  chooseTitle: string;
  chooseItems: { need: string; service: ServiceId }[];
  chooseCta: string;
  matrixTitle: string;
  matrix: { need: string; service: ServiceId }[];
  adaptTitle: string;
  adaptBody: string;
  journeyTitle: string;
  journeyNote: string;
  journey: string[];
  trustTitle: string;
  pillars: { title: string; body: string }[];
  craftTitle: string;
  craftIntro: string;
  craftPillars: { title: string; body: string }[];
  originTitle: string;
  originBody: string;
  pioneer: string;
  finalTitle: string;
  finalBody: string;
  finalPrimary: string;
  finalSecondary: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type HomePageContent = {
  eyebrow: string;
  h1: string;
  support: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  heroAltH1: string;
  heroAltSupport: string;
  heroCenter: string;
  heroNodes: string[];
  heroMobile: string[];
  heroCaption: string;
  journeyTitle: string;
  journeyBody: string;
  journeySteps: string[];
  journeyMap: string[];
  journeyNote: string;
  memorySteps: string[];
  memoryNote: string;
  problemTitle: string;
  problemChannels: string[];
  problemBody: string[];
  problemClose: string;
  fragmentTitle: string;
  beforeLabel: string;
  beforeItems: string[];
  beforeNote: string;
  afterLabel: string;
  afterFlow: string[];
  afterNote: string;
  visionTitle: string;
  visionItems: { title: string; body: string }[];
  visionClose: string;
  bookingTitle: string;
  bookingSupport: string;
  bookingPhrase: string;
  bookingCta: string;
  bookingBranches: { title: string; body: string }[];
  bookingResult: string;
  bookingNote: string;
  cardsTitle: string;
  cardsSupport: string;
  verbs: Record<ServiceId, string>;
  cards: Record<ServiceId, { category: string; body: string; cta: string }>;
  ownTech: string;
  solutionsCta: string;
  whereTitle: string;
  whereSupport: string;
  scenarios: { title: string; body: string; cta: string; placement: string; services: ServiceId[] }[];
  adaptTitle: string;
  adaptBody: string;
  adaptClose: string;
  shiftTitle: string;
  shiftNote: string;
  beforeWord: string;
  afterWord: string;
  shifts: { before: string; after: string }[];
  audienceTitle: string;
  audienceIntro: string;
  audiences: { title: string; body: string }[];
  audienceCta: string;
  processTitle: string;
  process: { title: string; body: string }[];
  processClose: string;
  processCta: string;
  trustTitle: string;
  pillars: { title: string; body: string }[];
  craftTitle: string;
  craftItems: string[];
  craftClose: string;
  originTitle: string;
  origin: string[];
  originCta: string;
  casesTitle: string;
  casesPlace: string;
  casesBody: string;
  casesCta: string;
  hopeTitle: string;
  hopeBody: string;
  hopeSteps: string[];
  finalTitle: string;
  finalBody: string;
  finalPrimary: string;
  finalSecondary: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type AccommodationsPageContent = {
  eyebrow: string;
  h1: string;
  support: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  heroCenter: string;
  heroNodes: string[];
  heroMobile: string[];
  heroCaption: string;
  identifyTitle: string;
  identifyBody: string;
  identifyClose: string;
  typesTitle: string;
  typesSupport: string;
  exploreCta: string;
  relatedLabel: string;
  serviceShort: Record<ServiceId, string>;
  types: { id: string; title: string; body: string; services: ServiceId[] }[];
  recognizeTitle: string;
  recognizeSupport: string;
  scenarios: { title: string; body: string; cta: string; placement: string; services: ServiceId[] }[];
  strategyTitle: string;
  strategyBody: string;
  strategyFlow: string[];
  strategyNote: string;
  ownTech: string;
  bookingTitle: string;
  bookingSupport: string;
  bookingPhrase: string;
  bookingCta: string;
  bookingSteps: string[];
  bookingBranches: { title: string; body: string }[];
  bookingResult: string;
  bookingNote: string;
  teamTitle: string;
  teamBody: string[];
  teamPillars: { title: string; body: string }[];
  stanceTitle: string;
  stanceBody: string;
  stagesTitle: string;
  stages: { title: string; body: string; services: ServiceId[] }[];
  stagesClose: string;
  processTitle: string;
  process: { title: string; body: string }[];
  processClose: string;
  processCta: string;
  trustTitle: string;
  pillars: { title: string; body: string }[];
  casesTitle: string;
  casesPlace: string;
  casesBody: string;
  casesCta: string;
  finalTitle: string;
  finalBody: string;
  finalPrimary: string;
  finalSecondary: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type AboutViewContent = {
  eyebrow: string;
  h1: string;
  support: string;
  tags: string;
  howCta: string;
  talkCta: string;
  micro: string;
  brandCaption: string;
  brand: string;
  brandColumns: { title: string; detail: string }[];
  lodging: string;
  ideaTitle: string;
  idea: string[];
  ideaMark: string;
  whyTitle: string;
  why: string[];
  whyClose: string;
  whyCaption: string;
  whySteps: string[];
  differentTitle: string;
  different: { title: string; body: string }[];
  guideTitle: string;
  principles: { title: string; body: string }[];
  methodCta: string;
  techTitle: string;
  techBody: string;
  techClose: string;
  techCta: string;
  techCaption: string;
  techSteps: string[];
  regionTitle: string;
  region: string[];
  regionOrigin: string;
  regionHorizon: string;
  regionCaption: string;
  visionTitle: string;
  vision: string;
  missionTitle: string;
  mission: string;
  formulaParts: string[];
  formulaEquals: string;
  behindTitle: string;
  behindBody: string;
  values: { title: string; body: string }[];
  pioneerTitle: string;
  pioneerEyebrow: string;
  pioneer: string[];
  pioneerClose: string;
  pioneerCta: string;
  futureTitle: string;
  future: string[];
  futureCaption: string;
  futureSteps: string[];
  exploreTitle: string;
  stayCta: string;
  solutionsCta: string;
  companyRole: string;
  faqs: FaqItem[];
  finalTitle: string;
  finalBody: string;
  diagnosisCta: string;
  finalNote: string;
};

export type HowWeWorkPageContent = {
  eyebrow: string;
  h1: string;
  support: string;
  primaryCta: string;
  secondaryCta: string;
  micro: string;
  route: string[];
  routeCaption: string;
  firstTitle: string;
  firstBody: string;
  firstMark: string;
  whyTitle: string;
  whyBody: string;
  pillars: { title: string; body: string }[];
  stepsTitle: string;
  stepsClose: string;
  resultLabel: string;
  steps: { title: string; headline: string; body: string; points: string[]; bridge: string[]; result: string }[];
  expectTitle: string;
  expect: { title: string; body: string }[];
  togetherTitle: string;
  togetherBody: string;
  together: { title: string; body: string }[];
  togetherClose: string;
  fitTitle: string;
  fit: string[];
  fitClose: string;
  honestTitle: string;
  honest: { title: string; body: string }[];
  thinkTitle: string;
  thinkFlow: string[];
  exampleTitle: string;
  exampleSteps: { title: string; body: string }[];
  exampleNote: string;
  methodTitle: string;
  methodBody: string;
  methodCaption: string;
  stayCta: string;
  casesCta: string;
  bookingTitle: string;
  bookingBody: string;
  bookingNote: string;
  bookingCta: string;
  relationTitle: string;
  relationFlow: string[];
  relationBody: string;
  clearTitle: string;
  clear: { title: string; body: string }[];
  finalTitle: string;
  finalBody: string;
  finalNote: string;
  faqs: FaqItem[];
};

export type AndarioWebContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  talkCta: string;
  connectCta: string;
  infoCta: string;
  whatsappCta: string;
  scopeLabel: string;
  exampleLabel: string;
  heroCaption: string;
  situations: string[];
  valueTitle: string;
  valueParts: string[];
  valueEquals: string;
  whatTitle: string;
  whatBody: string;
  anatomyTitle: string;
  anatomyCaption: string;
  anatomy: { title: string; body: string }[];
  journeyTitle: string;
  journey: { title: string; body: string }[];
  journeyNote: string;
  includesTitle: string;
  includesIntro: string;
  whatLabel: string;
  purposeLabel: string;
  whyLabel: string;
  groups: { title: string; items: { name: string; what: string; purpose: string; why: string }[] }[];
  designTitle: string;
  designBody: string;
  designPoints: string[];
  conversionTitle: string;
  conversionNote: string;
  conversionSteps: string[];
  conversionAround: string[];
  bookingTitle: string;
  bookingBody: string;
  bookingSteps: string[];
  bookingNote: string;
  whatsappTitle: string;
  whatsappBody: string;
  whatsappNote: string;
  seoTitle: string;
  seoBody: string;
  seoPoints: string[];
  seoNote: string;
  analyticsTitle: string;
  analyticsBody: string;
  analyticsPoints: string[];
  analyticsNote: string;
  performanceTitle: string;
  performanceBody: string;
  performancePoints: string[];
  accessTitle: string;
  accessBody: string;
  accessPoints: string[];
  mockNote: string;
  mockNav: string[];
  mockHero: string;
  mockBlocks: string[];
  processTitle: string;
  processIntro: string;
  process: { title: string; body: string }[];
  receiveTitle: string;
  receiveIntro: string;
  receive: string[];
  receiveNote: string;
  beforeTitle: string;
  beforeLabel: string;
  beforeItems: string[];
  afterLabel: string;
  afterItems: string[];
  whoTitle: string;
  whoTypes: string[];
  whoFit: string[];
  whenTitle: string;
  when: string[];
  destinationTitle: string;
  destinationBody: string;
  destinationPoints: string[];
  contentTitle: string;
  contentBody: string;
  contentWeb: string[];
  contentExtra: string[];
  contentNote: string;
  checkTitle: string;
  checkBody: string;
  checkSteps: string[];
  checkNote: string;
  visibilityTitle: string;
  visibilityBody: string;
  growthTitle: string;
  growthBody: string;
  notTitle: string;
  not: { title: string; body: string }[];
  pioneerTitle: string;
  pioneerBody: string;
  ecosystemTitle: string;
  ecosystem: string[];
  ecosystemNote: string;
  finalTitle: string;
  finalBody: string;
  finalNote: string;
};

export type DigitalCheckContent = {
  support: string;
  audienceLine: string;
  primaryCta: string;
  talkCta: string;
  knowCta: string;
  startCta: string;
  overviewCaption: string;
  overviewPieces: string[];
  overviewCore: string;
  overviewResult: string[];
  situations: string[];
  valueTitle: string;
  valueBody: string;
  valueSteps: string[];
  valueClose: string;
  whatTitle: string;
  whatBody: string;
  mapCaption: string;
  mapCenter: string;
  mapNodes: string[];
  reviewsLabel: string;
  whyLabel: string;
  outcomeLabel: string;
  areasTitle: string;
  areasIntro: string;
  areasNote: string;
  areas: { title: string; reviews: string[]; why: string; outcome: string }[];
  areasCta: string;
  methodTitle: string;
  methodIntro: string;
  method: { title: string; body: string }[];
  methodCta: string;
  matrixTitle: string;
  matrixIntro: string;
  matrixExample: string;
  matrixImpact: string;
  matrixEffort: string;
  matrixZones: { title: string; body: string }[];
  matrixPoints: string[];
  findingExample: string;
  finding: { label: string; value: string }[];
  receiveTitle: string;
  receiveIntro: string;
  receive: { title: string; body: string }[];
  receiveCta: string;
  reportNote: string;
  reportHeading: string;
  reportRows: { label: string; value: string }[];
  reportPrioritiesTitle: string;
  reportPriorities: string[];
  reportNextTitle: string;
  reportNext: string;
  priorityTitle: string;
  priorityBody: string;
  priorityCriteria: string[];
  priorityLevels: string[];
  decisionsTitle: string;
  decisionsIntro: string;
  decisions: string[];
  pathTitle: string;
  pathIntro: string;
  pathClose: string;
  pathServices: string[];
  whoTitle: string;
  whoTypes: string[];
  whenTitle: string;
  when: string[];
  notTitle: string;
  not: { title: string; body: string }[];
  modelTitle: string;
  model: string[];
  modelClose: string;
  finalTitle: string;
  finalBody: string;
  finalCta: string;
  finalNote: string;
};

export type BookingEngineContent = {
  support: string;
  primaryCta: string;
  talkCta: string;
  whatsappCta: string;
  availableLabel: string;
  roadmapLabel: string;
  hubCaption: string;
  hubCore: string;
  hubChannels: { name: string; status: ProductStatus }[];
  hubOutcomes: string[];
  problemPoints: string[];
  beforeTitle: string;
  beforeCaption: string;
  beforeChannels: string[];
  beforeResult: string;
  afterTitle: string;
  afterCaption: string;
  afterChannels: string[];
  afterResult: string;
  valueTitle: string;
  valueBody: string;
  valueItems: string[];
  exactTitle: string;
  exactBody: string;
  centralTitle: string;
  centralIntro: string;
  central: { title: string; body: string }[];
  featuresTitle: string;
  featuresIntro: string;
  featuresCta: string;
  doesLabel: string;
  whyLabel: string;
  groups: { title: string; items: { name: string; does: string; why: string }[] }[];
  flowTitle: string;
  flowIntro: string;
  flow: { title: string; body: string }[];
  reservationTitle: string;
  reservationNote: string;
  reservation: { label: string; value: string }[];
  channelsTitle: string;
  channelsBody: string;
  channels: { name: string; status: ProductStatus; note: string }[];
  rolesTitle: string;
  rolesIntro: string;
  roles: { name: string; role: string; points: string[] }[];
  rolesFlow: string[];
  rolesClose: string;
  benefitsTitle: string;
  benefits: { audience: string; points: string[] }[];
  otaTitle: string;
  otaBody: string;
  whoTitle: string;
  whoBody: string;
  whoTypes: string[];
  trustTitle: string;
  trustBody: string;
  trustPoints: string[];
  evolutionTitle: string;
  evolutionBody: string;
  evolution: { label: string; status: ProductStatus }[];
  pioneerTitle: string;
  pioneerBody: string;
  diffTitle: string;
  diff: { title: string; body: string }[];
  startTitle: string;
  startSteps: { title: string; body: string }[];
  startCta: string;
  finalTitle: string;
  finalBody: string;
  finalCta: string;
};

export type ServiceContent = {
  name: string;
  subtitle: string;
  summary: string;
  cardCta: string;
  metaTitle: string;
  metaDescription: string;
  h1: string;
  intro: string;
  problemTitle: string;
  problem: string;
  solutionTitle: string;
  solution: string;
  includedTitle: string;
  included: string[];
  howTitle: string;
  steps: { title: string; body: string }[];
  ecosystem: string;
  note?: string;
  futureTitle?: string;
  future: string[];
  faqs: FaqItem[];
  ctaTitle: string;
  ctaLabel: string;
};

export type TermsBlock =
  | { kind: 'p'; text: string }
  | { kind: 'list'; items: string[] }
  | { kind: 'h3'; text: string }
  | { kind: 'privacy' }
  | { kind: 'channels' }
  | { kind: 'identity' };

export type TermsViewContent = {
  h1: string;
  lead: string;
  note: string;
  updatedLabel: string;
  tocLabel: string;
  sections: { id: TermsSectionId; title: string; blocks: TermsBlock[] }[];
  closerTitle: string;
  closerBody: string;
};

export type Dictionary = {
  meta: {
    htmlLang: string;
    pages: Record<RouteId, { title: string; description: string }>;
  };
  chrome: {
    skip: string;
    primaryCta: string;
    secondaryCta: string;
    ctaSteps: readonly string[];
    ctaNote: string;
    menu: string;
    close: string;
    language: string;
    footerTagline: string;
    footerDescription: string;
    footerLine: string;
    footerCtaTitle: string;
    footerCtaBody: string;
    footerGroupDiagnosis: string;
    footerGroupPresence: string;
    footerGroupTechnology: string;
    footerTalkCta: string;
    footerWhatsappLabel: string;
    solutionsTitle: string;
    companyTitle: string;
    legalTitle: string;
    contactTitle: string;
    rights: string;
    map: string;
    analyticsTitle: string;
    analyticsBody: string;
    analyticsAccept: string;
    analyticsReject: string;
  };
  nav: Record<
    | 'home'
    | 'solutions'
    | 'accommodations'
    | 'how-we-work'
    | 'andario-booking-engine'
    | 'cases'
    | 'about'
    | 'contact'
    | 'faq'
    | 'privacy'
    | 'terms',
    string
  >;
  home: {
    eyebrow: string;
    h1: string;
    lead: string;
    micro: string;
    secondaryCta: string;
    problemTitle: string;
    problem: string[];
    problemClose: string;
    solutionTitle: string;
    solution: string[];
    solutionKey: string;
    portfolioTitle: string;
    portfolioIntro: string;
    diffTitle: string;
    diffLead: string;
    diffBody: string;
    highlights: { title: string; body: string }[];
    audienceTitle: string;
    audienceIntro: string;
    audiences: { title: string; body: string }[];
    processTitle: string;
    processIntro: string;
    process: { title: string; body: string }[];
    trustTitle: string;
    trust: string[];
    aboutTitle: string;
    about: string[];
    aboutCta: string;
    casesTitle: string;
    cases: string[];
    casesCta: string;
    finalTitle: string;
    final: string;
  };
  servicesIntro: { h1: string; lead: string; metaTitle: string; metaDescription: string };
  services: Record<ServiceId, ServiceContent>;
  bookingEngine: BookingEngineContent;
  digitalCheck: DigitalCheckContent;
  andarioWeb: AndarioWebContent;
  visibility: VisibilityContent;
  connect: ConnectContent;
  contentPage: ContentPage;
  growth: GrowthContent;
  solutionsHub: SolutionsHubContent;
  homePage: HomePageContent;
  accommodationsPage: AccommodationsPageContent;
  howWeWorkPage: HowWeWorkPageContent;
  aboutView: AboutViewContent;
  accommodations: {
    h1: string;
    lead: string;
    body: string[];
    types: { title: string; body: string }[];
    close: string;
  };
  processPage: {
    h1: string;
    lead: string;
    close: string;
  };
  casesPage: {
    h1: string;
    lead: string;
    name: string;
    place: string;
    label: string;
    body: string[];
    pending: string;
  };
  aboutPage: {
    h1: string;
    lead: string;
    body: string[];
    visionTitle: string;
    vision: string;
    missionTitle: string;
    mission: string;
  };
  faqPage: { h1: string; lead: string; items: FaqItem[] };
  contactPage: {
    h1: string;
    lead: string;
    micro: string;
    whatsappTitle: string;
    whatsappCta: string;
    orForm: string;
    progress: string;
    continueLabel: string;
    backLabel: string;
    stepOne: string;
    stepTwo: string;
    unavailable: string;
    fields: {
      name: string;
      establishment: string;
      location: string;
      type: string;
      whatsapp: string;
      whatsappHint: string;
      email: string;
      emailHint: string;
      note: string;
      noteHint: string;
      needs: string;
      consent: string;
      submit: string;
      sending: string;
    };
    types: Record<AccommodationType, string>;
    needs: Record<'bookings' | 'web' | 'google' | 'otas' | 'organize' | 'whatsapp' | 'unsure', string>;
    afterTitle: string;
    after: { title: string; body: string }[];
    afterNote: string;
    unsureTitle: string;
    unsureBody: string;
    checkCta: string;
    errors: { required: string; email: string; consent: string };
    result: { success: string; invalid: string; rate_limited: string; unavailable: string; error: string };
    honeypot: string;
  };
  legal: {
    privacy: { h1: string; lead: string; sections: { title: string; body: string[] }[] };
    review: string;
  };
  termsView: TermsViewContent;
  notFound: { title: string; body: string; cta: string };
  error: { title: string; body: string; retry: string };
};
