import type { AccommodationsPageContent } from '@/content/types';

export const accommodationsPageEs: AccommodationsPageContent = {
  eyebrow: 'Para alojamientos independientes',
  h1: 'Tu alojamiento es único. Tu estrategia digital también debería serlo.',
  support:
    'Desde un hostal hasta una cabaña, cada alojamiento tiene necesidades diferentes. En Andario Hospitality te ayudamos a construir una presencia digital profesional, conectar tus canales y avanzar hacia una operación digital más ordenada.',
  primaryCta: 'Solicitar diagnóstico digital',
  secondaryCta: 'Conocer nuestras soluciones',
  micro: 'Puedes empezar por una necesidad concreta y evolucionar desde ahí.',
  heroCenter: 'Alojamiento',
  heroNodes: ['Google', 'Web', 'WhatsApp', 'Content', 'Reservas', 'Visibility', 'Growth'],
  heroMobile: ['Web', 'Google', 'WhatsApp', 'Content', 'Visibility', 'Booking Engine', 'Growth'],
  heroCaption:
    'El alojamiento está en el centro. Web, Google, WhatsApp, contenido, visibilidad, reservas y medición se relacionan alrededor. No es un orden obligatorio ni una integración automática.',
  identifyTitle: 'Cada alojamiento tiene su propia historia. Y también sus propios retos.',
  identifyBody:
    'Un hostal puede necesitar ordenar sus reservas. Un hotel pequeño puede necesitar una web profesional. Una posada puede necesitar mejorar su visibilidad. Una cabaña puede necesitar mostrar mejor su experiencia y destino.',
  identifyClose: 'Por eso no creemos en una solución igual para todos.',
  typesTitle: 'Diseñamos pensando en alojamientos reales.',
  typesSupport:
    'Tu tamaño, operación y etapa importan. Por eso nuestras soluciones se adaptan al punto en el que se encuentra cada establecimiento.',
  exploreCta: 'Explorar soluciones',
  relatedLabel: 'Soluciones relacionadas',
  serviceShort: {
    'digital-check': 'Digital Check',
    'andario-web': 'Web',
    'andario-visibility': 'Visibility',
    'andario-booking-engine': 'Booking',
    'andario-connect': 'Connect',
    'andario-content': 'Content',
    'andario-growth': 'Growth',
  },
  types: [
    {
      id: 'hostel',
      title: 'Hostales',
      body: 'Soluciones para mejorar presencia digital, comunicación, reservas y presentación de la experiencia.',
      services: ['digital-check', 'andario-web', 'andario-connect', 'andario-booking-engine', 'andario-content'],
    },
    {
      id: 'small-hotel',
      title: 'Hoteles pequeños',
      body: 'Una presencia digital profesional y herramientas para construir una estrategia propia, sin perder la cercanía de un establecimiento independiente.',
      services: ['andario-web', 'andario-visibility', 'andario-booking-engine', 'andario-growth'],
    },
    {
      id: 'inn',
      title: 'Posadas',
      body: 'Convierte la identidad, la experiencia y el entorno de tu establecimiento en una presencia digital clara.',
      services: ['andario-content', 'andario-web', 'andario-visibility'],
    },
    {
      id: 'apartments',
      title: 'Apartamentos y apartahoteles',
      body: 'Presenta tus unidades con claridad y facilita el proceso de consulta y reserva.',
      services: ['andario-web', 'andario-booking-engine', 'andario-connect'],
    },
    {
      id: 'rural',
      title: 'Cabañas, villas y alojamientos rurales',
      body: 'Muestra el lugar, el destino y la experiencia que hacen especial a tu alojamiento.',
      services: ['andario-content', 'andario-web', 'andario-visibility'],
    },
    {
      id: 'venture',
      title: 'Emprendimientos turísticos',
      body: 'Construye una presencia digital profesional desde una base clara y preparada para evolucionar.',
      services: ['digital-check', 'andario-web', 'andario-growth'],
    },
  ],
  recognizeTitle: 'Quizás tu reto no sea tener más herramientas. Es saber qué necesitas primero.',
  recognizeSupport: 'Identifica la situación que más se parece a la de tu alojamiento. Es una orientación, no una recomendación obligatoria.',
  scenarios: [
    {
      title: 'Estoy empezando.',
      body: 'Necesito construir una presencia digital profesional desde una base clara.',
      cta: 'Quiero empezar',
      placement: 'starting',
      services: ['digital-check', 'andario-web', 'andario-content'],
    },
    {
      title: 'Tengo presencia, pero no me encuentran.',
      body: 'Tengo web o redes, pero quiero mejorar mi visibilidad ante personas que buscan opciones como la mía.',
      cta: 'Quiero mejorar mi visibilidad',
      placement: 'visibility',
      services: ['digital-check', 'andario-visibility', 'andario-content'],
    },
    {
      title: 'Recibo consultas, pero todo es manual.',
      body: 'Las conversaciones y reservas requieren demasiado trabajo repetitivo.',
      cta: 'Quiero ordenar mis reservas',
      placement: 'bookings',
      services: ['andario-connect', 'andario-booking-engine', 'andario-web'],
    },
    {
      title: 'Tengo varios canales desconectados.',
      body: 'Tengo web, redes, WhatsApp, OTAs u otros canales, pero siento que cada parte funciona por separado.',
      cta: 'Quiero conectar mi ecosistema',
      placement: 'channels',
      services: ['digital-check', 'andario-web', 'andario-connect', 'andario-booking-engine', 'andario-growth'],
    },
    {
      title: 'Tengo buenas instalaciones, pero no las estoy mostrando bien.',
      body: 'Necesito mejores fotografías, textos, contenido y una forma más clara de presentar la experiencia.',
      cta: 'Quiero mostrar mejor mi alojamiento',
      placement: 'show',
      services: ['andario-content', 'andario-web', 'andario-visibility'],
    },
    {
      title: 'No sé qué está funcionando.',
      body: 'Tengo presencia digital, pero necesito entender mejor qué ocurre y dónde debería concentrar mis esfuerzos.',
      cta: 'Quiero medir y mejorar',
      placement: 'measure',
      services: ['andario-growth', 'andario-visibility', 'digital-check'],
    },
  ],
  strategyTitle: 'Un alojamiento. Muchas necesidades. Una estrategia.',
  strategyBody:
    'Tu alojamiento puede necesitar diferentes soluciones en diferentes momentos. Nuestro trabajo es ayudarte a entender cuáles tienen sentido ahora y cuáles pueden venir después.',
  strategyFlow: ['Alojamiento', 'Web', 'WhatsApp', 'Google', 'Content', 'Reservas', 'Visibility', 'Booking Engine', 'Growth'],
  strategyNote: 'Este gráfico muestra una forma de leer las necesidades. No significa que todos los canales queden integrados de forma automática.',
  ownTech: 'Tecnología propia',
  bookingTitle: 'Tu alojamiento también puede construir su propio canal de reservas.',
  bookingSupport:
    'Andario Booking Engine es nuestra tecnología propia para gestionar disponibilidad, tarifas, huéspedes y reservas desde un canal directo.',
  bookingPhrase: 'Más control sobre tu propio canal. Menos dependencia de procesos manuales.',
  bookingCta: 'Conocer Andario Booking Engine',
  bookingSteps: ['Disponibilidad', 'Tarifa', 'Reserva'],
  bookingBranches: [
    { title: 'Web', body: 'Canal propio de partida para consultar disponibilidad y reservar.' },
    { title: 'WhatsApp', body: 'Sirve para conversar. Reservar dentro del chat no es un canal activo.' },
    { title: 'Otros canales', body: 'Se puede registrar el origen de una reserva. Eso no es una integración en vivo.' },
  ],
  bookingResult: 'Reserva en tu canal',
  bookingNote: 'El motor puede convivir con las OTAs. No las reemplaza y no afirma que Instagram, Facebook, Google o un asistente ya estén conectados.',
  teamTitle: 'Sabemos que no todos los alojamientos tienen un gran equipo detrás.',
  teamBody: [
    'En muchos establecimientos, la misma persona atiende huéspedes, responde WhatsApp, gestiona reservas, publica contenido y toma decisiones sobre el negocio.',
    'Por eso nuestras soluciones buscan ser prácticas, comprensibles y adaptables a la realidad de cada establecimiento.',
  ],
  teamPillars: [
    { title: 'Práctico', body: 'Soluciones pensadas para la operación real.' },
    { title: 'Comprensible', body: 'Tecnología explicada en lenguaje de negocio.' },
    { title: 'Escalable', body: 'Puedes empezar pequeño y evolucionar.' },
    { title: 'Acompañado', body: 'No tienes que descubrirlo todo solo.' },
  ],
  stanceTitle: 'No necesitas convertirte en una empresa tecnológica para aprovechar la tecnología.',
  stanceBody: 'Nosotros nos encargamos de hacerla comprensible y útil para tu alojamiento.',
  stagesTitle: 'No importa si estás empezando o si ya tienes presencia digital.',
  stages: [
    {
      title: 'Estoy empezando',
      body: 'Necesito construir una base profesional.',
      services: ['digital-check', 'andario-web', 'andario-content'],
    },
    {
      title: 'Ya estoy funcionando',
      body: 'Quiero mejorar visibilidad, reservas y comunicación.',
      services: ['andario-visibility', 'andario-booking-engine', 'andario-connect'],
    },
    {
      title: 'Quiero evolucionar',
      body: 'Ya tengo herramientas y quiero entender qué funciona.',
      services: ['andario-growth', 'andario-visibility', 'digital-check'],
    },
  ],
  stagesClose: 'Empieza donde estás. Nosotros te ayudamos a identificar el siguiente paso.',
  processTitle: 'No digitalizamos por digitalizar. Construimos lo que tiene sentido para tu negocio.',
  process: [
    { title: 'Entender', body: '¿Qué está pasando?' },
    { title: 'Priorizar', body: '¿Qué importa primero?' },
    { title: 'Construir', body: '¿Qué necesitamos implementar?' },
    { title: 'Medir', body: '¿Qué está ocurriendo?' },
    { title: 'Evolucionar', body: '¿Qué podemos mejorar?' },
  ],
  processClose: 'Tu estrategia se construye alrededor de tu negocio, no al revés.',
  processCta: 'Ver cómo trabajamos',
  trustTitle: 'Tecnología con una visión práctica.',
  pillars: [
    { title: 'Especialización', body: 'Pensamos en las necesidades de pequeños y medianos alojamientos independientes.' },
    { title: 'Simplicidad', body: 'La tecnología debe ayudarte, no convertirse en otra preocupación.' },
    { title: 'Tecnología propia', body: 'Desarrollamos soluciones propias como Andario Booking Engine.' },
    { title: 'Acompañamiento', body: 'No se trata solo de implementar. Se trata de entender, medir y evolucionar.' },
    {
      title: 'Transparencia',
      body: 'Explicamos qué hacemos, qué incluye cada solución y qué resultados no podemos garantizar.',
    },
  ],
  casesTitle: 'Ya estamos llevando esta visión a un alojamiento real.',
  casesPlace: 'BARUCH Hostal · Buritaca, Colombia',
  casesBody:
    'BARUCH es el establecimiento pionero con el que estamos llevando Andario Hospitality de la idea a la operación real. Todavía no publicamos métricas, reservas ni testimonios.',
  casesCta: 'Conocer el caso',
  finalTitle: 'Cuéntanos qué tipo de alojamiento tienes y qué quieres mejorar.',
  finalBody: 'Analizaremos tu situación y te ayudaremos a identificar por dónde podría empezar tu estrategia digital.',
  finalPrimary: 'Solicitar diagnóstico digital',
  finalSecondary: 'Hablar con Andario',
  finalNote: 'Sin compromiso. Sin venderte soluciones que no necesitas.',
  faqs: [
    {
      q: '¿Qué tipo de alojamientos trabajan con Andario?',
      a: 'Trabajamos principalmente con pequeños y medianos alojamientos independientes, como hostales, hoteles pequeños, posadas, apartamentos turísticos, apartahoteles, cabañas, villas y otros emprendimientos de alojamiento.',
    },
    {
      q: '¿Tengo que contratar todas las soluciones?',
      a: 'No. Puedes comenzar con una necesidad concreta y sumar otras soluciones cuando tu alojamiento esté preparado.',
    },
    {
      q: '¿Por dónde debería empezar?',
      a: 'Si no tienes claro qué necesitas, Digital Check puede ayudarte a identificar prioridades.',
    },
    {
      q: '¿Pueden ayudarme si todavía no tengo página web?',
      a: 'Sí. Andario Web puede ayudarte a construir una presencia digital profesional, y Digital Check puede servir como punto de partida para definir prioridades.',
    },
    {
      q: '¿Pueden ayudarme a conseguir más reservas?',
      a: 'Andario proporciona estrategia, tecnología y herramientas para fortalecer el ecosistema digital y los canales propios, pero las reservas dependen de múltiples factores y no se garantizan resultados específicos.',
    },
    {
      q: '¿Andario reemplaza Booking.com u otras OTAs?',
      a: 'No necesariamente. La propuesta busca fortalecer los canales propios del alojamiento y puede coexistir con plataformas externas según la estrategia de cada establecimiento.',
    },
    {
      q: '¿Puedo empezar solamente con Booking Engine?',
      a: 'Sí, dependiendo del alcance y las condiciones comerciales del producto.',
    },
    {
      q: '¿Cómo comienzo?',
      a: 'Puedes solicitar un diagnóstico digital o hablar directamente con Andario para contarnos qué tipo de alojamiento tienes y qué quieres mejorar.',
    },
  ],
};
