import type { AndarioWebContent, FaqItem } from '@/content/types';

export const andarioWebFaqsEs: FaqItem[] = [
  {
    q: '¿Qué es Andario Web?',
    a: 'Es el servicio de diseño y desarrollo de sitios web profesionales para alojamientos independientes. Construye la casa digital del establecimiento: identidad, unidades, servicios, confianza, contacto y, cuando corresponde, el camino hacia la reserva.',
  },
  {
    q: '¿Qué incluye un sitio web?',
    a: 'Según el alcance: arquitectura de información, UX/UI, diseño adaptable, páginas del alojamiento y sus unidades, servicios, galería, ubicación, experiencias, contacto, WhatsApp, integración con reservas, políticas, preguntas frecuentes, fundamentos de SEO técnico y analítica.',
  },
  {
    q: '¿Funcionará en celulares?',
    a: 'Sí. El sitio se diseña mobile-first y responsive, para que la información, las imágenes y el contacto se puedan usar en celulares y tablets.',
  },
  {
    q: '¿Puedo integrar Andario Booking Engine?',
    a: 'Sí, cuando forme parte del alcance. El sitio presenta e invita. La disponibilidad y la reserva se quedan en el motor. No duplicamos esa lógica en la web.',
  },
  {
    q: '¿Cuál es la diferencia entre la web y el Booking Engine?',
    a: 'Andario Web informa, genera confianza y orienta. Andario Booking Engine consulta disponibilidad y gestiona la reserva. Son piezas distintas que pueden trabajar juntas.',
  },
  {
    q: '¿Puedo seguir usando Booking.com o Airbnb?',
    a: 'Sí. La web no pide abandonar las OTAs ni afirma que elimine esa dependencia. Suma una casa digital propia.',
  },
  {
    q: '¿Andario Web incluye SEO?',
    a: 'Incluye fundamentos técnicos: títulos, metadatos, encabezados, URLs, sitemap, canonical, hreflang y datos estructurados cuando aportan. La estrategia de visibilidad continua corresponde a Andario Visibility. No prometemos una posición en Google.',
  },
  {
    q: '¿Incluye fotografía profesional?',
    a: 'El sitio organiza las imágenes que forman parte del alcance. La fotografía profesional, el video y la planificación editorial pueden ampliarse con Andario Content. No están incluidos de forma automática.',
  },
  {
    q: '¿Puedo conectar WhatsApp?',
    a: 'Sí. El sitio puede ofrecer un camino claro para escribir por WhatsApp. Automatizar o estructurar esas conversaciones corresponde a Andario Connect, si se contrata.',
  },
  {
    q: '¿Puedo mostrar habitaciones o unidades?',
    a: 'Sí, dentro del alcance: tipos de unidad, capacidades y características, para que el visitante entienda qué puede reservar.',
  },
  {
    q: '¿Puedo mostrar servicios y experiencias?',
    a: 'Sí, cuando formen parte de la oferta y del alcance: servicios del alojamiento, experiencias y, si corresponde, el entorno.',
  },
  {
    q: '¿Incluye Google Analytics?',
    a: 'Puede dejar la medición con GA4 y eventos de contacto, WhatsApp y acciones de reserva cuando sea técnicamente posible. No enviamos datos personales a la analítica. Andario Growth puede ampliar después la lectura.',
  },
  {
    q: '¿El sitio aparecerá primero en Google?',
    a: 'No. Nadie puede prometer el primer lugar ni una cantidad de tráfico. La web deja fundamentos técnicos. La visibilidad se trabaja aparte.',
  },
  {
    q: '¿Puedo actualizar la información?',
    a: 'Los cambios de contenido se acuerdan dentro del alcance. Esta página no presenta un panel de autogestión.',
  },
  {
    q: '¿Necesito tener fotografías y textos antes de comenzar?',
    a: 'Ayuda contar con ellos. Si faltan, lo identificamos al empezar y vemos qué prepara el alojamiento y qué puede ampliar Andario Content.',
  },
  {
    q: '¿Puedo comenzar solo con Andario Web?',
    a: 'Sí. Los servicios se contratan por separado. La web puede ser el primer paso, sin Digital Check y sin el resto del ecosistema.',
  },
  {
    q: '¿Tengo que contratar todos los servicios?',
    a: 'No. Visibility, Booking Engine, Connect, Content y Growth se suman solo si el alojamiento los necesita.',
  },
  {
    q: '¿Qué necesito para comenzar?',
    a: 'Contarnos el alojamiento, lo que ya tienes en Internet y qué quieres mejorar. Con eso se define el alcance. No hace falta tener todo el material listo.',
  },
  {
    q: '¿Cómo solicito información?',
    a: 'Desde Quiero digitalizar mi sitio o por WhatsApp. La conversación no obliga a contratar el resto de servicios.',
  },
];

export const andarioWebEs: AndarioWebContent = {
  support:
    'Diseñamos y desarrollamos sitios web profesionales para alojamientos independientes, pensados para presentar tu establecimiento, generar confianza, facilitar el contacto y conectar al visitante con tu estrategia digital y de reservas.',
  audienceLine:
    'Para hostales, hoteles pequeños, posadas, apartamentos turísticos, cabañas, villas y otros alojamientos independientes.',
  primaryCta: 'Quiero digitalizar mi sitio',
  talkCta: 'Hablar con Andario',
  connectCta: 'Conocer cómo podemos conectar tu web',
  infoCta: 'Solicitar información',
  whatsappCta: 'Escribir por WhatsApp',
  scopeLabel: 'Según alcance del proyecto',
  exampleLabel: 'Ejemplo ilustrativo',
  heroCaption:
    'Esquema de una portada: identidad, alojamiento, servicios y un camino para seguir. No es la captura de un sitio real.',
  situations: [
    'Tengo web, pero no explica con claridad qué ofrezco.',
    'La información está repartida entre varios sitios.',
    'Escribir o llamar cuesta más de la cuenta.',
    'En el celular la página se siente incómoda.',
    'Las unidades no se entienden antes de preguntar.',
    'No hay un camino claro hacia la reserva.',
    'La web no conversa con el resto de la presencia digital.',
  ],
  valueTitle: 'No construimos solamente una página. Construimos el espacio digital de tu alojamiento.',
  valueParts: ['Identidad', 'Contenido', 'Experiencia', 'Tecnología', 'Visibilidad', 'Contacto y reserva'],
  valueEquals: 'La casa digital del alojamiento',
  whatTitle: '¿Qué es Andario Web?',
  whatBody:
    'Es un servicio de diseño y desarrollo de sitios web profesionales para alojamientos independientes. El establecimiento presenta su identidad, unidades, servicios, ubicación, experiencias, políticas y formas de contacto. El sitio se piensa como parte de un ecosistema, no como una pieza aislada.',
  anatomyTitle: 'Anatomía de una web de alojamiento',
  anatomyCaption: 'Cada pieza ayuda al visitante a entender el alojamiento antes de escribir o reservar.',
  anatomy: [
    { title: 'Identidad', body: 'El alojamiento se reconoce desde el primer pantallazo.' },
    { title: 'Unidades', body: 'Habitaciones u otras unidades se explican con lo que el huésped necesita comparar.' },
    { title: 'Servicios', body: 'Lo que incluye la estancia queda visible, no escondido en un mensaje.' },
    { title: 'Galería', body: 'Las imágenes ordenan los espacios. No sustituyen una sesión que no esté en el alcance.' },
    { title: 'Experiencias', body: 'Lo que se puede vivir alrededor, cuando forma parte de la oferta.' },
    { title: 'Ubicación', body: 'Dónde está y cómo se llega, sin inventar datos del destino.' },
    { title: 'Información útil', body: 'Políticas y preguntas que evitan repetir lo mismo en cada conversación.' },
    { title: 'Contacto y reserva', body: 'WhatsApp, contacto y, si corresponde, la puerta hacia el motor de reservas.' },
  ],
  journeyTitle: 'El recorrido del huésped',
  journey: [
    { title: 'Descubre', body: 'Encuentra el alojamiento.' },
    { title: 'Entiende', body: 'Comprende qué ofrece y dónde está.' },
    { title: 'Compara', body: 'Conoce unidades, servicios y experiencia.' },
    { title: 'Confía', body: 'Ve información, imágenes, políticas y datos consistentes.' },
    { title: 'Consulta', body: 'Puede escribir con poco esfuerzo.' },
    { title: 'Reserva', body: 'Puede seguir hacia el canal de reserva cuando ese canal existe.' },
  ],
  journeyNote: 'La web facilita el recorrido. No prometemos que, por sí sola, genere reservas.',
  includesTitle: 'Qué puede incluir',
  includesIntro: 'Agrupado por lo que le importa al alojamiento. El alcance final se define con el establecimiento.',
  whatLabel: 'Qué',
  purposeLabel: 'Para qué',
  whyLabel: 'Por qué',
  groups: [
    {
      title: 'Arquitectura',
      items: [
        {
          name: 'Estructura y recorrido',
          what: 'Páginas, navegación y jerarquía.',
          purpose: 'Que el visitante encuentre lo importante sin perderse.',
          why: 'Una web clara se usa. Una web desordenada se abandona.',
        },
      ],
    },
    {
      title: 'Experiencia',
      items: [
        {
          name: 'UX, interfaz y móvil',
          what: 'Interfaz adaptable, llamados a la acción y contraste usable.',
          purpose: 'Que se pueda leer y actuar desde el celular.',
          why: 'La mayoría de las consultas empiezan en una pantalla pequeña.',
        },
      ],
    },
    {
      title: 'Alojamiento',
      items: [
        {
          name: 'Unidades y servicios',
          what: 'Establecimiento, habitaciones o unidades, capacidades y servicios.',
          purpose: 'Comparar la estancia antes de preguntar.',
          why: 'La decisión necesita ver qué se ofrece, no solo un nombre.',
        },
      ],
    },
    {
      title: 'Destino',
      items: [
        {
          name: 'Lugar y entorno',
          what: 'Ubicación, cómo llegar y el entorno cuando entra en el alcance.',
          purpose: 'Contar dónde está el alojamiento, no solo dónde se duerme.',
          why: 'El destino forma parte de la decisión.',
        },
      ],
    },
    {
      title: 'Imágenes',
      items: [
        {
          name: 'Galería',
          what: 'Fotografías organizadas y preparadas para la web.',
          purpose: 'Comprender los espacios.',
          why: 'Las imágenes participan en la decisión. La sesión profesional es de Content.',
        },
      ],
    },
    {
      title: 'Contacto',
      items: [
        {
          name: 'Escribir y ubicar',
          what: 'Contacto, correo, WhatsApp y ubicación.',
          purpose: 'Que el siguiente paso sea obvio.',
          why: 'Si cuesta escribir, la visita se queda en la página.',
        },
      ],
    },
    {
      title: 'Reservas',
      items: [
        {
          name: 'Puerta al motor',
          what: 'Llamados hacia la reserva e integración con Andario Booking Engine cuando corresponda.',
          purpose: 'Pasar de conocer el alojamiento a iniciar la reserva.',
          why: 'La disponibilidad no vive en la página. Vive en el motor.',
        },
      ],
    },
    {
      title: 'Visibilidad técnica',
      items: [
        {
          name: 'Bases de SEO',
          what: 'Encabezados, metadatos, URLs, sitemap, canonical, hreflang y datos estructurados cuando aportan.',
          purpose: 'Que los buscadores puedan leer el sitio.',
          why: 'Es la base. La estrategia continua es Visibility.',
        },
      ],
    },
    {
      title: 'Medición',
      items: [
        {
          name: 'Analítica',
          what: 'GA4 y eventos de contacto, WhatsApp y reserva cuando sea posible.',
          purpose: 'Ver qué se usa, sin enviar datos personales.',
          why: 'Lo que no se mide es más difícil de mejorar. Growth puede ampliar la lectura.',
        },
      ],
    },
  ],
  designTitle: 'Tu alojamiento debe verse como quieres que sea percibido.',
  designBody:
    'El diseño ordena la identidad, la tipografía, el color, la fotografía y la navegación para que el sitio se sienta del establecimiento y lleve a un siguiente paso. No es solo una página bonita.',
  designPoints: ['Identidad visual', 'Jerarquía', 'Fotografía', 'Navegación', 'Confianza', 'Llamados a la acción'],
  conversionTitle: 'De la visita al siguiente paso',
  conversionNote: 'La web reduce fricciones. No publicamos tasas de conversión.',
  conversionSteps: ['Visitante', 'Información', 'Confianza', 'Interés', 'Contacto', 'Reserva'],
  conversionAround: ['Contenido', 'Fotografías', 'Ubicación', 'Servicios', 'Preguntas', 'WhatsApp', 'Booking Engine'],
  bookingTitle: 'Tu web puede ser la puerta de tu canal propio de reservas.',
  bookingBody:
    'Andario Web presenta, informa e invita. Andario Booking Engine consulta la disponibilidad y gestiona la reserva. La lógica no se copia en el sitio.',
  bookingSteps: ['Andario Web presenta', 'Genera confianza', 'Invita a reservar', 'El motor consulta disponibilidad', 'El motor gestiona la reserva'],
  bookingNote: 'La integración entra cuando el proyecto la incluye. No está encendida por el solo hecho de tener la web.',
  whatsappTitle: 'Cuando el huésped quiere hablar, el camino debe ser sencillo.',
  whatsappBody:
    'El sitio puede mostrar WhatsApp en el recorrido, sobre todo en el celular, con un mensaje de contexto. Eso facilita el contacto.',
  whatsappNote: 'Estructurar o automatizar las conversaciones es Andario Connect, y solo si se contrata.',
  seoTitle: 'Una buena web también debe ser comprensible para los buscadores.',
  seoBody: 'Dejamos fundamentos para que el sitio pueda indexarse y entenderse. No prometemos el primer lugar ni una cifra de visitas.',
  seoPoints: ['Arquitectura', 'Títulos y metadatos', 'Encabezados', 'URLs', 'Enlaces internos', 'Sitemap', 'Canonical y hreflang', 'Datos estructurados', 'Rendimiento'],
  seoNote: 'Andario Visibility desarrolla la estrategia de visibilidad más amplia.',
  analyticsTitle: 'Lo que no se mide es más difícil de mejorar.',
  analyticsBody: 'Podemos dejar GA4 y eventos de los llamados, de WhatsApp y de las acciones de reserva cuando la técnica lo permita.',
  analyticsPoints: ['GA4', 'Clics de contacto', 'WhatsApp', 'Recorrido', 'Acciones de reserva, si son posibles'],
  analyticsNote: 'No enviamos nombres, correos ni mensajes a la analítica. Growth puede ampliar el análisis después.',
  performanceTitle: 'Diseñado para cargar con cuidado y funcionar bien.',
  performanceBody: 'Imágenes preparadas, carga diferida, poco JavaScript innecesario y una base pensada para móvil. No prometemos una nota de 100.',
  performancePoints: ['Imágenes optimizadas', 'Carga diferida', 'JavaScript contenido', 'Mobile-first', 'Core Web Vitals como referencia'],
  accessTitle: 'Un sitio que se pueda usar',
  accessBody: 'Contraste, teclado, etiquetas, encabezados, texto alternativo, foco visible y respeto por quien prefiere menos movimiento. No presentamos una certificación que no exista.',
  accessPoints: ['Contraste', 'Teclado', 'Etiquetas', 'Encabezados', 'Texto alternativo', 'Foco visible', 'Movimiento reducido'],
  mockNote: 'Ejemplo ilustrativo. No es la captura de un alojamiento real.',
  mockNav: ['Alojamiento', 'Servicios', 'Reservar'],
  mockHero: 'Descubre tu alojamiento',
  mockBlocks: ['Habitaciones', 'Servicios', 'Experiencias', 'Ubicación', 'Galería', 'Preguntas frecuentes', 'WhatsApp'],
  processTitle: 'De la idea al sitio listo para crecer.',
  processIntro: 'Siete momentos. El último no obliga a contratar el resto.',
  process: [
    { title: 'Entendemos', body: 'Alojamiento, identidad, público, destino y objetivos.' },
    { title: 'Estructuramos', body: 'Arquitectura, navegación y contenido.' },
    { title: 'Diseñamos', body: 'Experiencia visual y adaptable.' },
    { title: 'Desarrollamos', body: 'El sitio y las integraciones que entren en el alcance.' },
    { title: 'Probamos', body: 'Móvil, accesibilidad, SEO técnico, contacto, enlaces y rendimiento.' },
    { title: 'Publicamos', body: 'Dejamos el sitio preparado para producción.' },
    { title: 'Evolucionamos', body: 'Visibility, Booking Engine, Connect, Content o Growth, solo si hacen falta.' },
  ],
  receiveTitle: 'Un sitio listo para representar tu alojamiento.',
  receiveIntro: 'Según el alcance puede incluir:',
  receive: [
    'Arquitectura y UX/UI',
    'Diseño adaptable',
    'Páginas del alojamiento y sus unidades',
    'Servicios, galería y experiencias',
    'Ubicación y contacto',
    'WhatsApp',
    'Integración de reservas',
    'Políticas y preguntas frecuentes',
    'SEO técnico y analítica',
    'Preparación para publicar',
  ],
  receiveNote: 'El alcance final se define según las necesidades del establecimiento.',
  beforeTitle: 'De la presencia repartida a una casa propia',
  beforeLabel: 'Cuando la información vive suelta',
  beforeItems: ['Instagram', 'WhatsApp', 'OTA', 'Google', 'Información dispersa'],
  afterLabel: 'Con Andario Web',
  afterItems: ['Información organizada', 'Experiencia digital propia', 'WhatsApp', 'Reservas'],
  whoTitle: 'Para alojamientos que quieren una presencia digital propia y profesional.',
  whoTypes: ['Hostales', 'Hoteles pequeños', 'Posadas', 'Apartamentos turísticos', 'Apartahoteles', 'Cabañas', 'Villas', 'Alojamientos rurales', 'Otros establecimientos independientes'],
  whoFit: [
    'Todavía no tienen sitio.',
    'La web está desactualizada o cuesta usarla.',
    'Quieren profesionalizar la presencia.',
    'Quieren conectar la web con las reservas.',
    'Quieren una base propia, además de redes y OTAs.',
  ],
  whenTitle: 'Cuándo suele tener sentido',
  when: [
    'No hay sitio, o el que hay quedó atrás.',
    'En el celular no se usa bien.',
    'La información está desordenada.',
    'Las unidades se explican mal.',
    'Faltan imágenes o el contacto es difícil.',
    'No existe un camino hacia la reserva.',
    'Quieres integrar el Booking Engine.',
    'Necesitas una base para SEO y analítica.',
  ],
  destinationTitle: 'No mostramos solamente dónde duermes. Ayudamos a contar dónde estás.',
  destinationBody: 'Cuando entra en el alcance, el sitio puede hablar del lugar sin inventar datos.',
  destinationPoints: ['Destino', 'Ubicación', 'Cómo llegar', 'Entorno', 'Experiencias', 'Puntos de interés'],
  contentTitle: 'Una buena estructura necesita buen contenido.',
  contentBody: 'Andario Web organiza lo que ya se puede contar. Andario Content puede ampliar la producción.',
  contentWeb: ['Textos', 'Fotografías del alcance', 'Galerías', 'Información del establecimiento'],
  contentExtra: ['Fotografía profesional', 'Optimización', 'Redes', 'Video', 'Contenido de destino', 'Plan editorial'],
  contentNote: 'La fotografía profesional no está incluida de forma automática.',
  checkTitle: '¿No sabes qué necesita tu web? Puedes empezar por Digital Check.',
  checkBody: 'El diagnóstico ayuda a ver si la web es el primer paso. No es obligatorio.',
  checkSteps: ['Digital Check', '¿Hace falta la web?', 'Andario Web', '¿Hace falta visibilidad?', 'Visibility', '¿Hace falta reservar aquí?', 'Booking Engine'],
  checkNote: 'Puedes contratar Andario Web sin pasar por el diagnóstico.',
  visibilityTitle: 'La casa y la visibilidad',
  visibilityBody: 'Andario Web construye el sitio. Andario Visibility trabaja para que pueda encontrarse. Son complementarios. Ninguno promete el primer lugar.',
  growthTitle: 'La casa y la medición',
  growthBody: 'Andario Web deja la experiencia y las bases de analítica. Andario Growth puede ampliar la lectura y las mejoras después.',
  notTitle: 'Qué Andario Web no es',
  not: [
    { title: 'No es solamente diseño', body: 'Incluye estructura, experiencia, contenido y tecnología.' },
    { title: 'No es un motor de reservas', body: 'Booking Engine gestiona la disponibilidad y la reserva.' },
    { title: 'No es una estrategia SEO completa', body: 'Deja fundamentos. Visibility puede ampliar la estrategia.' },
    { title: 'No es fotografía ilimitada', body: 'La producción profesional se amplía con Content.' },
    { title: 'No garantiza reservas', body: 'Es infraestructura. Los resultados dependen de más factores.' },
    { title: 'No es una plantilla idéntica', body: 'La estructura se adapta al alojamiento.' },
  ],
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal es el establecimiento pionero de Andario Hospitality. No publicamos resultados de su sitio.',
  ecosystemTitle: 'Puede acompañar al resto. No los exige.',
  ecosystem: ['Digital Check', 'Andario Web', 'Visibility', 'Booking Engine', 'Connect', 'Content', 'Growth'],
  ecosystemNote: 'Cada servicio se contrata según lo que el alojamiento necesita. El orden no es obligatorio.',
  finalTitle: 'Tu alojamiento merece una casa propia en Internet.',
  finalBody: 'Cuéntanos qué tienes hoy, qué quieres mejorar y hacia dónde quieres llevar tu presencia digital.',
  finalNote: 'Podemos comenzar con el alcance que realmente necesita tu alojamiento.',
};
