import type { BookingEngineContent } from '@/content/types';

export const bookingEngineEs: BookingEngineContent = {
  support:
    'Permite que tus huéspedes consulten disponibilidad y reserven directamente desde la web de tu alojamiento, mientras centralizas la información de tus reservas.',
  assist: 'No necesitas conocimientos técnicos. Nosotros te ayudamos a configurarlo según la forma en que funciona tu alojamiento.',
  primaryCta: 'Quiero conocer Booking Engine',
  talkCta: 'Hablar con Andario',
  infoCta: 'Solicitar información',
  whatsappCta: 'Hablar por WhatsApp',
  heroMicro: 'Sin compromiso. Conversar no obliga a contratar.',
  path: [
    { title: 'Tu alojamiento', body: 'El punto de partida.' },
    { title: 'Tu página web', body: 'Donde el huésped te conoce.' },
    { title: 'Booking Engine', body: 'Donde ocurre la reserva.' },
    { title: 'Disponibilidad', body: 'Qué sigue libre.' },
    { title: 'Tarifa', body: 'El precio configurado.' },
    { title: 'Reserva', body: 'Queda registrada.' },
  ],
  whatTitle: '¿Qué es un motor de reservas?',
  whatBody:
    'Un motor de reservas es la herramienta que permite que un huésped consulte qué está disponible, vea el precio y realice una reserva desde el canal propio de tu alojamiento.',
  whatWeb: 'Tu página web presenta tu alojamiento.',
  whatEngine: 'El Booking Engine se encarga de la reserva.',
  whatFlow: [
    { title: 'Tu web', body: 'Presenta.' },
    { title: 'Tu alojamiento', body: 'Informa.' },
    { title: 'Booking Engine', body: 'Consulta disponibilidad.' },
    { title: 'Muestra opciones', body: 'El huésped ve lo que sí puede reservar.' },
    { title: 'El huésped reserva', body: 'Elige y deja sus datos.' },
    { title: 'Reserva registrada', body: 'El alojamiento la recibe organizada.' },
  ],
  contrastTitle: 'Tu página web y tu motor de reservas hacen cosas diferentes.',
  contrastClose: 'Una web atrae e informa. El Booking Engine permite reservar.',
  webCard: {
    name: 'Andario Web',
    role: 'Es la casa digital de tu alojamiento.',
    points: [
      'Presentar habitaciones',
      'Mostrar fotografías',
      'Explicar servicios',
      'Generar confianza',
      'Mostrar ubicación',
      'Presentar experiencias',
      'Recibir visitantes',
    ],
  },
  engineCard: {
    name: 'Andario Booking Engine',
    role: 'Es el sistema que organiza la reserva.',
    points: [
      'Consultar disponibilidad',
      'Mostrar tarifas',
      'Gestionar unidades',
      'Registrar huéspedes',
      'Crear reservas',
      'Aplicar reglas',
      'Registrar el origen',
    ],
  },
  manualTitle: '¿Qué pasa cuando las reservas se gestionan solo por WhatsApp?',
  manualSteps: [
    'El huésped pregunta: «¿tienen disponibilidad para el 12 al 15?»',
    'El propietario revisa manualmente.',
    'Calcula el precio.',
    'Pregunta cuántas personas son.',
    'Revisa de nuevo la disponibilidad.',
    'Envía instrucciones.',
    'Registra la reserva a mano.',
    'Actualiza la disponibilidad.',
    'Y el proceso se repite.',
  ],
  manualBody:
    'WhatsApp sigue siendo importante. Cuando todo depende de conversaciones y registros manuales, cada reserva puede requerir el mismo trabajo una y otra vez.',
  organizedTitle: 'Con un canal propio, parte del proceso queda organizado.',
  organizedSteps: [
    'El huésped entra a tu página.',
    'Selecciona fechas.',
    'Consulta disponibilidad.',
    'Ve opciones.',
    'Selecciona una unidad.',
    'Ingresa sus datos.',
    'Ve las condiciones configuradas.',
    'Se crea la reserva.',
    'El alojamiento la recibe organizada.',
  ],
  organizedBody:
    'El huésped puede avanzar por un recorrido de reserva claro, mientras el motor aplica la lógica configurada para tu alojamiento.',
  exampleTitle: 'Imagina un hostal con 8 habitaciones.',
  exampleIntro: 'El huésped quiere 2 personas y 3 noches. El motor:',
  exampleSteps: [
    'Recibe las fechas.',
    'Consulta disponibilidad.',
    'Encuentra una habitación disponible.',
    'Aplica la tarifa configurada.',
    'Calcula las condiciones.',
    'Registra los datos.',
    'Crea la reserva.',
  ],
  exampleClose: 'El propietario no necesita hacer manualmente cada uno de estos pasos. Es un ejemplo ilustrativo, no un establecimiento real.',
  useTitle: '¿Cómo puedes aprovechar Andario Booking Engine?',
  resultLabel: 'Resultado',
  uses: [
    {
      title: 'Ya tienes página web',
      body: 'Puedes incorporar el motor para que tu página no solo informe, sino que también permita iniciar el proceso de reserva.',
      result: 'Tu web se convierte en un canal propio de reservas.',
    },
    {
      title: 'Dependes mucho de Booking.com',
      body: 'Puedes mantener Booking.com y otras OTAs mientras construyes un canal propio. Andario Booking Engine actualmente no sincroniza OTAs.',
      result: 'No tienes que abandonar tus canales actuales para empezar a desarrollar el canal directo.',
    },
    {
      title: 'Recibes muchas consultas por WhatsApp',
      body: 'Puedes utilizar tu web como un punto donde el huésped consulte disponibilidad y avance en la reserva. WhatsApp sigue siendo conversación: reservar dentro del chat todavía no está activo.',
      result: 'Parte de las consultas que hoy requieren explicación manual pueden iniciar por un proceso estructurado.',
    },
    {
      title: 'Tienes un hostal con camas',
      body: 'El motor puede representar camas como recurso reservable cuando el establecimiento está configurado de esa manera.',
      result: 'Puedes trabajar con la realidad operativa de un hostal.',
    },
    {
      title: 'Tienes un hotel pequeño',
      body: 'Puedes trabajar con habitaciones, tarifas, disponibilidad y reservas desde una lógica central.',
      result: 'La reserva deja de depender de que alguien recuerde cada dato.',
    },
    {
      title: 'Tienes cabañas, apartamentos o villas',
      body: 'El concepto de unidad reservable permite adaptar el motor a diferentes tipos de alojamiento cuando el producto puede representarlos.',
      result: 'La unidad se parece a lo que realmente vendes.',
    },
  ],
  otaTitle: 'No tienes que abandonar Booking.com.',
  otaLead: 'Andario Booking Engine no busca obligarte a dejar las OTAs.',
  otaBody: 'Puedes seguir utilizando tus canales actuales y, al mismo tiempo, construir un canal propio.',
  otaExternalLabel: 'Canales externos',
  otaExternal: ['Booking.com', 'Airbnb', 'Otros'],
  otaOwnLabel: 'Canal propio',
  otaOwn: ['Tu página web', 'Andario Booking Engine'],
  otaSync: 'Andario Booking Engine actualmente no sincroniza OTAs.',
  otaNote: 'El objetivo es sumar infraestructura propia, no eliminar automáticamente tus canales actuales.',
  organizeTitle: '¿Qué organiza el motor?',
  doesLabel: 'Qué hace',
  whyLabel: 'Por qué te importa',
  groups: [
    {
      title: 'Catálogo',
      items: [
        {
          name: 'Establecimiento, unidades y servicios',
          does: 'Describe el alojamiento, sus habitaciones o camas y lo que ofrece.',
          why: 'La reserva parte de lo que realmente vendes.',
        },
      ],
    },
    {
      title: 'Disponibilidad',
      items: [
        {
          name: 'Fechas, recursos y conflictos',
          does: 'Consulta qué unidades siguen libres para las fechas que busca el huésped.',
          why: 'Permite saber qué puedes vender sin revisar todo a mano.',
        },
      ],
    },
    {
      title: 'Tarifas',
      items: [
        {
          name: 'Precios, moneda, vigencia e impuestos',
          does: 'Aplica los precios configurados para cada unidad.',
          why: 'El precio no depende de recordarlo en cada conversación.',
        },
      ],
    },
    {
      title: 'Reservas',
      items: [
        {
          name: 'Huésped, unidad, fechas, estado y origen',
          does: 'Registra la información de la reserva en un mismo lugar.',
          why: 'Te permite identificar de dónde llegó cuando ese origen está registrado.',
        },
      ],
    },
    {
      title: 'Administración',
      items: [
        {
          name: 'Configuración, reglas y acceso',
          does: 'Permite aplicar las condiciones configuradas para tu alojamiento.',
          why: 'El equipo opera con las mismas reglas, no con una versión distinta en cada chat.',
        },
      ],
    },
  ],
  dayTitle: '¿Qué cambia en tu día a día?',
  benefits: [
    {
      audience: 'Para quien dirige',
      points: [
        'Más control sobre el canal propio.',
        'Información organizada.',
        'Menos trabajo repetitivo.',
        'Más claridad sobre las reservas.',
        'Una base para crecer.',
      ],
    },
    {
      audience: 'Para el equipo',
      points: ['Un proceso estructurado.', 'Menos información repetida.', 'Reservas registradas.', 'Información consistente.'],
    },
    {
      audience: 'Para el huésped',
      points: ['Un recorrido más claro.', 'Consulta de disponibilidad.', 'Información ordenada.', 'Un proceso digital más sencillo.'],
    },
  ],
  demandTitle: 'Un motor de reservas no genera demanda por sí solo.',
  demand: [
    'El Booking Engine proporciona la infraestructura para que tu alojamiento pueda recibir reservas desde un canal propio.',
    'Para atraer huéspedes también necesitas visibilidad, contenido, una buena presencia digital y una estrategia comercial.',
  ],
  demandNote: 'Por eso puede trabajar junto a Andario Web, Visibility, Content, Connect y Growth. No necesitas contratarlo todo.',
  companions: [
    { label: 'Andario Web', routeId: 'andario-web' },
    { label: 'Andario Visibility', routeId: 'andario-visibility' },
    { label: 'Andario Content', routeId: 'andario-content' },
    { label: 'Andario Connect', routeId: 'andario-connect' },
    { label: 'Andario Growth', routeId: 'andario-growth' },
  ],
  ecosystemTitle: 'Puede acompañar al resto, sin ser obligatorio.',
  ecosystem: [
    { name: 'Andario Web', body: 'Te encuentran y conocen tu alojamiento.' },
    { name: 'Booking Engine', body: 'Reservan.' },
    { name: 'Connect', body: 'Conversas y acompañas.' },
    { name: 'Growth', body: 'Entiendes qué funciona.' },
  ],
  ecosystemNote: 'Puedes comenzar con Booking Engine o con otra solución y evolucionar según las necesidades de tu alojamiento.',
  flowTitle: 'Así funciona una reserva.',
  flowIntro: 'Ocho pasos, en el orden en que los vive un huésped.',
  flow: [
    { title: 'El huésped busca fechas', body: 'Indica cuándo quiere llegar y salir.' },
    { title: 'El motor consulta disponibilidad', body: 'Revisa qué sigue libre.' },
    { title: 'Se muestran las opciones disponibles', body: 'Solo aparece lo que sí se puede reservar.' },
    { title: 'El huésped elige', body: 'Selecciona la unidad que le sirve.' },
    { title: 'Se calculan las condiciones configuradas', body: 'Se aplican la tarifa y las reglas del alojamiento.' },
    { title: 'Se registran sus datos', body: 'Queda la información necesaria para la reserva.' },
    { title: 'Se crea la reserva', body: 'El alojamiento la recibe en un mismo registro.' },
    { title: 'Se confirma según la configuración', body: 'El cierre sigue la forma de pago que el alojamiento tenga activa.' },
  ],
  reservationTitle: 'Así se lee una reserva.',
  reservationNote: 'Ejemplo ilustrativo. No corresponde a un huésped real ni a una captura del producto.',
  reservation: [
    { label: 'Reserva', value: 'AND-000123' },
    { label: 'Huésped', value: 'María González' },
    { label: 'Llegada', value: '12 oct' },
    { label: 'Salida', value: '15 oct' },
    { label: 'Unidad', value: 'Habitación privada' },
    { label: 'Huéspedes', value: '2' },
    { label: 'Tarifa', value: 'Estándar' },
    { label: 'Estado', value: 'Confirmada' },
    { label: 'Origen', value: 'Sitio web' },
  ],
  todayTitle: 'Lo que puedes utilizar hoy y lo que estamos construyendo.',
  availableLabel: 'Disponible hoy',
  roadmapLabel: 'En evolución',
  todayItems: ['Canal web', 'Disponibilidad', 'Tarifas', 'Reservas', 'Administración'],
  laterItems: [
    'WhatsApp como canal de reserva',
    'Instagram',
    'Facebook',
    'Google',
    'Automatización ampliada',
    'Asistente de IA',
    'Otras integraciones',
  ],
  honesty: 'Preferimos decirte claramente qué puedes utilizar hoy y qué está en evolución. Registrar un origen no significa que ese canal ya reserve solo.',
  trustTitle: 'Una operación diseñada con seguridad en mente.',
  trustBody: 'El motor cuida la reserva con controles de operación. No publicamos el detalle técnico de esa protección.',
  trustPoints: [
    'Validación de operaciones',
    'Control de disponibilidad',
    'Reglas del negocio',
    'Separación entre establecimientos',
    'Control de acceso administrativo',
    'Registro de acciones cuando está disponible',
  ],
  trustHonest: 'No existe un sistema infalible. Sí existe una operación pensada para que cada alojamiento trabaje con sus propias reglas.',
  whoTitle: 'Para alojamientos independientes.',
  whoBody: 'Hostales, hoteles pequeños, posadas, apartamentos, cabañas, villas y alojamientos rurales.',
  whoQuestion: '¿Tu alojamiento vende habitaciones, camas o unidades completas?',
  whoAnswer: 'El motor está diseñado para adaptarse al tipo de unidad reservable que utiliza tu negocio, cuando el producto puede representarla.',
  whoTypes: ['Hostales', 'Hoteles pequeños', 'Posadas', 'Apartamentos turísticos', 'Apartahoteles', 'Cabañas', 'Villas', 'Alojamientos rurales'],
  whoNot:
    'Si buscas un sistema corporativo para una gran cadena hotelera con múltiples integraciones empresariales, Andario Booking Engine puede no ser el punto de partida adecuado.',
  techTitle: 'No necesitas saber de tecnología.',
  tech: [
    'Andario se encarga de la parte tecnológica.',
    'Te ayudamos a entender y configurar el motor según la forma en que funciona tu alojamiento.',
  ],
  techMark: 'Tú conoces tu negocio. Nosotros te ayudamos con la tecnología.',
  pioneer:
    'BARUCH Hostal, en Buritaca, Colombia, es el establecimiento pionero de Andario Hospitality y uno de los primeros escenarios reales donde Andario Booking Engine está evolucionando.',
  startTitle: '¿Qué necesitamos para empezar?',
  startNote: 'Andario acompaña el proceso. No es una configuración automática.',
  startSteps: [
    { title: 'Conocer tu alojamiento', body: 'Qué tipo de establecimiento tienes.' },
    { title: 'Entender cómo reservas hoy', body: 'WhatsApp, OTAs, recepción o una mezcla.' },
    { title: 'Identificar unidades', body: 'Habitaciones, camas o unidades completas.' },
    { title: 'Configurar tarifas y reglas', body: 'Precios y condiciones de tu operación.' },
    { title: 'Definir el canal propio', body: 'Hoy, el punto de partida es la web.' },
    { title: 'Probar el proceso', body: 'Recorremos una reserva de ejemplo.' },
    { title: 'Ponerlo en marcha', body: 'El canal queda listo para usarse.' },
  ],
  finalTitle: '¿Quieres saber cómo funcionaría en tu alojamiento?',
  finalBody:
    'Cuéntanos qué tipo de alojamiento tienes, cómo recibes reservas actualmente y qué te gustaría mejorar. Te mostramos cómo podría encajar Andario Booking Engine.',
  finalMicro: 'Sin compromiso. Primero entendemos tu alojamiento.',
};
