import type { BookingEngineContent } from '@/content/types';

export const bookingEngineEs: BookingEngineContent = {
  support: 'Tu huésped consulta disponibilidad, elige una opción y realiza su reserva en un proceso simple y seguro.',
  primaryCta: 'Ver cómo funciona',
  talkCta: 'Hablar con Andario',
  points: [
    'Para hostales, hoteles pequeños y alojamientos independientes',
    'Tu propio canal de reservas',
    'Más control sobre tu negocio',
  ],
  sampleNote: 'Ejemplo de interfaz. No es un alojamiento ni una tarifa real.',
  heroImage: '/booking-engine/hero-devices-es.jpg',
  heroAlt: 'Portátil y teléfono con un ejemplo de la página de reservas.',
  adminImage: '/booking-engine/admin-devices-es.jpg',
  adminAlt: 'Tableta y teléfono con un ejemplo del panel de reservas.',
  sampleName: 'La Casona del Mar',
  sampleNav: ['Inicio', 'Habitaciones', 'Experiencias', 'Contacto'],
  datesLabel: 'Selecciona tus fechas',
  bookLabel: 'Reservar',
  nightLabel: '/ noche',
  rooms: [
    { name: 'Habitación Doble', detail: 'Vista al mar', price: '$130' },
    { name: 'Habitación Superior', detail: 'Vista al jardín', price: '$160' },
    { name: 'Suite Familiar', detail: 'Hasta 4 personas', price: '$220' },
  ],
  webEyebrow: 'Tu web presenta. Nuestro Booking Engine recibe la reserva.',
  webTitle: 'Convierte tu página web en un canal de reservas.',
  webBody:
    'Tu web muestra tu alojamiento, tus espacios y lo que lo hace especial. Andario Booking Engine hace posible que tus huéspedes puedan reservar directamente, sin intermediarios.',
  webLink: 'Así funciona',
  presentCard: {
    title: 'Tu página web',
    role: 'Presenta tu alojamiento',
    points: ['Habitaciones y unidades', 'Fotos y descripciones', 'Servicios y experiencias', 'Ubicación', 'Genera confianza'],
  },
  reserveCard: {
    title: 'Andario Booking Engine',
    role: 'Hace posible la reserva',
    points: ['Disponibilidad en tiempo real', 'Tarifas y opciones', 'Datos del huésped', 'Reserva confirmada', 'Toda la información organizada'],
  },
  consultEyebrow: 'Menos conversaciones repetitivas. Más reservas organizadas.',
  consultTitle: 'De muchas consultas a un proceso simple.',
  consultBody:
    'Tu huésped puede consultar disponibilidad y reservar en pocos pasos, mientras tú te enfocas en lo más importante: ofrecer una gran experiencia.',
  beforeTitle: 'Antes: todo por mensajes',
  beforeMessages: [
    { text: 'Hola, ¿tienen disponibilidad?', time: '09:12' },
    { text: 'Sí, un momento…', time: '09:14' },
    { text: '¿Cuánto cuesta?', time: '09:16' },
    { text: '¿Qué incluye?', time: '09:18' },
    { text: '¿Cómo puedo reservar?', time: '09:21' },
  ],
  afterTitle: 'Con Andario Booking Engine',
  afterSteps: [
    'El huésped consulta disponibilidad',
    'Ve las opciones y precios',
    'Elige su habitación',
    'Deja sus datos y confirma',
    'La reserva queda registrada',
  ],
  adminEyebrow: 'Todo organizado en un solo lugar',
  adminTitle: 'Gestiona tus reservas de forma simple y clara.',
  adminBody: 'Recibe, consulta y organiza todas tus reservas desde un panel pensado para tu alojamiento.',
  adminMenu: ['Inicio', 'Reservas', 'Disponibilidad', 'Tarifas', 'Huéspedes'],
  adminTabs: ['Todas', 'Pendientes', 'Confirmadas'],
  adminColumns: ['Reserva', 'Fechas', 'Estado'],
  adminRows: [
    { id: 'RMND-000123', dates: '12 oct – 15 oct', status: 'Confirmada', done: true },
    { id: 'RMND-000124', dates: '18 oct – 20 oct', status: 'Pendiente', done: false },
    { id: 'RMND-000125', dates: '8 oct – 9 oct', status: 'Confirmada', done: true },
  ],
  confirmTitle: 'Confirmación de reserva',
  confirmId: 'RMND-000123',
  confirmLines: ['12 oct – 15 oct', 'Habitación Doble', '2 huéspedes'],
  detailsLabel: 'Ver detalles',
  adminPoints: [
    { title: 'Calendario de disponibilidad', body: 'Siempre actualizado' },
    { title: 'Reservas organizadas', body: 'Con estados y detalles' },
    { title: 'Información de huéspedes', body: 'Todo en un solo lugar' },
    { title: 'Tarifas y reglas', body: 'Según tus necesidades' },
  ],
  directEyebrow: 'Construye el canal directo',
  directTitle: 'Más reservas para tu alojamiento.',
  directBody:
    'Andario Booking Engine no genera demanda por sí solo. Convierte tu presencia digital en un canal donde esos huéspedes pueden reservar directamente.',
  directLink: 'Conoce cómo crecer tu canal directo',
  growthTitle: 'Tu crecimiento ocurre cuando:',
  growthSteps: [
    { title: 'Más personas te encuentran', body: 'Web + Visibility + Content' },
    { title: 'Más personas se interesan', body: 'Web + contenido + confianza' },
    { title: 'Pueden reservar', body: 'Andario Booking Engine' },
    { title: 'Tienes más información', body: 'Andario Growth' },
  ],
  otaEyebrow: 'No tienes que abandonar Booking.com',
  otaTitle: 'Úsalo junto con otros canales.',
  otaBody: 'Puedes seguir utilizando Booking.com, Airbnb y otros canales mientras construyes tu propio canal de reservas.',
  otaChannels: ['Booking.com', 'Airbnb', 'Otros canales'],
  otaOwnTitle: 'Tu página web con Andario Booking Engine',
  otaOwnNote: 'Unidades conectadas',
  typesEyebrow: 'Hecho para diferentes tipos de alojamientos',
  typesTitle: 'Funciona para tu alojamiento.',
  typesBody: 'Andario Booking Engine se adapta a la forma en que vendes tus espacios.',
  types: [
    { name: 'Hostales', detail: 'Habitaciones o camas', image: '/booking-engine/stay-hostel.jpg', alt: 'Habitación de hostal con literas de madera' },
    { name: 'Hoteles pequeños', detail: 'Habitaciones y tarifas', image: '/booking-engine/stay-hotel.jpg', alt: 'Habitación de un hotel pequeño' },
    { name: 'Cabañas', detail: 'Unidades completas', image: '/booking-engine/stay-cabin.jpg', alt: 'Cabaña de madera entre árboles' },
    { name: 'Apartamentos', detail: 'Unidades independientes', image: '/booking-engine/stay-apartment.jpg', alt: 'Sala y habitación de un apartamento turístico' },
  ],
  coastAlt: 'Terraza frente al mar al atardecer',
  processEyebrow: 'Te acompañamos en cada paso',
  processTitle: 'Así es el proceso.',
  processBody: 'Nos encargamos de la configuración para que puedas empezar a recibir reservas sin complicaciones.',
  processSteps: ['Conocemos tu alojamiento', 'Configuramos el motor de reservas', 'Probamos todo contigo', 'Lo ponemos en marcha'],
  finalEyebrow: '¿Quieres ver cómo funcionaría en tu alojamiento?',
  finalTitle: 'Conversemos sobre tu canal de reservas.',
  finalBody: 'Cuéntanos qué tipo de alojamiento tienes y cómo recibes reservas actualmente. Te mostramos cómo podría encajar Andario Booking Engine.',
  finalCta: 'Quiero conocer Booking Engine',
};
