import type { BookingEngineContent } from '@/content/types';

export const bookingEngineEs: BookingEngineContent = {
  support:
    'Centraliza disponibilidad, tarifas, unidades, huéspedes y reservas en una tecnología diseñada para alojamientos independientes. Empieza con tu canal web y evoluciona hacia un ecosistema de reservas más conectado.',
  primaryCta: 'Quiero conocer Booking Engine',
  talkCta: 'Hablar con Andario',
  whatsappCta: 'Hablar por WhatsApp',
  availableLabel: 'Disponible',
  roadmapLabel: 'Roadmap',
  hubCaption:
    'El sitio web entra hoy al motor. WhatsApp, Instagram, Facebook, Google y otros canales aparecen como evolución: todavía no son integraciones de reserva activas.',
  hubCore: 'Andario Booking Engine',
  hubChannels: [
    { name: 'Sitio web', status: 'available' },
    { name: 'WhatsApp', status: 'roadmap' },
    { name: 'Instagram', status: 'roadmap' },
    { name: 'Facebook', status: 'roadmap' },
    { name: 'Google', status: 'roadmap' },
    { name: 'Otros', status: 'roadmap' },
  ],
  hubOutcomes: ['Disponibilidad', 'Tarifas', 'Inventario', 'Huéspedes', 'Reservas', 'Origen'],
  problemPoints: [
    'Las reservas llegan desde distintos lugares.',
    'La disponibilidad cuesta de controlar cuando cada canal va por su lado.',
    'La misma información se copia más de una vez.',
    'Las consultas se resuelven a mano.',
    'El proceso queda repartido entre personas y herramientas.',
    'Cuesta ver de dónde salió cada reserva.',
    'La operación se entiende tarde, cuando ya hay que corregir.',
  ],
  beforeTitle: 'Cuando cada canal trabaja aparte',
  beforeCaption: 'No es la situación de todos los alojamientos. Aparece cuando la reserva no tiene un lugar común.',
  beforeChannels: ['Sitio web', 'WhatsApp', 'Recepción', 'OTAs'],
  beforeResult: 'Procesos dispersos',
  afterTitle: 'Con una lógica central',
  afterCaption: 'Los puntos de contacto pueden convivir. La reserva se apoya en el mismo motor.',
  afterChannels: ['Sitio web', 'WhatsApp', 'Otros canales'],
  afterResult: 'Inventario y reservas',
  valueTitle: 'Una sola lógica para organizar tu operación de reservas.',
  valueBody:
    'Andario Booking Engine está diseñado para reunir lo que un alojamiento necesita para reservar, sin pedirte que entiendas un sistema técnico.',
  valueItems: [
    'Disponibilidad',
    'Inventario',
    'Unidades',
    'Tarifas',
    'Huéspedes',
    'Reservas',
    'Reglas',
    'Estados',
    'Pagos según la configuración',
    'Origen del canal',
    'Administración',
  ],
  exactTitle: '¿Qué es exactamente?',
  exactBody:
    'Es la pieza donde vive la operación de reservar: qué se puede vender, en qué condiciones y qué quedó reservado. Este sitio corporativo solo lo explica. No consulta disponibilidad ni crea reservas.',
  centralTitle: 'Qué centraliza',
  centralIntro: 'Doce piezas de la operación, en lenguaje de alojamiento.',
  central: [
    { title: 'Establecimiento', body: 'La configuración del alojamiento.' },
    { title: 'Unidades', body: 'Habitaciones y otras unidades reservables.' },
    { title: 'Inventario', body: 'Los recursos que se pueden vender.' },
    { title: 'Disponibilidad', body: 'Qué sigue libre según fechas y recursos.' },
    { title: 'Tarifas', body: 'Cómo se configuran y se aplican los precios.' },
    { title: 'Huéspedes', body: 'La información ligada a cada reserva.' },
    { title: 'Reservas', body: 'La creación y el seguimiento de cada reserva.' },
    { title: 'Reglas', body: 'Las condiciones que ordenan la operación.' },
    { title: 'Estados', body: 'En qué punto está cada reserva.' },
    { title: 'Pagos', body: 'La lógica de pago según lo que el establecimiento tenga configurado.' },
    { title: 'Origen', body: 'De qué canal proviene la reserva.' },
    { title: 'Administración', body: 'La gestión operativa del establecimiento.' },
  ],
  featuresTitle: 'Todo lo que necesitas para construir un canal propio de reservas.',
  featuresIntro: 'Agrupado por lo que le importa al alojamiento, no como una lista técnica.',
  featuresCta: 'Quiero conocer Andario Booking Engine',
  doesLabel: 'Qué hace',
  whyLabel: 'Por qué importa',
  groups: [
    {
      title: 'Catálogo e inventario',
      items: [
        {
          name: 'Establecimiento',
          does: 'Guarda la identidad y la configuración del alojamiento.',
          why: 'La reserva parte de un establecimiento concreto, no de una ficha genérica.',
        },
        {
          name: 'Unidades y camas',
          does: 'Describe tipos de unidad, habitaciones y camas cuando el alojamiento vende plazas.',
          why: 'Un hostal con dormitorios y un hotel pequeño no reservan de la misma forma.',
        },
        {
          name: 'Servicios e imágenes',
          does: 'Asocia amenities e imágenes a lo que se ofrece.',
          why: 'El huésped ve una opción reconocible antes de reservar.',
        },
      ],
    },
    {
      title: 'Disponibilidad',
      items: [
        {
          name: 'Búsqueda por fechas',
          does: 'Consulta qué se puede reservar entre una llegada y una salida.',
          why: 'La respuesta sale de la misma información, no de una hoja aparte.',
        },
        {
          name: 'Recursos y conflictos',
          does: 'Tiene en cuenta unidades ya ocupadas y evita vender el mismo recurso dos veces.',
          why: 'Ayuda a que la reserva trabaje con inventario real.',
        },
      ],
    },
    {
      title: 'Tarifas',
      items: [
        {
          name: 'Precios configurados',
          does: 'Aplica tarifas por tipo de unidad, moneda y vigencia.',
          why: 'El precio no depende de que alguien lo recuerde en cada conversación.',
        },
        {
          name: 'Impuestos',
          does: 'Suma los impuestos que el establecimiento tenga configurados.',
          why: 'La condición de la reserva queda más completa.',
        },
      ],
    },
    {
      title: 'Reservas',
      items: [
        {
          name: 'Alta de la reserva',
          does: 'Registra huésped, unidad, fechas, estado y origen.',
          why: 'La reserva deja de vivir solo en un mensaje.',
        },
        {
          name: 'Pagos según configuración',
          does: 'Confirma el pago con las capacidades que el establecimiento tenga activas.',
          why: 'El cobro sigue la regla del alojamiento, no una promesa genérica.',
        },
      ],
    },
    {
      title: 'Administración',
      items: [
        {
          name: 'Configuración',
          does: 'Permite ajustar establecimiento, catálogo, tarifas, impuestos y reglas.',
          why: 'El equipo opera desde un mismo lugar.',
        },
        {
          name: 'Acceso del equipo',
          does: 'Separa quién administra cada establecimiento.',
          why: 'La operación no queda abierta para cualquiera.',
        },
      ],
    },
  ],
  flowTitle: 'Cómo funciona una reserva',
  flowIntro: 'Ocho pasos, en el orden en que los vive un huésped.',
  flow: [
    { title: 'El huésped busca', body: 'Indica fechas y a quién quiere alojar.' },
    { title: 'El motor consulta disponibilidad', body: 'Revisa qué recursos siguen libres.' },
    { title: 'Se muestran opciones', body: 'Aparecen las unidades que sí se pueden reservar.' },
    { title: 'El huésped selecciona', body: 'Elige la opción que le sirve.' },
    { title: 'Se calculan las condiciones', body: 'Tarifa e impuestos configurados se resuelven en el motor.' },
    { title: 'Se registran los datos', body: 'Quedan los datos necesarios para la reserva.' },
    { title: 'Se crea la reserva', body: 'El inventario queda comprometido con esa solicitud.' },
    { title: 'Se confirma según la configuración', body: 'El cierre sigue la forma de pago que el alojamiento tenga activa.' },
  ],
  reservationTitle: 'Así se lee una reserva',
  reservationNote: 'Ejemplo ilustrativo. No corresponde a un huésped real ni a una captura del producto.',
  reservation: [
    { label: 'Reserva', value: 'AND-000123' },
    { label: 'Huésped', value: 'María González' },
    { label: 'Llegada', value: '12 oct' },
    { label: 'Salida', value: '15 oct' },
    { label: 'Unidad', value: 'Habitación privada' },
    { label: 'Huéspedes', value: '2' },
    { label: 'Tarifa', value: 'Estándar' },
    { label: 'Estado', value: 'Confirmada' },
    { label: 'Origen', value: 'Sitio web' },
  ],
  channelsTitle: 'Una lógica central. Diferentes puntos de contacto.',
  channelsBody:
    'Conectar un canal significa que la reserva nazca ahí. Registrar el origen de una reserva no es lo mismo: el equipo puede anotar de dónde vino, aunque ese canal todavía no reserve por sí solo.',
  channels: [
    {
      name: 'Sitio web',
      status: 'available',
      note: 'Es el canal propio de partida. El sitio puede abrir el motor; la disponibilidad y la reserva se quedan en el motor.',
    },
    {
      name: 'WhatsApp',
      status: 'roadmap',
      note: 'Hoy acompaña la conversación. Reservar dentro de WhatsApp todavía no está activo.',
    },
    {
      name: 'Instagram',
      status: 'roadmap',
      note: 'Aparece en la arquitectura futura. No es una integración de reservas en marcha.',
    },
    {
      name: 'Facebook',
      status: 'roadmap',
      note: 'Misma condición: previsto, no operativo como canal de reserva.',
    },
    {
      name: 'Google',
      status: 'roadmap',
      note: 'No está conectado como canal de reserva.',
    },
    {
      name: 'Asistente de IA',
      status: 'roadmap',
      note: 'Es una evolución posterior. Esta página no lo presenta como disponible.',
    },
  ],
  rolesTitle: 'No son lo mismo. Trabajan juntos.',
  rolesIntro: 'Tres piezas del ecosistema, con un trabajo distinto cada una.',
  roles: [
    {
      name: 'Andario Web',
      role: 'La presencia digital del alojamiento.',
      points: ['Informa', 'Inspira confianza', 'Presenta habitaciones y servicios', 'Recibe al visitante'],
    },
    {
      name: 'Andario Booking Engine',
      role: 'La lógica de reservas.',
      points: ['Disponibilidad', 'Tarifas', 'Inventario', 'Huéspedes, reservas, reglas y origen'],
    },
    {
      name: 'Andario Connect',
      role: 'El canal de conversación.',
      points: ['Conversar', 'Responder', 'Orientar', 'Acompañar al huésped'],
    },
  ],
  rolesFlow: ['Andario Web atrae e informa', 'Booking Engine gestiona la reserva', 'Connect acompaña la conversación'],
  rolesClose: 'Pueden sumarse de a poco. No hace falta contratar el ecosistema completo para empezar.',
  benefitsTitle: 'Qué cambia en el día a día',
  benefits: [
    {
      audience: 'Para quien dirige',
      points: [
        'Más control sobre el canal propio.',
        'La información de reservas en un solo lugar.',
        'Menos dependencia de procesos manuales.',
        'Más claridad sobre el origen de cada reserva.',
        'Una base para crecer el ecosistema digital cuando el negocio lo pida.',
      ],
    },
    {
      audience: 'Para el equipo',
      points: [
        'Un proceso más estructurado.',
        'Menos datos copiados en varios lados.',
        'Las reservas se ven en el mismo registro.',
        'La información se mantiene más consistente.',
      ],
    },
    {
      audience: 'Para el huésped',
      points: [
        'Un recorrido de reserva más claro.',
        'Disponibilidad que se puede consultar.',
        'La información de la estancia ordenada.',
        'Una experiencia digital coherente con la conversación.',
      ],
    },
  ],
  otaTitle: '¿Tengo que dejar Booking.com o Airbnb?',
  otaBody:
    'No necesariamente. Andario Booking Engine está pensado para ayudarte a construir y fortalecer un canal propio. Las OTAs pueden seguir en la estrategia comercial. El objetivo es que el establecimiento desarrolle una relación más directa con sus huéspedes y cuente con infraestructura propia para sus reservas. El motor no sincroniza OTAs mientras esa integración no exista.',
  whoTitle: 'Diseñado para alojamientos independientes.',
  whoBody:
    'La unidad reservable se adapta al establecimiento cuando el producto puede representarla: una habitación, una cama en un dormitorio o una unidad completa.',
  whoTypes: [
    'Hostales',
    'Hoteles pequeños',
    'Posadas',
    'Apartamentos turísticos',
    'Apartahoteles',
    'Cabañas',
    'Villas',
    'Alojamientos rurales',
    'Otros establecimientos pequeños',
  ],
  trustTitle: 'Tu operación merece una tecnología confiable.',
  trustBody:
    'El motor valida las operaciones, controla la disponibilidad y aplica las reglas del establecimiento. Cada alojamiento queda separado de los demás. El acceso administrativo está controlado y, donde ya existe, las acciones quedan registradas. No publicamos el detalle técnico de esa protección y no afirmamos que un sistema sea infalible.',
  trustPoints: [
    'Validación de cada operación',
    'Control de disponibilidad',
    'Reglas del negocio',
    'Separación entre establecimientos',
    'Acceso administrativo',
    'Registro de acciones cuando está disponible',
  ],
  evolutionTitle: 'Construido para crecer contigo.',
  evolutionBody:
    'Andario Booking Engine es un producto en evolución. Lo que ya opera el canal propio está marcado como disponible. Lo demás es roadmap.',
  evolution: [
    { label: 'Canal web propio', status: 'available' },
    { label: 'Disponibilidad', status: 'available' },
    { label: 'Tarifas', status: 'available' },
    { label: 'Reservas', status: 'available' },
    { label: 'Administración', status: 'available' },
    { label: 'Integraciones de canales', status: 'roadmap' },
    { label: 'Omnicanalidad', status: 'roadmap' },
    { label: 'Automatización ampliada', status: 'roadmap' },
    { label: 'IA', status: 'roadmap' },
  ],
  pioneerTitle: 'BARUCH Hostal, el escenario pionero',
  pioneerBody:
    'BARUCH Hostal es el establecimiento pionero de Andario Hospitality y uno de los primeros escenarios reales donde Andario Booking Engine está evolucionando.',
  diffTitle: 'Por qué encaja en un alojamiento independiente',
  diff: [
    { title: 'Especialización', body: 'Está pensado alrededor de alojamientos independientes, no de una cadena.' },
    { title: 'Simplicidad', body: 'La tecnología tiene que ordenar la operación, no añadirle otra capa confusa.' },
    { title: 'Tecnología propia', body: 'Forma parte de una plataforma desarrollada por Andario.' },
    { title: 'Evolución', body: 'Puede crecer por etapas, sin presentar el futuro como si ya estuviera encendido.' },
    { title: 'Ecosistema', body: 'Puede acompañar a Web, Visibility, Connect, Content y Growth cuando haga falta.' },
  ],
  startTitle: 'Empieza con lo que tu alojamiento necesita hoy.',
  startSteps: [
    { title: 'Conversemos', body: 'Entendemos tu establecimiento y cómo reservas hoy.' },
    { title: 'Definimos la configuración', body: 'Identificamos unidades, tarifas, reglas y el canal con el que conviene empezar.' },
    { title: 'Implementamos', body: 'Configuramos el motor y lo conectamos con el sitio cuando ese sea el paso.' },
    { title: 'Ponemos en marcha', body: 'Probamos el flujo y dejamos el canal preparado.' },
    { title: 'Evolucionamos', body: 'Sumamos capacidades cuando el negocio las necesite.' },
  ],
  startCta: 'Solicitar información sobre Booking Engine',
  finalTitle: 'Construye el canal propio de reservas de tu alojamiento.',
  finalBody: 'Cuéntanos cómo funciona hoy tu operación y te mostramos cómo podría encajar Andario Booking Engine.',
  finalCta: 'Solicitar información',
};
