import type { ConnectContent, FaqItem } from '@/content/types';

export const connectFaqsEs: FaqItem[] = [
  {
    q: '¿Qué es Andario Connect?',
    a: 'Una capa de comunicación y automatización para alojamientos. Conecta las conversaciones con el recorrido comercial y, cuando corresponde, con la reserva.',
  },
  {
    q: '¿Funciona con WhatsApp?',
    a: 'Sí, según la configuración del canal y las capacidades disponibles. WhatsApp es el canal. Connect es la capa que ordena la comunicación.',
  },
  {
    q: '¿Es un chatbot?',
    a: 'Puede incluir respuestas y flujos acordados, pero el servicio es más amplio: ordenar la comunicación y orientarla dentro del recorrido del huésped.',
  },
  {
    q: '¿Puede responder preguntas frecuentes?',
    a: 'Sí, cuando esas preguntas y sus respuestas forman parte del alcance.',
  },
  {
    q: '¿Puede responder de forma automática?',
    a: 'Puede automatizar respuestas y recorridos que se hayan definido. No responde “todo” por su cuenta.',
  },
  {
    q: '¿Puede llevar a un huésped hacia una reserva?',
    a: 'Puede orientar hacia el canal de reserva. La disponibilidad, las tarifas y la reserva viven en Andario Booking Engine cuando esa pieza forma parte del recorrido. Completar la reserva dentro del chat es una evolución prevista, no una función que esta página presente como productiva.',
  },
  {
    q: '¿Cuál es la diferencia entre Connect y Booking Engine?',
    a: 'Connect organiza la comunicación. Booking Engine gestiona la lógica de disponibilidad, tarifas, inventario y reserva, según las capacidades del motor.',
  },
  {
    q: '¿Puede capturar interesados?',
    a: 'Sí, cuando el flujo y la configuración lo permiten. No es un CRM.',
  },
  {
    q: '¿Puede hacer seguimiento?',
    a: 'Puede formar parte del alcance, con mensajes pertinentes y dentro de las reglas del canal.',
  },
  {
    q: '¿Puede enviar recordatorios?',
    a: 'Puede formar parte del alcance. No publicamos aquí una lista cerrada de avisos que el producto envíe hoy.',
  },
  {
    q: '¿Puede enviar confirmaciones?',
    a: 'Puede formar parte del alcance, según las acciones y la configuración disponibles.',
  },
  {
    q: '¿Puede reemplazar a una persona?',
    a: 'No. Ayuda con lo repetitivo. Las situaciones complejas siguen necesitando a alguien del equipo.',
  },
  {
    q: '¿Puedo automatizar todas las conversaciones?',
    a: 'No es recomendable ni siempre posible. La automatización se usa donde aporta. El criterio humano se queda donde importa.',
  },
  {
    q: '¿Necesito Andario Booking Engine?',
    a: 'No. Connect puede ordenar la comunicación sin el motor. La integración amplía el recorrido cuando está disponible y forma parte del alcance.',
  },
  {
    q: '¿Necesito Andario Web?',
    a: 'No. La web y Connect se complementan, pero se contratan por separado.',
  },
  {
    q: '¿Puedo seguir usando WhatsApp como hasta ahora?',
    a: 'Sí. Depende de cómo se configure el canal y de qué automatizaciones se acuerden.',
  },
  {
    q: '¿Puede conectarse con Instagram o Facebook?',
    a: 'Hoy no se presenta como una integración productiva. Puede formar parte de una evolución prevista.',
  },
  {
    q: '¿Andario Connect incluye inteligencia artificial?',
    a: 'El asistente de IA es una evolución prevista. Esta página no lo presenta como una función disponible.',
  },
  {
    q: '¿La IA puede inventar disponibilidad?',
    a: 'No debe hacerlo. En esa evolución, las respuestas sobre disponibilidad tendrían que consultar fuentes autorizadas y, cuando corresponda, el Booking Engine.',
  },
  {
    q: '¿Puede enviar mensajes de forma automática?',
    a: 'Sí, en flujos definidos y dentro de las políticas del canal. No es una herramienta de mensajes masivos.',
  },
  {
    q: '¿Cómo se cuida la información de los huéspedes?',
    a: 'La implementación debe limitar los datos al mínimo necesario, proteger accesos y credenciales, y seguir la política de privacidad. No es una certificación ni un dictamen legal.',
  },
  {
    q: '¿Las conversaciones se envían a Google Analytics?',
    a: 'No. No se envía el contenido de las conversaciones ni datos personales a la analítica. Solo eventos de la página, sin nombres, teléfonos ni mensajes.',
  },
  {
    q: '¿Puedo contratar solo Connect?',
    a: 'Sí. Los servicios de Andario se contratan por separado.',
  },
  {
    q: '¿Qué necesito para comenzar?',
    a: 'Datos del establecimiento, las preguntas que se repiten, cómo atienden hoy, el canal de WhatsApp y qué quieren ordenar.',
  },
  {
    q: '¿Cómo solicito información?',
    a: 'Por el formulario de contacto, por WhatsApp o con los botones de esta página. Conversar no obliga a contratar.',
  },
];

export const connectEs: ConnectContent = {
  support:
    'WhatsApp puede ser uno de los principales puntos de contacto de un alojamiento. Andario Connect ayuda a estructurar consultas, respuestas, seguimiento y orientación hacia la reserva para que la comunicación forme parte del recorrido digital del huésped.',
  audienceLine: 'Automatiza lo repetitivo. Mantén el criterio humano donde importa.',
  primaryCta: 'Conocer Andario Connect',
  problemCta: 'Quiero organizar mis conversaciones',
  bookingCta: 'Ver cómo se conectan comunicación y reservas',
  talkCta: 'Hablar con Andario',
  whatsappCta: 'Escribir por WhatsApp',
  scopeLabel: 'El alcance final se define según las necesidades del establecimiento y las capacidades disponibles.',
  exampleLabel: 'Ejemplo conceptual. No es una conversación real ni una integración en producción.',
  roadmapLabel: 'Evolución prevista',
  heroCaption: 'Un huésped pregunta. Connect orienta. La disponibilidad y la reserva siguen en el motor, cuando esa pieza forma parte del recorrido.',
  heroGuest: 'Huésped',
  heroGuestMsg: '¿Tienen disponibilidad mañana?',
  heroReply: 'Connect',
  heroReplyMsg: 'Claro. Puedo ayudarte a revisar el siguiente paso.',
  heroAction: 'Orientar hacia la disponibilidad',
  heroEngine: 'Booking Engine',
  heroAvailability: 'Disponibilidad',
  heroReserve: 'Reserva',
  questions: [
    '¿Tienen disponibilidad?',
    '¿Cuánto cuesta?',
    '¿Qué incluye?',
    '¿Dónde están?',
    '¿Cómo llego?',
    '¿Aceptan mascotas?',
    '¿Tienen habitaciones privadas?',
    '¿Puedo reservar por WhatsApp?',
  ],
  problems: [
    { title: 'Las mismas preguntas, una y otra vez', body: 'El equipo responde a mano lo que ya se explicó muchas veces.' },
    { title: 'Respuestas que no coinciden', body: 'Varias personas pueden contar la misma cosa de formas distintas.' },
    { title: 'Interesados sin continuidad', body: 'Una consulta queda abierta y nadie retoma el hilo.' },
    { title: 'El chat, aparte de la reserva', body: 'La conversación y el proceso de reserva no se hablan.' },
    { title: 'Información que se pierde', body: 'Fechas, preguntas y acuerdos quedan repartidos en mensajes.' },
    { title: 'Tiempo en lo repetitivo', body: 'El equipo atiende tareas que podrían tener una respuesta estable.' },
  ],
  problemNote: 'No todos los alojamientos viven esto. Son situaciones que pueden aparecer cuando WhatsApp sostiene buena parte de la atención.',
  journeyTitle: 'WhatsApp puede ser una puerta de entrada al viaje del huésped.',
  journeySteps: ['Descubre', 'Pregunta', 'WhatsApp', 'Información', 'Orientación', 'Reserva', 'Confirmación', 'Seguimiento'],
  journeyNote: 'Connect busca unir estas etapas. No toda pregunta termina en una reserva.',
  whatTitle: '¿Qué es Andario Connect?',
  whatBody:
    'Es una capa de comunicación y automatización para alojamientos. Conecta las conversaciones con el recorrido comercial y de reservas. Puede ayudar a responder preguntas frecuentes, registrar interesados, orientar hacia una reserva y acompañar con confirmaciones, recordatorios o seguimiento, según el alcance.',
  whatNote: 'El objetivo no es automatizar por automatizar. Es reducir tareas repetitivas y hacer más consistente la comunicación.',
  hubCaption: 'Consultas, orientación y seguimiento se encuentran en una comunicación más ordenada. El gráfico muestra relaciones, no un producto cerrado.',
  hubColumns: [
    { title: 'Consultas', points: ['Preguntas frecuentes', 'Información básica', 'Primera respuesta'] },
    { title: 'Reservas', points: ['Orientación', 'Canal de reserva', 'Siguiente paso'] },
    { title: 'Seguimiento', points: ['Continuidad', 'Recordatorios', 'Después de la consulta'] },
  ],
  autoTitle: 'Automatiza lo repetitivo. No automatices lo que necesita criterio.',
  autoBody: 'Una conversación puede dividirse entre lo que se repite y lo que pide a una persona. Esa división se acuerda. El sistema no clasifica solo cada caso.',
  autoRepeatTitle: 'Suele poder ordenarse',
  autoRepeat: ['Preguntas frecuentes', 'Información básica', 'Horarios', 'Ubicación', 'Servicios', 'Instrucciones', 'Mensajes de confirmación', 'Recordatorios', 'Seguimiento'],
  autoHumanTitle: 'Suele pedir a una persona',
  autoHuman: ['Casos especiales', 'Solicitudes complejas', 'Cambios fuera de las reglas', 'Situaciones sensibles', 'Decisiones comerciales', 'Excepciones'],
  autoNote: 'No afirmamos que cada mensaje se detecte solo. El equipo define qué se automatiza.',
  includesTitle: 'Qué puede incluir',
  includesIntro: 'Cada pieza se acuerda. No todos los proyectos incluyen todas las actividades.',
  whatLabel: 'Qué es',
  purposeLabel: 'Para qué sirve',
  exampleCardLabel: 'Ejemplo de uso',
  groups: [
    { title: 'WhatsApp Business', what: 'El canal de mensajes del establecimiento.', purpose: 'Acercar ese canal al recorrido digital.', example: 'Una consulta que hoy vive solo en el chat puede tener un siguiente paso claro.' },
    { title: 'Preguntas frecuentes', what: 'Respuestas estables a lo que se pregunta seguido.', purpose: 'Dar la misma información útil sin reescribirla cada vez.', example: 'Horario de llegada, cómo llegar o qué incluye la estadía.' },
    { title: 'Respuestas automatizadas', what: 'Mensajes definidos para momentos repetidos.', purpose: 'Bajar el trabajo manual donde la respuesta ya está clara.', example: 'Un saludo con las opciones más pedidas, dentro de lo acordado.' },
    { title: 'Captura de interesados', what: 'Un registro de la intención cuando el flujo lo permite.', purpose: 'Que una consulta no dependa solo de la memoria del chat.', example: 'Alguien pregunta por fechas futuras y queda identificado para un seguimiento.' },
    { title: 'Guía hacia la reserva', what: 'Una orientación al canal de reserva que corresponda.', purpose: 'Separar la conversación de la lógica de disponibilidad.', example: 'Después de las fechas, la persona sigue hacia el motor, si el alojamiento lo usa.' },
    { title: 'Confirmaciones', what: 'Información posterior a una acción relevante, cuando está configurada.', purpose: 'Dejar al huésped enterado de lo que ya ocurrió.', example: 'Un mensaje después de una reserva, si ese aviso forma parte del alcance.' },
    { title: 'Recordatorios', what: 'Un aviso antes de una etapa acordada.', purpose: 'Ayudar a que un paso no dependa de recordarlo a mano.', example: 'Un mensaje previo a la llegada, si el flujo y el canal lo permiten.' },
    { title: 'Seguimiento', what: 'Continuar una conversación que no cerró.', purpose: 'Retomar el interés sin perder el hilo.', example: 'Alguien dijo que consultaría y recibe un mensaje pertinente después.' },
  ],
  flowTitle: 'Una conversación, paso a paso.',
  flow: [
    { who: 'Huésped', line: 'Hola, quiero saber si tienen disponibilidad.' },
    { who: 'Connect', line: 'Claro. ¿Qué fechas necesitas?' },
    { who: 'Huésped', line: 'Del 12 al 15.' },
    { who: 'Connect', line: 'Voy a orientarte hacia la disponibilidad.' },
    { who: 'Booking Engine', line: 'Disponibilidad' },
    { who: 'Huésped', line: 'Elige una opción' },
    { who: 'Reserva', line: 'La reserva se gestiona en el motor.' },
    { who: 'Confirmación', line: 'El huésped recibe información del siguiente paso, si está configurado.' },
  ],
  flowNote: 'Ejemplo conceptual. Estos pasos no están todos conectados en producción. Reservar dentro de WhatsApp es una evolución prevista.',
  bookingTitle: 'Connect comunica. Booking Engine gestiona la reserva.',
  bookingBody:
    'Connect ordena la conversación y la intención. El motor consulta disponibilidad, calcula tarifas y crea la reserva, según sus capacidades. Connect no copia esa lógica.',
  bookingConnect: ['Comunicación', 'Preguntas', 'Orientación'],
  bookingEnginePoints: ['Disponibilidad', 'Tarifas', 'Inventario', 'Reserva'],
  bookingNote: 'Registrar que alguien escribió por WhatsApp no es una integración en vivo. Completar la reserva dentro del chat no se presenta como función actual.',
  webTitle: 'Tu web atrae. WhatsApp continúa la conversación.',
  webBody: 'Andario Web presenta el alojamiento. Connect puede continuar cuando la persona escribe. Son piezas distintas y se contratan por separado.',
  webSteps: ['Andario Web', 'Información', 'Interés', 'WhatsApp', 'Andario Connect', 'Orientación', 'Booking Engine'],
  webNote: 'Tener la web de Andario no es obligatorio para conversar sobre Connect.',
  checkTitle: 'Primero se puede ver dónde se traban las conversaciones.',
  checkBody: 'Digital Check puede mostrar fricciones de comunicación antes de automatizar. Connect trabaja después las áreas que se definan.',
  checkSteps: ['Digital Check', 'Diagnóstico', 'Fricciones', 'Connect', 'Estructura'],
  checkNote: 'El diagnóstico no es un paso obligatorio.',
  growthTitle: 'Las conversaciones también dejan señales.',
  growthBody: 'Andario Growth puede leer después eventos de la presencia digital, según lo que esté instrumentado. No lee el contenido privado de los chats.',
  growthPoints: ['Clics hacia WhatsApp', 'Acciones de la página', 'Origen del tráfico', 'Eventos de reserva disponibles'],
  growthNote: 'No prometemos una atribución completa ni un análisis del texto de las conversaciones.',
  leadTitle: 'No todas las conversaciones terminan en una reserva inmediata.',
  leadBody: 'A veces la persona pide información, consulta fechas lejanas o necesita pensarlo. Connect puede ayudar a dejar ese interés ordenado para un seguimiento, cuando el flujo lo permite.',
  leadSteps: ['Visitante', 'Consulta', 'Interés', 'Registro', 'Seguimiento', 'Reserva, si corresponde'],
  leadExamples: ['Pide información', 'Pregunta por fechas futuras', 'Consulta un grupo', 'Pregunta por una experiencia', 'Pide una condición especial'],
  leadNote: 'No es un CRM. No prometemos que cada interesado reserve.',
  followTitle: 'Una conversación que no cerró hoy no tiene por qué perderse.',
  followBody: 'El seguimiento retoma un hilo con un mensaje pertinente. No es una secuencia de avisos invasivos.',
  followSteps: ['Día 1 · Consulta', 'Día 1 · Información', 'Después · Seguimiento', 'Decisión', 'Reserva, si la persona sigue'],
  followNote: 'Todo mensaje automático debe respetar el consentimiento, las reglas del canal y la normativa que aplique.',
  confirmTitle: 'Confirmaciones',
  confirmBody: 'Ayudan a informar al huésped después de una acción relevante, cuando ese aviso está configurado. No publicamos aquí un catálogo fijo de eventos.',
  reminderTitle: 'Recordatorios',
  reminderBody: 'Pueden ayudar a que un paso acordado no dependa de la memoria. Entran en el alcance solo si el flujo y el canal lo permiten.',
  messagesNote: 'No inventamos avisos que el producto todavía no soporte para ese establecimiento.',
  faqLayerTitle: 'Las preguntas frecuentes pueden ser una primera capa de atención.',
  faqLayer: ['Pregunta', 'Respuesta frecuente', '¿Quedó resuelto?', 'Sí: la persona sigue', 'No: puede hablar con alguien'],
  faqLayerNote: 'Una respuesta automática no debe cerrar la puerta cuando hace falta una persona.',
  humanTitle: 'La automatización no reemplaza la hospitalidad. La acompaña.',
  humanBody: 'El huésped puede recibir una respuesta estable y, cuando el caso lo pide, seguir con alguien del equipo. Connect ayuda al equipo. No lo sustituye.',
  humanAuto: ['Preguntas básicas', 'Información', 'Recordatorios'],
  humanPerson: ['Situaciones especiales', 'Excepciones', 'Decisiones'],
  humanNote: 'La hospitalidad sigue siendo humana.',
  aiTitle: 'Evolución prevista: un asistente que entienda mejor el contexto.',
  aiBody:
    'Más adelante, Andario Connect contempla un asistente capaz de conversar con más naturalidad. Hoy no está disponible. Cuando exista, deberá consultar las fuentes autorizadas del establecimiento y, si corresponde, el Booking Engine para disponibilidad y reservas.',
  aiRules: ['No inventar disponibilidad', 'No inventar tarifas', 'No inventar reservas', 'No inventar políticas', 'No inventar datos del establecimiento'],
  aiNote: 'Esta sección describe una evolución prevista. No es una función actual.',
  securityTitle: 'La comunicación con tus huéspedes también necesita cuidado.',
  securityBody: 'Ordenar WhatsApp implica tratar datos de personas. El trabajo debe pedir solo lo necesario y proteger los accesos.',
  securityPoints: [
    'Datos limitados a lo que el flujo necesita',
    'Control de quién accede',
    'Credenciales protegidas',
    'Proveedores que correspondan al canal',
    'Consentimiento cuando haga falta',
    'Política de privacidad del sitio',
    'Sin datos sensibles de más',
    'Sin conversaciones ni datos personales en la analítica',
  ],
  securityNote: 'Esto no es una certificación ni un cumplimiento legal absoluto. La revisión jurídica, cuando haga falta, es aparte.',
  channelTitle: 'WhatsApp es el canal. Connect es la capa.',
  channelBody: 'WhatsApp Business pertenece a su propia plataforma. Andario no es dueño de WhatsApp. Connect aporta la lógica de comunicación que se acuerde encima de ese canal.',
  channelSteps: ['WhatsApp', 'Canal', 'Andario Connect', 'Lógica de comunicación', 'Recorrido comercial'],
  channelNote: 'Seguir usando el canal depende de su configuración y de las reglas de la plataforma.',
  otherChannelsTitle: 'Instagram y Facebook',
  otherChannelsBody: 'No se presentan como integraciones productivas. Pueden formar parte de una evolución prevista, no de lo que esta página ofrece hoy.',
  casesTitle: 'Situaciones ilustrativas',
  cases: [
    { title: 'Pregunta frecuente', quote: '¿A qué hora es el check-in?', steps: ['Pregunta', 'Respuesta frecuente', 'Persona informada'] },
    { title: 'Disponibilidad', quote: '¿Tienen habitación para este fin de semana?', steps: ['Consulta', 'Orientación', 'Booking Engine', 'Reserva, si sigue'] },
    { title: 'Información del alojamiento', quote: '¿Tienen restaurante?', steps: ['Pregunta', 'Información', 'Siguiente paso'] },
    { title: 'Seguimiento', quote: 'Voy a consultarlo y te aviso.', steps: ['Interesado', 'Seguimiento', 'Retoma la conversación'] },
    { title: 'Después de reservar', quote: 'La reserva ya existe.', steps: ['Reserva', 'Confirmación', 'Información útil', 'Recordatorio'] },
  ],
  casesNote: 'Ejemplos ilustrativos. No son conversaciones de un cliente ni resultados medidos.',
  ownerTitle: 'Qué puede cambiar para quien administra el alojamiento',
  owner: [
    { title: 'Menos tareas repetitivas', body: 'Las interacciones que se repiten pueden tener una respuesta acordada.' },
    { title: 'Comunicación más consistente', body: 'La misma pregunta puede recibir la misma información útil.' },
    { title: 'Más continuidad', body: 'El recorrido no depende solo de recordar cada chat.' },
    { title: 'Mejor enlace con la reserva', body: 'La conversación puede orientar hacia el canal de reserva.' },
    { title: 'Más orden', body: 'La comunicación entra en la estrategia, no se queda en una bandeja aparte.' },
    { title: 'Una base que puede crecer', body: 'La estructura puede ampliarse con el establecimiento, según el alcance.' },
  ],
  teamTitle: 'También está pensado para quien responde.',
  team: ['Menos preguntas repetidas', 'Más contexto del siguiente paso', 'Mejor continuidad entre turnos', 'La persona interviene donde de verdad importa'],
  teamNote: 'Connect ayuda al equipo. No propone reemplazarlo.',
  whoTitle: 'Para alojamientos donde WhatsApp ya forma parte del negocio.',
  whoTypes: ['Hostales', 'Hoteles pequeños', 'Posadas', 'Apartamentos turísticos', 'Apartahoteles', 'Cabañas', 'Villas', 'Alojamientos rurales', 'Otros establecimientos independientes'],
  whoFit: ['Llegan muchas preguntas repetidas.', 'WhatsApp es un canal importante.', 'Se pierden conversaciones.', 'El seguimiento es manual.', 'Responden varias personas.', 'Quieren unir comunicación y reserva.'],
  whenTitle: 'Cuándo suele tener sentido',
  when: [
    'Recibes las mismas preguntas casi todos los días.',
    'Muchas personas preguntan antes de reservar.',
    'El equipo responde todo a mano.',
    'Se pierden conversaciones.',
    'Los interesados no reciben continuidad.',
    'Quieres orientar consultas hacia tu canal de reserva.',
    'Quieres una capa de automatización, no un bot que lo haga todo.',
  ],
  notTitle: 'Qué Andario Connect no es',
  not: [
    { title: 'No es solo un chatbot', body: 'Es una capa de comunicación dentro del ecosistema.' },
    { title: 'No reemplaza la hospitalidad', body: 'Lo complejo puede seguir necesitando a una persona.' },
    { title: 'No es el Booking Engine', body: 'El motor gestiona disponibilidad, tarifas, inventario y reservas.' },
    { title: 'No garantiza reservas', body: 'Puede ordenar el recorrido. La reserva depende de más factores.' },
    { title: 'No es spam', body: 'Los mensajes tienen que ser pertinentes y respetar el canal.' },
    { title: 'No es un asistente de IA disponible', body: 'Esa pieza es una evolución prevista.' },
    { title: 'No es automatizar todo', body: 'Se automatiza donde aporta. El criterio se queda donde importa.' },
  ],
  processTitle: 'De conversaciones dispersas a una comunicación más estructurada.',
  process: [
    { title: 'Entendemos', body: 'Canales, preguntas, procesos y fricciones.' },
    { title: 'Estructuramos', body: 'Preguntas frecuentes, respuestas, flujos y criterios.' },
    { title: 'Conectamos', body: 'El recorrido con la web y, cuando corresponda, con el Booking Engine.' },
    { title: 'Automatizamos', body: 'Solo las automatizaciones acordadas.' },
    { title: 'Probamos', body: 'Respuestas, caminos, errores y excepciones.' },
    { title: 'Medimos', body: 'Interacciones y eventos disponibles, sin el texto de los chats.' },
    { title: 'Evolucionamos', body: 'Ajustamos los flujos y revisamos capacidades nuevas.' },
  ],
  receiveTitle: 'Una capa de comunicación pensada alrededor de su operación.',
  receive: [
    'Preguntas frecuentes definidas',
    'Estructura de respuestas',
    'Flujos de conversación acordados',
    'WhatsApp Business, según el canal',
    'Captura de interesados, si el flujo lo permite',
    'Orientación hacia la reserva',
    'Confirmaciones y recordatorios, si entran en el alcance',
    'Seguimiento',
    'Eventos de medición de la página, sin datos personales',
    'Una guía básica de operación',
  ],
  receiveNote: 'El alcance final se define según las necesidades y las capacidades disponibles. No incluye un asistente de IA ni una reserva dentro del chat.',
  ecosystemTitle: 'Connect conversa. Las otras piezas hacen otra cosa.',
  ecosystemSteps: ['Google o redes', 'Andario Web', 'WhatsApp', 'Andario Connect', 'Consulta o interés', 'Booking Engine', 'Reserva', 'Seguimiento', 'Growth'],
  ecosystemNote: 'Es una lectura del ecosistema, no un paquete obligatorio. Cada servicio se contrata por separado.',
  lifecycleTitle: 'La vida de una conversación',
  lifecycle: ['Descubrimiento', 'Consulta', 'Respuesta', 'Interés', 'Orientación', 'Reserva', 'Confirmación', 'Estancia', 'Seguimiento'],
  boundaryAutoTitle: 'Puede ordenarse',
  boundaryAuto: ['Preguntas frecuentes', 'Información básica', 'Horarios', 'Ubicación', 'Recordatorios', 'Confirmaciones', 'Seguimiento'],
  boundaryHumanTitle: 'Pide a una persona',
  boundaryHuman: ['Excepciones', 'Casos especiales', 'Cambios complejos', 'Situaciones sensibles', 'Decisiones comerciales'],
  boundaryNote: 'Esta división es una guía de trabajo. No es una clasificación automática.',
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal es el establecimiento pionero de Andario Hospitality. No publicamos volumen de conversaciones, automatización ni reservas de su comunicación.',
  finalTitle: 'Haz que tus conversaciones formen parte de tu estrategia digital.',
  finalBody: 'Organiza las preguntas frecuentes, automatiza tareas repetitivas y conecta la comunicación con el recorrido de tu huésped.',
  finalNote: 'Automatiza lo repetitivo. Mantén lo humano donde importa.',
};
