import type { ContentPage, FaqItem } from '@/content/types';

export const contentFaqsEs: FaqItem[] = [
  {
    q: '¿Qué es Andario Content?',
    a: 'Es el servicio de fotografía y contenido para alojamientos. Ayuda a mostrar y explicar el establecimiento, sus espacios, servicios, experiencias y destino.',
  },
  {
    q: '¿Andario toma las fotografías?',
    a: 'Puede coordinarse la producción según la ciudad y el alcance. No hay un equipo propio de fotografía en todas las ciudades. Si participa un tercero, no es un empleado de Andario.',
  },
  {
    q: '¿La fotografía está incluida siempre?',
    a: 'No. Entra solo si forma parte del alcance de ese establecimiento.',
  },
  {
    q: '¿Pueden trabajar con fotografías que ya tengo?',
    a: 'Sí. Ordenar y preparar material que ya existe puede formar parte del alcance.',
  },
  {
    q: '¿Crean textos para la página web?',
    a: 'Sí, según lo acordado. Los textos explican el alojamiento. No prometen una posición en Google.',
  },
  {
    q: '¿También crean contenido para redes?',
    a: 'Puede incluirse, adaptado al formato de cada canal. No es lo mismo que administrar las redes todos los días.',
  },
  {
    q: '¿Crean videos?',
    a: 'Puede incluirse video corto, según el alcance. No todos los proyectos lo llevan.',
  },
  {
    q: '¿Crean contenido sobre el destino?',
    a: 'Puede formar parte del servicio cuando hay información relevante y verificable. No se inventan datos del lugar.',
  },
  {
    q: '¿Hacen el manejo permanente de redes?',
    a: 'No se asume. Publicar y responder todos los días es otro alcance y se define aparte, si corresponde.',
  },
  {
    q: '¿Pueden organizar la galería?',
    a: 'Sí. Selección y orden para que las fotos cuenten el alojamiento, no una carpeta suelta.',
  },
  {
    q: '¿Pueden preparar las imágenes para la web?',
    a: 'Sí, según el alcance: formato, peso, tamaño y texto alternativo cuando haga falta. No prometemos una velocidad concreta sin medirla.',
  },
  {
    q: '¿El contenido ayuda al SEO?',
    a: 'Puede aportar material útil para una estrategia de visibilidad. No garantiza posiciones en Google.',
  },
  {
    q: '¿Andario Content incluye SEO?',
    a: 'Content puede crear material para Visibility. El trabajo de SEO y visibilidad es Andario Visibility.',
  },
  {
    q: '¿Cuál es la diferencia con Andario Web?',
    a: 'La web construye la estructura del sitio. Content produce y ordena el material con el que se comunica el alojamiento.',
  },
  {
    q: '¿Cuál es la diferencia con Visibility?',
    a: 'Content crea y organiza contenido. Visibility trabaja la capacidad del establecimiento de ser encontrado.',
  },
  {
    q: '¿Cuál es la relación con Connect?',
    a: 'El contenido puede ser la base de respuestas y mensajes, cuando esa pieza exista y el alcance lo permita.',
  },
  {
    q: '¿Cuál es la relación con Booking Engine?',
    a: 'Content ayuda a comprender el alojamiento antes de reservar. El motor gestiona la lógica de la reserva.',
  },
  {
    q: '¿Necesito contratar todos los servicios?',
    a: 'No. Se contratan por separado.',
  },
  {
    q: '¿Puedo comenzar solo con Content?',
    a: 'Sí.',
  },
  {
    q: '¿Qué necesito para comenzar?',
    a: 'Datos del establecimiento, qué quieres mostrar, el material que ya tienes y qué te falta.',
  },
  {
    q: '¿Pueden trabajar en cualquier ciudad?',
    a: 'La producción fotográfica depende de la ubicación y del alcance. Conversar no exige una sesión en el lugar.',
  },
  {
    q: '¿El contenido garantiza más reservas?',
    a: 'No. Puede mejorar cómo se presenta el alojamiento. La reserva depende de más factores.',
  },
  {
    q: '¿Pueden crear contenido de forma recurrente?',
    a: 'Puede definirse si entra en la propuesta. No es una producción mensual ilimitada.',
  },
  {
    q: '¿Puedo usar el contenido en varios canales?',
    a: 'Sí, según los derechos, los formatos y el alcance acordados. No se publica el mismo archivo igual en todos lados.',
  },
  {
    q: '¿Cómo solicito información?',
    a: 'Por el formulario, por WhatsApp o con los botones de esta página. Conversar no obliga a contratar.',
  },
];

const puede = 'Puede servir';
const alcance = 'Según alcance';

export const contentPageEs: ContentPage = {
  support:
    'Las fotografías, los textos y la forma de presentar un alojamiento influyen en cómo las personas imaginan su experiencia antes de reservar. Andario Content ayuda a crear material útil y coherente para mostrar el establecimiento, sus espacios, servicios, experiencias y destino.',
  audienceLine: 'Contenido pensado para alojamientos, no para publicar por publicar.',
  primaryCta: 'Mejorar mi contenido',
  problemCta: 'Mejorar cómo se ve mi alojamiento',
  photoCta: 'Quiero mejorar mis fotografías',
  scopeCta: 'Conocer Andario Content',
  talkCta: 'Hablar con Andario',
  whatsappCta: 'Escribir por WhatsApp',
  scopeLabel: 'El alcance final se define según lo que necesita el establecimiento.',
  exampleLabel: 'Ejemplo conceptual. No es material de un cliente ni una fotografía real.',
  heroCaption: 'Fotos, textos y video se encuentran en la experiencia que el huésped imagina antes de llegar.',
  heroLayers: ['Alojamiento', 'Fotos', 'Textos', 'Video', 'Experiencia', 'Huésped'],
  questions: [
    { q: '¿Cómo es realmente el lugar?', a: 'Fotografías de lo que existe.' },
    { q: '¿Cómo son las habitaciones o unidades?', a: 'Galería e información.' },
    { q: '¿Qué voy a encontrar?', a: 'Textos y servicios reales.' },
    { q: '¿Qué puedo hacer allí?', a: 'Experiencias y destino, cuando se pueden respaldar.' },
    { q: '¿El lugar encaja conmigo?', a: 'Información clara.' },
    { q: '¿Puedo confiar?', a: 'Una presentación coherente.' },
  ],
  decisionSteps: ['Pregunta', 'Contenido', 'Comprensión', 'Confianza', 'Decisión'],
  decisionNote: 'El contenido ayuda a imaginar. No decide solo la reserva.',
  whatTitle: '¿Qué es Andario Content?',
  whatBody:
    'Es el servicio de fotografía y contenido de Andario Hospitality. Construimos material visual y editorial para presentar el alojamiento, sus espacios, servicios, experiencias y destino. Está pensado para hospedaje y turismo, no para una marca genérica.',
  whatNote: 'El objetivo no es producir por producir. Es crear material que pueda usarse con coherencia en la web y en otros puntos de contacto.',
  anatomyCaption: 'El alojamiento, las personas y el destino se cuentan con fotografía, texto, video y un plan. Ninguna pieza sola es el servicio completo.',
  anatomyColumns: [
    { title: 'Alojamiento', points: ['Espacios', 'Servicios', 'Identidad'] },
    { title: 'Personas', points: ['Experiencia', 'Claridad', 'Confianza'] },
    { title: 'Destino', points: ['Contexto', 'Lugar', 'Cómo llegar'] },
  ],
  anatomyParts: ['Fotografía', 'Texto', 'Video', 'Destino', 'Planificación'],
  anatomyEquals: 'Ecosistema de contenido',
  photoTitle: 'Las fotografías no solo muestran espacios. Ayudan a anticipar una experiencia.',
  photoBody: 'Una foto de alojamiento puede ayudar a entender el espacio, la escala, el ambiente y los detalles. Solo se muestran servicios y experiencias que el establecimiento tiene de verdad.',
  photoCategories: [
    { title: 'Habitaciones o unidades', body: 'El espacio donde se duerme, con claridad.' },
    { title: 'Áreas comunes', body: 'Cómo se vive el establecimiento, si existen.' },
    { title: 'Servicios', body: 'Lo que el alojamiento ofrece de verdad, sin inventar piezas.' },
    { title: 'Detalles', body: 'Elementos que ayudan a reconocer la identidad.' },
    { title: 'Experiencias', body: 'Momentos que se pueden mostrar cuando corresponden.' },
    { title: 'Entorno', body: 'El lugar alrededor, cuando aporta y se puede respaldar.' },
  ],
  photoNote: 'No hay un catálogo fijo de piscina, restaurante o actividades. Entra lo que el alojamiento tiene.',
  coordinationTitle: 'La fotografía se coordina. No se promete un equipo en cada ciudad.',
  coordinationBody: 'Según la ubicación y el alcance, el trabajo puede incluir planificación, lista de tomas, coordinación, selección y preparación para publicar.',
  coordinationPoints: ['Planificación', 'Lista de tomas', 'Coordinación', 'Selección', 'Organización', 'Listo para publicar'],
  coordinationNote: 'Si la sesión la hace un tercero, no se presenta como personal de Andario.',
  optimizeTitle: 'Una buena fotografía también necesita estar lista para Internet.',
  optimizeBody: 'Preparar una imagen puede incluir formato, peso, tamaño, un nombre útil y texto alternativo cuando corresponda. También el orden dentro de la galería.',
  optimizeSteps: ['Foto de origen', 'Selección', 'Preparación', 'Web, redes o galería', 'Uso digital'],
  optimizeNote: 'No afirmamos una mejora de velocidad sin medirla.',
  galleryTitle: 'Una galería debe contar una historia, no ser una carpeta de fotos.',
  galleryBody: 'El orden puede ayudar a recorrer el lugar: llegada, espacio, habitación, servicios, experiencia y destino. No hay un orden único para todos los alojamientos.',
  gallerySteps: ['Llegada', 'Espacio', 'Habitación', 'Servicios', 'Experiencia', 'Destino'],
  galleryNote: 'La secuencia se adapta a lo que el establecimiento puede mostrar.',
  copyTitle: 'Las imágenes muestran. Las palabras explican.',
  copyBody: 'Los textos pueden ayudar a decir quién es el alojamiento, qué ofrece, dónde está y qué conviene saber antes de escribir o reservar.',
  copyPoints: ['Identidad', 'Propuesta', 'Unidades', 'Servicios', 'Ubicación', 'Experiencias', 'Políticas', 'Preguntas frecuentes', 'Destino'],
  copyPrinciple: 'Se escribe primero para personas. El buscador entra cuando hay una estrategia de visibilidad, sin prometer una posición.',
  genericLabel: 'Genérico',
  genericExample: 'Habitación cómoda con excelentes servicios.',
  usefulLabel: 'Más útil',
  usefulExample: 'Habitación privada pensada para descansar después de un día en el destino.',
  videoTitle: 'Hay experiencias que una fotografía no alcanza a contar.',
  videoBody: 'Un video corto puede mostrar ambiente, un recorrido o un momento del lugar. Entra solo si el alcance lo incluye.',
  videoPoints: ['Clip breve', 'Ambiente', 'Recorrido', 'Momento', 'Destino'],
  videoNote: 'Video corto según alcance. No es una producción audiovisual ilimitada.',
  destinationTitle: 'El alojamiento no existe aislado del lugar que lo rodea.',
  destinationBody: 'Puede ser útil contar el destino, cómo llegar y el contexto, cuando esa información existe y se puede verificar.',
  destinationPoints: ['Destino', 'Entorno', 'Cómo llegar', 'Actividades que se puedan respaldar', 'Contexto'],
  destinationNote: 'No se inventa información de un lugar ni se publica lo que el establecimiento no puede sostener.',
  socialTitle: 'Un mismo alojamiento, varios puntos de contacto.',
  socialBody: 'El material central puede adaptarse a la web, a redes y a WhatsApp. Cada formato pide un recorte distinto.',
  socialChannels: ['Contenido central', 'Web', 'Instagram', 'Facebook', 'WhatsApp'],
  socialNote: 'No se publica el mismo archivo, igual, en todas las plataformas.',
  editorialTitle: 'Publicar con intención es distinto de publicar por obligación.',
  editorialSteps: ['Objetivo', 'Tema', 'Formato', 'Canal', 'Momento', 'Publicación', 'Aprendizaje'],
  editorialCategories: ['Alojamiento', 'Servicios', 'Experiencias', 'Destino', 'Recomendaciones', 'Preguntas', 'Historias', 'Temporada'],
  editorialNote: 'No armamos un calendario genérico sin conocer el establecimiento.',
  relations: [
    {
      title: 'Content alimenta la casa digital.',
      body: 'Andario Web construye la estructura. Content ayuda a llenarla con material que represente al establecimiento.',
      steps: ['Andario Content', 'Fotos, textos y video', 'Andario Web', 'Presentación'],
      note: 'Tener la web de Andario no es obligatorio para trabajar el contenido.',
      hrefLabel: 'Andario Web',
    },
    {
      title: 'El contenido útil también forma parte de la visibilidad.',
      body: 'Textos, destino y preguntas pueden alimentar Andario Visibility. Publicar no garantiza un puesto en Google.',
      steps: ['Content', 'Información útil', 'Intención', 'Visibility', 'Descubrimiento'],
      note: 'Visibility es el servicio de SEO y visibilidad. Content no lo reemplaza.',
      hrefLabel: 'Andario Visibility',
    },
    {
      title: 'Una buena respuesta también necesita contenido detrás.',
      body: 'Connect puede usar después la información del alojamiento para orientar una conversación, cuando esa pieza exista.',
      steps: ['Pregunta del huésped', 'Connect', 'Contenido', 'Respuesta útil'],
      note: 'El ejemplo es conceptual. No afirma que cada chat ya consulte una biblioteca de contenido.',
      hrefLabel: 'Andario Connect',
    },
    {
      title: 'Antes de reservar, el huésped necesita información clara.',
      body: 'Content ayuda a comprender el lugar. Andario Booking Engine gestiona disponibilidad, tarifas y la reserva.',
      steps: ['Content', 'Información', 'Confianza', 'Booking Engine', 'Reserva'],
      note: 'Content no controla la reserva.',
      hrefLabel: 'Andario Booking Engine',
    },
    {
      title: 'El contenido también puede aprender de las señales.',
      body: 'Andario Growth puede leer después interacciones de la presencia digital, si hay medición. No lee conversaciones privadas.',
      steps: ['Content', 'Publicación', 'Interacción', 'Datos', 'Growth', 'Aprendizaje'],
      note: 'No prometemos una atribución completa de cada pieza.',
      hrefLabel: 'Andario Growth',
    },
  ],
  beforeLabel: 'Material suelto',
  before: ['Fotos mezcladas', 'Textos genéricos', 'Galería sin orden', 'Piezas aisladas', 'Publicaciones improvisadas'],
  afterLabel: 'Con una línea de contenido',
  after: ['Fotografías seleccionadas', 'Textos útiles', 'Galería con sentido', 'Material reutilizable', 'Plan editorial', 'Contexto del destino'],
  beforeNote: 'Ejemplo conceptual. No todos los alojamientos empiezan así.',
  matrixTitle: 'Una pieza puede vivir en más de un lugar.',
  matrixCenter: 'Contenido',
  matrixAround: ['Web', 'Redes', 'WhatsApp', 'Destino', 'Experiencias'],
  matrixColumns: ['Web', 'Redes', 'WhatsApp', 'Visibility'],
  matrixRows: [
    { name: 'Fotografías', cells: [puede, puede, puede, puede] },
    { name: 'Textos', cells: [puede, puede, puede, puede] },
    { name: 'Preguntas', cells: [puede, puede, puede, puede] },
    { name: 'Destino', cells: [puede, puede, puede, puede] },
    { name: 'Video corto', cells: [puede, puede, alcance, '—'] },
  ],
  matrixNote: 'Es una lectura de reutilización posible. No es una integración automática ni una promesa de publicar en todos los canales.',
  includesTitle: 'Qué puede incluir',
  includesIntro: 'Cada pieza se acuerda. No todos los proyectos incluyen todas las actividades.',
  whatLabel: 'Qué es',
  purposeLabel: 'Para qué sirve',
  exampleCardLabel: 'Ejemplo',
  groups: [
    { title: 'Coordinación de fotografía', what: 'Plan y coordinación de la producción, según ciudad y alcance.', purpose: 'Tener imágenes del establecimiento real.', example: 'Una lista de tomas de las unidades que sí existen.' },
    { title: 'Preparación de imágenes', what: 'Fotos listas para web y otros canales.', purpose: 'Que se vean bien y pesen lo necesario.', example: 'Una selección con tamaño y texto alternativo.' },
    { title: 'Textos del sitio', what: 'Palabras que explican el alojamiento.', purpose: 'Que la persona entienda la propuesta.', example: 'Una descripción de la unidad que dice para qué sirve, no solo que es cómoda.' },
    { title: 'Contenido para redes', what: 'Adaptación a formatos sociales.', purpose: 'Mantener una línea, no publicar por obligación.', example: 'Una pieza del mismo espacio, recortada para el canal.' },
    { title: 'Video corto', what: 'Una pieza breve, si entra en el alcance.', purpose: 'Mostrar ambiente o recorrido cuando la foto no basta.', example: 'Un clip del lugar, no una producción ilimitada.' },
    { title: 'Contenido de destino', what: 'Información verificable del lugar.', purpose: 'Situar el alojamiento en su contexto.', example: 'Cómo llegar, si ese dato se puede respaldar.' },
    { title: 'Preparación de galería', what: 'Selección y orden.', purpose: 'Que la visita visual tenga sentido.', example: 'De la llegada a la habitación, según lo que haya que mostrar.' },
    { title: 'Plan editorial', what: 'Temas, formatos y momentos.', purpose: 'Publicar con una razón.', example: 'Una línea de temporada, no un calendario vacío.' },
  ],
  notIncludedTitle: 'Qué no está incluido por el solo hecho de conversar.',
  notIncludedBody: 'El contenido se define según lo que ese establecimiento necesita. Estas piezas no se asumen.',
  notIncluded: [
    'Sesión fotográfica completa',
    'Video profesional amplio',
    'Manejo permanente de redes',
    'Producción mensual ilimitada',
    'Community management',
    'Fotografía aérea',
    'Producción con modelos',
    'Viajes',
    'Equipo audiovisual propio en cada ciudad',
    'Publicación diaria',
  ],
  notIncludedNote: 'Si alguna hace falta, entra en el alcance que se acuerde.',
  processTitle: 'Del material que hay a contenido listo para comunicar.',
  process: [
    { title: 'Entendemos', body: 'Alojamiento, identidad, público, destino y objetivos.' },
    { title: 'Planificamos', body: 'Qué debe mostrarse y qué material falta.' },
    { title: 'Producimos o reunimos', body: 'Fotografía, textos, video u otro material, según el alcance.' },
    { title: 'Seleccionamos', body: 'Nos quedamos con lo más útil.' },
    { title: 'Adaptamos', body: 'Formatos para web, redes y otros canales.' },
    { title: 'Entregamos', body: 'El material queda ordenado para usarse.' },
    { title: 'Evolucionamos', body: 'Se ajusta según necesidades y señales disponibles.' },
  ],
  receiveTitle: 'Contenido listo para representar mejor el alojamiento.',
  receive: [
    'Selección fotográfica, si entra en el alcance',
    'Imágenes preparadas para publicar',
    'Textos',
    'Estructura de galería',
    'Piezas para redes, si se acuerdan',
    'Videos cortos, si se acuerdan',
    'Contenido de destino verificable',
    'Una línea editorial',
    'Archivos ordenados',
    'Recomendaciones de uso',
  ],
  receiveNote: 'El alcance final se define con el establecimiento. No es una producción ilimitada.',
  whoTitle: 'Para alojamientos que quieren mostrar mejor lo que realmente ofrecen.',
  whoTypes: ['Hostales', 'Hoteles pequeños', 'Posadas', 'Apartamentos turísticos', 'Apartahoteles', 'Cabañas', 'Villas', 'Alojamientos rurales', 'Otros establecimientos independientes'],
  whoFit: ['Las fotos ya no representan el lugar.', 'Hay material, pero no se sabe cuál usar.', 'La web tiene poco que mostrar.', 'Las unidades se explican poco.', 'Las redes no tienen una línea.', 'El destino no está contado.', 'Hay mucho archivo y poco orden.', 'Quieren una base que se pueda reutilizar.'],
  whenTitle: 'Cuándo suele tener sentido',
  when: [
    'Las fotografías ya no muestran cómo está hoy el alojamiento.',
    'Tienes fotos y no sabes cuáles publicar.',
    'La web tiene poco material visual.',
    'Las habitaciones o unidades se explican poco.',
    'Las redes publican sin una línea.',
    'Quieres mostrar experiencias y destino.',
    'Quieres una biblioteca de contenido reutilizable.',
    'Quieres unir el material con la web, la visibilidad y la comunicación.',
  ],
  notTitle: 'Qué Andario Content no es',
  not: [
    { title: 'No es solo fotografía', body: 'También puede haber textos, video, destino, galería y un plan.' },
    { title: 'No es publicar por publicar', body: 'Cada pieza tiene que servir para mostrar o explicar.' },
    { title: 'No es community management ilimitado', body: 'La gestión permanente de redes se define aparte, si corresponde.' },
    { title: 'No garantiza reservas', body: 'Ayuda a comunicar. La reserva depende de más factores.' },
    { title: 'No es un banco de fotos genéricas', body: 'El material tiene que ser de ese establecimiento.' },
    { title: 'No es fotografía ilimitada', body: 'La producción depende del alcance.' },
    { title: 'No reemplaza a Visibility', body: 'Content crea y ordena. Visibility trabaja el ser encontrado.' },
    { title: 'No reemplaza a la web', body: 'La web es la estructura. Content aporta el material.' },
  ],
  authenticTitle: 'Mostrar lo que realmente existe también construye confianza.',
  authenticBody: 'La presentación puede ser atractiva y, al mismo tiempo, fiel a lo que la persona va a encontrar.',
  authenticPoints: [
    'No alterar de forma engañosa lo que importa',
    'No usar fotos de otro alojamiento como si fueran propias',
    'No inventar servicios',
    'No mostrar espacios que no existen',
    'No publicar lo que el establecimiento no puede respaldar',
  ],
  journeyTitle: 'El contenido trabaja sobre todo antes de la llegada.',
  journeySteps: ['Antes de viajar', 'Descubre', 'Imagina', 'Compara', 'Decide', 'Reserva', 'Llega'],
  journeyNote: 'Content no controla todas esas etapas. Ayuda a que el lugar se entienda en la experiencia digital.',
  assetTitle: 'Una buena pieza puede vivir en más de un lugar.',
  assetSteps: ['Una pieza', 'Web', 'Redes', 'WhatsApp', 'Archivo', 'Usos posteriores'],
  assetNote: 'Se adapta al canal. No se duplica el mismo formato en todos.',
  ecosystemTitle: 'Content crea el material. Las otras piezas hacen otra cosa.',
  ecosystemSteps: ['Digital Check', 'Entender', 'Content', 'Crear material', 'Web', 'Presentar', 'Visibility', 'Ser encontrado', 'Connect', 'Comunicar', 'Booking Engine', 'Reservar', 'Growth', 'Medir'],
  ecosystemNote: 'Es una lectura del ecosistema, no un paquete obligatorio.',
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal es el establecimiento pionero de Andario Hospitality. No publicamos reservas, tráfico ni fotografías de su material como caso de resultados.',
  finalTitle: 'Haz que tu alojamiento se vea y se entienda como merece.',
  finalBody: 'Cuéntanos qué material tienes hoy, qué quieres mejorar y cómo quieres presentar el alojamiento. Podemos ayudarte a construir contenido útil para la web, los canales digitales y la comunicación.',
  finalNote: 'Sin contenido genérico. Con material pensado para tu alojamiento.',
};
