import type { DigitalCheckContent, FaqItem } from '@/content/types';

export const digitalCheckFaqsEs: FaqItem[] = [
  {
    q: '¿Qué es Digital Check?',
    a: 'Es un diagnóstico estructurado de la presencia digital de tu alojamiento. Analizamos los principales puntos de contacto y convertimos los hallazgos en una hoja de ruta priorizada.',
  },
  {
    q: '¿Qué aspectos analiza Digital Check?',
    a: 'Presencia en Google, sitio web, SEO, redes sociales, WhatsApp, OTAs, proceso de reserva, contenido y fotografía, experiencia de uso, analítica, contexto competitivo y la relación entre esas piezas.',
  },
  {
    q: '¿Qué recibo al finalizar?',
    a: 'Un diagnóstico de la situación actual, los hallazgos, las oportunidades, las prioridades, una hoja de ruta y los próximos pasos. No es solo una lista de observaciones.',
  },
  {
    q: '¿Necesito tener página web para hacer un Digital Check?',
    a: 'No necesariamente. El diagnóstico mira la situación actual, también cuando algunas piezas todavía no existen.',
  },
  {
    q: '¿Necesito contratar otros servicios de Andario después?',
    a: 'No. El diagnóstico orienta la decisión. Los servicios posteriores se contratan por separado, con Andario, con tu equipo o con otro proveedor.',
  },
  {
    q: '¿Digital Check garantiza más reservas?',
    a: 'No. No garantiza reservas, ingresos, tráfico ni una posición en buscadores. Sirve para ver la situación con más claridad y decidir qué hacer primero.',
  },
  {
    q: '¿Digital Check incluye SEO?',
    a: 'Analiza aspectos de SEO dentro del diagnóstico. Eso no incluye, por sí solo, la implementación completa de un proyecto de SEO.',
  },
  {
    q: '¿Analizan mi presencia en Booking.com, Airbnb u otras OTAs?',
    a: 'Sí, cuando forman parte de la presencia del establecimiento y hay información suficiente para revisarlas. No afirmamos una sincronización ni un acceso que el alojamiento no haya facilitado.',
  },
  {
    q: '¿Analizan mi WhatsApp?',
    a: 'Sí. Se puede revisar cómo funciona como punto de contacto dentro del recorrido digital.',
  },
  {
    q: '¿Qué pasa si no tengo Google Analytics?',
    a: 'No impide el diagnóstico. La falta de medición puede ser uno de los hallazgos y de las recomendaciones.',
  },
  {
    q: '¿El diagnóstico incluye a mis competidores?',
    a: 'Puede considerar el contexto de establecimientos comparables cuando haya información pública suficiente y relevante.',
  },
  {
    q: '¿Cuánto tarda?',
    a: 'No publicamos un plazo fijo. El tiempo depende del alcance y de la información disponible, y se acuerda al empezar.',
  },
  {
    q: '¿Puedo hacer el diagnóstico si mi alojamiento todavía está en construcción?',
    a: 'Sí, si hay información suficiente sobre lo que ya existe y lo que está previsto. La profundidad depende de ese estado.',
  },
  {
    q: '¿Puedo implementar las recomendaciones por mi cuenta?',
    a: 'Sí. La hoja de ruta sirve para decidir. Andario puede acompañar la implementación cuando lo pidas.',
  },
  {
    q: '¿Cómo solicito un Digital Check?',
    a: 'Desde Solicitar diagnóstico digital o por WhatsApp. La conversación no obliga a contratar el resto de servicios.',
  },
];

export const digitalCheckEs: DigitalCheckContent = {
  support:
    'Antes de construir nuevas herramientas, necesitamos entender dónde estás. Analizamos la presencia digital de tu establecimiento y convertimos los hallazgos en una hoja de ruta priorizada para saber qué mejorar primero.',
  audienceLine:
    'Para hostales, hoteles pequeños, posadas, apartamentos turísticos, cabañas y otros alojamientos independientes.',
  primaryCta: 'Solicitar diagnóstico',
  talkCta: 'Hablar con Andario',
  knowCta: 'Quiero conocer mi situación digital',
  startCta: 'Empezar mi Digital Check',
  overviewCaption:
    'Google, el sitio, WhatsApp, las OTAs, las reservas y las redes se miran juntos. Digital Check los convierte en un diagnóstico y una hoja de ruta.',
  overviewPieces: ['Google', 'Sitio web', 'WhatsApp', 'OTAs', 'Reservas', 'Redes'],
  overviewCore: 'Digital Check',
  overviewResult: ['Diagnóstico', 'Prioridades', 'Hoja de ruta'],
  situations: [
    'Estoy en Google, pero no sé qué tan visible soy.',
    'Tengo web, pero no sé si realmente ayuda a convertir.',
    'Recibo consultas por WhatsApp, pero todo es manual.',
    'Estoy en OTAs, pero no tengo claro cómo funciona mi canal propio.',
    'Publico en redes, pero no sé cómo se conecta con las reservas.',
    'Tengo herramientas, pero no sé qué debería mejorar primero.',
  ],
  valueTitle: 'No necesitas empezar construyendo. Necesitas empezar entendiendo.',
  valueBody: 'Digital Check establece una línea base. Convierte información dispersa en prioridades concretas.',
  valueSteps: [
    '¿Dónde estamos?',
    '¿Qué está funcionando?',
    '¿Qué está fallando o fragmentado?',
    '¿Qué oportunidades existen?',
    '¿Qué debería hacerse primero?',
    '¿Qué puede esperar?',
  ],
  valueClose: 'El resultado es una dirección, no una lista interminable de problemas.',
  whatTitle: '¿Qué es Digital Check?',
  whatBody:
    'Es un diagnóstico estructurado de la presencia digital de tu alojamiento. Revisamos los principales puntos de contacto, identificamos oportunidades y organizamos los hallazgos según su prioridad. El objetivo es entender qué merece atención primero y qué camino tiene sentido seguir.',
  mapCaption:
    'El diagnóstico mira el conjunto: visibilidad, redes, WhatsApp, sitio, reserva, OTAs, analítica, SEO, contenido, fotografía, experiencia y contexto.',
  mapCenter: 'Tu ecosistema digital',
  mapNodes: ['Google', 'Visibilidad', 'Redes', 'WhatsApp', 'Sitio web', 'Reservas', 'OTAs', 'Analítica', 'SEO', 'Contenido', 'Fotografía', 'Experiencia'],
  reviewsLabel: 'Qué revisamos',
  whyLabel: 'Por qué importa',
  outcomeLabel: 'Qué puede salir',
  areasTitle: 'Qué analizamos',
  areasIntro: 'Doce piezas del ecosistema. No es solo una revisión del sitio web.',
  areasNote:
    'Cuando una revisión necesite acceso a una cuenta o a información interna, lo pedimos. No suponemos ese acceso.',
  areas: [
    {
      title: 'Presencia en Google',
      reviews: ['Información visible para quien busca', 'Coherencia de los datos públicos', 'Cómo se presenta el alojamiento'],
      why: 'Es uno de los primeros lugares donde un huésped puede encontrarte.',
      outcome: 'Oportunidades para ordenar esa presencia.',
    },
    {
      title: 'Sitio web',
      reviews: ['Claridad', 'Estructura', 'Contenido', 'Puntos de contacto'],
      why: 'La web puede informar, generar confianza o frenar el siguiente paso.',
      outcome: 'Qué de la web conviene mejorar y qué puede esperar.',
    },
    {
      title: 'SEO',
      reviews: ['Estructura', 'Contenido', 'Metadatos', 'Fundamentos técnicos'],
      why: 'Ayuda a que los buscadores entiendan el establecimiento.',
      outcome: 'Oportunidades y prioridades de SEO, no una implementación completa.',
    },
    {
      title: 'Redes sociales',
      reviews: ['Presencia', 'Coherencia', 'Información', 'Relación con el resto del recorrido'],
      why: 'Publicar no es lo mismo que conectar esa presencia con una decisión.',
      outcome: 'Cómo se relacionan las redes con el resto de la presencia.',
    },
    {
      title: 'WhatsApp',
      reviews: ['Facilidad para escribir', 'Información disponible', 'Experiencia de contacto'],
      why: 'Suele ser el canal donde llegan las preguntas reales.',
      outcome: 'Si el contacto ayuda o se vuelve un proceso manual.',
    },
    {
      title: 'OTAs',
      reviews: ['Presencia', 'Información pública', 'Relación con el canal propio'],
      why: 'Las OTAs pueden convivir con un canal propio. El diagnóstico no pide abandonarlas.',
      outcome: 'Cómo se ve esa presencia dentro de la estrategia general.',
    },
    {
      title: 'Proceso de reserva',
      reviews: ['Del interés al intento de reserva', 'Fricciones', 'Canales que intervienen'],
      why: 'El problema a veces no es la visibilidad, sino lo que pasa después.',
      outcome: 'Dónde se corta o se complica el camino.',
    },
    {
      title: 'Contenido y fotografía',
      reviews: ['Cómo se presenta el alojamiento', 'Si el contenido explica la propuesta'],
      why: 'El huésped decide con lo que entiende y con lo que ve.',
      outcome: 'Qué falta comunicar antes de producir más piezas.',
    },
    {
      title: 'Experiencia de uso',
      reviews: ['Claridad', 'Navegación', 'Accesibilidad', 'Fricciones'],
      why: 'Una presencia confusa cuesta de usar, aunque exista.',
      outcome: 'Qué estorba el recorrido y qué está claro.',
    },
    {
      title: 'Analítica',
      reviews: ['Si hay herramientas de medición', 'Qué comportamiento se puede observar'],
      why: 'Sin medición, las decisiones siguientes se toman a ciegas.',
      outcome: 'Qué falta medir. No hace falta tener Analytics para empezar.',
    },
    {
      title: 'Contexto competitivo',
      reviews: ['Información pública de establecimientos comparables', 'Solo cuando esa información alcanza'],
      why: 'Ayuda a ver el entorno, no a copiar a otro alojamiento.',
      outcome: 'Un contexto, no un ranking inventado.',
    },
    {
      title: 'Ecosistema',
      reviews: ['Cómo se relacionan las piezas', 'Qué está conectado y qué va por separado'],
      why: 'El valor aparece cuando el conjunto tiene una dirección.',
      outcome: 'Por dónde empezar para que las piezas dejen de trabajar solas.',
    },
  ],
  areasCta: 'Solicitar diagnóstico',
  methodTitle: 'Así convertimos tu presencia digital en una hoja de ruta.',
  methodIntro: 'Cinco pasos. El diagnóstico no termina en una lista de errores.',
  method: [
    { title: 'Contexto', body: 'Entendemos el tipo de alojamiento, la ubicación, la oferta, los objetivos y la situación actual.' },
    { title: 'Presencia', body: 'Revisamos los principales puntos de contacto digitales.' },
    { title: 'Hallazgos', body: 'Separamos lo que funciona, lo que falta, lo que está fragmentado y las oportunidades.' },
    { title: 'Priorización', body: 'Ordenamos los hallazgos según importancia y esfuerzo.' },
    { title: 'Hoja de ruta', body: 'Las acciones quedan concretas y en secuencia.' },
  ],
  methodCta: 'Empezar mi Digital Check',
  matrixTitle: 'No solo detecta. Ayuda a priorizar.',
  matrixIntro: 'El impacto y el esfuerzo sirven para separar lo que conviene hacer pronto de lo que puede planearse.',
  matrixExample: 'Ejemplos ilustrativos. No son hallazgos de un alojamiento real.',
  matrixImpact: 'Impacto',
  matrixEffort: 'Esfuerzo',
  matrixZones: [
    { title: 'Hacer pronto', body: 'Mucho impacto y poco esfuerzo relativo.' },
    { title: 'Prioridad', body: 'Mucho impacto y más esfuerzo.' },
    { title: 'Planificar', body: 'Menos impacto inmediato y poco esfuerzo.' },
    { title: 'Evaluar', body: 'Más esfuerzo y menos impacto claro por ahora.' },
  ],
  matrixPoints: ['Mejorar el contacto', 'Ordenar la información en Google', 'Rediseñar la web', 'Medir conversiones'],
  findingExample: 'Ejemplo ilustrativo. No es un hallazgo real.',
  finding: [
    { label: 'Hallazgo', value: 'La información de contacto cuesta de encontrar.' },
    { label: 'Oportunidad', value: 'Reducir la fricción para escribir.' },
    { label: 'Prioridad', value: 'Alta' },
    { label: 'Acción', value: 'Mejorar el llamado a la acción, el contacto y WhatsApp.' },
    { label: 'Siguiente paso', value: 'Implementación, si decides hacerla.' },
  ],
  receiveTitle: 'No te entregamos solamente observaciones. Te entregamos una dirección.',
  receiveIntro: 'El entregable es un diagnóstico y una hoja de ruta de acciones prioritarias.',
  receive: [
    { title: 'Diagnóstico', body: 'Una lectura ordenada de la situación actual.' },
    { title: 'Hallazgos', body: 'Qué funciona, qué falta y qué puede mejorar.' },
    { title: 'Oportunidades', body: 'Dónde hay posibilidad de avance.' },
    { title: 'Prioridades', body: 'Qué conviene atender primero.' },
    { title: 'Hoja de ruta', body: 'Qué acciones podrían seguir y en qué orden.' },
    { title: 'Próximos pasos', body: 'Qué soluciones de Andario pueden tener sentido, solo cuando corresponda.' },
  ],
  receiveCta: 'Quiero conocer mi situación digital',
  reportNote: 'Mockup ilustrativo. No es el informe de un cliente.',
  reportHeading: 'Diagnóstico digital',
  reportRows: [
    { label: 'Google', value: 'Revisar' },
    { label: 'Sitio web', value: 'Prioridad alta' },
    { label: 'SEO', value: 'Oportunidad' },
    { label: 'WhatsApp', value: 'Correcto' },
    { label: 'Reservas', value: 'Prioridad' },
    { label: 'Analítica', value: 'Falta medir' },
  ],
  reportPrioritiesTitle: 'Prioridades',
  reportPriorities: ['Mejorar la presencia web', 'Ordenar el proceso de contacto', 'Implementar medición'],
  reportNextTitle: 'Próximos pasos',
  reportNext: 'Web, luego reservas, luego medición. Solo si el diagnóstico lo indica.',
  priorityTitle: 'Cómo se ordenan las oportunidades',
  priorityBody: 'No usamos una nota inventada. Clasificamos con categorías.',
  priorityCriteria: ['Impacto potencial', 'Urgencia', 'Esfuerzo', 'Dependencia', 'Madurez actual', 'Alineación con tus objetivos'],
  priorityLevels: ['Prioridad alta', 'Prioridad media', 'Para planificar', 'Oportunidad futura'],
  decisionsTitle: 'Un buen diagnóstico también ayuda a decidir qué no hacer todavía.',
  decisionsIntro: 'Estas son las preguntas que el diagnóstico permite ordenar.',
  decisions: [
    '¿Necesito una web nueva?',
    '¿Debo mejorar primero mi presencia en Google?',
    '¿Necesito un motor de reservas?',
    '¿Tengo que trabajar SEO?',
    '¿Mi WhatsApp está facilitando el contacto?',
    '¿Necesito mejorar contenido y fotografías?',
    '¿Estoy midiendo lo que ocurre?',
    '¿Qué debería hacer primero?',
    '¿Qué inversión puede esperar?',
  ],
  pathTitle: 'El diagnóstico puede ser el comienzo. La decisión es tuya.',
  pathIntro:
    'Puede indicar que conviene mejorar el sitio, la visibilidad, un canal propio de reservas, WhatsApp, el contenido o la medición.',
  pathClose: 'No necesitas contratar todos los servicios.',
  pathServices: ['Andario Web', 'Visibility', 'Booking Engine', 'Connect', 'Content', 'Growth'],
  whoTitle: 'Pensado para alojamientos que quieren saber por dónde empezar.',
  whoTypes: [
    'Hostales',
    'Hoteles pequeños',
    'Posadas',
    'Apartamentos turísticos',
    'Apartahoteles',
    'Cabañas',
    'Villas',
    'Alojamientos rurales',
    'Otros alojamientos independientes',
  ],
  whenTitle: 'Cuándo suele tener sentido',
  when: [
    'Estás empezando a digitalizar el alojamiento.',
    'Tienes varios canales y no una estrategia integrada.',
    'Tienes web y no sabes si funciona bien.',
    'Quieres construir un canal propio.',
    'Dependes mucho de las OTAs.',
    'Recibes muchas consultas por WhatsApp.',
    'Quieres invertir y no sabes por dónde.',
    'Estás pensando en rediseñar la web.',
    'Quieres mejorar la visibilidad.',
    'Quieres medir mejor lo que sucede.',
  ],
  notTitle: 'Qué Digital Check no es',
  not: [
    { title: 'No es una garantía de resultados', body: 'No promete reservas, ingresos, tráfico ni una posición en buscadores.' },
    { title: 'No es solo una auditoría web', body: 'Analiza el ecosistema digital, no únicamente el sitio.' },
    { title: 'No es una lista interminable de errores', body: 'El objetivo es priorizar.' },
    { title: 'No obliga a contratar otros servicios', body: 'Las recomendaciones pueden hacerse con Andario, con tu equipo o con otros proveedores.' },
    { title: 'No sustituye herramientas especializadas', body: 'Si hace falta un acceso o un dato concreto, se indica.' },
    { title: 'No es una auditoría financiera', body: 'No revisa cuentas ni resultados económicos.' },
  ],
  modelTitle: 'El primer paso de un recorrido más largo',
  model: ['Diagnóstico', 'Estrategia', 'Implementación', 'Medición', 'Evolución'],
  modelClose:
    'Digital Check ayuda a decidir qué necesita el alojamiento y en qué orden. Después pueden venir la estrategia, la implementación, la medición y la evolución.',
  finalTitle: 'Antes de invertir en nuevas herramientas, descubre qué necesita realmente tu alojamiento.',
  finalBody:
    'Cuéntanos cómo funciona hoy tu presencia digital. Analizaremos el contexto y te ayudaremos a identificar por dónde tiene sentido empezar.',
  finalCta: 'Solicitar diagnóstico digital',
  finalNote: 'Sin obligación de contratar todos los servicios.',
};
