import type { FaqItem, GrowthContent } from '@/content/types';

export const growthFaqsEs: FaqItem[] = [
  {
    q: '¿Qué es Andario Growth?',
    a: 'Es el servicio de medición, análisis y optimización. Ayuda a leer señales del ecosistema digital para decidir con más contexto. No es un tablero ni una instalación suelta de una herramienta.',
  },
  {
    q: '¿Garantiza más reservas o más ingresos?',
    a: 'No. La medición muestra lo que se puede observar. No promete reservas, ingresos, crecimiento ni un retorno.',
  },
  {
    q: '¿Garantiza una posición en Google?',
    a: 'No. Search Console ayuda a observar la búsqueda. No vende un puesto.',
  },
  {
    q: '¿Es lo mismo que instalar Google Analytics?',
    a: 'No. Analytics puede ser una fuente. Growth ordena qué mirar, cómo leerlo y qué ajuste tiene sentido después.',
  },
  {
    q: '¿Necesito ser analista?',
    a: 'No. La lectura se traduce a preguntas del alojamiento: de dónde llegan, qué consultan y qué sigue.',
  },
  {
    q: '¿Todas las preguntas se pueden responder siempre?',
    a: 'No. Depende de la instrumentación y de las fuentes conectadas. Si un dato no existe, no se inventa.',
  },
  {
    q: '¿Qué es Search Console?',
    a: 'Una herramienta de Google para ver cómo el sitio aparece en búsquedas y avisos técnicos. No es un ranking de un cliente.',
  },
  {
    q: '¿Miden el contenido de WhatsApp?',
    a: 'No. Se pueden observar clics hacia WhatsApp. No se envía el texto de las conversaciones ni datos personales a la analítica.',
  },
  {
    q: '¿Miden las reservas?',
    a: 'Se pueden observar interacciones y conversiones del proceso cuando están instrumentadas. Growth no crea la reserva: eso vive en el Booking Engine, si el alojamiento lo usa.',
  },
  {
    q: '¿La atribución es completa?',
    a: 'No. Se puede ver el origen cuando la visita lo permite. No prometemos saber el recorrido entero de cada persona.',
  },
  {
    q: '¿Instagram o Facebook están integrados?',
    a: 'Pueden aparecer como origen de una visita si esa visita se identifica. No es una integración productiva con esas plataformas.',
  },
  {
    q: '¿Growth hace campañas de anuncios?',
    a: 'No. Puede leer una visita que llegue con una marca de campaña, si existe. No es un servicio de publicidad.',
  },
  {
    q: '¿Cuál es la diferencia con Digital Check?',
    a: 'Digital Check diagnostica la situación. Growth mide lo que ocurre después, según las fuentes disponibles. El diagnóstico no es obligatorio.',
  },
  {
    q: '¿Cuál es la diferencia con Visibility?',
    a: 'Visibility trabaja la base para ser encontrado. Growth observa señales de búsqueda y de comportamiento. Ninguno promete una posición.',
  },
  {
    q: '¿Necesito contratar todos los servicios?',
    a: 'No.',
  },
  {
    q: '¿Puedo contratar solo Growth?',
    a: 'Sí. Mide lo que ya exista. Si no hay sitio ni eventos, el alcance se limita a lo que se pueda observar.',
  },
  {
    q: '¿Qué recibo?',
    a: 'Según el alcance: una medición ordenada, lectura de las fuentes conectadas, informes y recomendaciones. No un porcentaje inventado.',
  },
  {
    q: '¿Con qué frecuencia hay informes?',
    a: 'Se acuerda en el alcance. No hay un calendario publicado como obligación.',
  },
  {
    q: '¿Qué necesito para comenzar?',
    a: 'El sitio si existe, accesos a las herramientas cuando hagan falta, los canales que ya usas y qué decisiones quieres aclarar.',
  },
  {
    q: '¿Cómo empiezo?',
    a: 'Con una conversación. No obliga a contratar.',
  },
];

export const growthEs: GrowthContent = {
  support:
    'Tu sitio, Google, WhatsApp y las reservas pueden dejar señales. Andario Growth ayuda a medir las interacciones importantes, entender qué está ocurriendo y convertir esos datos en oportunidades de mejora.',
  audienceLine: 'Medición, análisis y optimización para el ecosistema digital de tu alojamiento.',
  primaryCta: 'Quiero medir mejor',
  talkCta: 'Hablar con Andario',
  whatsappCta: 'Escribir por WhatsApp',
  scopeLabel: 'Lo que se puede ver depende de la instrumentación y de las fuentes conectadas.',
  exampleLabel: 'Esquema conceptual. No son cifras de un alojamiento.',
  loop: ['Visitas', 'Interacciones', 'Conversiones', 'Reservas', 'Datos', 'Aprendizaje', 'Decisión', 'Optimización'],
  loopNote: 'El ciclo vuelve a empezar. Una medición no cierra el trabajo ni promete el siguiente resultado.',
  hub: [
    { title: 'Medir', body: 'Elegir las señales que el alojamiento puede usar.' },
    { title: 'Entender', body: 'Pasar de números sueltos a una lectura.' },
    { title: 'Mejorar', body: 'Priorizar un cambio y volver a observar.' },
  ],
  sources: ['Google', 'Instagram', 'Facebook', 'WhatsApp', 'Sitio web', 'Reservas'],
  sourceNote: 'Las visitas pueden llegar por varios lados. El problema aparece cuando nadie convierte esas señales en una decisión.',
  guessLine: 'Sin medición, cada cambio es una suposición.',
  questionsTitle: 'No necesitas mirar más números. Necesitas saber cuáles importan.',
  questions: [
    '¿De dónde llegan las personas?',
    '¿Qué páginas consultan?',
    '¿Qué contenido genera interacción?',
    '¿Cuántas personas hacen clic en WhatsApp?',
    '¿Dónde se interrumpe el recorrido?',
    '¿Cuántas interacciones llegan al proceso de reserva?',
    '¿Qué canales dejan visitas identificables?',
    '¿Qué acción vale la pena ajustar?',
    '¿Qué todavía no estamos midiendo?',
  ],
  questionsNote: 'No todas estas respuestas existen el primer día. Si la fuente no está conectada, la pregunta queda abierta.',
  whatTitle: '¿Qué es Andario Growth?',
  whatBody:
    'Es el servicio de medición, análisis y optimización de Andario Hospitality. Estructura la lectura del ecosistema digital para entender mejor comportamiento, canales y eventos relevantes. A partir de eso se pueden ver oportunidades y priorizar.',
  whatNote: 'Medir, entender, mejorar. No se trata de mirar más datos. Se trata de saber qué hacer con ellos.',
  ecosystemCaption:
    'Growth no reemplaza a Google, a la web ni al motor. Organiza la lectura de las fuentes que existan para facilitar una decisión.',
  ecosystemColumns: [
    { title: 'Google', points: ['Búsqueda', 'Search Console', 'Origen, si se identifica'] },
    { title: 'Web', points: ['Analytics', 'Páginas', 'Interacciones'] },
    { title: 'Contacto y reserva', points: ['Clics de WhatsApp', 'Formulario', 'Pasos de reserva, si están medidos'] },
  ],
  measureTitle: 'Qué puede observar',
  measureIntro: 'Cada grupo entra solo si hay una fuente y un evento. No es un inventario que ya esté activo en todos los alojamientos.',
  measureGroups: [
    { title: 'Descubrimiento', items: ['Tráfico', 'Búsquedas', 'Fuentes', 'Canales', 'Páginas de llegada'] },
    { title: 'Interacción', items: ['Páginas', 'Recorrido', 'Clics', 'Elementos del sitio'] },
    { title: 'Comunicación', items: ['Clics de WhatsApp', 'Formularios', 'Contactos'] },
    { title: 'Reservas', items: ['Inicio del proceso', 'Disponibilidad, si el evento existe', 'Pasos', 'Conversiones medidas', 'Origen, cuando está instrumentado'] },
    { title: 'Contenido', items: ['Páginas', 'Piezas', 'Interacción', 'Comportamiento'] },
  ],
  measureNote: 'No publicamos porcentajes ni un abandono universal. El dato aparece cuando se mide.',
  channelsTitle: 'Los canales se leen. No se controlan desde aquí.',
  channelsBody:
    'Una visita puede venir de búsqueda, de una red, de un enlace o de una campaña marcada. Growth ayuda a distinguir esas llegadas cuando la herramienta las muestra. No opera las redes ni compra anuncios.',
  channels: [
    { title: 'Búsqueda', body: 'Search Console y Analytics, cuando hay acceso. Observar no es posicionar.' },
    { title: 'Sitio', body: 'Páginas e interacciones de la web propia, si Analytics está configurado.' },
    { title: 'WhatsApp', body: 'Clics hacia el canal. No el texto de la conversación.' },
    { title: 'Reservas', body: 'Interacciones del proceso cuando el motor y los eventos existen. Registrar un origen no es una integración en vivo.' },
    { title: 'Redes', body: 'Pueden verse como origen de una visita. No hay una integración productiva con Instagram o Facebook.' },
    { title: 'Campañas', body: 'Solo si la visita trae una marca identificable. Growth no es un servicio de anuncios.' },
  ],
  channelsNote: 'La atribución por canal es parcial. No reconstruimos el camino completo de cada persona.',
  includesTitle: 'Qué puede incluir',
  includesIntro: 'El alcance se define con el establecimiento y con los accesos que existan.',
  whatLabel: 'Qué es',
  purposeLabel: 'Para qué sirve',
  groups: [
    { title: 'Google Analytics', what: 'La lectura de visitas e interacciones del sitio.', purpose: 'Ver qué ocurre después de llegar.' },
    { title: 'Search Console', what: 'La lectura de aparición en búsquedas y avisos técnicos.', purpose: 'Observar la búsqueda sin prometer un puesto.' },
    { title: 'Eventos de conversión', what: 'Acciones que se acuerdan medir: contacto, WhatsApp, pasos de reserva.', purpose: 'Distinguir una visita de un siguiente paso.' },
    { title: 'Comportamiento del sitio', what: 'Páginas y recorridos disponibles.', purpose: 'Ver dónde la persona se queda o sigue.' },
    { title: 'Clics de WhatsApp', what: 'El clic, no el mensaje.', purpose: 'Saber que alguien eligió escribir.' },
    { title: 'Interacciones de reserva', what: 'Eventos del proceso, si el motor los deja ver.', purpose: 'Relacionar la visita con la reserva sin duplicar la lógica del motor.' },
    { title: 'Conversión de reservas', what: 'La reserva completada, cuando ese evento existe.', purpose: 'Contar un hecho, no prometer el siguiente.' },
    { title: 'Atribución por canal', what: 'El origen que la herramienta puede mostrar.', purpose: 'Comparar llegadas, sin una atribución total.' },
    { title: 'Informes y recomendaciones', what: 'Una lectura y un siguiente ajuste.', purpose: 'Decidir, no acumular números.' },
  ],
  privacyTitle: 'Lo que no viaja a la analítica',
  privacyPoints: [
    'Nombres',
    'Correos',
    'Teléfonos',
    'Texto de conversaciones',
    'Datos de huéspedes',
  ],
  privacyNote: 'Los eventos son categorías. No son un expediente de la persona.',
  relations: [
    {
      title: 'Antes de medir, a veces conviene saber dónde estás.',
      body: 'Digital Check puede ordenar prioridades. Growth mide después lo que se haya instrumentado.',
      steps: ['Digital Check', 'Diagnóstico', 'Growth', 'Lectura'],
      note: 'El diagnóstico no es obligatorio.',
      hrefLabel: 'Digital Check',
    },
    {
      title: 'La web es una de las fuentes.',
      body: 'Andario Web puede dejar la base de medición. Growth amplía la lectura. No hace falta haber contratado la web de Andario.',
      steps: ['Web', 'Eventos', 'Growth', 'Lectura'],
      note: 'Sin sitio, se mide lo que sí exista.',
      hrefLabel: 'Andario Web',
    },
    {
      title: 'La visibilidad también deja señales.',
      body: 'Visibility trabaja la base para ser encontrado. Growth puede observar búsqueda y comportamiento. Ninguno promete una posición.',
      steps: ['Visibility', 'Señales', 'Growth', 'Ajuste'],
      note: 'No hay una atribución completa de cada búsqueda.',
      hrefLabel: 'Andario Visibility',
    },
    {
      title: 'La conversación no se lee por dentro.',
      body: 'Connect ordena la comunicación. Growth puede ver el clic hacia WhatsApp, no el contenido del chat.',
      steps: ['Connect', 'Clic', 'Growth'],
      note: 'No analizamos mensajes privados.',
      hrefLabel: 'Andario Connect',
    },
    {
      title: 'El contenido se puede observar, no adivinar.',
      body: 'Content crea el material. Growth puede ver interacción con páginas cuando esa medición existe.',
      steps: ['Content', 'Publicación', 'Interacción', 'Growth'],
      note: 'Una pieza no trae su propio resultado garantizado.',
      hrefLabel: 'Andario Content',
    },
    {
      title: 'La reserva sigue en el motor.',
      body: 'Booking Engine gestiona disponibilidad y la reserva. Growth puede leer eventos de ese proceso si están instrumentados.',
      steps: ['Visita', 'Proceso', 'Booking Engine', 'Growth'],
      note: 'Medir una reserva no la genera.',
      hrefLabel: 'Andario Booking Engine',
    },
  ],
  processTitle: 'De las señales a una decisión.',
  process: [
    { title: 'Elegimos', body: 'Qué preguntas del alojamiento merecen un dato.' },
    { title: 'Conectamos', body: 'Las fuentes y los accesos que existan.' },
    { title: 'Medimos', body: 'Eventos acordados, sin datos personales.' },
    { title: 'Leemos', body: 'Qué se ve y qué todavía no se puede ver.' },
    { title: 'Recomendamos', body: 'Un ajuste concreto, no un tablero decorativo.' },
    { title: 'Volvemos a mirar', body: 'El cambio se observa. No se da por cerrado.' },
  ],
  receiveTitle: 'Qué puede recibir el establecimiento',
  receive: [
    'Una medición ordenada de lo que ya se puede ver',
    'Acceso o lectura de Analytics y Search Console, según permisos',
    'Eventos de contacto, WhatsApp y reserva cuando existan',
    'Una lectura de canales identificables',
    'Informes según el alcance',
    'Recomendaciones de qué ajustar después',
  ],
  receiveNote: 'El entregable depende del alcance. No incluye un crecimiento prometido ni cifras de otro alojamiento.',
  whoTitle: 'Para alojamientos que ya generan señales y quieren leerlas.',
  whoTypes: ['Hostales', 'Hoteles pequeños', 'Posadas', 'Apartamentos turísticos', 'Apartahoteles', 'Cabañas', 'Villas', 'Alojamientos rurales', 'Otros establecimientos independientes'],
  whoFit: [
    'Hay visitas y no está claro de dónde vienen.',
    'El sitio existe y nadie lee qué pasa después.',
    'WhatsApp es importante y solo se ve el chat, no el clic.',
    'Hay reservas y no se relacionan con el canal.',
    'Se cambian cosas por intuición.',
    'Quieren un ciclo de medición, no un informe genérico.',
  ],
  notTitle: 'Qué Andario Growth no es',
  not: [
    { title: 'No es un tablero', body: 'Los números sirven si ayudan a decidir.' },
    { title: 'No es instalar una herramienta y marcharse', body: 'La lectura y el siguiente ajuste forman parte del servicio, según el alcance.' },
    { title: 'No es una promesa de crecimiento', body: 'No hay reservas, ingresos ni retorno garantizados.' },
    { title: 'No es SEO', body: 'Eso es Visibility. Growth observa. No posiciona.' },
    { title: 'No es publicidad', body: 'No compra tráfico ni opera campañas.' },
    { title: 'No sustituye al propietario', body: 'La decisión sigue siendo del alojamiento, con más contexto.' },
    { title: 'No predice el futuro', body: 'Lee lo que ya ocurrió en las fuentes conectadas.' },
  ],
  ecosystemTitle: 'Growth cierra la lectura. No obliga a contratar el resto.',
  ecosystemSteps: ['Digital Check', 'Entender', 'Web', 'Presentar', 'Visibility', 'Ser encontrado', 'Content', 'Mostrar', 'Connect', 'Conversar', 'Booking Engine', 'Reservar', 'Growth', 'Medir'],
  ecosystemNote: 'Es el lugar de Growth en el ecosistema. Cada servicio se contrata por separado.',
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal es el establecimiento pionero de Andario Hospitality. No publicamos su tráfico, sus reservas ni sus conversiones.',
  finalTitle: 'Haz que las decisiones de tu alojamiento tengan más contexto.',
  finalBody: 'Cuéntanos qué ya puedes ver y qué te gustaría entender. Podemos ayudarte a ordenar la medición y a elegir por dónde seguir.',
  finalNote: 'Sin promesas de crecimiento. Con una lectura de lo que las fuentes permiten ver.',
};
