import type { HomePageContent } from '@/content/types';

export const homePageEs: HomePageContent = {
  h1: 'Haz crecer tu alojamiento en Internet',
  support:
    'Te ayudamos a tener una página web profesional, aparecer en Google, recibir reservas directas y atender mejor a tus huéspedes.',
  trust: 'No necesitas saber de tecnología. Nosotros te acompañamos paso a paso.',
  primaryCta: 'Quiero saber por dónde empezar',
  secondaryCta: 'Hablar con Andario',
  forLine: 'Para hostales · hoteles pequeños · posadas · cabañas · apartamentos turísticos · alojamientos independientes',
  problemTitle: '¿Sientes que tu alojamiento podría vender más por Internet?',
  problemIntro: 'Tal vez algunas de estas situaciones te resultan conocidas.',
  problems: [
    'Tengo redes sociales, pero no sé si realmente me ayudan.',
    'La mayoría de mis reservas vienen de Booking u otras plataformas.',
    'No tengo una página web profesional.',
    'Los huéspedes me escriben constantemente por WhatsApp.',
    'Quiero aparecer mejor en Google.',
    'No sé qué debería mejorar primero.',
  ],
  problemClose: 'No tienes que resolverlo todo de una vez.',
  problemNext: 'Primero entendemos tu situación y te ayudamos a decidir por dónde empezar.',
  problemCta: 'Quiero un diagnóstico',
  offerTitle: '¿Qué podemos hacer por tu alojamiento?',
  offerSupport:
    'Ayudamos a pequeños y medianos alojamientos a mejorar su presencia, sus reservas y la forma en que trabajan por Internet.',
  cards: {
    'andario-web': {
      title: 'Una página web profesional',
      body: 'Para que tus huéspedes conozcan tu alojamiento, vean lo que ofreces y puedan contactarte o reservar.',
      cta: 'Conocer Andario Web',
    },
    'andario-visibility': {
      title: 'Que te encuentren en Google',
      body: 'Trabajamos para mejorar la presencia de tu alojamiento cuando las personas buscan dónde hospedarse.',
      cta: 'Conocer Andario Visibility',
    },
    'andario-booking-engine': {
      title: 'Recibe reservas directamente',
      body: 'Construimos un canal propio para que tus huéspedes puedan consultar y gestionar sus reservas.',
      cta: 'Conocer Andario Booking Engine',
    },
    'andario-connect': {
      title: 'Atiende mejor por WhatsApp',
      body: 'Te ayudamos a organizar la comunicación con tus huéspedes y responder más fácilmente.',
      cta: 'Conocer Andario Connect',
    },
    'andario-content': {
      title: 'Muestra mejor tu alojamiento',
      body: 'Fotografías, textos y contenido para mostrar la experiencia que ofreces.',
      cta: 'Conocer Andario Content',
    },
    'andario-growth': {
      title: 'Entiende qué está funcionando',
      body: 'Te ayudamos a conocer qué canales y acciones están generando resultados.',
      cta: 'Conocer Andario Growth',
    },
    'digital-check': {
      title: 'Descubre por dónde empezar',
      body: 'Analizamos tu situación y te ayudamos a definir qué deberías mejorar primero.',
      cta: 'Conocer Digital Check',
    },
  },
  solutionsCta: 'Ver todas las soluciones',
  paceTitle: 'No tienes que hacerlo todo de una vez',
  pace: [
    'Cada alojamiento tiene necesidades diferentes.',
    'Primero entendemos dónde estás, qué quieres mejorar y qué puede ayudarte realmente.',
    'Después construimos contigo el camino.',
  ],
  paceSteps: ['Entender', 'Priorizar', 'Mejorar', 'Medir', 'Seguir creciendo'],
  knownTitle: 'Tú conoces tu alojamiento.\nNosotros te ayudamos con la tecnología.',
  knownBody: [
    'No necesitas convertirte en experto en páginas web, Google, reservas o herramientas digitales.',
    'Nuestro trabajo es explicarte las opciones, ayudarte a elegir lo que realmente necesitas y acompañarte durante el proceso.',
  ],
  audienceTitle: 'Pensado para alojamientos como el tuyo',
  audiences: [
    'Hostales',
    'Hoteles pequeños',
    'Posadas',
    'Casas de huéspedes',
    'Cabañas',
    'Alojamientos rurales',
    'Apartamentos turísticos',
    'Apartahoteles',
  ],
  audienceCta: 'Ver alojamientos',
  processTitle: 'Empezamos por lo que necesitas',
  process: [
    { title: 'Hablamos', body: 'Nos cuentas cómo funciona actualmente tu alojamiento.' },
    { title: 'Revisamos', body: 'Miramos tu página, Google, redes, WhatsApp y reservas.' },
    { title: 'Te recomendamos', body: 'Te explicamos qué conviene hacer primero.' },
    { title: 'Lo construimos contigo', body: 'Implementamos las soluciones que realmente necesitas.' },
    { title: 'Seguimos mejorando', body: 'Medimos los resultados y buscamos nuevas oportunidades.' },
  ],
  processCta: 'Conocer nuestra forma de trabajar',
  bookingTitle: 'Tu alojamiento también puede tener su propio canal de reservas',
  booking: [
    'No tienes que depender únicamente de plataformas externas.',
    'Con Andario Booking Engine puedes ofrecer a tus huéspedes una forma sencilla de consultar disponibilidad y gestionar sus reservas desde tus propios canales.',
  ],
  bookingCta: 'Conocer Andario Booking Engine',
  bookingBranches: [
    { title: 'Tu página', body: 'El lugar donde tus huéspedes conocen el alojamiento y pueden consultar.' },
    { title: 'WhatsApp', body: 'El canal por el que ya te escriben. Aquí ordenamos esa conversación.' },
    { title: 'Otras plataformas', body: 'Pueden seguir funcionando al mismo tiempo que tu propio canal.' },
  ],
  bookingResult: 'Una reserva en tu canal',
  bookingNote: 'Booking y otras plataformas pueden seguir ahí. Este canal es tuyo y convive con ellas.',
  pioneerTitle: 'Estamos empezando con alojamientos reales',
  pioneer: [
    'BARUCH Hostal, en Buritaca, Magdalena, es nuestro establecimiento pionero.',
    'Este proyecto nos permite poner nuestras soluciones a prueba, aprender y seguir mejorándolas en un alojamiento real.',
  ],
  pioneerCta: 'Conocer el proyecto',
  finalTitle: '¿No sabes por dónde empezar?',
  finalBody: ['Cuéntanos cómo funciona hoy tu alojamiento.', 'Te ayudamos a identificar qué deberías mejorar primero.'],
  finalPrimary: 'Solicitar diagnóstico digital',
  finalSecondary: 'Hablar por WhatsApp',
  faqs: [
    {
      q: '¿Tengo que saber de tecnología?',
      a: 'No. Tú conoces tu alojamiento. Nosotros te explicamos las opciones y te acompañamos paso a paso.',
    },
    {
      q: '¿Tengo que contratar todas las soluciones?',
      a: 'No. Puedes empezar por lo que tu alojamiento necesita ahora y sumar después, si tiene sentido.',
    },
    {
      q: '¿Por dónde debería empezar?',
      a: 'Por una conversación. Si no tienes claro qué mejorar primero, el diagnóstico te ayuda a verlo.',
    },
    { q: '¿Puedo empezar solo con una página web?', a: 'Sí.' },
    {
      q: '¿Andario reemplaza Booking u otras plataformas?',
      a: 'No. Puedes seguir usándolas y, al mismo tiempo, tener un canal propio para tus huéspedes.',
    },
    {
      q: '¿Garantizan más reservas?',
      a: 'No. Te ayudamos a tener una mejor presencia, una página clara y un camino para recibir reservas. Los resultados dependen de muchos factores.',
    },
    { q: '¿Trabajan con alojamientos pequeños?', a: 'Sí. Trabajamos con hostales, hoteles pequeños, posadas, cabañas y otros alojamientos independientes.' },
    { q: '¿Cómo comienzo?', a: 'Puedes solicitar un diagnóstico o escribirnos por WhatsApp.' },
  ],
};
