import type { HomePageContent } from '@/content/types';

export const homePageEs: HomePageContent = {
  eyebrow: 'Andario Hospitality',
  h1: 'Tu alojamiento merece mucho más que estar en Internet.',
  support:
    'Construimos contigo una estrategia digital para que tu alojamiento tenga una presencia profesional, sea más fácil de encontrar, pueda fortalecer sus canales propios de reserva y convierta cada interacción digital en parte de una misma experiencia.',
  primaryCta: 'Quiero mejorar mi alojamiento',
  secondaryCta: 'Descubrir cómo',
  micro: 'Para hostales, hoteles pequeños, posadas, apartahoteles, cabañas y alojamientos independientes.',
  heroAltH1: 'De estar en Internet a trabajar digitalmente para tu alojamiento.',
  heroAltSupport:
    'Estrategia, tecnología y acompañamiento para construir tu presencia, mejorar tu visibilidad, conectar tus conversaciones, facilitar tus reservas y entender qué está funcionando.',
  heroCenter: 'Tu alojamiento',
  heroNodes: ['Visibility', 'Content', 'Web', 'Booking', 'Connect', 'Growth', 'Digital Check'],
  heroMobile: ['Digital Check', 'Web', 'Visibility', 'Content', 'Connect', 'Booking Engine', 'Growth'],
  heroCaption:
    'El alojamiento está en el centro. Alrededor se relacionan visibilidad, contenido, web, comunicación, reservas, medición y diagnóstico. No es un orden obligatorio ni una integración automática.',
  journeyTitle: 'Tu huésped empieza su experiencia mucho antes de llegar.',
  journeyBody:
    'Andario trabaja contigo en ese recorrido digital: desde cómo te encuentran hasta cómo descubren tu alojamiento, conversan contigo, reservan y generan señales que pueden ayudarte a seguir mejorando.',
  journeySteps: ['Te encuentra', 'Te conoce', 'Te escribe', 'Te compara', 'Reserva', 'Llega'],
  journeyMap: ['Google', 'Web', 'Content', 'WhatsApp', 'Booking Engine', 'Reserva', 'Growth'],
  journeyNote: 'Este mapa explica el recorrido. No significa que todos los canales queden integrados de forma automática.',
  memorySteps: ['Encuentra', 'Conoce', 'Confía', 'Conversa', 'Reserva', 'Regresa'],
  memoryNote: 'Es una lectura del ecosistema digital. Andario no controla cada uno de estos pasos.',
  problemTitle: 'Tu alojamiento ya está haciendo muchas cosas. ¿Pero están trabajando juntas?',
  problemChannels: ['Google', 'Instagram', 'Facebook', 'WhatsApp', 'OTA', 'Web', 'Reservas', 'Fotografías', 'Contenido'],
  problemBody: [
    'Quizás tienes presencia en varios canales. Quizás recibes consultas por WhatsApp, tienes redes sociales, apareces en Google o incluso tienes una página web.',
    'Cuando cada parte funciona por separado, el esfuerzo se multiplica y la experiencia se fragmenta.',
  ],
  problemClose: 'No necesitas más canales. Necesitas que los que ya tienes trabajen mejor juntos.',
  fragmentTitle: 'De piezas separadas a un camino con dirección.',
  beforeLabel: 'Antes',
  beforeItems: ['Web', 'Redes', 'Google', 'WhatsApp', 'OTA', 'Reservas', 'Content', 'Fotos'],
  beforeNote: 'Todo existe. Pero está separado.',
  afterLabel: 'Con una estrategia',
  afterFlow: ['Web', 'Visibility', 'Content', 'Connect', 'Booking Engine', 'Growth'],
  afterNote: 'Una estrategia. Un ecosistema. Un camino de evolución. No es una integración automática de todos los canales.',
  visionTitle: 'Imagina que todo tu ecosistema digital empieza a trabajar en la misma dirección.',
  visionItems: [
    { title: 'Tu web presenta', body: 'Tu alojamiento de forma profesional.' },
    { title: 'Google te ayuda a ser encontrado', body: 'Con una base de visibilidad y SEO. Sin prometer la primera posición.' },
    { title: 'Tu contenido muestra la experiencia', body: 'Espacios, servicios, destino y propuesta.' },
    { title: 'WhatsApp mantiene la conversación', body: 'Con comunicación organizada.' },
    { title: 'Booking Engine facilita la reserva', body: 'Con tecnología propia para tu canal de reservas.' },
    { title: 'Growth ayuda a entender lo que ocurre', body: 'Midiendo señales e interacciones disponibles.' },
  ],
  visionClose: 'Eso es lo que queremos construir contigo.',
  bookingTitle: 'Tu alojamiento puede tener su propio canal de reservas.',
  bookingSupport:
    'Andario Booking Engine es nuestra tecnología propia para gestionar disponibilidad, tarifas, huéspedes y reservas desde un canal directo.',
  bookingPhrase: 'Más control sobre tu propio canal. Menos dependencia de procesos manuales.',
  bookingCta: 'Conocer Andario Booking Engine',
  bookingBranches: [
    { title: 'Web', body: 'Canal propio de partida para consultar disponibilidad y reservar.' },
    { title: 'WhatsApp', body: 'Sirve para conversar. Reservar dentro del chat no es un canal activo.' },
    { title: 'Otros canales', body: 'Se puede registrar el origen de una reserva. Eso no es una integración en vivo.' },
  ],
  bookingResult: 'Reserva en tu canal',
  bookingNote:
    'El motor concentra disponibilidad, tarifas, unidades, huéspedes y reservas. Puede convivir con las OTAs. No las reemplaza.',
  cardsTitle: 'Construimos el ecosistema alrededor de tu alojamiento.',
  cardsSupport: 'Cada solución responde a una necesidad concreta. Puedes empezar por una y evolucionar cuando estés preparado.',
  verbs: {
    'digital-check': 'Entender',
    'andario-web': 'Construir',
    'andario-visibility': 'Ser encontrado',
    'andario-booking-engine': 'Reservar',
    'andario-connect': 'Comunicar',
    'andario-content': 'Mostrar',
    'andario-growth': 'Medir y evolucionar',
  },
  cards: {
    'digital-check': {
      category: 'Diagnóstico y estrategia',
      body: 'Entender qué funciona, qué falta y qué deberías priorizar.',
      cta: 'Conocer Digital Check',
    },
    'andario-web': {
      category: 'Presencia digital',
      body: 'Una web profesional para presentar tu alojamiento, destino, servicios, experiencias y canales de contacto.',
      cta: 'Conocer Andario Web',
    },
    'andario-visibility': {
      category: 'SEO, Google y visibilidad',
      body: 'Trabajamos bases técnicas, locales y de contenido para mejorar la capacidad de tu establecimiento de aparecer ante búsquedas relevantes.',
      cta: 'Conocer Andario Visibility',
    },
    'andario-booking-engine': {
      category: 'Reservas directas',
      body: 'Tecnología propia para gestionar disponibilidad, tarifas, huéspedes y reservas desde un canal propio.',
      cta: 'Conocer Booking Engine',
    },
    'andario-connect': {
      category: 'Comunicación y automatización',
      body: 'Conectamos WhatsApp y otros puntos de comunicación con el recorrido comercial y de reservas, reduciendo tareas repetitivas cuando la automatización aplica.',
      cta: 'Conocer Connect',
    },
    'andario-content': {
      category: 'Fotografía y contenido',
      body: 'Ayudamos a presentar mejor el alojamiento mediante fotografías, textos, video, contenido de destino y planificación editorial, según el alcance acordado.',
      cta: 'Conocer Content',
    },
    'andario-growth': {
      category: 'Analítica y optimización',
      body: 'Medimos interacciones, canales, eventos y señales del ecosistema para convertir datos disponibles en información útil para decidir y mejorar.',
      cta: 'Conocer Growth',
    },
  },
  ownTech: 'Tecnología propia',
  solutionsCta: 'Ver todas las soluciones',
  whereTitle: 'No todos los alojamientos necesitan lo mismo.',
  whereSupport:
    'Lo importante no es contratar más herramientas. Es empezar por la necesidad que hoy tiene mayor impacto para tu negocio. Es una orientación, no una recomendación obligatoria.',
  scenarios: [
    {
      title: 'Estoy empezando',
      body: 'Necesito construir una presencia digital profesional.',
      cta: 'Quiero empezar',
      placement: 'starting',
      services: ['digital-check', 'andario-web', 'andario-content'],
    },
    {
      title: 'Tengo presencia, pero no me encuentran',
      body: 'La prioridad es aparecer ante búsquedas relevantes.',
      cta: 'Quiero mejorar mi visibilidad',
      placement: 'visibility',
      services: ['digital-check', 'andario-visibility', 'andario-content'],
    },
    {
      title: 'Recibo consultas, pero todo es manual',
      body: 'Las conversaciones y las reservas todavía dependen de procesos sueltos.',
      cta: 'Quiero ordenar mis reservas',
      placement: 'bookings',
      services: ['andario-connect', 'andario-booking-engine', 'andario-web'],
    },
    {
      title: 'Tengo varios canales desconectados',
      body: 'Hay piezas, pero no forman un recorrido.',
      cta: 'Quiero conectar mi ecosistema',
      placement: 'ecosystem',
      services: ['digital-check', 'andario-web', 'andario-connect', 'andario-booking-engine', 'andario-growth'],
    },
    {
      title: 'Ya tengo presencia y quiero mejorarla',
      body: 'Hace falta entender qué está ocurriendo para decidir el siguiente paso.',
      cta: 'Quiero medir y mejorar',
      placement: 'measure',
      services: ['andario-growth', 'andario-visibility', 'digital-check'],
    },
  ],
  adaptTitle: 'No necesitas hacerlo todo de una vez.',
  adaptBody:
    'Cada alojamiento tiene una situación diferente. Puedes empezar con una necesidad concreta y sumar nuevas soluciones cuando tu negocio esté preparado.',
  adaptClose: 'No queremos venderte todo. Queremos ayudarte a construir lo que realmente necesitas.',
  shiftTitle: 'Del esfuerzo disperso a una estrategia con dirección.',
  shiftNote: 'Es una transformación conceptual. No es una promesa de resultados.',
  beforeWord: 'Antes',
  afterWord: 'Después',
  shifts: [
    { before: 'Web sin estrategia.', after: 'Presencia digital orientada al negocio.' },
    { before: 'Consultas dispersas.', after: 'Comunicación más organizada.' },
    { before: 'Reservas manuales.', after: 'Un canal propio de reservas.' },
    { before: 'Datos sin contexto.', after: 'Información para decidir.' },
  ],
  audienceTitle: 'Diseñado para quienes hacen que cada alojamiento sea diferente.',
  audienceIntro: 'El foco está en pequeños y medianos alojamientos independientes. No hay un tamaño mínimo ni un formato único.',
  audiences: [
    { title: 'Hostales', body: 'Una presencia digital a la altura de una operación cercana y con varias unidades.' },
    { title: 'Hoteles pequeños', body: 'Un canal propio sin la complejidad de una gran plataforma.' },
    { title: 'Posadas', body: 'La identidad del lugar, contada con claridad antes de la llegada.' },
    { title: 'Apartamentos turísticos', body: 'Unidades, disponibilidad y una forma ordenada de consultar y reservar.' },
    { title: 'Cabañas y villas', body: 'El destino y la estancia, presentados como una experiencia.' },
    { title: 'Emprendimientos turísticos', body: 'Empezar por lo que hoy hace falta y crecer después.' },
  ],
  audienceCta: 'Ver alojamientos',
  processTitle: 'No digitalizamos por digitalizar. Construimos lo que tiene sentido para tu negocio.',
  process: [
    { title: 'Entender', body: '¿Qué está pasando?' },
    { title: 'Priorizar', body: '¿Qué importa primero?' },
    { title: 'Construir', body: '¿Qué necesitamos implementar?' },
    { title: 'Medir', body: '¿Qué está ocurriendo?' },
    { title: 'Evolucionar', body: '¿Qué podemos mejorar?' },
  ],
  processClose: 'Tu estrategia se construye alrededor de tu negocio, no al revés.',
  processCta: 'Ver cómo trabajamos',
  trustTitle: 'Tecnología sin complicarte la vida.',
  pillars: [
    { title: 'Especialización', body: 'Trabajamos pensando en pequeños y medianos alojamientos independientes.' },
    { title: 'Simplicidad', body: 'La tecnología debe ser comprensible y útil.' },
    { title: 'Tecnología propia', body: 'Desarrollamos soluciones propias como Andario Booking Engine.' },
    { title: 'Acompañamiento', body: 'No se trata solo de implementar. Se trata de entender, medir y evolucionar.' },
    {
      title: 'Transparencia',
      body: 'Explicamos qué hacemos, qué incluye cada solución y qué resultados no podemos garantizar.',
    },
  ],
  craftTitle: 'Una estrategia digital no debería sentirse más complicada que el problema que intenta resolver.',
  craftItems: ['Claridad', 'Estrategia', 'Tecnología', 'Acompañamiento', 'Medición'],
  craftClose: 'Eso es Andario Hospitality.',
  originTitle: 'Nacemos en Colombia con una visión latinoamericana.',
  origin: [
    'Andario Hospitality nace para ayudar a pequeños y medianos alojamientos independientes a profesionalizar su presencia digital y construir canales propios.',
    'Queremos llevar esta visión desde Colombia hacia Latinoamérica, acompañando establecimientos que necesitan tecnología accesible, estrategia y acompañamiento.',
  ],
  originCta: 'Conocer Andario',
  casesTitle: 'Historias reales. Aprendizajes reales.',
  casesPlace: 'BARUCH Hostal · Buritaca, Colombia',
  casesBody:
    'BARUCH es el establecimiento pionero con el que estamos llevando Andario Hospitality de la idea a la operación real. Todavía no publicamos métricas, reservas ni testimonios.',
  casesCta: 'Conocer nuestros casos',
  hopeTitle: 'No importa dónde esté hoy tu alojamiento. Importa saber cuál es el siguiente paso.',
  hopeBody:
    'Algunos alojamientos están comenzando. Otros ya tienen web, redes, WhatsApp y presencia en diferentes plataformas. No todos necesitan lo mismo. Nuestro trabajo es ayudarte a entender tu punto de partida y construir desde allí.',
  hopeSteps: ['Hoy', 'Diagnóstico', 'Prioridad', 'Implementación', 'Medición', 'Evolución'],
  finalTitle: 'El siguiente paso de tu alojamiento empieza con una conversación.',
  finalBody:
    'Cuéntanos dónde estás hoy, qué te preocupa y qué quieres mejorar. Analizaremos tu situación y te ayudaremos a identificar por dónde empezar.',
  finalPrimary: 'Solicitar diagnóstico digital',
  finalSecondary: 'Hablar con Andario',
  finalNote: 'Sin compromiso. Sin venderte soluciones que no necesitas.',
  faqs: [
    { q: '¿Tengo que contratar todas las soluciones?', a: 'No. Puedes contratar solo las que respondan a lo que tu alojamiento necesita ahora.' },
    { q: '¿Por dónde debería empezar?', a: 'Si no tienes claro qué necesitas, Digital Check puede ayudarte a identificar prioridades.' },
    { q: '¿Puedo contratar solo Booking Engine?', a: 'Sí, dependiendo del alcance y de las condiciones comerciales del producto.' },
    { q: '¿Andario reemplaza Booking.com?', a: 'No. Andario busca fortalecer tus canales propios y puede coexistir con las OTAs.' },
    {
      q: '¿Andario garantiza más reservas?',
      a: 'No. Aporta estrategia, tecnología y herramientas para construir y mejorar el ecosistema digital. Los resultados dependen de muchos factores.',
    },
    { q: '¿Puedo empezar solo con una web?', a: 'Sí.' },
    { q: '¿Puedo sumar soluciones después?', a: 'Sí. La propuesta está pensada para evolucionar cuando el alojamiento esté preparado.' },
    {
      q: '¿Las soluciones están conectadas?',
      a: 'Pueden formar un ecosistema, según lo que contrates y las integraciones disponibles. No todo queda conectado de forma automática.',
    },
    { q: '¿Trabajan con alojamientos pequeños?', a: 'Sí. El foco está en pequeños y medianos alojamientos independientes.' },
    { q: '¿Cómo comienzo?', a: 'Puedes solicitar un diagnóstico digital o hablar directamente con Andario.' },
  ],
};
