import type { HomePageContent } from '@/content/types';

export const homePageEs: HomePageContent = {
  h1: 'Haz crecer tu alojamiento en Internet',
  support:
    'Te ayudamos a tener una página web profesional, aparecer en Google, recibir reservas directas y atender mejor a tus huéspedes.',
  trust: 'No necesitas saber de tecnología. Nosotros te acompañamos paso a paso.',
  primaryCta: 'Quiero saber por dónde empezar',
  secondaryCta: 'Hablar con Andario',
  forLine: 'Para hostales · hoteles pequeños · posadas · cabañas · apartamentos turísticos · alojamientos independientes',
  heroAlt: 'Edificio urbano con la marca Andario Hospitality en la fachada, sobre una calle de ciudad.',
  heroBadge: 'Alojamiento independiente',
  checkAlt: 'Escritorio con un computador que muestra el diagnóstico digital de Andario Hospitality, una lista de presencia y un resumen estratégico.',
  checkNote: 'Representación conceptual. No es una captura del producto.',
  checkItems: [
    { label: 'Página web', tone: 'steady' },
    { label: 'Google', tone: 'steady' },
    { label: 'Reservas', tone: 'attention' },
    { label: 'WhatsApp', tone: 'attention' },
    { label: 'Contenido', tone: 'steady' },
    { label: 'Medición', tone: 'attention' },
  ],
  knownAlt: 'Dos personas revisando un computador en la recepción de un alojamiento, con patio y plantas al fondo.',
  mockProperty: 'Casa del patio',
  mockDates: '12–15 oct',
  mockGuests: '2 huéspedes',
  mockUnit: 'Habitación disponible',
  mockPrice: 'Tarifa del alojamiento',
  mockAction: 'Reservar',
  mockNote: 'Ejemplo ilustrativo. No es una captura del producto.',
  bookingAlt:
    'Interfaz ilustrativa de Andario Booking Engine en computador y teléfono, con habitaciones y una reserva de ejemplo.',
  bridge: 'Tener presencia digital no significa tener una estrategia digital.',
  situationsTitle: '¿Dónde está hoy tu alojamiento?',
  situations: [
    { title: 'Estoy empezando', body: 'Presencia digital mínima y no sé por dónde comenzar.' },
    { title: 'Estoy, pero no me encuentran', body: 'Tengo presencia digital, pero poca visibilidad.' },
    { title: 'Recibo consultas, pero todo es manual', body: 'WhatsApp, llamadas y reservas se gestionan manualmente.' },
    { title: 'Tengo varios canales desconectados', body: 'Web, OTAs, redes y WhatsApp no están conectados.' },
    { title: 'Tengo herramientas, pero no sé qué funciona', body: 'No tengo claridad sobre visitas, consultas y reservas.' },
  ],
  situationClose: 'No importa dónde esté hoy tu alojamiento. Importa saber cuál es el siguiente paso.',
  situationCta: 'Descubrir por dónde empezar',
  boardTitle: 'Diagnóstico digital',
  boardStatus: 'Estado actual de tu alojamiento',
  boardAreas: 'Áreas revisadas',
  boardOpportunities: 'Oportunidades prioritarias',
  boardNext: 'Próximos pasos',
  opportunities: ['Reservas directas', 'Atención por WhatsApp', 'Medición de lo que ocurre'],
  nextSteps: ['Definir el alcance', 'Armar una hoja de ruta', 'Implementar lo prioritario', 'Medir y ajustar'],
  offerTitle: 'Un sistema, no siete productos sueltos',
  offerSupport: 'Digital Check dice por dónde empezar. Las demás soluciones construyen solo lo que tu alojamiento necesita.',
  cards: {
    'andario-web': {
      role: 'Construir',
      title: 'Una página web profesional',
      body: 'Para que tus huéspedes conozcan tu alojamiento, vean lo que ofreces y puedan contactarte o reservar.',
      cta: 'Conocer Andario Web',
    },
    'andario-visibility': {
      role: 'Ser encontrado',
      title: 'Que te encuentren en Google',
      body: 'Trabajamos para mejorar la presencia de tu alojamiento cuando las personas buscan dónde hospedarse.',
      cta: 'Conocer Andario Visibility',
    },
    'andario-booking-engine': {
      role: 'Recibir reservas',
      title: 'Recibe reservas directamente',
      body: 'Construimos un canal propio para que tus huéspedes puedan consultar y gestionar sus reservas.',
      cta: 'Conocer Andario Booking Engine',
    },
    'andario-connect': {
      role: 'Comunicar',
      title: 'Atiende mejor por WhatsApp',
      body: 'Te ayudamos a organizar la comunicación con tus huéspedes y responder más fácilmente.',
      cta: 'Conocer Andario Connect',
    },
    'andario-content': {
      role: 'Mostrar',
      title: 'Muestra mejor tu alojamiento',
      body: 'Fotografías, textos y contenido para mostrar la experiencia que ofreces.',
      cta: 'Conocer Andario Content',
    },
    'andario-growth': {
      role: 'Medir y mejorar',
      title: 'Entiende qué está funcionando',
      body: 'Te ayudamos a conocer qué canales y acciones están generando resultados.',
      cta: 'Conocer Andario Growth',
    },
    'digital-check': {
      role: 'Entender',
      title: 'Descubre por dónde empezar',
      body: 'Analizamos tu situación y te ayudamos a definir qué deberías mejorar primero.',
      cta: 'Conocer Digital Check',
    },
  },
  solutionsCta: 'Conocer nuestras soluciones',
  roadmapTitle: 'Del diagnóstico a la acción',
  roadmapIntro: 'Primero entendemos. Después hacemos solo lo que tiene sentido para tu alojamiento.',
  roadmap: ['Diagnóstico', 'Priorización', 'Hoja de ruta', 'Implementación', 'Medición', 'Evolución'],
  knownTitle: 'Tú conoces tu alojamiento.\nNosotros te ayudamos con la tecnología.',
  knownBody: [
    'No necesitas convertirte en experto en páginas web, Google, reservas o herramientas digitales.',
    'Nuestro trabajo es explicarte las opciones, ayudarte a elegir lo que realmente necesitas y acompañarte durante el proceso.',
  ],
  audienceTitle: 'Pensado para alojamientos como el tuyo',
  audiences: [
    'Hostales',
    'Hoteles pequeños',
    'Posadas',
    'Casas de huéspedes',
    'Cabañas',
    'Alojamientos rurales',
    'Apartamentos turísticos',
    'Apartahoteles',
  ],
  audienceCta: 'Ver alojamientos',
  processCta: 'Conocer nuestra forma de trabajar',
  differentiatorsTitle: 'Por qué trabajar con Andario',
  differentiators: [
    { title: 'Especialización', body: 'Trabajamos con alojamientos, no con cualquier negocio.' },
    { title: 'Simplicidad', body: 'Te explicamos las opciones en lenguaje claro.' },
    { title: 'Tecnología propia', body: 'Construimos herramientas pensadas para tu operación.' },
    { title: 'Acompañamiento', body: 'No te dejamos solo después de entregar.' },
    { title: 'Transparencia', body: 'Decimos qué está listo y qué sigue en evolución.' },
  ],
  bookingTitle: 'Construye tu propio canal de reservas.',
  booking: [
    'Tu página web presenta tu alojamiento. Andario Booking Engine se encarga de gestionar la reserva.',
    'Hoy el canal web es el punto de partida. WhatsApp, Instagram, Facebook, Google y los asistentes de IA siguen en evolución.',
  ],
  bookingCta: 'Conocer Andario Booking Engine',
  bookingBranches: [
    { title: 'Tu página', body: 'El lugar donde tus huéspedes conocen el alojamiento y pueden consultar.' },
    { title: 'WhatsApp', body: 'El canal por el que ya te escriben. Aquí ordenamos esa conversación.' },
    { title: 'Otras plataformas', body: 'Pueden seguir funcionando al mismo tiempo que tu propio canal.' },
  ],
  bookingResult: 'Una reserva en tu canal',
  bookingNote: 'Ejemplo ilustrativo. No es una captura del producto.',
  bookingOta: 'No necesitas abandonar las OTAs. Necesitas fortalecer tu canal propio.',
  bookingPoints: ['Disponibilidad', 'Tarifas', 'Habitaciones o unidades', 'Huéspedes', 'Reservas', 'Reglas', 'Origen del canal', 'Administración'],
  finalTitle: '¿No sabes por dónde empezar?',
  finalBody: ['Cuéntanos dónde está hoy tu alojamiento, qué te preocupa y qué quieres mejorar.'],
  finalPrimary: 'Solicitar diagnóstico digital',
  finalSecondary: 'Hablar con Andario',
  faqs: [
    {
      q: '¿Tengo que saber de tecnología?',
      a: 'No. Tú conoces tu alojamiento. Nosotros te explicamos las opciones y te acompañamos paso a paso.',
    },
    {
      q: '¿Tengo que contratar todas las soluciones?',
      a: 'No. Puedes empezar por lo que tu alojamiento necesita ahora y sumar después, si tiene sentido.',
    },
    {
      q: '¿Por dónde debería empezar?',
      a: 'Por una conversación. Si no tienes claro qué mejorar primero, el diagnóstico te ayuda a verlo.',
    },
    { q: '¿Puedo empezar solo con una página web?', a: 'Sí.' },
    {
      q: '¿Andario reemplaza Booking u otras plataformas?',
      a: 'No. Puedes seguir usándolas y, al mismo tiempo, tener un canal propio para tus huéspedes.',
    },
    {
      q: '¿Garantizan más reservas?',
      a: 'No. Te ayudamos a tener una mejor presencia, una página clara y un camino para recibir reservas. Los resultados dependen de muchos factores.',
    },
    { q: '¿Trabajan con alojamientos pequeños?', a: 'Sí. Trabajamos con hostales, hoteles pequeños, posadas, cabañas y otros alojamientos independientes.' },
    { q: '¿Cómo comienzo?', a: 'Puedes solicitar un diagnóstico o escribirnos por WhatsApp.' },
  ],
};
