import type { HowWeWorkPageContent } from '@/content/types';

export const howWeWorkPageEs: HowWeWorkPageContent = {
  eyebrow: 'Cómo trabajamos',
  h1: 'Antes de digitalizar tu alojamiento, descubre qué necesita realmente.',
  support:
    'No necesitas saber de tecnología para empezar. Revisamos cómo funciona hoy tu presencia online, identificamos oportunidades de mejora y te ayudamos a decidir qué deberías mejorar primero.',
  primaryCta: 'Solicitar Digital Check',
  secondaryCta: 'Hablar con Andario',
  micro: 'Sin compromiso. Primero entendemos tu situación.',
  route: [
    'Tu alojamiento',
    'Digital Check',
    'Entendemos dónde estás',
    'Identificamos oportunidades',
    'Priorizamos',
    'Creamos una hoja de ruta',
    'Implementamos',
    'Medimos',
    'Evolucionamos',
  ],
  lostTitle: '¿No sabes por dónde empezar?',
  lostBody:
    'Es normal. Un alojamiento puede tener Instagram, WhatsApp, Booking.com, una página web o incluso varias herramientas, y aun así no tener claro qué debería mejorar primero.',
  situations: [
    'Tengo presencia en Internet, pero no sé si está funcionando.',
    'Tengo redes sociales, pero no me encuentran fácilmente.',
    'Dependo mucho de Booking.com u otras plataformas.',
    'Recibo muchas consultas por WhatsApp y hago procesos manuales.',
    'Tengo página web, pero no sé si realmente ayuda a mi negocio.',
    'Quiero mejorar, pero no sé qué debería hacer primero.',
  ],
  lostClose: 'No necesitas resolverlo todo de una vez.',
  lostMark: 'Primero necesitamos entender dónde estás.',
  checkLabel: 'Primer paso',
  checkTitle: 'Digital Check: el diagnóstico digital de tu alojamiento.',
  checkBody:
    'Digital Check es una revisión inicial de tu presencia online para entender cómo está funcionando hoy tu alojamiento, detectar oportunidades de mejora y ayudarte a definir por dónde empezar.',
  checkMark: 'No se trata de venderte más herramientas. Se trata de entender qué necesitas realmente.',
  reviewTitle: '¿Qué revisamos?',
  reviews: [
    { title: 'Tu página web', body: 'Cómo se presenta tu alojamiento y qué tan fácil es para un visitante entenderlo y contactarte.' },
    { title: 'Google y visibilidad', body: 'Qué tan fácil es encontrar tu alojamiento cuando una persona busca opciones como la tuya.' },
    { title: 'Redes sociales', body: 'Cómo estás mostrando tu alojamiento y qué papel cumplen tus redes dentro de tu presencia digital.' },
    { title: 'WhatsApp y comunicación', body: 'Cómo atiendes consultas y qué partes del proceso podrían simplificarse.' },
    { title: 'OTAs y canales externos', body: 'Cómo funcionan actualmente tus canales de reserva y qué papel cumplen dentro de tu estrategia.' },
    { title: 'Proceso de reserva', body: 'Qué ocurre desde que una persona muestra interés hasta que finalmente reserva.' },
    { title: 'Contenido e imágenes', body: 'Cómo fotografías, textos y contenidos influyen en la percepción de tu alojamiento.' },
    { title: 'Medición', body: 'Qué información tienes disponible para saber qué está funcionando y qué necesita mejorar.' },
    { title: 'Experiencia del visitante', body: 'Qué tan sencillo resulta encontrar información, contactar y avanzar hacia una reserva.' },
  ],
  receiveTitle: '¿Qué obtienes después del Digital Check?',
  receive: [
    { title: 'Diagnóstico', body: 'Entiendes dónde está hoy tu presencia digital.' },
    { title: 'Hallazgos', body: 'Identificamos qué está funcionando y dónde existen oportunidades de mejora.' },
    { title: 'Prioridades', body: 'Definimos qué debería atenderse primero y qué puede esperar.' },
    { title: 'Hoja de ruta', body: 'Construimos un camino de mejora adaptado a tus objetivos.' },
    { title: 'Recomendaciones', body: 'Identificamos qué soluciones pueden ayudarte y por qué.' },
    { title: 'Siguiente paso', body: 'Tú decides qué quieres implementar y cuándo.' },
  ],
  receiveMark: 'El Digital Check no te obliga a contratar todas las soluciones de Andario.',
  receiveNote: 'La hoja de ruta se construye alrededor de tu alojamiento, tus objetivos y tus prioridades.',
  mapTitle: 'De saber que necesitas mejorar a saber qué hacer primero.',
  mapBody: 'Muchas veces el problema no es saber que necesitas mejorar. El problema es no saber por dónde empezar.',
  beforeLabel: 'Antes',
  before: [
    'Tengo muchas cosas por mejorar.',
    'No sé cuál debería hacer primero.',
    'No sé qué herramienta necesito.',
    'No sé si mi página web está funcionando.',
    'No sé si estoy aprovechando Google.',
    'No sé qué está funcionando.',
  ],
  afterLabel: 'Después del Digital Check',
  after: [
    'Sé dónde estoy.',
    'Entiendo mis principales oportunidades.',
    'Sé qué debería priorizar.',
    'Entiendo qué soluciones pueden ayudarme.',
    'Tengo una ruta de mejora.',
    'Sé cuál puede ser mi siguiente paso.',
  ],
  goalsTitle: 'Tu objetivo también define el camino.',
  goalsIntro: 'No todos los alojamientos necesitan lo mismo. Estas son rutas posibles, no un paquete obligatorio.',
  goals: [
    { title: 'Quiero que más personas encuentren mi alojamiento.', services: ['andario-visibility', 'andario-web', 'andario-content'] },
    { title: 'Quiero tener una página web profesional.', services: ['andario-web'] },
    { title: 'Quiero recibir reservas directamente.', services: ['andario-web', 'andario-booking-engine'] },
    { title: 'Quiero organizar mejor las conversaciones con mis huéspedes.', services: ['andario-connect'] },
    { title: 'Quiero mostrar mejor mi alojamiento.', services: ['andario-content'] },
    { title: 'Quiero entender qué está funcionando.', services: ['andario-growth'] },
  ],
  unsure: 'No sé qué necesito. Empieza por Digital Check.',
  processTitle: 'Así trabajamos contigo',
  process: [
    { title: 'Conocemos tu alojamiento', body: 'Entendemos cómo funciona hoy y qué quieres conseguir.' },
    { title: 'Realizamos tu Digital Check', body: 'Revisamos tu presencia digital e identificamos oportunidades.' },
    { title: 'Definimos prioridades', body: 'Decidimos qué tiene más sentido mejorar primero.' },
    { title: 'Construimos contigo', body: 'Implementamos las soluciones que realmente necesitas.' },
    { title: 'Medimos', body: 'Observamos qué está ocurriendo y qué información está disponible.' },
    { title: 'Evolucionamos', body: 'Aprendemos de lo implementado y definimos los siguientes pasos.' },
  ],
  processClose: 'Tu alojamiento marca el ritmo. Nosotros construimos contigo el camino digital.',
  paceTitle: 'No tienes que hacerlo todo de una vez.',
  paceBody: 'Tu alojamiento puede empezar por una necesidad concreta y avanzar con el tiempo.',
  pace: ['Digital Check', 'Una prioridad', 'Una solución', 'Medición', 'Siguiente oportunidad'],
  paceNote: 'El objetivo no es llenarte de herramientas. Es ayudarte a construir una presencia digital que tenga sentido para tu negocio.',
  solutionsTitle: 'Dependiendo de lo que encontremos, podemos ayudarte en distintas áreas.',
  solutionsBody: 'El orden lo definen el diagnóstico y tus objetivos. No hay una secuencia obligatoria.',
  solutions: [
    { id: 'digital-check', body: 'Descubre por dónde empezar.' },
    { id: 'andario-web', body: 'Construye una presencia web profesional.' },
    { id: 'andario-visibility', body: 'Trabaja para que tu alojamiento pueda ser encontrado.' },
    { id: 'andario-content', body: 'Muestra mejor la experiencia que ofreces.' },
    { id: 'andario-connect', body: 'Organiza mejor la comunicación con tus huéspedes.' },
    { id: 'andario-booking-engine', body: 'Construye tu propio canal de reservas.' },
    { id: 'andario-growth', body: 'Entiende qué está funcionando y qué mejorar.' },
  ],
  knownMark: 'Tú conoces tu alojamiento.\nNosotros te ayudamos con la tecnología.',
  knownBody:
    'No necesitas convertirte en experto en páginas web, Google, reservas o herramientas digitales. Tú conoces tu negocio. Nosotros aportamos estrategia, tecnología y acompañamiento.',
  beliefs: [
    'No empezamos por vender. Primero entendemos.',
    'No recomendamos lo que no tiene sentido.',
    'No prometemos resultados que no podemos controlar.',
    'No creemos en digitalizar por digitalizar.',
    'Sí creemos en construir paso a paso.',
  ],
  bookingTitle: 'Cuando tu alojamiento necesita fortalecer su canal propio de reservas.',
  bookingBody:
    'Andario Booking Engine es nuestra tecnología propia para gestionar disponibilidad, tarifas, huéspedes y reservas desde un canal directo.',
  bookingNote: 'Puede convivir con OTAs. No necesitas abandonar Booking.com u otras plataformas para construir tu propio canal. Hoy no sincroniza esas plataformas.',
  bookingCta: 'Conocer Booking Engine',
  pioneerTitle: 'BARUCH Hostal: nuestro establecimiento pionero.',
  pioneerBody:
    'BARUCH Hostal, en Buritaca, Magdalena, es el primer establecimiento con el que estamos llevando este enfoque a la práctica y aprendiendo de un caso real.',
  finalTitle: '¿No sabes por dónde empezar?',
  finalBody:
    'Cuéntanos cómo funciona hoy tu alojamiento y qué quieres conseguir. Empezaremos por entender tu situación y, si tiene sentido, construiremos contigo una hoja de ruta de mejora.',
  finalNote: 'Sin compromiso. Primero entendemos. Después recomendamos.',
  faqs: [
    {
      q: '¿Qué es Digital Check?',
      a: 'Es el diagnóstico digital de tu alojamiento. Revisamos cómo está funcionando hoy tu presencia online y te ayudamos a ver por dónde empezar.',
    },
    {
      q: '¿Tengo que contratar Digital Check obligatoriamente?',
      a: 'No necesariamente. Si no tienes claro por dónde empezar, es nuestro punto de entrada recomendado. Si ya tienes una necesidad concreta, podemos hablar directamente sobre ella.',
    },
    {
      q: '¿Qué revisan en Digital Check?',
      a: 'Tu web, cómo te encuentran, tus redes, WhatsApp, los canales externos, el camino hasta la reserva, el contenido y la información que ya tienes para saber qué funciona.',
    },
    {
      q: '¿Qué recibo después del diagnóstico?',
      a: 'Una lectura de dónde estás, los hallazgos, las prioridades, una hoja de ruta y una recomendación del siguiente paso. Tú decides qué implementar.',
    },
    {
      q: '¿La hoja de ruta me obliga a contratar todas las soluciones?',
      a: 'No. La hoja de ruta es una recomendación basada en las necesidades y objetivos de tu alojamiento.',
    },
    {
      q: '¿Puedo empezar solamente con una página web?',
      a: 'Sí. Si esa es la necesidad clara, podemos hablar de Andario Web sin contratar el resto.',
    },
    {
      q: '¿Puedo incorporar Booking Engine después?',
      a: 'Sí. El canal propio de reservas puede sumarse cuando tu alojamiento esté listo. No reemplaza Booking.com y hoy no sincroniza las OTAs.',
    },
    {
      q: '¿Necesito conocimientos técnicos?',
      a: 'No. Tú conoces tu alojamiento y nosotros nos encargamos de ayudarte con la estrategia y la tecnología.',
    },
    {
      q: '¿Andario reemplaza Booking.com?',
      a: 'No. Puedes seguir usando tus plataformas y, si tiene sentido, construir además un canal propio.',
    },
    {
      q: '¿Cómo comienzo?',
      a: 'Si no sabes por dónde empezar, solicita tu Digital Check. Ese será el punto de partida para entender tu situación y construir una hoja de ruta.',
    },
  ],
};
