import type { SolutionsHubContent } from '@/content/types';

export const solutionsHubEs: SolutionsHubContent = {
  eyebrow: 'Soluciones para alojamientos independientes',
  h1: 'Digitaliza tu alojamiento, paso a paso.',
  support:
    'Te ayudamos a tener una página web profesional, aparecer en Google, recibir reservas directas, comunicarte mejor con tus huéspedes y entender qué está funcionando.',
  assist: 'No necesitas hacerlo todo de una vez. Empezamos por lo que tu alojamiento realmente necesita.',
  primaryCta: 'Quiero saber por dónde empezar',
  secondaryCta: 'Hablar con Andario',
  micro: 'Sin compromiso. Sin venderte soluciones que no necesitas.',
  heroAlt:
    'Recorrido visual de la digitalización de un alojamiento: página web, visibilidad, atención, reservas directas y medición.',
  problemTitle: '¿Te pasa algo de esto?',
  problemIntro: 'No todos los alojamientos necesitan lo mismo. Identifiquemos qué te está frenando hoy.',
  problems: [
    'No tengo una página web profesional.',
    'Mi alojamiento no aparece como quisiera en Google.',
    'Recibo muchas consultas por WhatsApp y hago gran parte del proceso manualmente.',
    'Dependo demasiado de plataformas como Booking.com o Airbnb para conseguir reservas.',
    'Tengo redes, pero no sé si realmente me ayudan a conseguir reservas.',
    'Tengo varias herramientas, pero no sé qué está funcionando.',
  ],
  whereTitle: '¿Dónde está hoy tu alojamiento?',
  whereIntro: 'No todos necesitan lo mismo. Elige la situación que más se parece a la tuya.',
  resultLabel: 'Tu siguiente paso',
  solutionLabel: 'Digital Check',
  whereAlt: 'Mujer atendiendo la recepción de un pequeño alojamiento, con el nombre Andario Hospitality en la pared.',
  scenarios: [
    {
      title: 'Estoy empezando',
      summary: 'Quiero construir una presencia digital profesional.',
      result: 'Antes de construir más herramientas, revisamos dónde está hoy tu alojamiento y qué conviene mejorar primero.',
      cta: 'Conocer Digital Check',
      placement: 'starting',
      service: 'digital-check',
    },
    {
      title: 'Quiero que me encuentren',
      summary: 'Tengo presencia, pero necesito mayor visibilidad.',
      result: 'Antes de construir más herramientas, revisamos dónde está hoy tu alojamiento y qué conviene mejorar primero.',
      cta: 'Conocer Digital Check',
      placement: 'visibility',
      service: 'digital-check',
    },
    {
      title: 'Quiero recibir reservas directamente',
      summary: 'Quiero construir mi propio canal de reservas.',
      result: 'Antes de construir más herramientas, revisamos dónde está hoy tu alojamiento y qué conviene mejorar primero.',
      cta: 'Conocer Digital Check',
      placement: 'bookings',
      service: 'digital-check',
    },
    {
      title: 'Quiero dedicar menos tiempo a tareas repetitivas',
      summary: 'Recibo consultas y gestiono buena parte del proceso manualmente.',
      result: 'Antes de construir más herramientas, revisamos dónde está hoy tu alojamiento y qué conviene mejorar primero.',
      cta: 'Conocer Digital Check',
      placement: 'connect',
      service: 'digital-check',
    },
    {
      title: 'Tengo herramientas, pero no sé aprovecharlas',
      summary: 'Tengo presencia en varios canales y necesito más claridad.',
      result: 'Antes de construir más herramientas, revisamos dónde está hoy tu alojamiento y qué conviene mejorar primero.',
      cta: 'Conocer Digital Check',
      placement: 'tools',
      service: 'digital-check',
    },
    {
      title: 'Quiero saber qué funciona',
      summary: 'Ya tengo presencia digital y quiero medir resultados.',
      result: 'Antes de construir más herramientas, revisamos dónde está hoy tu alojamiento y qué conviene mejorar primero.',
      cta: 'Conocer Digital Check',
      placement: 'measure',
      service: 'digital-check',
    },
  ],
  cardsTitle: 'Soluciones para cada etapa de tu alojamiento',
  cardsSupport: 'Empieza por una necesidad concreta y suma nuevas soluciones a medida que tu negocio evoluciona.',
  checkPrompt: '¿No sabes por dónde empezar?',
  checkNote: 'No necesitas saber qué solución contratar. Primero entendemos tu alojamiento.',
  portfolioTitle: 'Soluciones para tu alojamiento',
  portfolioBody: 'No necesitas contratarlo todo. Puedes empezar por una solución concreta y sumar otras cuando tengan sentido para tu negocio.',
  unsureTitle: '¿No sabes cuál necesitas?',
  unsureBody: 'Cuéntanos cómo funciona hoy tu alojamiento y te ayudamos a identificar por dónde empezar.',
  unsureCta: 'Solicitar diagnóstico digital',
  cards: {
    'digital-check': {
      category: 'Diagnóstico digital de tu alojamiento',
      problem: 'No sabes qué deberías mejorar primero.',
      body: 'Entendemos dónde estás, identificamos oportunidades y definimos qué conviene mejorar primero.',
      cta: 'Conocer Digital Check',
    },
    'andario-web': {
      category: 'Página web profesional',
      problem: 'No tienes una web profesional que represente tu alojamiento.',
      body: 'Una web que presenta tu alojamiento y facilita que tus visitantes conozcan tus espacios, servicios y formas de contacto.',
      cta: 'Conocer Andario Web',
    },
    'andario-visibility': {
      category: 'Google y visibilidad',
      problem: 'Tu alojamiento existe en Internet, pero no siempre es fácil encontrarlo.',
      body: 'Trabajamos la presencia de tu alojamiento para mejorar sus posibilidades de ser encontrado cuando las personas buscan opciones como la tuya.',
      cta: 'Conocer Visibility',
    },
    'andario-booking-engine': {
      category: 'Motor de reservas propio',
      problem: 'Muchas reservas dependen de procesos manuales o de plataformas externas.',
      body: 'Permite que tus huéspedes consulten disponibilidad y realicen reservas directamente desde tu propio canal.',
      cta: 'Conocer Booking Engine',
    },
    'andario-connect': {
      category: 'WhatsApp y comunicación',
      problem: 'Pasas demasiado tiempo respondiendo consultas y tareas repetitivas.',
      body: 'Te ayudamos a organizar mejor las consultas y la comunicación con tus huéspedes.',
      cta: 'Conocer Connect',
    },
    'andario-content': {
      category: 'Fotografía y contenido',
      problem: 'Tu alojamiento puede estar bien, pero no estás mostrando todo lo que ofrece.',
      body: 'Muestra mejor tus espacios, servicios y experiencias para que tu presencia digital represente lo que realmente ofreces.',
      cta: 'Conocer Content',
    },
    'andario-growth': {
      category: 'Medición y optimización',
      problem: 'No sabes qué está funcionando.',
      body: 'Entiende qué está funcionando en tus canales digitales y dónde puedes seguir mejorando.',
      cta: 'Conocer Growth',
    },
  },
  ownTech: 'Tecnología propia',
  paceEyebrow: 'Encuentra tu solución',
  paceTitle: 'No necesitas contratarlo todo.',
  paceBody: 'Empieza por lo que tu alojamiento necesita hoy. Más adelante puedes incorporar nuevas soluciones cuando tengan sentido para tu negocio.',
  paths: [
    {
      need: 'No sé qué necesita mi alojamiento.',
      support: 'Quiero entender mi punto de partida y definir qué conviene mejorar primero.',
      service: 'digital-check',
    },
    {
      need: 'No tengo una página web profesional.',
      support: 'Quiero presentar mi alojamiento, servicios y formas de contacto.',
      service: 'andario-web',
    },
    {
      need: 'Quiero mejorar mi visibilidad en Google.',
      support: 'Quiero que más personas encuentren mi alojamiento cuando buscan opciones como la mía.',
      service: 'andario-visibility',
    },
    {
      need: 'Quiero recibir reservas directamente.',
      support: 'Quiero que mis huéspedes consulten disponibilidad y reserven desde mi propio canal.',
      service: 'andario-booking-engine',
    },
    {
      need: 'Paso demasiado tiempo atendiendo consultas.',
      support: 'Quiero organizar mejor la comunicación con mis huéspedes.',
      service: 'andario-connect',
    },
    {
      need: 'Quiero mostrar mejor mi alojamiento.',
      support: 'Necesito fotografías y contenidos que representen bien mis espacios y experiencias.',
      service: 'andario-content',
    },
    {
      need: 'Quiero saber qué está funcionando.',
      support: 'Quiero medir resultados y entender dónde puedo mejorar.',
      service: 'andario-growth',
    },
  ],
  paceCloseTitle: '¿No sabes por dónde empezar?',
  paceCloseBody: 'Cuéntanos cómo funciona hoy tu alojamiento y te ayudamos a identificar qué conviene mejorar primero.',
  paceCta: 'Solicitar diagnóstico digital',
  trustTitle: '¿Por qué trabajar con Andario?',
  trustSupport: 'Pensamos en tu negocio, no solo en la tecnología.',
  pillars: [
    { title: 'Especialización', body: 'Conocemos las necesidades de los alojamientos independientes.' },
    { title: 'Simplicidad', body: 'No necesitas ser experto en tecnología. Nosotros la hacemos comprensible y útil para tu alojamiento.' },
    { title: 'Acompañamiento', body: 'No te dejamos solo después de implementar una solución.' },
    { title: 'Tecnología propia', body: 'Desarrollamos soluciones como Andario Booking Engine para fortalecer tus canales propios.' },
  ],
  trustNoteTitle: 'Transparencia en cada paso.',
  trustNoteBody: 'Te explicamos qué incluye cada solución y qué puedes esperar de ella.',
  finalTitle: '¿No sabes por dónde empezar?',
  finalBody: 'Cuéntanos cómo funciona hoy tu alojamiento y qué te gustaría mejorar. Te ayudamos a identificar el siguiente paso.',
  finalPrimary: 'Solicitar diagnóstico digital',
  finalSecondary: 'Hablar con Andario',
  finalNote: 'Sin compromiso. Sin venderte soluciones que no necesitas.',
  faqs: [
    { q: '¿Tengo que contratar todas las soluciones?', a: 'No. Puedes contratar solo la que responde a lo que tu alojamiento necesita ahora.' },
    { q: '¿Por dónde debería empezar?', a: 'Si no lo tienes claro, Digital Check sirve para ver prioridades. Si ya sabes la necesidad, puedes empezar por esa solución.' },
    { q: '¿Puedo contratar solo el Booking Engine?', a: 'Sí, según el alcance y las condiciones del producto.' },
    { q: '¿Andario reemplaza Booking.com?', a: 'No. Puedes seguir usando plataformas externas y, al mismo tiempo, tener un canal propio.' },
    { q: '¿Puedo empezar solo con una página web?', a: 'Sí.' },
    { q: '¿Puedo agregar otras soluciones después?', a: 'Sí. La idea es avanzar cuando tu alojamiento esté listo, no contratar todo el primer día.' },
    { q: '¿Trabajan con hostales pequeños?', a: 'Sí. Trabajamos con hostales, hoteles pequeños, posadas, cabañas y otros alojamientos independientes.' },
    { q: '¿Necesito saber de tecnología?', a: 'No. Tú conoces tu alojamiento. Nosotros explicamos las opciones y te acompañamos.' },
    { q: '¿Garantizan más reservas?', a: 'No. Ayudamos a tener una presencia más clara y un canal propio. Los resultados dependen de muchos factores.' },
    { q: '¿Cómo puedo comenzar?', a: 'Puedes solicitar un diagnóstico o escribirnos por WhatsApp.' },
  ],
};
