import type { SolutionsHubContent } from '@/content/types';

export const solutionsHubEs: SolutionsHubContent = {
  eyebrow: 'Soluciones para alojamientos independientes',
  h1: 'Todo lo que tu alojamiento necesita para construir una presencia digital más sólida.',
  support:
    'No necesitas resolver todo de una vez. En Andario conectamos estrategia, presencia digital, visibilidad, reservas, comunicación, contenido y medición para ayudarte a construir el ecosistema que realmente necesita tu alojamiento.',
  primaryCta: 'Solicitar diagnóstico digital',
  secondaryCta: 'Explorar soluciones',
  micro: 'Puedes comenzar por una sola solución y evolucionar progresivamente.',
  heroCenter: 'Alojamiento',
  heroNodes: ['Visibility', 'Content', 'Web', 'Booking', 'Connect', 'Growth', 'Digital Check'],
  heroMobile: ['Digital Check', 'Web', 'Visibility', 'Content', 'Connect', 'Booking Engine', 'Growth'],
  heroCaption:
    'El alojamiento está en el centro. Alrededor se relacionan diagnóstico, presencia, visibilidad, contenido, comunicación, reservas y medición. No es un orden obligatorio.',
  startTitle: 'No necesitas hacerlo todo. Necesitas empezar por lo que más importa.',
  startBody:
    'Cada alojamiento tiene una situación diferente. Algunos necesitan construir su primera web. Otros necesitan mejorar su visibilidad, ordenar sus reservas, profesionalizar su contenido o entender qué está funcionando. Por eso nuestras soluciones pueden contratarse de manera individual y crecer contigo.',
  startSteps: ['Tu situación', 'Tus prioridades', 'La solución adecuada', 'Siguiente paso'],
  whereTitle: '¿Dónde está tu alojamiento?',
  whereIntro: 'Elige la situación más cercana. No es un test: es una forma de ver por dónde podrías empezar.',
  scenarios: [
    {
      title: 'Todavía no tengo una presencia digital sólida.',
      cta: 'Quiero empezar',
      placement: 'scenario-start',
      services: ['digital-check', 'andario-web', 'andario-content'],
    },
    {
      title: 'Tengo presencia digital, pero no me encuentran.',
      cta: 'Quiero mejorar mi visibilidad',
      placement: 'scenario-visibility',
      services: ['digital-check', 'andario-visibility', 'andario-content'],
    },
    {
      title: 'Recibo consultas, pero el proceso de reserva es manual.',
      cta: 'Quiero ordenar mis reservas',
      placement: 'scenario-bookings',
      services: ['andario-booking-engine', 'andario-connect', 'andario-web'],
    },
    {
      title: 'Tengo varios canales y todo está desconectado.',
      cta: 'Quiero conectar mi ecosistema',
      placement: 'scenario-connect',
      services: ['andario-booking-engine', 'andario-connect', 'andario-growth', 'andario-web'],
    },
    {
      title: 'Ya tengo herramientas, pero no sé qué está funcionando.',
      cta: 'Quiero medir mejor',
      placement: 'scenario-measure',
      services: ['andario-growth', 'andario-visibility', 'digital-check'],
    },
  ],
  cardsTitle: 'Un ecosistema construido alrededor de tu alojamiento.',
  cardsSupport:
    'Cada solución responde a una necesidad concreta. Juntas pueden formar un ecosistema digital conectado; por separado, pueden resolver una necesidad específica.',
  cards: {
    'digital-check': {
      category: 'Diagnóstico y estrategia',
      problem: 'No sabes qué deberías mejorar primero.',
      body: 'Revisamos tu presencia digital para identificar qué funciona, qué falta, qué está desconectado y dónde conviene empezar.',
      chain: 'Observar → Analizar → Priorizar',
      related: 'Suele ser el punto de partida hacia Web, Visibility y Content.',
      cta: 'Conocer Digital Check',
    },
    'andario-web': {
      category: 'Presencia digital',
      problem: 'Tu alojamiento necesita una casa propia en Internet.',
      body: 'Construimos una web profesional para presentar tu alojamiento, destino, servicios, experiencias y canales de contacto.',
      chain: 'Alojamiento → Web → Confianza → Acción',
      related: 'Se apoya en Content y puede conectar con Booking Engine.',
      cta: 'Conocer Andario Web',
    },
    'andario-visibility': {
      category: 'SEO, Google y visibilidad',
      problem: 'Estar en Internet no significa ser encontrado.',
      body: 'Trabajamos bases técnicas, locales y de contenido para mejorar la capacidad de tu establecimiento de aparecer ante búsquedas relevantes.',
      chain: 'Búsqueda → Google → Alojamiento',
      related: 'Se apoya en Web y Content. No promete la primera posición.',
      cta: 'Conocer Andario Visibility',
    },
    'andario-booking-engine': {
      category: 'Reservas directas',
      problem: 'Tus reservas no deberían depender únicamente de procesos manuales o canales externos.',
      body: 'Tecnología propia para gestionar disponibilidad, tarifas, unidades, huéspedes, reservas y la lógica de reserva desde un canal propio.',
      chain: 'Disponibilidad → Tarifa → Reserva → Huésped',
      related: 'La web es el canal directo de partida. Puede convivir con OTAs.',
      cta: 'Conocer Andario Booking Engine',
    },
    'andario-connect': {
      category: 'Comunicación y automatización',
      problem: 'Las conversaciones también forman parte del recorrido de reserva.',
      body: 'Conectamos WhatsApp y otros puntos de comunicación con el recorrido comercial y de reservas, reduciendo tareas repetitivas cuando la automatización aplica.',
      chain: 'Consulta → WhatsApp → Respuesta → Orientación',
      related: 'Complementa Web y Booking Engine. Reservar dentro del chat no es un canal activo.',
      cta: 'Conocer Andario Connect',
    },
    'andario-content': {
      category: 'Fotografía y contenido',
      problem: 'La experiencia comienza antes de la llegada.',
      body: 'Ayudamos a presentar mejor el alojamiento mediante fotografías, textos, video, contenido de destino y planificación editorial, según el alcance acordado.',
      chain: 'Fotos + Textos + Video + Destino → Contenido',
      related: 'Alimenta Web y Visibility.',
      cta: 'Conocer Andario Content',
    },
    'andario-growth': {
      category: 'Analítica y optimización',
      problem: 'Sin medición, cada cambio puede convertirse en una suposición.',
      body: 'Medimos interacciones, canales, eventos y señales del ecosistema para convertir datos disponibles en información útil para decidir y mejorar.',
      chain: 'Medir → Entender → Mejorar',
      related: 'Lee señales de Web, Visibility y Booking Engine. No inventa resultados.',
      cta: 'Conocer Andario Growth',
    },
  },
  ownTech: 'Tecnología propia',
  bookingTitle: 'La tecnología que puede convertirse en el centro de tus reservas directas.',
  bookingSupport:
    'Andario Booking Engine nace para ayudar a los alojamientos independientes a construir y operar su propio canal de reservas, con una lógica central para disponibilidad, tarifas, huéspedes y reservas.',
  bookingBranches: [
    { title: 'Web', body: 'Canal propio de partida para consultar disponibilidad y reservar.' },
    { title: 'WhatsApp', body: 'Sirve para conversar. Reservar dentro del chat es una evolución prevista, no un canal activo.' },
    { title: 'Otros canales', body: 'Se puede registrar el origen de una reserva. Eso no es una integración en vivo.' },
  ],
  bookingResult: 'Reserva central',
  bookingNote:
    'El motor concentra disponibilidad, tarifas, unidades, huéspedes y reservas. No afirma que Instagram, Facebook, Google o los asistentes de IA ya estén conectados.',
  bookingCta: 'Conocer Andario Booking Engine',
  connectTitle: 'Las soluciones se conectan. Tu alojamiento también puede hacerlo.',
  connectBody:
    'No necesitas contratar todo al mismo tiempo. Puedes empezar donde exista una necesidad concreta y evolucionar desde allí.',
  connectFlow: [
    'Digital Check — entender',
    'Estrategia',
    'Web — construir',
    'Visibility — ser encontrado',
    'Content — mostrar',
    'Connect — comunicar',
    'Booking Engine — reservar',
    'Growth — medir y evolucionar',
  ],
  connectNote:
    'Esta lectura ayuda a ver cómo se relacionan. No es una secuencia obligatoria: puedes entrar por cualquier solución.',
  beforeTitle: 'De la fragmentación a la conexión',
  beforeLabel: 'Antes: canales separados',
  beforeItems: ['Google', 'Instagram', 'Facebook', 'WhatsApp', 'OTA', 'Web', 'Reservas'],
  afterLabel: 'Con una estrategia',
  afterFlow: ['Estrategia', 'Web', 'Visibility', 'Content', 'Connect', 'Booking Engine', 'Growth'],
  afterNote:
    'Una estrategia ordena prioridades. No significa que todos esos canales queden integrados de forma automática.',
  hopeTitle: 'No importa dónde esté hoy tu alojamiento. Importa saber cuál es el siguiente paso.',
  hopeBody:
    'Algunos alojamientos están comenzando. Otros ya tienen web, redes, WhatsApp y presencia en diferentes plataformas. No todos necesitan lo mismo. Nuestro trabajo es ayudarte a entender tu punto de partida y construir desde allí.',
  hopeSteps: ['Hoy', 'Próximo paso', 'Mejora', 'Siguiente paso', 'Evolución'],
  chooseTitle: '¿Por dónde empezar?',
  chooseItems: [
    { need: 'Si no sabes qué necesitas', service: 'digital-check' },
    { need: 'Si no tienes una web profesional', service: 'andario-web' },
    { need: 'Si no te encuentran', service: 'andario-visibility' },
    { need: 'Si quieres reservas directas', service: 'andario-booking-engine' },
    { need: 'Si tienes muchas conversaciones manuales', service: 'andario-connect' },
    { need: 'Si necesitas mejores fotos y contenido', service: 'andario-content' },
    { need: 'Si ya tienes presencia y quieres medir', service: 'andario-growth' },
  ],
  chooseCta: 'No sé por dónde empezar',
  matrixTitle: 'Una necesidad, una solución posible',
  matrix: [
    { need: 'No sé por dónde empezar', service: 'digital-check' },
    { need: 'Necesito una web', service: 'andario-web' },
    { need: 'No me encuentran', service: 'andario-visibility' },
    { need: 'Quiero reservas directas', service: 'andario-booking-engine' },
    { need: 'Tengo muchas consultas', service: 'andario-connect' },
    { need: 'Necesito mejores contenidos', service: 'andario-content' },
    { need: 'Quiero medir y mejorar', service: 'andario-growth' },
  ],
  adaptTitle: 'Andario se adapta a tu momento.',
  adaptBody:
    'Puedes empezar con una necesidad concreta y sumar nuevas soluciones cuando tu alojamiento esté preparado. Nuestra propuesta no parte de venderte todo, sino de entender qué tiene sentido para tu negocio.',
  journeyTitle: 'Tu transformación digital puede empezar con una conversación.',
  journeyNote: 'Conversar no implica una implementación inmediata.',
  journey: ['Conversamos', 'Entendemos tu situación', 'Priorizamos', 'Proponemos', 'Implementamos', 'Medimos', 'Evolucionamos'],
  trustTitle: 'Tecnología sin complicarte la vida.',
  pillars: [
    { title: 'Especialización', body: 'Diseñamos pensando en alojamientos independientes.' },
    { title: 'Simplicidad', body: 'Queremos que la tecnología sea comprensible y útil.' },
    { title: 'Tecnología propia', body: 'Desarrollamos soluciones propias como Andario Booking Engine.' },
    { title: 'Acompañamiento', body: 'No entregamos una herramienta y desaparecemos.' },
    { title: 'Transparencia', body: 'Explicamos qué hacemos, qué incluye cada servicio y qué resultados no podemos garantizar.' },
  ],
  craftTitle: 'Una estrategia no debería sentirse más complicada que el problema que intenta resolver.',
  craftIntro: 'Claridad primero. Después, la herramienta que haga falta.',
  craftPillars: [
    { title: 'Claridad', body: 'Nombramos la situación antes de proponer un servicio.' },
    { title: 'Tecnología', body: 'Usamos herramientas propias cuando el alojamiento las necesita.' },
    { title: 'Estrategia', body: 'El orden lo marca la prioridad del negocio, no un paquete fijo.' },
    { title: 'Acompañamiento', body: 'Seguimos cerca para implementar y ajustar.' },
    { title: 'Medición', body: 'Lo que se puede observar se usa para decidir el siguiente paso.' },
  ],
  originTitle: 'Nacemos en Colombia con una visión latinoamericana.',
  originBody:
    'Andario Hospitality nace para ayudar a pequeños y medianos alojamientos independientes a profesionalizar su presencia digital y construir canales propios de crecimiento.',
  pioneer: 'BARUCH Hostal — establecimiento pionero de Andario Hospitality.',
  finalTitle: 'Tu alojamiento puede avanzar. Empecemos por saber dónde estás.',
  finalBody:
    'Cuéntanos cómo funciona hoy tu presencia digital y qué quieres mejorar. Te ayudaremos a identificar el siguiente paso con sentido para tu alojamiento.',
  finalPrimary: 'Solicitar diagnóstico digital',
  finalSecondary: 'Hablar con Andario',
  finalNote: 'Sin compromiso. Sin venderte soluciones que no necesitas.',
  faqs: [
    {
      q: '¿Tengo que contratar todas las soluciones?',
      a: 'No. Puedes contratar solo las que respondan a las necesidades actuales de tu alojamiento.',
    },
    {
      q: '¿Por dónde debería empezar?',
      a: 'Si no tienes claro qué necesitas, Digital Check puede ayudarte a identificar prioridades.',
    },
    {
      q: '¿Puedo contratar solo el Booking Engine?',
      a: 'Sí, dependiendo del alcance y condiciones comerciales del producto.',
    },
    {
      q: '¿Andario reemplaza Booking.com?',
      a: 'No. Andario busca fortalecer tus canales propios y puede coexistir con OTAs.',
    },
    {
      q: '¿Andario garantiza más reservas?',
      a: 'No. Proporciona estrategia, tecnología y herramientas para construir y mejorar el ecosistema digital, pero los resultados dependen de múltiples factores.',
    },
    {
      q: '¿Puedo empezar solo con una página web?',
      a: 'Sí.',
    },
    {
      q: '¿Puedo agregar otras soluciones después?',
      a: 'Sí. La propuesta está diseñada para evolucionar progresivamente.',
    },
    {
      q: '¿Las soluciones están conectadas?',
      a: 'Pueden formar un ecosistema conectado, dependiendo de las soluciones contratadas y de las integraciones disponibles.',
    },
    {
      q: '¿Trabajan con hostales pequeños?',
      a: 'Sí. El foco está precisamente en pequeños y medianos alojamientos independientes.',
    },
    {
      q: '¿Cómo comienzo?',
      a: 'Puedes solicitar un diagnóstico digital o hablar directamente con Andario.',
    },
  ],
};
