import type { SolutionsHubContent } from '@/content/types';

export const solutionsHubEs: SolutionsHubContent = {
  eyebrow: 'Soluciones para alojamientos independientes',
  h1: 'Digitaliza tu alojamiento, paso a paso.',
  support:
    'Te ayudamos a tener una página web profesional, aparecer en Google, recibir reservas directas, comunicarte mejor con tus huéspedes y entender qué está funcionando.',
  assist: 'No necesitas hacerlo todo de una vez. Empezamos por lo que tu alojamiento realmente necesita.',
  primaryCta: 'Quiero saber por dónde empezar',
  secondaryCta: 'Hablar con Andario',
  micro: 'Sin compromiso. Sin venderte soluciones que no necesitas.',
  problemTitle: '¿Te pasa algo de esto?',
  problemIntro: 'Cada alojamiento parte de una situación diferente. Lo importante es identificar qué necesitas mejorar primero.',
  problems: [
    'Tengo presencia en redes, pero no sé si realmente me ayuda a conseguir reservas.',
    'Mi alojamiento no aparece como quisiera en Google.',
    'No tengo una página web profesional.',
    'Recibo muchas consultas por WhatsApp y hago gran parte del proceso manualmente.',
    'Dependo demasiado de plataformas externas para conseguir reservas.',
    'Tengo varias herramientas, pero no sé qué está funcionando.',
  ],
  whereTitle: '¿Dónde está hoy tu alojamiento?',
  whereIntro: 'No todos necesitan lo mismo. Elige la situación que más se parece a la tuya.',
  resultLabel: 'Resultado',
  solutionLabel: 'Solución',
  scenarios: [
    {
      title: 'Estoy empezando mi presencia digital.',
      result: 'Ordena el punto de partida y define qué conviene construir primero.',
      cta: 'Conocer Digital Check',
      placement: 'starting',
      service: 'digital-check',
    },
    {
      title: 'Tengo presencia digital, pero quiero que más personas me encuentren.',
      result: 'Mejora las bases para que tu alojamiento aparezca cuando alguien busca dónde hospedarse.',
      cta: 'Conocer Visibility',
      placement: 'visibility',
      service: 'andario-visibility',
    },
    {
      title: 'Quiero recibir reservas directamente.',
      result: 'Construye un canal propio para que tus huéspedes puedan consultar disponibilidad y reservar.',
      cta: 'Conocer Booking Engine',
      placement: 'bookings',
      service: 'andario-booking-engine',
    },
    {
      title: 'Paso demasiado tiempo atendiendo consultas y tareas repetitivas.',
      result: 'Organiza la comunicación con tus huéspedes para responder con menos esfuerzo.',
      cta: 'Conocer Connect',
      placement: 'connect',
      service: 'andario-connect',
    },
    {
      title: 'Tengo varias herramientas, pero no sé cómo aprovecharlas mejor.',
      result: 'Mira lo que ya tienes y decide qué merece atención antes de sumar algo nuevo.',
      cta: 'Conocer Digital Check',
      placement: 'tools',
      service: 'digital-check',
    },
    {
      title: 'Ya tengo presencia digital y quiero medir qué funciona.',
      result: 'Usa los datos que ya tienes para ver qué conviene mejorar.',
      cta: 'Conocer Growth',
      placement: 'measure',
      service: 'andario-growth',
    },
  ],
  cardsTitle: 'Soluciones para lo que tu alojamiento necesita hoy.',
  cardsSupport: 'Puedes empezar con una solución concreta y sumar otras cuando tenga sentido para tu negocio.',
  cards: {
    'digital-check': {
      category: 'Diagnóstico digital',
      problem: 'No sabes qué deberías mejorar primero.',
      body: 'Obtén una visión clara de tu situación digital y un camino de prioridades.',
      cta: 'Conocer Digital Check',
    },
    'andario-web': {
      category: 'Página web profesional',
      problem: 'No tienes una web profesional que represente tu alojamiento.',
      body: 'Presenta tu alojamiento, genera confianza y facilita que tus visitantes contacten o reserven.',
      cta: 'Conocer Andario Web',
    },
    'andario-visibility': {
      category: 'Google y visibilidad',
      problem: 'Tu alojamiento existe en Internet, pero no siempre es fácil encontrarlo.',
      body: 'Construye mejores bases para aparecer ante búsquedas relevantes. Sin prometer un puesto en Google.',
      cta: 'Conocer Visibility',
    },
    'andario-booking-engine': {
      category: 'Motor de reservas propio',
      problem: 'Muchas reservas dependen de procesos manuales o de plataformas externas.',
      body: 'Construye tu propio canal de reservas directas. Gestiona disponibilidad, tarifas, unidades, huéspedes y reservas desde una lógica central.',
      cta: 'Conocer Booking Engine',
    },
    'andario-connect': {
      category: 'WhatsApp y comunicación',
      problem: 'Pasas demasiado tiempo respondiendo consultas y tareas repetitivas.',
      body: 'Organiza mejor la comunicación con tus huéspedes y conecta las conversaciones con tu recorrido de reserva.',
      cta: 'Conocer Connect',
    },
    'andario-content': {
      category: 'Fotografía y contenido',
      problem: 'Tu alojamiento puede estar bien, pero no estás mostrando todo lo que ofrece.',
      body: 'Presenta mejor tus espacios, experiencias y destino.',
      cta: 'Conocer Content',
    },
    'andario-growth': {
      category: 'Medición y optimización',
      problem: 'No sabes qué está funcionando.',
      body: 'Utiliza los datos disponibles para entender qué mejorar.',
      cta: 'Conocer Growth',
    },
  },
  ownTech: 'Tecnología propia',
  paceTitle: 'No necesitas contratarlo todo.',
  paceBody: 'Tu alojamiento puede empezar por una necesidad concreta. A medida que creces, puedes incorporar nuevas soluciones.',
  paths: [
    { need: 'No sé qué necesito', service: 'digital-check' },
    { need: 'No tengo web', service: 'andario-web' },
    { need: 'No me encuentran', service: 'andario-visibility' },
    { need: 'Quiero reservas directas', service: 'andario-booking-engine' },
    { need: 'Recibo demasiadas consultas', service: 'andario-connect' },
    { need: 'Necesito mejores contenidos', service: 'andario-content' },
    { need: 'Quiero medir', service: 'andario-growth' },
  ],
  paceCta: 'No sé por dónde empezar',
  bookingTitle: 'Tu alojamiento también puede tener su propio canal de reservas.',
  bookingSupport: 'Andario Booking Engine es nuestra tecnología propia para ayudarte a gestionar reservas directas.',
  bookingItems: ['Disponibilidad', 'Tarifas', 'Unidades', 'Huéspedes', 'Reservas'],
  bookingNote: 'Puede convivir con Booking.com y otras plataformas. No busca eliminar tus canales, sino fortalecer el tuyo.',
  bookingCta: 'Conocer Andario Booking Engine',
  processTitle: 'Te acompañamos paso a paso.',
  processMark: 'Tú conoces tu alojamiento. Nosotros te ayudamos con la tecnología.',
  processNote: 'No necesitas saber de tecnología para comenzar.',
  process: ['Hablamos', 'Entendemos tu situación', 'Priorizamos', 'Proponemos', 'Implementamos', 'Medimos', 'Evolucionamos'],
  trustTitle: '¿Por qué trabajar con Andario?',
  pillars: [
    { title: 'Especialización', body: 'Pensamos específicamente en alojamientos independientes.' },
    { title: 'Simplicidad', body: 'Hacemos que la tecnología sea comprensible y útil.' },
    { title: 'Tecnología propia', body: 'Desarrollamos soluciones propias como Andario Booking Engine.' },
    { title: 'Acompañamiento', body: 'No entregamos una herramienta y desaparecemos.' },
    { title: 'Transparencia', body: 'Te explicamos qué hacemos, qué incluye cada solución y qué resultados no podemos garantizar.' },
  ],
  pioneer: 'BARUCH Hostal, en Buritaca, Colombia, es el establecimiento pionero de Andario Hospitality.',
  pioneerSoon: 'Próximamente: caso de estudio.',
  finalTitle: '¿No sabes por dónde empezar?',
  finalBody: 'Cuéntanos cómo funciona hoy tu alojamiento y qué te gustaría mejorar. Te ayudamos a identificar el siguiente paso.',
  finalPrimary: 'Solicitar diagnóstico digital',
  finalSecondary: 'Hablar con Andario',
  finalNote: 'Sin compromiso. Sin venderte soluciones que no necesitas.',
  faqs: [
    { q: '¿Tengo que contratar todas las soluciones?', a: 'No. Puedes contratar solo la que responde a lo que tu alojamiento necesita ahora.' },
    { q: '¿Por dónde debería empezar?', a: 'Si no lo tienes claro, Digital Check sirve para ver prioridades. Si ya sabes la necesidad, puedes empezar por esa solución.' },
    { q: '¿Puedo contratar solo el Booking Engine?', a: 'Sí, según el alcance y las condiciones del producto.' },
    { q: '¿Andario reemplaza Booking.com?', a: 'No. Puedes seguir usando plataformas externas y, al mismo tiempo, tener un canal propio.' },
    { q: '¿Puedo empezar solo con una página web?', a: 'Sí.' },
    { q: '¿Puedo agregar otras soluciones después?', a: 'Sí. La idea es avanzar cuando tu alojamiento esté listo, no contratar todo el primer día.' },
    { q: '¿Trabajan con hostales pequeños?', a: 'Sí. Trabajamos con hostales, hoteles pequeños, posadas, cabañas y otros alojamientos independientes.' },
    { q: '¿Necesito saber de tecnología?', a: 'No. Tú conoces tu alojamiento. Nosotros explicamos las opciones y te acompañamos.' },
    { q: '¿Garantizan más reservas?', a: 'No. Ayudamos a tener una presencia más clara y un canal propio. Los resultados dependen de muchos factores.' },
    { q: '¿Cómo puedo comenzar?', a: 'Puedes solicitar un diagnóstico o escribirnos por WhatsApp.' },
  ],
};
