import type { FaqItem, VisibilityContent } from '@/content/types';

export const visibilityFaqsEs: FaqItem[] = [
  {
    q: '¿Qué es Andario Visibility?',
    a: 'Es el servicio de SEO, Google y visibilidad digital para alojamientos independientes. Trabaja la base técnica, la presencia local y el contenido para que el establecimiento pueda ser comprendido y encontrado en búsquedas relevantes.',
  },
  {
    q: '¿Me garantiza aparecer primero en Google?',
    a: 'No. Nadie puede prometer una posición fija. Los resultados cambian y dependen de muchas señales.',
  },
  {
    q: '¿Entonces qué puedo esperar?',
    a: 'Un trabajo ordenado sobre lo técnico, lo local, el contenido y la medición, según el alcance. El objetivo es fortalecer la base, no vender un puesto.',
  },
  {
    q: '¿Qué diferencia hay entre SEO técnico y SEO local?',
    a: 'El SEO técnico ayuda a que el sitio se pueda descubrir y comprender. El SEO local relaciona el establecimiento con su lugar, su información y las búsquedas de quien viaja.',
  },
  {
    q: '¿Trabajan Google Search Console?',
    a: 'Sí, cuando forma parte del alcance: configuración y lectura de lo que la herramienta muestra sobre el sitio.',
  },
  {
    q: '¿Qué es Search Console?',
    a: 'Es una herramienta de Google para ver cómo el sitio aparece en búsquedas y detectar asuntos técnicos. No es un ranking ni un informe de un cliente.',
  },
  {
    q: '¿Necesito tener una página web?',
    a: 'No hace falta tenerla para conversar. Una web propia suele ser una base importante, pero no es un requisito para empezar la conversación.',
  },
  {
    q: '¿Puedo contratar Visibility si ya tengo una web?',
    a: 'Sí. Se puede trabajar sobre un sitio que ya existe.',
  },
  {
    q: '¿Puedo contratar Visibility sin Andario Web?',
    a: 'Sí. Los servicios se contratan por separado.',
  },
  {
    q: '¿Qué relación tiene con Digital Check?',
    a: 'Digital Check diagnostica y ordena prioridades. Visibility trabaja las áreas de visibilidad que se definan. El diagnóstico no es obligatorio.',
  },
  {
    q: '¿Trabajan el perfil de Google del negocio?',
    a: 'Puede entrar en el trabajo de presencia local, según el alcance. No afirmamos acciones que no se hayan acordado.',
  },
  {
    q: '¿Crean contenido?',
    a: 'Se identifican oportunidades y se puede ordenar información útil. Una producción más amplia de textos, fotos o video corresponde a Andario Content, si se contrata.',
  },
  {
    q: '¿Trabajan palabras clave?',
    a: 'Sí, como parte de la intención de búsqueda y de la estructura del contenido. No se trata de repetir términos.',
  },
  {
    q: '¿Cuánto tarda en mejorar el posicionamiento?',
    a: 'No hay un plazo garantizado. El SEO depende de muchas señales y se observa con el tiempo. No prometemos un día ni una posición.',
  },
  {
    q: '¿Visibility genera reservas?',
    a: 'No de forma directa. Busca fortalecer el descubrimiento. La reserva puede seguir en la web, en WhatsApp o en el Booking Engine, y depende de más factores.',
  },
  {
    q: '¿Puedo seguir usando Booking.com o Airbnb?',
    a: 'Sí. Visibility no pide abandonar las OTAs.',
  },
  {
    q: '¿Qué necesito para comenzar?',
    a: 'Datos del establecimiento, el sitio si existe, los perfiles digitales, la ubicación, los objetivos y el acceso a las herramientas cuando haga falta.',
  },
  {
    q: '¿Cómo sé qué debería mejorar primero?',
    a: 'Digital Check puede ayudar a priorizar. También se puede definir un alcance concreto de Visibility sin ese diagnóstico.',
  },
  {
    q: '¿Necesito contratar todos los servicios de Andario?',
    a: 'No.',
  },
  {
    q: '¿Cómo empiezo?',
    a: 'Con una conversación o, si lo prefieres, con Digital Check. Ninguno obliga a contratar el resto.',
  },
];

export const visibilityEs: VisibilityContent = {
  support:
    'Una presencia digital profesional necesita visibilidad. Trabajamos SEO técnico, SEO local, estructura, contenido y oportunidades de búsqueda para ayudar a que tu establecimiento sea más comprensible y pueda ser encontrado por personas que buscan lo que ofreces.',
  audienceLine: 'Sin prometer posiciones. Con una estrategia digital medible.',
  primaryCta: 'Mejorar mi visibilidad',
  problemCta: 'Quiero mejorar mi visibilidad',
  talkCta: 'Hablar con Andario',
  reviewCta: 'Revisar mi presencia digital',
  infoCta: 'Solicitar información',
  whatsappCta: 'Escribir por WhatsApp',
  scopeLabel: 'El alcance se define según la situación del establecimiento.',
  exampleLabel: 'Ejemplo conceptual. No es un caso real ni un volumen de búsqueda.',
  heroCaption:
    'Una persona busca un tipo de alojamiento. Google muestra piezas de información. El alojamiento puede ofrecer un siguiente paso. No es un resultado real.',
  heroQuery: 'hostal en un destino',
  problems: [
    { title: 'Información difícil de encontrar', body: 'Quien busca no llega rápido a una explicación clara.' },
    { title: 'Web sin estructura', body: 'El contenido existe, pero cuesta comprenderlo.' },
    { title: 'Presencia local débil', body: 'El lugar y los datos del establecimiento están incompletos o poco conectados.' },
    { title: 'Contenido sin una pregunta clara', body: 'Se publica sin responder lo que alguien necesita saber.' },
    { title: 'Información inconsistente', body: 'La web, los perfiles y otras plataformas no dicen lo mismo.' },
    { title: 'No sabemos qué medir', body: 'Sin datos es más difícil ver qué pasa después de que alguien encuentra el alojamiento.' },
  ],
  systemTitle: 'La visibilidad digital es un sistema, no un botón.',
  systemParts: ['Estructura', 'Contenido', 'Contexto local', 'Relevancia', 'Experiencia', 'Medición'],
  systemEquals: 'Base de visibilidad',
  systemNote: 'Ningún elemento por sí solo garantiza una posición. Trabajamos el conjunto.',
  chain: ['Ser encontrado', 'Ser relevante', 'Ser comprensible', 'Ser útil', 'Facilitar el siguiente paso'],
  whatTitle: '¿Qué es Andario Visibility?',
  whatBody:
    'Es el servicio de SEO, Google y visibilidad digital de Andario Hospitality. Trabajamos la estructura técnica, la presencia local, la información del establecimiento y las oportunidades de contenido para que los buscadores comprendan mejor el alojamiento y las personas encuentren información útil.',
  whatNote: 'No prometemos una posición específica en Google. Construimos una base digital sólida y medible.',
  technicalTitle: 'Primero, hacemos que tu sitio sea técnicamente comprensible.',
  technicalBody: 'Un buscador necesita poder descubrir, recorrer y entender el contenido. Eso no garantiza un puesto.',
  technicalDo: ['Arquitectura', 'Encabezados', 'Metadatos', 'URLs', 'Sitemap', 'Canonical', 'Indexación', 'Enlaces internos', 'Rendimiento', 'Datos estructurados cuando aportan'],
  technicalWhy: 'Sin esa base, el contenido útil puede existir y aun así costar de leer para un buscador.',
  localTitle: 'Tu alojamiento no está en Internet. Está en un lugar concreto.',
  localBody:
    'Quien busca hospedaje suele combinar destino, zona, tipo de establecimiento, servicios y lo que quiere hacer. El SEO local fortalece la relación entre el establecimiento, su lugar y la información útil.',
  localSteps: ['La persona busca un lugar', 'Aparece la ubicación', 'Se reconoce el establecimiento', 'Hay información local', 'Puede seguir hacia el contacto'],
  localNote: 'No garantizamos aparecer en mapas ni en los primeros resultados.',
  googleTitle: 'Google necesita entender quién eres, dónde estás y qué ofreces.',
  googleBody:
    'Los buscadores usan muchas señales. Los resultados cambian, la competencia cambia y la intención de quien busca importa. La parte técnica es una base, no un control sobre Google.',
  googleParts: [
    { title: 'Quién', body: 'El establecimiento y su información.' },
    { title: 'Dónde', body: 'El lugar y la coherencia de los datos.' },
    { title: 'Qué ofrece', body: 'Servicios, unidades y contenido útil.' },
  ],
  googleNote: 'Esto no es el algoritmo completo de Google.',
  consoleTitle: 'Search Console ayuda a observar, no a prometer.',
  consoleBody:
    'Es una herramienta de Google para ver cómo el sitio aparece en búsquedas y detectar asuntos de indexación o técnicos, cuando el acceso forma parte del alcance.',
  consoleRows: ['Consultas', 'Impresiones', 'Clics', 'Páginas', 'Avisos técnicos', 'Oportunidades'],
  contentTitle: 'No se trata de publicar más. Se trata de responder mejor.',
  contentBody:
    'El contenido útil responde preguntas reales: dónde está, qué ofrece, cómo llegar, qué tipo de alojamiento es, qué servicios tiene y qué conviene saber antes de escribir o reservar.',
  contentSteps: ['Búsqueda', 'Intención', 'Pregunta', 'Contenido útil', 'Confianza', 'Siguiente paso'],
  intentTitle: 'La intención importa más que repetir una palabra.',
  intentIntro: 'Estas frases muestran tipos de necesidad. No son volúmenes ni resultados de un alojamiento.',
  intents: [
    { query: 'hostal en un destino', intent: 'Encontrar alojamiento.' },
    { query: 'qué hacer en el destino', intent: 'Descubrir el lugar.' },
    { query: 'hostal cerca de…', intent: 'Ubicar el establecimiento.' },
    { query: 'habitaciones del hostal', intent: 'Comparar opciones.' },
  ],
  intentNote: 'No afirmamos cuántas personas buscan cada frase.',
  destinationTitle: 'El destino también forma parte de la visibilidad.',
  destinationBody:
    'El contexto puede incluir el lugar, cómo llegar, el entorno y las experiencias, cuando esa información existe y entra en el alcance. Andario Content puede ampliar la producción.',
  destinationPoints: ['Destino', 'Ubicación', 'Cómo llegar', 'Entorno', 'Experiencias', 'Información útil'],
  ecosystemCaption: 'Técnica, presencia local y contenido se encuentran en información útil. Ninguna pieza promete una posición.',
  ecosystemColumns: [
    { title: 'Técnica', points: ['Indexación', 'Estructura', 'Sitemap'] },
    { title: 'Local', points: ['Lugar', 'Google', 'Datos coherentes'] },
    { title: 'Contenido', points: ['Intención', 'Preguntas', 'Utilidad'] },
  ],
  discoveryTitle: 'Ser encontrado es el comienzo. La experiencia sigue en el sitio.',
  discoverySteps: ['Búsqueda', 'Descubrimiento', 'Sitio web', 'Información', 'Confianza', 'WhatsApp o reserva', 'Booking Engine'],
  discoveryNote:
    'Visibility trabaja el descubrimiento. La web presenta. Connect puede ordenar la conversación. El motor gestiona la reserva. No toda búsqueda termina en una reserva.',
  includesTitle: 'Qué puede incluir',
  includesIntro: 'Cada pieza se acuerda. No todos los proyectos incluyen todas las actividades.',
  whatLabel: 'Qué hacemos',
  purposeLabel: 'Para qué sirve',
  groups: [
    { title: 'SEO técnico y de página', what: 'Estructura, encabezados, metadatos y fundamentos técnicos.', purpose: 'Ayudar a que el sitio se pueda descubrir y comprender.' },
    { title: 'SEO local', what: 'Ubicación, contexto y presencia del establecimiento.', purpose: 'Relacionar el alojamiento con el lugar donde está.' },
    { title: 'Search Console', what: 'Configuración y lectura, según acceso y alcance.', purpose: 'Observar aparición en búsquedas y avisos técnicos.' },
    { title: 'Sitemap', what: 'Un mapa de las direcciones del sitio.', purpose: 'Facilitar el descubrimiento de páginas.' },
    { title: 'Datos estructurados', what: 'Marcado cuando aporta y corresponde.', purpose: 'Ayudar a describir el establecimiento de forma explícita.' },
    { title: 'Enlaces internos', what: 'Conexiones entre contenidos relacionados.', purpose: 'Que la información se recorra con sentido.' },
    { title: 'Presencia en Google', what: 'Revisión de la información pública disponible.', purpose: 'Reducir datos incompletos o contradictorios.' },
    { title: 'Contenido y destino', what: 'Oportunidades de información útil del alojamiento y su contexto.', purpose: 'Responder preguntas reales, no llenar páginas.' },
    { title: 'Intención de búsqueda', what: 'Preguntas y necesidades que el contenido puede atender.', purpose: 'Ordenar qué merece una respuesta.' },
  ],
  matrixTitle: 'Visibility une varias dimensiones.',
  matrixCenter: 'Visibility',
  matrixPoints: ['Personas', 'Contenido útil', 'Técnica', 'Contexto local', 'Medición'],
  matrixNote: 'El gráfico muestra relaciones. No es una puntuación.',
  processTitle: 'De entender el problema a construir una base.',
  process: [
    { title: 'Revisamos', body: 'Presencia, sitio, Google, estructura y oportunidades.' },
    { title: 'Priorizamos', body: 'Qué acciones tienen sentido en este establecimiento.' },
    { title: 'Optimizamos', body: 'Implementamos las mejoras acordadas.' },
    { title: 'Medimos', body: 'Observamos las señales y los datos disponibles.' },
    { title: 'Evolucionamos', body: 'Ajustamos según lo que se aprende. No es una posición cerrada.' },
  ],
  receiveTitle: 'Qué puede recibir el establecimiento',
  receive: [
    'Lectura de la situación',
    'Oportunidades priorizadas',
    'Mejoras técnicas acordadas',
    'Orden de la estructura',
    'Recomendaciones de contenido',
    'Trabajo de presencia local',
    'Search Console, si entra en el alcance',
    'Sitemap y datos estructurados cuando correspondan',
    'Una base para medir',
  ],
  receiveNote: 'El entregable depende del alcance definido. No incluye una posición en Google.',
  structureTitle: 'Ejemplo conceptual de estructura',
  structureBefore: ['Inicio', 'Habitaciones', 'Contacto', 'Un texto genérico'],
  structureAfter: ['Dónde estamos', 'Cómo llegar', 'Habitaciones', 'Servicios', 'Experiencias', 'Preguntas', 'Contacto', 'Reservar'],
  finding: [
    { label: 'Hallazgo', value: 'La ubicación se entiende poco.' },
    { label: 'Oportunidad', value: 'Fortalecer el contexto local.' },
    { label: 'Acción', value: 'Mejorar contenido y estructura.' },
    { label: 'Medición', value: 'Observar comportamiento y búsqueda, sin prometer un puesto.' },
  ],
  webTitle: 'La visibilidad se apoya en una casa digital.',
  webBody: 'Andario Web organiza la información. Visibility trabaja para fortalecer la posibilidad de encontrarla. Una no reemplaza a la otra.',
  webNote: 'Tener la web de Andario no es obligatorio para conversar sobre visibilidad.',
  checkTitle: 'Antes de optimizar, conviene saber dónde estás.',
  checkBody: 'Digital Check puede mostrar qué merece atención primero. Visibility trabaja después las áreas de visibilidad que se definan.',
  checkNote: 'El diagnóstico no es un paso obligatorio.',
  bookingTitle: 'Encontrar al huésped es solo una parte del recorrido.',
  bookingBody: 'Visibility no consulta disponibilidad ni crea reservas. Eso vive en Andario Booking Engine, si el alojamiento lo usa.',
  growthTitle: 'La visibilidad también necesita medición.',
  growthBody: 'Visibility deja trabajo y señales. Andario Growth puede ampliar la lectura después. No prometemos una atribución completa.',
  whoTitle: 'Para alojamientos que no quieren depender solo de que alguien ya los conozca.',
  whoTypes: ['Hostales', 'Hoteles pequeños', 'Posadas', 'Apartamentos turísticos', 'Apartahoteles', 'Cabañas', 'Villas', 'Alojamientos rurales', 'Otros alojamientos independientes'],
  whoFit: ['Hay web, pero cuesta entender la oferta.', 'La presencia está repartida.', 'La base SEO es débil.', 'La información local está incompleta.', 'Quieren un canal propio.', 'Quieren medir mejor.'],
  whenTitle: 'Cuándo suele tener sentido',
  when: [
    'La web no explica con claridad qué ofreces.',
    'La presencia local está incompleta.',
    'El contenido no responde preguntas reales.',
    'No sabes qué buscan quienes podrían hospedarse.',
    'No sabes cómo aparece el alojamiento en Google.',
    'Quieres una base SEO.',
    'Quieres unir visibilidad, web y reserva.',
  ],
  notTitle: 'Qué Andario Visibility no es',
  not: [
    { title: 'No es una primera posición', body: 'Google decide con muchas señales y los resultados cambian.' },
    { title: 'No es comprar un puesto', body: 'No vendemos una posición en Google.' },
    { title: 'No es publicar sin criterio', body: 'El contenido tiene que responder una necesidad.' },
    { title: 'No es solo palabras clave', body: 'También hay estructura, técnica, lugar, contenido y experiencia.' },
    { title: 'No es una campaña de anuncios', body: 'Esto es visibilidad orgánica. La publicidad paga es otra cosa y pueden convivir.' },
    { title: 'No garantiza reservas', body: 'Puede ayudar al descubrimiento. La reserva depende de más factores.' },
    { title: 'No siempre es un trabajo de una sola vez', body: 'Observar, medir y ajustar puede continuar según los objetivos.' },
  ],
  adsTitle: 'Visibilidad orgánica y publicidad no son lo mismo.',
  adsIntro: 'Pueden convivir. Andario Visibility no es un servicio de anuncios.',
  organicTitle: 'Visibilidad orgánica',
  organicPoints: ['SEO', 'Trabajo de estructura', 'Contenido', 'Resultados no garantizados', 'Construcción progresiva'],
  paidTitle: 'Publicidad',
  paidPoints: ['Anuncios', 'Inversión publicitaria', 'Campañas', 'Visibilidad ligada al presupuesto', 'Activación de campañas'],
  adsNote: 'No decimos que una sea mejor. Explicamos que son caminos distintos.',
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal es el establecimiento pionero de Andario Hospitality. No publicamos tráfico, posiciones ni reservas de su presencia.',
  finalTitle: 'Haz que tu presencia digital sea más fácil de encontrar y entender.',
  finalBody: 'Cuéntanos cómo aparece hoy tu alojamiento en Internet y qué quieres mejorar. Podemos ayudarte a ver oportunidades y definir por dónde empezar.',
  finalNote: 'Sin promesas de posiciones. Con una estrategia clara y medible.',
};
