import type { AccommodationsPageContent } from '@/content/types';

export const accommodationsPageEn: AccommodationsPageContent = {
  eyebrow: 'For independent accommodations',
  h1: 'Your property is unique. Your digital strategy should be too.',
  support:
    'From a hostel to a cabin, every property has different needs. At Andario Hospitality we help you build a professional digital presence, connect your channels and move toward a more orderly digital operation.',
  primaryCta: 'Request a digital diagnosis',
  secondaryCta: 'See our solutions',
  micro: 'You can start with one concrete need and grow from there.',
  heroCenter: 'Property',
  heroNodes: ['Google', 'Web', 'WhatsApp', 'Content', 'Bookings', 'Visibility', 'Growth'],
  heroMobile: ['Web', 'Google', 'WhatsApp', 'Content', 'Visibility', 'Booking Engine', 'Growth'],
  heroCaption:
    'The property sits at the center. Website, Google, WhatsApp, content, visibility, bookings and measurement relate around it. This is not a required order and not an automatic integration.',
  identifyTitle: 'Every property has its own story. And its own challenges.',
  identifyBody:
    'A hostel may need to organize bookings. A small hotel may need a professional website. An inn may need to be found more easily. A cabin may need to show the experience and the destination more clearly.',
  identifyClose: 'That is why we do not believe in one solution for everyone.',
  typesTitle: 'We design with real properties in mind.',
  typesSupport: 'Your size, your operation and your stage matter. The solutions adapt to where each property is today.',
  exploreCta: 'Explore the solutions',
  relatedLabel: 'Related solutions',
  serviceShort: {
    'digital-check': 'Digital Check',
    'andario-web': 'Web',
    'andario-visibility': 'Visibility',
    'andario-booking-engine': 'Booking',
    'andario-connect': 'Connect',
    'andario-content': 'Content',
    'andario-growth': 'Growth',
  },
  types: [
    {
      id: 'hostel',
      title: 'Hostels',
      body: 'Ways to improve digital presence, communication, bookings and how the experience is presented.',
      services: ['digital-check', 'andario-web', 'andario-connect', 'andario-booking-engine', 'andario-content'],
    },
    {
      id: 'small-hotel',
      title: 'Small hotels',
      body: 'A professional digital presence and tools to build your own strategy, without losing the closeness of an independent property.',
      services: ['andario-web', 'andario-visibility', 'andario-booking-engine', 'andario-growth'],
    },
    {
      id: 'inn',
      title: 'Inns',
      body: 'Turn the identity, the experience and the setting of the property into a clear digital presence.',
      services: ['andario-content', 'andario-web', 'andario-visibility'],
    },
    {
      id: 'apartments',
      title: 'Apartments and apart-hotels',
      body: 'Present your units clearly and make inquiry and booking easier to follow.',
      services: ['andario-web', 'andario-booking-engine', 'andario-connect'],
    },
    {
      id: 'rural',
      title: 'Cabins, villas and rural stays',
      body: 'Show the place, the destination and the experience that make the property distinct.',
      services: ['andario-content', 'andario-web', 'andario-visibility'],
    },
    {
      id: 'venture',
      title: 'Tourism ventures',
      body: 'Build a professional digital presence from a clear base that can evolve.',
      services: ['digital-check', 'andario-web', 'andario-growth'],
    },
  ],
  recognizeTitle: 'The challenge may not be more tools. It may be knowing what you need first.',
  recognizeSupport: 'Choose the situation closest to your property. This is guidance, not a required recommendation.',
  scenarios: [
    {
      title: 'I am just starting.',
      body: 'I need to build a professional digital presence from a clear base.',
      cta: 'I want to start',
      placement: 'starting',
      services: ['digital-check', 'andario-web', 'andario-content'],
    },
    {
      title: 'I have a presence, but people do not find me.',
      body: 'I have a website or social profiles, and I want to be easier to find for people looking for a place like mine.',
      cta: 'I want to improve my visibility',
      placement: 'visibility',
      services: ['digital-check', 'andario-visibility', 'andario-content'],
    },
    {
      title: 'I get inquiries, but everything is manual.',
      body: 'Conversations and bookings still take too much repetitive work.',
      cta: 'I want to organize my bookings',
      placement: 'bookings',
      services: ['andario-connect', 'andario-booking-engine', 'andario-web'],
    },
    {
      title: 'I have several disconnected channels.',
      body: 'I have a website, social profiles, WhatsApp, OTAs or other channels, and each part still works on its own.',
      cta: 'I want to connect my ecosystem',
      placement: 'channels',
      services: ['digital-check', 'andario-web', 'andario-connect', 'andario-booking-engine', 'andario-growth'],
    },
    {
      title: 'The place is strong, but I am not showing it well.',
      body: 'I need better photographs, writing, content and a clearer way to present the experience.',
      cta: 'I want to show the property better',
      placement: 'show',
      services: ['andario-content', 'andario-web', 'andario-visibility'],
    },
    {
      title: 'I do not know what is working.',
      body: 'I have a digital presence, and I need to understand what is happening and where to focus.',
      cta: 'I want to measure and improve',
      placement: 'measure',
      services: ['andario-growth', 'andario-visibility', 'digital-check'],
    },
  ],
  strategyTitle: 'One property. Many needs. One strategy.',
  strategyBody:
    'A property may need different solutions at different moments. Our work is to help you see which ones make sense now and which ones can come later.',
  strategyFlow: ['Property', 'Website', 'WhatsApp', 'Google', 'Content', 'Bookings', 'Visibility', 'Booking Engine', 'Growth'],
  strategyNote: 'This diagram is a way to read the needs. It does not mean every channel is integrated automatically.',
  ownTech: 'Our own technology',
  bookingTitle: 'Your property can also build its own booking channel.',
  bookingSupport:
    'Andario Booking Engine is our own technology for managing availability, rates, guests and reservations from a direct channel.',
  bookingPhrase: 'More control over your own channel. Less dependence on manual processes.',
  bookingCta: 'Explore Andario Booking Engine',
  bookingSteps: ['Availability', 'Rate', 'Reservation'],
  bookingBranches: [
    { title: 'Website', body: 'The starting channel you own, where a guest can check availability and book.' },
    { title: 'WhatsApp', body: 'It is for conversation. Booking inside the chat is not a live channel.' },
    { title: 'Other channels', body: 'A reservation can record where it came from. That is not a live integration.' },
  ],
  bookingResult: 'A reservation on your channel',
  bookingNote:
    'The engine can coexist with OTAs. It does not replace them, and it does not claim that Instagram, Facebook, Google or an assistant are already connected.',
  teamTitle: 'We know not every property has a large team behind it.',
  teamBody: [
    'In many properties, the same person welcomes guests, answers WhatsApp, manages bookings, publishes content and makes decisions about the business.',
    'That is why the solutions aim to be practical, understandable and adaptable to how each property actually runs.',
  ],
  teamPillars: [
    { title: 'Practical', body: 'Solutions shaped around the real operation.' },
    { title: 'Understandable', body: 'Technology explained in the language of the business.' },
    { title: 'Able to grow', body: 'You can start small and evolve.' },
    { title: 'Supported', body: 'You do not have to figure it all out alone.' },
  ],
  stanceTitle: 'You do not need to become a technology company to use technology well.',
  stanceBody: 'We take care of making it understandable and useful for your property.',
  stagesTitle: 'It does not matter if you are starting or if you already have a digital presence.',
  stages: [
    {
      title: 'I am starting',
      body: 'I need to build a professional base.',
      services: ['digital-check', 'andario-web', 'andario-content'],
    },
    {
      title: 'I am already operating',
      body: 'I want to improve visibility, bookings and communication.',
      services: ['andario-visibility', 'andario-booking-engine', 'andario-connect'],
    },
    {
      title: 'I want to evolve',
      body: 'I already have tools and I want to understand what works.',
      services: ['andario-growth', 'andario-visibility', 'digital-check'],
    },
  ],
  stagesClose: 'Start where you are. We help you identify the next step.',
  processTitle: 'We do not digitalize for its own sake. We build what makes sense for your business.',
  process: [
    { title: 'Understand', body: 'What is happening?' },
    { title: 'Prioritize', body: 'What matters first?' },
    { title: 'Build', body: 'What do we need to implement?' },
    { title: 'Measure', body: 'What is going on?' },
    { title: 'Evolve', body: 'What can we improve?' },
  ],
  processClose: 'Your strategy is built around the business, not the other way around.',
  processCta: 'See how we work',
  trustTitle: 'Technology with a practical outlook.',
  pillars: [
    { title: 'Specialization', body: 'We think about the needs of small and medium independent accommodations.' },
    { title: 'Simplicity', body: 'Technology should help you, not become another worry.' },
    { title: 'Our own technology', body: 'We build our own solutions, including Andario Booking Engine.' },
    { title: 'Support', body: 'It is not only about implementing. It is about understanding, measuring and evolving.' },
    {
      title: 'Transparency',
      body: 'We explain what we do, what each solution includes and which results we cannot guarantee.',
    },
  ],
  casesTitle: 'We are already taking this into a real property.',
  casesPlace: 'BARUCH Hostal · Buritaca, Colombia',
  casesBody:
    'BARUCH is the pioneering property with which we are taking Andario Hospitality from the idea into real operation. We do not publish metrics, bookings or testimonials yet.',
  casesCta: 'See the case',
  finalTitle: 'Tell us what kind of property you have and what you want to improve.',
  finalBody: 'We will look at your situation and help you see where a digital strategy could start.',
  finalPrimary: 'Request a digital diagnosis',
  finalSecondary: 'Talk with Andario',
  finalNote: 'No commitment. We will not sell you solutions you do not need.',
  faqs: [
    {
      q: 'What kinds of properties does Andario work with?',
      a: 'Mainly small and medium independent accommodations: hostels, small hotels, inns, tourist apartments, apart-hotels, cabins, villas and other lodging ventures.',
    },
    {
      q: 'Do I have to contract every solution?',
      a: 'No. You can start with one concrete need and add others when the property is ready.',
    },
    {
      q: 'Where should I start?',
      a: 'If you are not sure what you need, Digital Check can help you identify priorities.',
    },
    {
      q: 'Can you help if I do not have a website yet?',
      a: 'Yes. Andario Web can help you build a professional digital presence, and Digital Check can be the starting point for setting priorities.',
    },
    {
      q: 'Can you help me get more bookings?',
      a: 'Andario provides strategy, technology and tools to strengthen the digital ecosystem and your own channels. Bookings depend on many factors, and specific results are not guaranteed.',
    },
    {
      q: 'Does Andario replace Booking.com or other OTAs?',
      a: 'Not necessarily. The proposal aims to strengthen the property’s own channels and can coexist with external platforms, according to each strategy.',
    },
    {
      q: 'Can I start with only Booking Engine?',
      a: 'Yes, depending on the scope and the commercial conditions of the product.',
    },
    {
      q: 'How do I begin?',
      a: 'You can request a digital diagnosis or talk with Andario and tell us what kind of property you have and what you want to improve.',
    },
  ],
};
