import type { AndarioWebContent, FaqItem } from '@/content/types';

export const andarioWebFaqsEn: FaqItem[] = [
  {
    q: 'What is Andario Web?',
    a: 'The design and development service for professional websites for independent accommodations. It builds the property’s own digital home: identity, units, services, trust, contact and, when it fits, the path toward booking.',
  },
  {
    q: 'What does a website include?',
    a: 'Depending on scope: information architecture, UX/UI, responsive design, property and unit pages, services, a gallery, location, experiences, contact, WhatsApp, booking integration, policies, questions, technical SEO foundations and analytics.',
  },
  {
    q: 'Will it work on phones?',
    a: 'Yes. The site is designed mobile-first and responsive, so information, images and contact work on phones and tablets.',
  },
  {
    q: 'Can I integrate Andario Booking Engine?',
    a: 'Yes, when it is part of the scope. The site presents and invites. Availability and the booking stay in the engine. That logic is not copied onto the website.',
  },
  {
    q: 'What is the difference between the website and the Booking Engine?',
    a: 'Andario Web informs, builds trust and guides. Andario Booking Engine checks availability and manages the booking. They are different pieces that can work together.',
  },
  {
    q: 'Can I keep using Booking.com or Airbnb?',
    a: 'Yes. The website does not ask you to leave OTAs, and it does not claim to remove that dependence. It adds a digital home of your own.',
  },
  {
    q: 'Does Andario Web include SEO?',
    a: 'It includes technical foundations: titles, metadata, headings, URLs, a sitemap, canonical, hreflang and structured data when they help. Ongoing visibility strategy belongs to Andario Visibility. We do not promise a Google position.',
  },
  {
    q: 'Does it include professional photography?',
    a: 'The site organizes the images that are part of the scope. Professional photography, video and editorial planning can be extended with Andario Content. They are not included automatically.',
  },
  {
    q: 'Can I connect WhatsApp?',
    a: 'Yes. The site can offer a clear way to write on WhatsApp. Structuring or automating those conversations belongs to Andario Connect, if you contract it.',
  },
  {
    q: 'Can I show rooms or units?',
    a: 'Yes, within the scope: unit types, capacity and features, so a visitor can understand what they might book.',
  },
  {
    q: 'Can I show services and experiences?',
    a: 'Yes, when they are part of the offer and the scope: property services, experiences and, if it fits, the surroundings.',
  },
  {
    q: 'Does it include Google Analytics?',
    a: 'It can set up GA4 and events for contact, WhatsApp and booking actions when that is technically possible. We do not send personal data to analytics. Andario Growth can extend the reading later.',
  },
  {
    q: 'Will the site rank first on Google?',
    a: 'No. No one can promise the first place or a traffic figure. The website leaves technical foundations. Visibility is a separate piece of work.',
  },
  {
    q: 'Can I update the information?',
    a: 'Content changes are agreed within the scope. This page does not offer a self-service admin panel.',
  },
  {
    q: 'Do I need photographs and copy before we start?',
    a: 'It helps. If they are missing, we identify that at the start and see what the property prepares and what Andario Content can extend.',
  },
  {
    q: 'Can I start with Andario Web only?',
    a: 'Yes. Services are contracted separately. The website can be the first step, without Digital Check and without the rest of the ecosystem.',
  },
  {
    q: 'Do I have to contract every service?',
    a: 'No. Visibility, Booking Engine, Connect, Content and Growth are added only if the property needs them.',
  },
  {
    q: 'What do I need to start?',
    a: 'Tell us about the property, what you already have online and what you want to improve. Scope is defined from that. You do not need every asset ready.',
  },
  {
    q: 'How do I request information?',
    a: 'Through I want to digitalize my site or WhatsApp. The conversation does not require you to contract the other services.',
  },
];

export const andarioWebEn: AndarioWebContent = {
  support:
    'We design and build professional websites for independent accommodations, made to present the property, build trust, make contact easy and connect the visitor with your digital and booking strategy.',
  audienceLine: 'For hostels, small hotels, inns, holiday apartments, cabins, villas and other independent accommodations.',
  primaryCta: 'I want to digitalize my site',
  talkCta: 'Talk with Andario',
  connectCta: 'See how we can connect your website',
  infoCta: 'Request information',
  whatsappCta: 'Write on WhatsApp',
  scopeLabel: 'Depends on project scope',
  exampleLabel: 'Illustrative example',
  heroCaption: 'A sketch of a homepage: identity, the property, services and a way to continue. It is not a screenshot of a real site.',
  situations: [
    'I have a website, but it does not explain clearly what I offer.',
    'Information is split across several places.',
    'Writing or calling takes more effort than it should.',
    'On a phone the page feels awkward.',
    'The units are hard to understand before asking.',
    'There is no clear path toward booking.',
    'The website does not sit with the rest of the digital presence.',
  ],
  valueTitle: 'We do not build only a page. We build the digital space of your property.',
  valueParts: ['Identity', 'Content', 'Experience', 'Technology', 'Visibility', 'Contact and booking'],
  valueEquals: 'The property’s digital home',
  whatTitle: 'What is Andario Web?',
  whatBody:
    'A design and development service for professional websites for independent accommodations. The property presents its identity, units, services, location, experiences, policies and ways to get in touch. The site is planned as part of an ecosystem, not as an isolated piece.',
  anatomyTitle: 'Anatomy of an accommodation website',
  anatomyCaption: 'Each piece helps a visitor understand the property before they write or book.',
  anatomy: [
    { title: 'Identity', body: 'The property is recognizable from the first screen.' },
    { title: 'Units', body: 'Rooms or other units are explained with what a guest needs in order to compare.' },
    { title: 'Services', body: 'What the stay includes is visible, not hidden in a message.' },
    { title: 'Gallery', body: 'Images organize the spaces. They do not replace a shoot that is outside the scope.' },
    { title: 'Experiences', body: 'What can be done around the stay, when it is part of the offer.' },
    { title: 'Location', body: 'Where it is and how to arrive, without inventing destination facts.' },
    { title: 'Useful information', body: 'Policies and questions that avoid repeating the same answers in every conversation.' },
    { title: 'Contact and booking', body: 'WhatsApp, contact and, if it fits, the door to the booking engine.' },
  ],
  journeyTitle: 'The guest journey',
  journey: [
    { title: 'Discover', body: 'They find the property.' },
    { title: 'Understand', body: 'They see what it offers and where it is.' },
    { title: 'Compare', body: 'They learn the units, services and experience.' },
    { title: 'Trust', body: 'They find consistent information, images, policies and details.' },
    { title: 'Ask', body: 'They can write without much effort.' },
    { title: 'Book', body: 'They can continue to the booking channel when that channel exists.' },
  ],
  journeyNote: 'The website makes the journey easier. We do not promise that it generates bookings by itself.',
  includesTitle: 'What it can include',
  includesIntro: 'Grouped by what matters to the property. Final scope is defined with the establishment.',
  whatLabel: 'What',
  purposeLabel: 'What for',
  whyLabel: 'Why',
  groups: [
    {
      title: 'Architecture',
      items: [
        {
          name: 'Structure and path',
          what: 'Pages, navigation and hierarchy.',
          purpose: 'So a visitor finds what matters without getting lost.',
          why: 'A clear site gets used. A messy site gets left.',
        },
      ],
    },
    {
      title: 'Experience',
      items: [
        {
          name: 'UX, interface and mobile',
          what: 'A responsive interface, calls to action and usable contrast.',
          purpose: 'So it can be read and used from a phone.',
          why: 'Most enquiries start on a small screen.',
        },
      ],
    },
    {
      title: 'The property',
      items: [
        {
          name: 'Units and services',
          what: 'The establishment, rooms or units, capacity and services.',
          purpose: 'Compare the stay before asking.',
          why: 'A decision needs to see the offer, not only a name.',
        },
      ],
    },
    {
      title: 'Place',
      items: [
        {
          name: 'Location and surroundings',
          what: 'Location, how to arrive and the surroundings when they are in scope.',
          purpose: 'Tell where the property is, not only where someone sleeps.',
          why: 'The place is part of the decision.',
        },
      ],
    },
    {
      title: 'Images',
      items: [
        {
          name: 'Gallery',
          what: 'Photographs organized and prepared for the web.',
          purpose: 'Understand the spaces.',
          why: 'Images take part in the decision. A professional shoot belongs to Content.',
        },
      ],
    },
    {
      title: 'Contact',
      items: [
        {
          name: 'Write and locate',
          what: 'Contact, email, WhatsApp and location.',
          purpose: 'Make the next step obvious.',
          why: 'If writing is hard, the visit stays on the page.',
        },
      ],
    },
    {
      title: 'Bookings',
      items: [
        {
          name: 'Door to the engine',
          what: 'Paths toward booking and integration with Andario Booking Engine when it fits.',
          purpose: 'Move from knowing the property to starting a booking.',
          why: 'Availability does not live on the page. It lives in the engine.',
        },
      ],
    },
    {
      title: 'Technical visibility',
      items: [
        {
          name: 'SEO foundations',
          what: 'Headings, metadata, URLs, sitemap, canonical, hreflang and structured data when they help.',
          purpose: 'So search engines can read the site.',
          why: 'This is the base. Ongoing strategy is Visibility.',
        },
      ],
    },
    {
      title: 'Measurement',
      items: [
        {
          name: 'Analytics',
          what: 'GA4 and events for contact, WhatsApp and booking when possible.',
          purpose: 'See what gets used, without sending personal data.',
          why: 'What is not measured is harder to improve. Growth can extend the reading.',
        },
      ],
    },
  ],
  designTitle: 'Your property should look the way you want it to be perceived.',
  designBody:
    'Design organizes identity, type, color, photography and navigation so the site feels like the property and leads to a next step. It is not only a pretty page.',
  designPoints: ['Visual identity', 'Hierarchy', 'Photography', 'Navigation', 'Trust', 'Calls to action'],
  conversionTitle: 'From the visit to the next step',
  conversionNote: 'The website reduces friction. We do not publish conversion rates.',
  conversionSteps: ['Visitor', 'Information', 'Trust', 'Interest', 'Contact', 'Booking'],
  conversionAround: ['Content', 'Photographs', 'Location', 'Services', 'Questions', 'WhatsApp', 'Booking Engine'],
  bookingTitle: 'Your website can be the door to your own booking channel.',
  bookingBody:
    'Andario Web presents, informs and invites. Andario Booking Engine checks availability and manages the booking. That logic is not copied onto the site.',
  bookingSteps: ['Andario Web presents', 'Builds trust', 'Invites a booking', 'The engine checks availability', 'The engine manages the booking'],
  bookingNote: 'Integration is included when the project includes it. It is not switched on just because the website exists.',
  whatsappTitle: 'When a guest wants to talk, the path should be simple.',
  whatsappBody: 'The site can show WhatsApp in the journey, especially on a phone, with a contextual message. That makes contact easier.',
  whatsappNote: 'Structuring or automating conversations is Andario Connect, and only if you contract it.',
  seoTitle: 'A good website should also be readable by search engines.',
  seoBody: 'We leave foundations so the site can be indexed and understood. We do not promise the first place or a visit count.',
  seoPoints: ['Architecture', 'Titles and metadata', 'Headings', 'URLs', 'Internal links', 'Sitemap', 'Canonical and hreflang', 'Structured data', 'Performance'],
  seoNote: 'Andario Visibility develops the broader visibility strategy.',
  analyticsTitle: 'What is not measured is harder to improve.',
  analyticsBody: 'We can leave GA4 and events for calls to action, WhatsApp and booking actions when the technology allows it.',
  analyticsPoints: ['GA4', 'Contact clicks', 'WhatsApp', 'Journey', 'Booking actions, when possible'],
  analyticsNote: 'We do not send names, emails or messages to analytics. Growth can extend the analysis later.',
  performanceTitle: 'Designed to load with care and work well.',
  performanceBody: 'Prepared images, deferred loading, little unnecessary JavaScript and a mobile-first base. We do not promise a score of 100.',
  performancePoints: ['Optimized images', 'Deferred loading', 'Contained JavaScript', 'Mobile-first', 'Core Web Vitals as a reference'],
  accessTitle: 'A site people can use',
  accessBody: 'Contrast, keyboard, labels, headings, alternative text, visible focus and respect for people who prefer less motion. We do not claim a certification we do not have.',
  accessPoints: ['Contrast', 'Keyboard', 'Labels', 'Headings', 'Alternative text', 'Visible focus', 'Reduced motion'],
  mockNote: 'Illustrative example. It is not a screenshot of a real property.',
  mockNav: ['Stay', 'Services', 'Book'],
  mockHero: 'Discover your stay',
  mockBlocks: ['Rooms', 'Services', 'Experiences', 'Location', 'Gallery', 'Questions', 'WhatsApp'],
  processTitle: 'From the idea to a site ready to grow.',
  processIntro: 'Seven moments. The last one does not require contracting the rest.',
  process: [
    { title: 'Understand', body: 'The property, identity, audience, place and goals.' },
    { title: 'Structure', body: 'Architecture, navigation and content.' },
    { title: 'Design', body: 'A visual, responsive experience.' },
    { title: 'Build', body: 'The site and the integrations that are in scope.' },
    { title: 'Test', body: 'Mobile, accessibility, technical SEO, contact, links and performance.' },
    { title: 'Publish', body: 'Leave the site ready for production.' },
    { title: 'Evolve', body: 'Visibility, Booking Engine, Connect, Content or Growth, only if they are needed.' },
  ],
  receiveTitle: 'A site ready to represent your property.',
  receiveIntro: 'Depending on scope, it can include:',
  receive: [
    'Architecture and UX/UI',
    'Responsive design',
    'Property and unit pages',
    'Services, gallery and experiences',
    'Location and contact',
    'WhatsApp',
    'Booking integration',
    'Policies and questions',
    'Technical SEO and analytics',
    'Preparation to publish',
  ],
  receiveNote: 'Final scope is defined by what the property needs.',
  beforeTitle: 'From a scattered presence to a home of your own',
  beforeLabel: 'When information lives apart',
  beforeItems: ['Instagram', 'WhatsApp', 'OTA', 'Google', 'Scattered information'],
  afterLabel: 'With Andario Web',
  afterItems: ['Organized information', 'A digital experience of your own', 'WhatsApp', 'Bookings'],
  whoTitle: 'For properties that want a professional digital presence of their own.',
  whoTypes: ['Hostels', 'Small hotels', 'Inns', 'Holiday apartments', 'Aparthotels', 'Cabins', 'Villas', 'Rural stays', 'Other independent properties'],
  whoFit: [
    'They do not have a site yet.',
    'The website is outdated or hard to use.',
    'They want to professionalize the presence.',
    'They want to connect the website with bookings.',
    'They want a base of their own, alongside social profiles and OTAs.',
  ],
  whenTitle: 'When it tends to make sense',
  when: [
    'There is no site, or the current one has fallen behind.',
    'It does not work well on a phone.',
    'Information is disorganized.',
    'Units are poorly explained.',
    'Images are missing or contact is difficult.',
    'There is no path toward booking.',
    'You want to integrate the Booking Engine.',
    'You need a base for SEO and analytics.',
  ],
  destinationTitle: 'We do not only show where you sleep. We help tell where you are.',
  destinationBody: 'When it is in scope, the site can talk about the place without inventing facts.',
  destinationPoints: ['Place', 'Location', 'How to arrive', 'Surroundings', 'Experiences', 'Points of interest'],
  contentTitle: 'A good structure needs good content.',
  contentBody: 'Andario Web organizes what can already be told. Andario Content can extend the production.',
  contentWeb: ['Copy', 'Photographs in scope', 'Galleries', 'Property information'],
  contentExtra: ['Professional photography', 'Optimization', 'Social', 'Video', 'Destination content', 'Editorial plan'],
  contentNote: 'Professional photography is not included automatically.',
  checkTitle: 'Not sure what the website needs? You can start with Digital Check.',
  checkBody: 'The diagnosis helps see whether the website is the first step. It is not required.',
  checkSteps: ['Digital Check', 'Is a website needed?', 'Andario Web', 'Is visibility needed?', 'Visibility', 'Should booking happen here?', 'Booking Engine'],
  checkNote: 'You can contract Andario Web without the diagnosis.',
  visibilityTitle: 'The home and the visibility',
  visibilityBody: 'Andario Web builds the site. Andario Visibility works so it can be found. They complement each other. Neither promises the first place.',
  growthTitle: 'The home and the measurement',
  growthBody: 'Andario Web leaves the experience and the analytics foundations. Andario Growth can extend the reading and the improvements later.',
  notTitle: 'What Andario Web is not',
  not: [
    { title: 'Not only design', body: 'It includes structure, experience, content and technology.' },
    { title: 'Not a booking engine', body: 'Booking Engine manages availability and the reservation.' },
    { title: 'Not a full SEO strategy', body: 'It leaves foundations. Visibility can extend the strategy.' },
    { title: 'Not unlimited photography', body: 'Professional production is extended with Content.' },
    { title: 'Not a booking guarantee', body: 'It is infrastructure. Results depend on more than the site.' },
    { title: 'Not an identical template', body: 'The structure adapts to the property.' },
  ],
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal is the pioneer property of Andario Hospitality. We do not publish results from its website.',
  ecosystemTitle: 'It can sit with the rest. It does not require them.',
  ecosystem: ['Digital Check', 'Andario Web', 'Visibility', 'Booking Engine', 'Connect', 'Content', 'Growth'],
  ecosystemNote: 'Each service is contracted according to what the property needs. The order is not mandatory.',
  finalTitle: 'Your property deserves a home of its own on the internet.',
  finalBody: 'Tell us what you have today, what you want to improve and where you want the digital presence to go.',
  finalNote: 'We can start with the scope your property actually needs.',
};
