import type { BookingEngineContent } from '@/content/types';

export const bookingEngineEn: BookingEngineContent = {
  support:
    'It centralizes availability, rates, units, guests and reservations in technology designed for independent accommodations. Start with your web channel and grow toward a more connected booking ecosystem.',
  primaryCta: 'I want to know Booking Engine',
  talkCta: 'Talk with Andario',
  whatsappCta: 'Talk on WhatsApp',
  availableLabel: 'Available',
  roadmapLabel: 'Roadmap',
  hubCaption:
    'The website enters the engine today. WhatsApp, Instagram, Facebook, Google and other channels are shown as evolution: they are not live booking integrations yet.',
  hubCore: 'Andario Booking Engine',
  hubChannels: [
    { name: 'Website', status: 'available' },
    { name: 'WhatsApp', status: 'roadmap' },
    { name: 'Instagram', status: 'roadmap' },
    { name: 'Facebook', status: 'roadmap' },
    { name: 'Google', status: 'roadmap' },
    { name: 'Others', status: 'roadmap' },
  ],
  hubOutcomes: ['Availability', 'Rates', 'Inventory', 'Guests', 'Bookings', 'Source'],
  problemPoints: [
    'Bookings arrive from different places.',
    'Availability is hard to control when each channel works alone.',
    'The same information gets copied more than once.',
    'Enquiries are handled by hand.',
    'The process is split across people and tools.',
    'It is hard to see where each booking came from.',
    'The operation becomes clear late, when something already needs fixing.',
  ],
  beforeTitle: 'When each channel works apart',
  beforeCaption: 'This is not every property. It shows up when bookings have no shared place.',
  beforeChannels: ['Website', 'WhatsApp', 'Front desk', 'OTAs'],
  beforeResult: 'Scattered processes',
  afterTitle: 'With one central logic',
  afterCaption: 'Contact points can coexist. The booking leans on the same engine.',
  afterChannels: ['Website', 'WhatsApp', 'Other channels'],
  afterResult: 'Inventory and bookings',
  valueTitle: 'One logic to organize how you take bookings.',
  valueBody:
    'Andario Booking Engine is designed to hold what a property needs in order to take a booking, without asking you to learn a technical system.',
  valueItems: [
    'Availability',
    'Inventory',
    'Units',
    'Rates',
    'Guests',
    'Bookings',
    'Rules',
    'Statuses',
    'Payments according to configuration',
    'Channel source',
    'Administration',
  ],
  exactTitle: 'What is it, exactly?',
  exactBody:
    'It is where the booking operation lives: what can be sold, on what terms, and what was reserved. This corporate site only explains it. It does not check availability or create bookings.',
  centralTitle: 'What it centralizes',
  centralIntro: 'Twelve pieces of the operation, in lodging language.',
  central: [
    { title: 'Property', body: 'The accommodation’s configuration.' },
    { title: 'Units', body: 'Rooms and other bookable units.' },
    { title: 'Inventory', body: 'The resources that can be sold.' },
    { title: 'Availability', body: 'What is still open for the dates and resources.' },
    { title: 'Rates', body: 'How prices are configured and applied.' },
    { title: 'Guests', body: 'The information tied to each booking.' },
    { title: 'Bookings', body: 'Creating and following each reservation.' },
    { title: 'Rules', body: 'The conditions that shape the operation.' },
    { title: 'Statuses', body: 'Where each booking stands.' },
    { title: 'Payments', body: 'Payment logic according to what the property has configured.' },
    { title: 'Source', body: 'Which channel the booking came from.' },
    { title: 'Administration', body: 'Day-to-day management of the property.' },
  ],
  featuresTitle: 'What you need to build a booking channel of your own.',
  featuresIntro: 'Grouped by what matters to the property, not as a technical list.',
  featuresCta: 'I want to know Andario Booking Engine',
  doesLabel: 'What it does',
  whyLabel: 'Why it matters',
  groups: [
    {
      title: 'Catalog and inventory',
      items: [
        {
          name: 'Property',
          does: 'Holds the identity and configuration of the accommodation.',
          why: 'A booking starts from a real property, not a generic form.',
        },
        {
          name: 'Units and beds',
          does: 'Describes unit types, rooms and beds when the property sells bed spaces.',
          why: 'A hostel with dorms and a small hotel do not book in the same way.',
        },
        {
          name: 'Amenities and images',
          does: 'Attaches amenities and images to what is offered.',
          why: 'The guest sees a recognizable option before booking.',
        },
      ],
    },
    {
      title: 'Availability',
      items: [
        {
          name: 'Search by dates',
          does: 'Checks what can be booked between arrival and departure.',
          why: 'The answer comes from the same information, not a separate sheet.',
        },
        {
          name: 'Resources and conflicts',
          does: 'Accounts for units already taken and avoids selling the same resource twice.',
          why: 'The booking works from real inventory.',
        },
      ],
    },
    {
      title: 'Rates',
      items: [
        {
          name: 'Configured prices',
          does: 'Applies rates by unit type, currency and validity.',
          why: 'The price does not depend on someone remembering it in every conversation.',
        },
        {
          name: 'Taxes',
          does: 'Adds the taxes the property has configured.',
          why: 'The booking terms are more complete.',
        },
      ],
    },
    {
      title: 'Bookings',
      items: [
        {
          name: 'Creating the booking',
          does: 'Records the guest, unit, dates, status and source.',
          why: 'The reservation no longer lives only in a message.',
        },
        {
          name: 'Payments by configuration',
          does: 'Confirms payment with the capabilities the property has switched on.',
          why: 'Collection follows the property’s rule, not a generic promise.',
        },
      ],
    },
    {
      title: 'Administration',
      items: [
        {
          name: 'Configuration',
          does: 'Lets the team adjust the property, catalog, rates, taxes and rules.',
          why: 'The team works from one place.',
        },
        {
          name: 'Team access',
          does: 'Separates who administers each property.',
          why: 'The operation is not open to everyone.',
        },
      ],
    },
  ],
  flowTitle: 'How a booking works',
  flowIntro: 'Eight steps, in the order a guest experiences them.',
  flow: [
    { title: 'The guest searches', body: 'They enter dates and who is staying.' },
    { title: 'The engine checks availability', body: 'It looks at which resources are still open.' },
    { title: 'Options appear', body: 'Only units that can actually be booked are shown.' },
    { title: 'The guest chooses', body: 'They pick the option that fits.' },
    { title: 'Terms are calculated', body: 'Configured rates and taxes are resolved in the engine.' },
    { title: 'Details are recorded', body: 'The information the booking needs is stored.' },
    { title: 'The booking is created', body: 'Inventory is committed to that request.' },
    { title: 'It is confirmed by configuration', body: 'Closing follows the payment method the property has active.' },
  ],
  reservationTitle: 'How a booking reads',
  reservationNote: 'Illustrative example. It is not a real guest and not a screenshot of the product.',
  reservation: [
    { label: 'Booking', value: 'AND-000123' },
    { label: 'Guest', value: 'María González' },
    { label: 'Check-in', value: '12 Oct' },
    { label: 'Check-out', value: '15 Oct' },
    { label: 'Unit', value: 'Private room' },
    { label: 'Guests', value: '2' },
    { label: 'Rate', value: 'Standard' },
    { label: 'Status', value: 'Confirmed' },
    { label: 'Source', value: 'Website' },
  ],
  channelsTitle: 'One central logic. Different points of contact.',
  channelsBody:
    'Connecting a channel means a booking can start there. Recording the source is different: the team can note where a booking came from even when that channel cannot book on its own yet.',
  channels: [
    {
      name: 'Website',
      status: 'available',
      note: 'This is the starting direct channel. The site can open the engine; availability and the booking stay in the engine.',
    },
    {
      name: 'WhatsApp',
      status: 'roadmap',
      note: 'Today it accompanies the conversation. Booking inside WhatsApp is not live yet.',
    },
    {
      name: 'Instagram',
      status: 'roadmap',
      note: 'It belongs to the future architecture. It is not a live booking integration.',
    },
    {
      name: 'Facebook',
      status: 'roadmap',
      note: 'Same status: planned, not operating as a booking channel.',
    },
    {
      name: 'Google',
      status: 'roadmap',
      note: 'It is not connected as a booking channel.',
    },
    {
      name: 'AI assistant',
      status: 'roadmap',
      note: 'A later evolution. This page does not present it as available.',
    },
  ],
  rolesTitle: 'They are not the same. They work together.',
  rolesIntro: 'Three pieces of the ecosystem, each with a different job.',
  roles: [
    {
      name: 'Andario Web',
      role: 'The property’s digital presence.',
      points: ['Informs', 'Builds trust', 'Presents rooms and services', 'Welcomes the visitor'],
    },
    {
      name: 'Andario Booking Engine',
      role: 'The booking logic.',
      points: ['Availability', 'Rates', 'Inventory', 'Guests, bookings, rules and source'],
    },
    {
      name: 'Andario Connect',
      role: 'The conversation channel.',
      points: ['Talk', 'Reply', 'Guide', 'Stay with the guest'],
    },
  ],
  rolesFlow: ['Andario Web attracts and informs', 'Booking Engine handles the reservation', 'Connect stays with the conversation'],
  rolesClose: 'They can be added gradually. You do not need the whole ecosystem to begin.',
  benefitsTitle: 'What changes day to day',
  benefits: [
    {
      audience: 'For the owner',
      points: [
        'More control over the direct channel.',
        'Booking information in one place.',
        'Less dependence on manual processes.',
        'Clearer sight of where each booking came from.',
        'A base to grow the digital ecosystem when the business asks for it.',
      ],
    },
    {
      audience: 'For the team',
      points: [
        'A more structured process.',
        'Less data copied in several places.',
        'Bookings visible in the same record.',
        'Information that stays more consistent.',
      ],
    },
    {
      audience: 'For the guest',
      points: [
        'A clearer booking path.',
        'Availability they can look up.',
        'Stay information that is organized.',
        'A digital experience that matches the conversation.',
      ],
    },
  ],
  otaTitle: 'Do I have to leave Booking.com or Airbnb?',
  otaBody:
    'Not necessarily. Andario Booking Engine is meant to help you build and strengthen a channel of your own. OTAs can remain part of the commercial strategy. The aim is a more direct relationship with guests and your own infrastructure for reservations. The engine does not sync OTAs while that integration does not exist.',
  whoTitle: 'Designed for independent accommodations.',
  whoBody:
    'The bookable unit adapts to the property when the product can represent it: a room, a bed in a dorm, or a whole unit.',
  whoTypes: [
    'Hostels',
    'Small hotels',
    'Inns',
    'Holiday apartments',
    'Aparthotels',
    'Cabins',
    'Villas',
    'Rural stays',
    'Other small properties',
  ],
  trustTitle: 'Your operation deserves technology you can rely on.',
  trustBody:
    'The engine validates operations, controls availability and applies the property’s rules. Each property stays separate from the others. Administrative access is controlled and, where it already exists, actions are recorded. We do not publish sensitive technical detail here, and we do not claim any system is infallible.',
  trustPoints: [
    'Validation of each operation',
    'Availability control',
    'Business rules',
    'Separation between properties',
    'Administrative access',
    'An action record where it is available',
  ],
  evolutionTitle: 'Built to grow with you.',
  evolutionBody:
    'Andario Booking Engine is a product in evolution. What already runs the direct channel is marked available. The rest is roadmap.',
  evolution: [
    { label: 'Own web channel', status: 'available' },
    { label: 'Availability', status: 'available' },
    { label: 'Rates', status: 'available' },
    { label: 'Bookings', status: 'available' },
    { label: 'Administration', status: 'available' },
    { label: 'Channel integrations', status: 'roadmap' },
    { label: 'Omnichannel', status: 'roadmap' },
    { label: 'Broader automation', status: 'roadmap' },
    { label: 'AI', status: 'roadmap' },
  ],
  pioneerTitle: 'BARUCH Hostal, the pioneer setting',
  pioneerBody:
    'BARUCH Hostal is the pioneer property of Andario Hospitality and one of the first real settings where Andario Booking Engine is evolving.',
  diffTitle: 'Why it fits an independent property',
  diff: [
    { title: 'Specialization', body: 'It is shaped around independent accommodations, not a chain.' },
    { title: 'Simplicity', body: 'The technology should organize the operation, not add another confusing layer.' },
    { title: 'Own technology', body: 'It is part of a platform developed by Andario.' },
    { title: 'Evolution', body: 'It can grow in stages, without presenting the future as if it were already on.' },
    { title: 'Ecosystem', body: 'It can sit with Web, Visibility, Connect, Content and Growth when you need them.' },
  ],
  startTitle: 'Start with what your property needs today.',
  startSteps: [
    { title: 'We talk', body: 'We learn the property and how you take bookings today.' },
    { title: 'We define the setup', body: 'We identify units, rates, rules and the channel worth starting with.' },
    { title: 'We implement', body: 'We configure the engine and connect it to the site when that is the step.' },
    { title: 'We go live', body: 'We test the flow and leave the channel ready.' },
    { title: 'We evolve', body: 'We add capabilities when the business needs them.' },
  ],
  startCta: 'Request information about Booking Engine',
  finalTitle: 'Build the direct booking channel for your property.',
  finalBody: 'Tell us how your operation works today and we will show you how Andario Booking Engine could fit.',
  finalCta: 'Request information',
};
