import type { BookingEngineContent } from '@/content/types';

const image = (name: string) => `/images/booking-engine/${name}`;

export const bookingEngineEn: BookingEngineContent = {
  support:
    'Take bookings from your different channels, manage guests and operations, and turn your property’s information into data for better decisions.',
  primaryCta: 'Request a demonstration',
  talkCta: 'Talk with Andario',
  capabilities: ['Direct bookings', 'Guest management', 'Check-in / Check-out', 'Invoicing', 'Reports and analytics'],
  heroImage: image('booking-engine-hero-desk-en.webp'),
  heroAlt: 'A room with a sea view, a laptop showing the Andario bookings panel and a phone with the booking experience.',
  webTitle: 'Turn your website into a booking channel.',
  webBody:
    'Your website shows your property, your spaces and what makes it special. Andario Booking Engine makes it possible for guests to book directly.',
  presentCard: {
    title: 'Your website',
    role: 'Presents the property',
    points: ['Rooms and units', 'Photos and descriptions', 'Services and experiences', 'Location', 'Builds trust'],
  },
  reserveCard: {
    title: 'Andario Booking Engine',
    role: 'Makes the booking possible',
    points: ['Availability', 'Rates and options', 'Guest details', 'Confirmed booking', 'Organized information'],
  },
  guestTitle: 'A simple, clear booking experience.',
  guestBody: 'Your guest can check availability, choose an option, book and receive a confirmation in a few steps.',
  guestSteps: ['Check', 'Choose', 'Book', 'Pay', 'Receive confirmation'],
  guestImage: image('booking-engine-guest.webp'),
  guestAlt: 'A phone showing a conceptual booking experience, on a bedside table.',
  channelsEyebrow: 'Your booking can start wherever your guest is',
  channelsTitle: 'One center. Different channels. Your whole operation.',
  channelsBody:
    'Share your Booking Engine link on the channels where you promote your property. When a guest wants to book, they can come straight to your booking process.',
  channels: [
    { id: 'web', label: 'Web' },
    { id: 'facebook', label: 'Facebook' },
    { id: 'instagram', label: 'Instagram' },
    { id: 'tiktok', label: 'TikTok' },
    { id: 'whatsapp', label: 'WhatsApp' },
    { id: 'google', label: 'Google' },
    { id: 'other', label: 'Other channels' },
  ],
  channelDestination: 'Andario Booking Engine',
  channelOutcomes: ['Check', 'Book', 'Pay', 'Confirmation', 'Management', 'Check-in', 'Check-out', 'Invoice', 'Reports'],
  compareTitle: 'From many inquiries to a simple process.',
  compareBody:
    'Your guest can check availability and book in a few steps, while you focus on what matters most: offering a great stay.',
  beforeTitle: 'Before',
  beforePoints: ['Scattered messages', 'Repeated questions', 'Manual availability', 'Information spread out', 'Manual follow-up'],
  afterTitle: 'With Andario',
  afterPoints: ['Checks availability', 'Sees options and prices', 'Chooses a stay', 'Leaves their details', 'Books', 'Receives confirmation'],
  adminTitle: 'The booking is only the beginning.',
  adminBody: 'Once a booking is created, Andario helps you run the property from one place.',
  adminImage: image('booking-engine-dashboard.webp'),
  adminAlt: 'A conceptual panel with a calendar, a booking list and statuses, without real data.',
  conceptualNote: 'Conceptual representation.',
  adminPoints: [
    { title: 'Booking management', body: 'Bookings in order.' },
    { title: 'Guests', body: 'Information on hand.' },
    { title: 'Check-in and check-out', body: 'The stay under control.' },
    { title: 'Invoicing', body: 'Information ready to manage.' },
    { title: 'Reports', body: 'Look up and download information.' },
    { title: 'Analytics', body: 'Understand what is happening.' },
  ],
  analyticsTitle: 'You do more than take bookings. You understand your business.',
  analyticsBody: 'Every booking creates information. Andario organizes that data so you can understand what is happening at your property.',
  analyticsImage: image('booking-engine-analytics.webp'),
  analyticsAlt: 'Conceptual charts for booking trends, source and patterns, without figures.',
  analyticsPoints: ['Booking trends', 'Booking source', 'Guest information', 'Operations data', 'Patterns'],
  journeyTitle: 'From the first interaction to operations.',
  journeySteps: [
    'They find you',
    'They click',
    'They book',
    'They pay',
    'They receive confirmation',
    'You manage the booking',
    'Check-in',
    'Check-out',
    'Invoice',
    'Reports and analytics',
  ],
  typesTitle: 'It works for your property.',
  typesBody: 'Andario Booking Engine adapts to the way you sell and manage your spaces.',
  types: [
    { name: 'Hostels', image: image('booking-engine-hostel.webp'), alt: 'A hostel room with wooden bunk beds' },
    { name: 'Small hotels', image: image('booking-engine-hotel.webp'), alt: 'A bedroom in a small hotel' },
    { name: 'Cabins', image: image('booking-engine-cabin.webp'), alt: 'A wooden cabin among the trees' },
    { name: 'Apartments', image: image('booking-engine-apartment.webp'), alt: 'The living room of a tourist apartment' },
    { name: 'Inns', image: image('booking-engine-posada.webp'), alt: 'The courtyard of a small inn, with a bench and clay tiles' },
  ],
  directTitle: 'Build your direct channel.',
  directBody:
    'Andario Booking Engine lets you create your own booking channel that complements the channels where you already promote your property.',
  directNote: 'It can sit alongside Booking.com, Airbnb and other channels. It does not sync with them automatically.',
  directParts: ['Channels you already use', 'Your website', 'Andario Booking Engine'],
  ecosystemTitle: 'A booking channel that can grow with you.',
  ecosystemBody:
    'Booking Engine can work alongside Andario’s other solutions to gradually build a digital ecosystem around your property.',
  ecosystem: [
    { id: 'andario-web', label: 'Web' },
    { id: 'andario-visibility', label: 'Visibility' },
    { id: 'andario-booking-engine', label: 'Booking Engine' },
    { id: 'andario-connect', label: 'Connect' },
    { id: 'andario-growth', label: 'Growth' },
  ],
  processTitle: 'This is the process.',
  processBody: 'We handle the setup so you can start taking bookings in an organized way.',
  processSteps: ['We get to know your property', 'We configure the booking engine', 'We test everything with you', 'We put it into use'],
  finalTitle: 'Want to bring your property’s bookings and operations into one place?',
  finalBody: 'Tell us how your property works today and we will show you how Andario Booking Engine can fit.',
  finalCta: 'Request a demonstration',
  finalImage: image('booking-engine-final-cta.webp'),
  finalAlt: 'A property terrace facing the sea at sunset',
};
