import type { BookingEngineContent } from '@/content/types';

export const bookingEngineEn: BookingEngineContent = {
  support:
    'Let your guests check availability and book directly from your property website while keeping your reservation information organized in one place.',
  assist: "You don't need technical knowledge. We help configure it around the way your property actually operates.",
  primaryCta: 'Learn about Booking Engine',
  talkCta: 'Talk to Andario',
  infoCta: 'Request information',
  whatsappCta: 'Talk on WhatsApp',
  heroMicro: 'No commitment. A conversation does not lock you into a contract.',
  path: [
    { title: 'Your property', body: 'Where it starts.' },
    { title: 'Your website', body: 'Where guests get to know you.' },
    { title: 'Booking Engine', body: 'Where the reservation happens.' },
    { title: 'Availability', body: 'What is still free.' },
    { title: 'Rate', body: 'The price you configured.' },
    { title: 'Reservation', body: 'It is recorded.' },
  ],
  whatTitle: 'What is a booking engine?',
  whatBody:
    'A booking engine is the tool that lets a guest see what is available, check the price and make a reservation from your property’s own channel.',
  whatWeb: 'Your website presents your property.',
  whatEngine: 'The Booking Engine handles the reservation.',
  whatFlow: [
    { title: 'Your website', body: 'Presents.' },
    { title: 'Your property', body: 'Informs.' },
    { title: 'Booking Engine', body: 'Checks availability.' },
    { title: 'Shows options', body: 'The guest sees what can actually be booked.' },
    { title: 'The guest books', body: 'They choose and leave their details.' },
    { title: 'Reservation recorded', body: 'The property receives it in order.' },
  ],
  contrastTitle: 'Your website and your booking engine do different jobs.',
  contrastClose: 'A website attracts and informs. The Booking Engine lets people book.',
  webCard: {
    name: 'Andario Web',
    role: 'It is the digital home of your property.',
    points: ['Present rooms', 'Show photographs', 'Explain services', 'Build trust', 'Show the location', 'Present experiences', 'Welcome visitors'],
  },
  engineCard: {
    name: 'Andario Booking Engine',
    role: 'It is the system that organizes the reservation.',
    points: ['Check availability', 'Show rates', 'Manage units', 'Record guests', 'Create reservations', 'Apply rules', 'Record the source'],
  },
  manualTitle: 'What happens when bookings live only in WhatsApp?',
  manualSteps: [
    'A guest writes: “Do you have availability from the 12th to the 15th?”',
    'You check by hand.',
    'You work out the price.',
    'You ask how many people are coming.',
    'You check availability again.',
    'You send instructions.',
    'You write the booking down yourself.',
    'You update availability.',
    'Then the same loop starts again.',
  ],
  manualBody:
    'WhatsApp still matters. When everything depends on conversations and handwritten records, each booking can ask for the same work all over again.',
  organizedTitle: 'With your own channel, part of that process stays organized.',
  organizedSteps: [
    'The guest opens your website.',
    'They choose dates.',
    'They check availability.',
    'They see options.',
    'They select a unit.',
    'They enter their details.',
    'They see the conditions you configured.',
    'The reservation is created.',
    'The property receives it in order.',
  ],
  organizedBody: 'The guest can move through a clear booking path while the engine applies the logic configured for your property.',
  exampleTitle: 'Picture a hostel with 8 rooms.',
  exampleIntro: 'The guest wants 2 people and 3 nights. The engine:',
  exampleSteps: [
    'Receives the dates.',
    'Checks availability.',
    'Finds a room that is free.',
    'Applies the rate you configured.',
    'Calculates the conditions.',
    'Records the details.',
    'Creates the reservation.',
  ],
  exampleClose: 'The owner does not have to do each of these steps by hand. This is an illustration, not a real property.',
  useTitle: 'How can you use Andario Booking Engine?',
  resultLabel: 'What you get',
  uses: [
    {
      title: 'You already have a website',
      body: 'You can add the engine so the site does more than inform. It can also start the booking.',
      result: 'Your website becomes a direct booking channel.',
    },
    {
      title: 'You depend heavily on Booking.com',
      body: 'You can keep Booking.com and other OTAs while you build a channel of your own. Andario Booking Engine does not sync OTAs today.',
      result: 'You do not have to leave your current channels to start a direct one.',
    },
    {
      title: 'You get a lot of WhatsApp inquiries',
      body: 'Your website can be the place where a guest checks availability and moves into the booking. WhatsApp stays a conversation: booking inside the chat is not live yet.',
      result: 'Some questions that now need a manual explanation can start in a structured path.',
    },
    {
      title: 'You run a hostel with beds',
      body: 'The engine can treat a bed as a bookable resource when the property is set up that way.',
      result: 'You can work with the way a hostel actually sells space.',
    },
    {
      title: 'You run a small hotel',
      body: 'You can work with rooms, rates, availability and reservations from one central logic.',
      result: 'The booking no longer depends on someone remembering every detail.',
    },
    {
      title: 'You have cabins, apartments or villas',
      body: 'A bookable unit can adapt the engine to different kinds of property when the product can represent them.',
      result: 'The unit looks like what you actually sell.',
    },
  ],
  otaTitle: 'You do not have to leave Booking.com.',
  otaLead: 'Andario Booking Engine is not here to make you drop your OTAs.',
  otaBody: 'You can keep using your current channels and, at the same time, build one of your own.',
  otaExternalLabel: 'Outside channels',
  otaExternal: ['Booking.com', 'Airbnb', 'Others'],
  otaOwnLabel: 'Your own channel',
  otaOwn: ['Your website', 'Andario Booking Engine'],
  otaSync: 'Andario Booking Engine does not sync OTAs today.',
  otaNote: 'The aim is to add infrastructure you own, not to switch off the channels you already use.',
  organizeTitle: 'What does the engine organize?',
  doesLabel: 'What it does',
  whyLabel: 'Why it matters',
  groups: [
    {
      title: 'Catalog',
      items: [
        {
          name: 'Property, units and services',
          does: 'Describes the property, its rooms or beds, and what it offers.',
          why: 'The booking starts from what you actually sell.',
        },
      ],
    },
    {
      title: 'Availability',
      items: [
        {
          name: 'Dates, resources and conflicts',
          does: 'Checks which units are still free for the dates the guest wants.',
          why: 'You can see what you can sell without checking everything by hand.',
        },
      ],
    },
    {
      title: 'Rates',
      items: [
        {
          name: 'Prices, currency, validity and taxes',
          does: 'Applies the prices configured for each unit.',
          why: 'The price does not depend on remembering it in every chat.',
        },
      ],
    },
    {
      title: 'Reservations',
      items: [
        {
          name: 'Guest, unit, dates, status and source',
          does: 'Keeps the reservation details in one place.',
          why: 'You can see where it came from when that source is recorded.',
        },
      ],
    },
    {
      title: 'Administration',
      items: [
        {
          name: 'Setup, rules and access',
          does: 'Applies the conditions configured for your property.',
          why: 'The team works from the same rules, not a different version in every chat.',
        },
      ],
    },
  ],
  dayTitle: 'What changes in the day to day?',
  benefits: [
    {
      audience: 'For the owner',
      points: ['More control over your own channel.', 'Information in order.', 'Less repeated work.', 'A clearer view of reservations.', 'A base you can grow from.'],
    },
    {
      audience: 'For the team',
      points: ['A structured process.', 'Less repeated information.', 'Reservations on record.', 'Consistent details.'],
    },
    {
      audience: 'For the guest',
      points: ['A clearer path.', 'An availability check.', 'Information in order.', 'A simpler digital process.'],
    },
  ],
  demandTitle: 'A booking engine does not create demand on its own.',
  demand: [
    'Booking Engine gives you the infrastructure to receive reservations from a channel you own.',
    'To attract guests you also need visibility, content, a clear digital presence and a commercial plan.',
  ],
  demandNote: 'That is why it can work alongside Andario Web, Visibility, Content, Connect and Growth. You do not have to contract all of them.',
  companions: [
    { label: 'Andario Web', routeId: 'andario-web' },
    { label: 'Andario Visibility', routeId: 'andario-visibility' },
    { label: 'Andario Content', routeId: 'andario-content' },
    { label: 'Andario Connect', routeId: 'andario-connect' },
    { label: 'Andario Growth', routeId: 'andario-growth' },
  ],
  ecosystemTitle: 'It can sit with the rest. None of it is mandatory.',
  ecosystem: [
    { name: 'Andario Web', body: 'People find you and get to know the property.' },
    { name: 'Booking Engine', body: 'They book.' },
    { name: 'Connect', body: 'You talk and stay with them.' },
    { name: 'Growth', body: 'You see what is working.' },
  ],
  ecosystemNote: 'You can start with Booking Engine or with another solution and add the rest when the property needs it.',
  flowTitle: 'How a reservation works.',
  flowIntro: 'Eight steps, in the order a guest actually lives them.',
  flow: [
    { title: 'The guest looks for dates', body: 'They say when they want to arrive and leave.' },
    { title: 'The engine checks availability', body: 'It looks at what is still free.' },
    { title: 'Available options appear', body: 'Only what can be booked is shown.' },
    { title: 'The guest chooses', body: 'They pick the unit that fits.' },
    { title: 'Configured conditions are calculated', body: 'The property’s rate and rules are applied.' },
    { title: 'Their details are recorded', body: 'The information the reservation needs is kept.' },
    { title: 'The reservation is created', body: 'The property receives it in one record.' },
    { title: 'It is confirmed according to the setup', body: 'The close follows the payment method the property has active.' },
  ],
  reservationTitle: 'How a reservation reads.',
  reservationNote: 'Illustrative example. It is not a real guest and not a screenshot of the product.',
  reservation: [
    { label: 'Reservation', value: 'AND-000123' },
    { label: 'Guest', value: 'María González' },
    { label: 'Arrival', value: '12 Oct' },
    { label: 'Departure', value: '15 Oct' },
    { label: 'Unit', value: 'Private room' },
    { label: 'Guests', value: '2' },
    { label: 'Rate', value: 'Standard' },
    { label: 'Status', value: 'Confirmed' },
    { label: 'Source', value: 'Website' },
  ],
  todayTitle: 'What you can use today, and what we are building.',
  availableLabel: 'Available today',
  roadmapLabel: 'In progress',
  todayItems: ['Web channel', 'Availability', 'Rates', 'Reservations', 'Administration'],
  laterItems: ['WhatsApp as a booking channel', 'Instagram', 'Facebook', 'Google', 'Broader automation', 'AI assistant', 'Other integrations'],
  honesty: 'We would rather say clearly what you can use today and what is still being built. Recording a source is not the same as that channel booking on its own.',
  trustTitle: 'An operation designed with security in mind.',
  trustBody: 'The engine looks after the reservation with operational checks. We do not publish the sensitive technical detail.',
  trustPoints: [
    'Validation of operations',
    'Availability control',
    'Business rules',
    'Separation between properties',
    'Administrative access control',
    'An action record when it is available',
  ],
  trustHonest: 'No system is infallible. This one is built so each property works with its own rules.',
  whoTitle: 'For independent accommodations.',
  whoBody: 'Hostels, small hotels, inns, apartments, cabins, villas and rural stays.',
  whoQuestion: 'Does your property sell rooms, beds or whole units?',
  whoAnswer: 'The engine is designed to follow the bookable unit your business uses, when the product can represent it.',
  whoTypes: ['Hostels', 'Small hotels', 'Inns', 'Holiday apartments', 'Aparthotels', 'Cabins', 'Villas', 'Rural stays'],
  whoNot:
    'If you are looking for a corporate system for a large hotel group with many enterprise integrations, Andario Booking Engine may not be the right starting point.',
  techTitle: 'You do not need to know about technology.',
  tech: ['Andario handles the technology.', 'We help you understand and configure the engine around the way your property works.'],
  techMark: 'You know your business. We help you with the technology.',
  pioneer:
    'BARUCH Hostal, in Buritaca, Colombia, is Andario Hospitality’s pioneering property and one of the first real settings where Andario Booking Engine is evolving.',
  startTitle: 'What do we need to begin?',
  startNote: 'Andario walks through this with you. It is not an automatic setup.',
  startSteps: [
    { title: 'Get to know the property', body: 'What kind of place you run.' },
    { title: 'See how you take bookings today', body: 'WhatsApp, OTAs, the front desk, or a mix.' },
    { title: 'Identify the units', body: 'Rooms, beds or whole units.' },
    { title: 'Set rates and rules', body: 'Prices and the conditions of your operation.' },
    { title: 'Choose the direct channel', body: 'Today, the starting point is the website.' },
    { title: 'Try the process', body: 'We walk through a sample reservation.' },
    { title: 'Put it to work', body: 'The channel is ready to use.' },
  ],
  finalTitle: 'Want to see how it would work for your property?',
  finalBody:
    'Tell us what kind of property you have, how you take bookings today and what you would like to improve. We show you how Andario Booking Engine could fit.',
  finalMicro: 'No commitment. First we understand your property.',
};
