import type { ConnectContent, FaqItem } from '@/content/types';

export const connectFaqsEn: FaqItem[] = [
  {
    q: 'What is Andario Connect?',
    a: 'A communication and automation layer for accommodations. It connects conversations with the commercial journey and, when it fits, with booking.',
  },
  {
    q: 'Does it work with WhatsApp?',
    a: 'Yes, according to the channel setup and the capabilities available. WhatsApp is the channel. Connect is the layer that organizes the communication.',
  },
  {
    q: 'Is it a chatbot?',
    a: 'It can include agreed replies and flows, but the service is wider: organizing communication and placing it inside the guest journey.',
  },
  {
    q: 'Can it answer frequent questions?',
    a: 'Yes, when those questions and replies are part of the scope.',
  },
  {
    q: 'Can it reply automatically?',
    a: 'It can automate replies and paths that have been defined. It does not answer everything on its own.',
  },
  {
    q: 'Can it send a guest toward a booking?',
    a: 'It can point someone to the booking channel. Availability, rates and the reservation live in Andario Booking Engine when that piece is part of the journey. Completing the booking inside the chat is a planned evolution, not a live feature on this page.',
  },
  {
    q: 'What is the difference between Connect and Booking Engine?',
    a: 'Connect organizes communication. Booking Engine manages availability, rates, inventory and the reservation, according to the engine’s capabilities.',
  },
  {
    q: 'Can it capture interested people?',
    a: 'Yes, when the flow and the setup allow it. It is not a CRM.',
  },
  {
    q: 'Can it follow up?',
    a: 'It can be part of the scope, with relevant messages and within the channel’s rules.',
  },
  {
    q: 'Can it send reminders?',
    a: 'It can be part of the scope. This page does not publish a fixed list of notices the product sends today.',
  },
  {
    q: 'Can it send confirmations?',
    a: 'It can be part of the scope, according to the actions and setup available.',
  },
  {
    q: 'Can it replace a person?',
    a: 'No. It helps with repetitive work. Complex situations still need someone on the team.',
  },
  {
    q: 'Can I automate every conversation?',
    a: 'That is neither wise nor always possible. Automation is used where it helps. Human judgment stays where it matters.',
  },
  {
    q: 'Do I need Andario Booking Engine?',
    a: 'No. Connect can organize communication without the engine. An integration extends the journey when it is available and in scope.',
  },
  {
    q: 'Do I need Andario Web?',
    a: 'No. The website and Connect complement each other, and they are contracted separately.',
  },
  {
    q: 'Can I keep using WhatsApp as I do now?',
    a: 'Yes. It depends on how the channel is configured and which automations are agreed.',
  },
  {
    q: 'Can it connect to Instagram or Facebook?',
    a: 'It is not presented as a live integration. It can be part of a planned evolution.',
  },
  {
    q: 'Does Andario Connect include artificial intelligence?',
    a: 'An AI assistant is a planned evolution. This page does not present it as an available feature.',
  },
  {
    q: 'Can the AI invent availability?',
    a: 'It must not. In that evolution, availability answers would have to consult authorized sources and, when it applies, the Booking Engine.',
  },
  {
    q: 'Can it send messages automatically?',
    a: 'Yes, in defined flows and within the channel’s policies. It is not a bulk-messaging tool.',
  },
  {
    q: 'How is guest information looked after?',
    a: 'The implementation should keep data to what the flow needs, protect access and credentials, and follow the privacy policy. This is not a certification or a legal opinion.',
  },
  {
    q: 'Are conversations sent to Google Analytics?',
    a: 'No. Conversation content and personal data are not sent to analytics. Only page events, without names, phone numbers or messages.',
  },
  {
    q: 'Can I contract Connect on its own?',
    a: 'Yes. Andario services are contracted separately.',
  },
  {
    q: 'What do I need to start?',
    a: 'Property details, the questions that repeat, how you reply today, the WhatsApp channel and what you want to organize.',
  },
  {
    q: 'How do I request information?',
    a: 'Through the contact form, WhatsApp or the buttons on this page. A conversation does not lock you into a contract.',
  },
];

export const connectEn: ConnectContent = {
  support:
    'WhatsApp can be one of a property’s main points of contact. Andario Connect helps structure questions, replies, follow-up and guidance toward a booking, so communication becomes part of the guest’s digital journey.',
  audienceLine: 'Automate what repeats. Keep human judgment where it matters.',
  primaryCta: 'Explore Andario Connect',
  problemCta: 'I want to organize my conversations',
  bookingCta: 'See how communication and bookings connect',
  talkCta: 'Talk with Andario',
  whatsappCta: 'Write on WhatsApp',
  scopeLabel: 'The final scope is defined by the property’s needs and the capabilities available.',
  exampleLabel: 'Conceptual example. Not a real conversation and not a live integration.',
  roadmapLabel: 'Planned evolution',
  heroCaption: 'A guest asks. Connect points the way. Availability and the booking stay in the engine, when that piece is part of the journey.',
  heroGuest: 'Guest',
  heroGuestMsg: 'Do you have availability tomorrow?',
  heroReply: 'Connect',
  heroReplyMsg: 'Yes. I can help you with the next step.',
  heroAction: 'Point toward availability',
  heroEngine: 'Booking Engine',
  heroAvailability: 'Availability',
  heroReserve: 'Booking',
  questions: [
    'Do you have availability?',
    'How much does it cost?',
    'What is included?',
    'Where are you?',
    'How do I get there?',
    'Do you allow pets?',
    'Do you have private rooms?',
    'Can I book on WhatsApp?',
  ],
  problems: [
    { title: 'The same questions, again and again', body: 'The team answers by hand what has already been explained many times.' },
    { title: 'Replies that do not match', body: 'Several people can describe the same thing in different ways.' },
    { title: 'Interest with no continuation', body: 'A question stays open and nobody picks the thread back up.' },
    { title: 'The chat, apart from the booking', body: 'The conversation and the booking process do not meet.' },
    { title: 'Information that gets lost', body: 'Dates, questions and agreements are scattered across messages.' },
    { title: 'Time spent on what repeats', body: 'The team handles tasks that could have a stable reply.' },
  ],
  problemNote: 'Not every property lives this. These are situations that can appear when WhatsApp carries a large share of guest care.',
  journeyTitle: 'WhatsApp can be a door into the guest’s journey.',
  journeySteps: ['Discover', 'Ask', 'WhatsApp', 'Information', 'Guidance', 'Booking', 'Confirmation', 'Follow-up'],
  journeyNote: 'Connect aims to join these stages. Not every question becomes a booking.',
  whatTitle: 'What is Andario Connect?',
  whatBody:
    'A communication and automation layer for accommodations. It connects conversations with the commercial and booking journey. It can help answer frequent questions, record interested people, point toward a booking and accompany with confirmations, reminders or follow-up, according to scope.',
  whatNote: 'The aim is not to automate for its own sake. It is to reduce repetitive work and make communication more consistent.',
  hubCaption: 'Questions, guidance and follow-up meet in more orderly communication. The diagram shows relationships, not a closed product.',
  hubColumns: [
    { title: 'Questions', points: ['Frequent questions', 'Basic information', 'A first reply'] },
    { title: 'Bookings', points: ['Guidance', 'Booking channel', 'Next step'] },
    { title: 'Follow-up', points: ['Continuity', 'Reminders', 'After the question'] },
  ],
  autoTitle: 'Automate what repeats. Do not automate what needs judgment.',
  autoBody: 'A conversation can be split between what repeats and what needs a person. That split is agreed. The system does not classify every case on its own.',
  autoRepeatTitle: 'Often ready to organize',
  autoRepeat: ['Frequent questions', 'Basic information', 'Hours', 'Location', 'Services', 'Instructions', 'Confirmation messages', 'Reminders', 'Follow-up'],
  autoHumanTitle: 'Often needs a person',
  autoHuman: ['Special cases', 'Complex requests', 'Changes outside the rules', 'Sensitive situations', 'Commercial decisions', 'Exceptions'],
  autoNote: 'We do not claim that every message is detected on its own. The team decides what is automated.',
  includesTitle: 'What it can include',
  includesIntro: 'Each piece is agreed. Not every project includes every activity.',
  whatLabel: 'What it is',
  purposeLabel: 'What it is for',
  exampleCardLabel: 'Example of use',
  groups: [
    { title: 'WhatsApp Business', what: 'The property’s messaging channel.', purpose: 'Bring that channel closer to the digital journey.', example: 'A question that today lives only in the chat can have a clear next step.' },
    { title: 'Frequent questions', what: 'Stable replies to what people ask often.', purpose: 'Give the same useful information without rewriting it each time.', example: 'Arrival time, how to get there, or what the stay includes.' },
    { title: 'Automated replies', what: 'Messages defined for moments that repeat.', purpose: 'Lower manual work where the answer is already clear.', example: 'A greeting with the options people ask for most, within what was agreed.' },
    { title: 'Capturing interest', what: 'A record of intent when the flow allows it.', purpose: 'A question does not have to live only in someone’s memory of the chat.', example: 'Someone asks about later dates and can be recognized for a follow-up.' },
    { title: 'Guidance toward a booking', what: 'A pointer to the booking channel that applies.', purpose: 'Keep the conversation separate from availability logic.', example: 'After the dates, the person continues to the engine, if the property uses it.' },
    { title: 'Confirmations', what: 'Information after a relevant action, when it is configured.', purpose: 'Let the guest know what has already happened.', example: 'A message after a booking, if that notice is in scope.' },
    { title: 'Reminders', what: 'A notice before an agreed stage.', purpose: 'A step does not have to depend on remembering it by hand.', example: 'A message before arrival, if the flow and the channel allow it.' },
    { title: 'Follow-up', what: 'Continuing a conversation that did not close.', purpose: 'Pick the interest back up without losing the thread.', example: 'Someone said they would check, and later receives a relevant message.' },
  ],
  flowTitle: 'One conversation, step by step.',
  flow: [
    { who: 'Guest', line: 'Hello, I want to know if you have availability.' },
    { who: 'Connect', line: 'Of course. Which dates do you need?' },
    { who: 'Guest', line: 'From the 12th to the 15th.' },
    { who: 'Connect', line: 'I will point you toward availability.' },
    { who: 'Booking Engine', line: 'Availability' },
    { who: 'Guest', line: 'Chooses an option' },
    { who: 'Booking', line: 'The reservation is managed in the engine.' },
    { who: 'Confirmation', line: 'The guest receives the next step, if that message is configured.' },
  ],
  flowNote: 'Conceptual example. These steps are not all connected in production. Booking inside WhatsApp is a planned evolution.',
  bookingTitle: 'Connect communicates. Booking Engine manages the reservation.',
  bookingBody:
    'Connect organizes the conversation and the intent. The engine checks availability, calculates rates and creates the reservation, according to its capabilities. Connect does not copy that logic.',
  bookingConnect: ['Communication', 'Questions', 'Guidance'],
  bookingEnginePoints: ['Availability', 'Rates', 'Inventory', 'Reservation'],
  bookingNote: 'Recording that someone wrote on WhatsApp is not a live integration. Completing the booking inside the chat is not presented as a current feature.',
  webTitle: 'Your website attracts. WhatsApp continues the conversation.',
  webBody: 'Andario Web presents the property. Connect can continue when someone writes. They are different pieces and they are contracted separately.',
  webSteps: ['Andario Web', 'Information', 'Interest', 'WhatsApp', 'Andario Connect', 'Guidance', 'Booking Engine'],
  webNote: 'An Andario website is not required in order to talk about Connect.',
  checkTitle: 'It helps to see first where conversations get stuck.',
  checkBody: 'Digital Check can show communication friction before anything is automated. Connect then works on the areas that are defined.',
  checkSteps: ['Digital Check', 'Diagnosis', 'Friction', 'Connect', 'Structure'],
  checkNote: 'The diagnosis is not a required step.',
  growthTitle: 'Conversations also leave signals.',
  growthBody: 'Andario Growth can later read events from the digital presence, according to what is instrumented. It does not read the private text of chats.',
  growthPoints: ['Clicks toward WhatsApp', 'Page actions', 'Traffic source', 'Booking events that are available'],
  growthNote: 'We do not promise complete attribution or an analysis of conversation text.',
  leadTitle: 'Not every conversation becomes a booking right away.',
  leadBody: 'Sometimes a person asks for information, checks distant dates or needs time. Connect can help keep that interest orderly for a follow-up, when the flow allows it.',
  leadSteps: ['Visitor', 'Question', 'Interest', 'Record', 'Follow-up', 'Booking, if it follows'],
  leadExamples: ['Asks for information', 'Asks about later dates', 'Asks about a group', 'Asks about an experience', 'Asks for a special condition'],
  leadNote: 'It is not a CRM. We do not promise that every interested person books.',
  followTitle: 'A conversation that did not close today does not have to disappear.',
  followBody: 'Follow-up picks a thread back up with a relevant message. It is not a sequence of intrusive notices.',
  followSteps: ['Day 1 · Question', 'Day 1 · Information', 'Later · Follow-up', 'Decision', 'Booking, if the person continues'],
  followNote: 'Every automatic message should respect consent, the channel’s rules and the rules that apply.',
  confirmTitle: 'Confirmations',
  confirmBody: 'They help inform the guest after a relevant action, when that notice is configured. This page does not publish a fixed catalog of events.',
  reminderTitle: 'Reminders',
  reminderBody: 'They can help an agreed step not depend on memory. They enter the scope only if the flow and the channel allow it.',
  messagesNote: 'We do not invent notices the product does not yet support for that property.',
  faqLayerTitle: 'Frequent questions can be a first layer of attention.',
  faqLayer: ['Question', 'Frequent reply', 'Was it resolved?', 'Yes: the person continues', 'No: they can talk with someone'],
  faqLayerNote: 'An automatic reply should not close the door when a person is needed.',
  humanTitle: 'Automation does not replace hospitality. It accompanies it.',
  humanBody: 'A guest can receive a stable reply and, when the case needs it, continue with someone on the team. Connect helps the team. It does not replace it.',
  humanAuto: ['Basic questions', 'Information', 'Reminders'],
  humanPerson: ['Special situations', 'Exceptions', 'Decisions'],
  humanNote: 'Hospitality stays human.',
  aiTitle: 'Planned evolution: an assistant that understands context more clearly.',
  aiBody:
    'Later, Andario Connect contemplates an assistant able to talk more naturally. It is not available today. When it exists, it will have to consult the property’s authorized sources and, when it applies, the Booking Engine for availability and reservations.',
  aiRules: ['Do not invent availability', 'Do not invent rates', 'Do not invent reservations', 'Do not invent policies', 'Do not invent property details'],
  aiNote: 'This section describes a planned evolution. It is not a current feature.',
  securityTitle: 'Communication with your guests also needs care.',
  securityBody: 'Organizing WhatsApp means handling people’s data. The work should ask only for what is needed and protect access.',
  securityPoints: [
    'Data limited to what the flow needs',
    'Control of who can access it',
    'Protected credentials',
    'Providers that fit the channel',
    'Consent when it is required',
    'The site’s privacy policy',
    'No extra sensitive data',
    'No conversations or personal data in analytics',
  ],
  securityNote: 'This is not a certification or a claim of complete legal compliance. A legal review, when one is needed, is separate.',
  channelTitle: 'WhatsApp is the channel. Connect is the layer.',
  channelBody: 'WhatsApp Business belongs to its own platform. Andario does not own WhatsApp. Connect adds the communication logic that is agreed on top of that channel.',
  channelSteps: ['WhatsApp', 'Channel', 'Andario Connect', 'Communication logic', 'Commercial journey'],
  channelNote: 'Continuing to use the channel depends on its setup and on the platform’s rules.',
  otherChannelsTitle: 'Instagram and Facebook',
  otherChannelsBody: 'They are not presented as live integrations. They can be part of a planned evolution, not of what this page offers today.',
  casesTitle: 'Illustrative situations',
  cases: [
    { title: 'A frequent question', quote: 'What time is check-in?', steps: ['Question', 'Frequent reply', 'A person informed'] },
    { title: 'Availability', quote: 'Do you have a room this weekend?', steps: ['Question', 'Guidance', 'Booking Engine', 'Booking, if they continue'] },
    { title: 'Property information', quote: 'Do you have a restaurant?', steps: ['Question', 'Information', 'Next step'] },
    { title: 'Follow-up', quote: 'I will check and let you know.', steps: ['Interested person', 'Follow-up', 'The conversation resumes'] },
    { title: 'After booking', quote: 'The reservation already exists.', steps: ['Booking', 'Confirmation', 'Useful information', 'Reminder'] },
  ],
  casesNote: 'Illustrative examples. They are not a client’s conversations and not measured results.',
  ownerTitle: 'What can change for the person running the property',
  owner: [
    { title: 'Less repetitive work', body: 'Interactions that repeat can have an agreed reply.' },
    { title: 'More consistent communication', body: 'The same question can receive the same useful information.' },
    { title: 'More continuity', body: 'The journey does not depend only on remembering every chat.' },
    { title: 'A clearer link to booking', body: 'The conversation can point toward the booking channel.' },
    { title: 'More order', body: 'Communication enters the strategy, instead of staying in a separate inbox.' },
    { title: 'A base that can grow', body: 'The structure can expand with the property, according to scope.' },
  ],
  teamTitle: 'It is also meant for the person who replies.',
  team: ['Fewer repeated questions', 'Clearer context for the next step', 'Better continuity between shifts', 'A person steps in where it truly matters'],
  teamNote: 'Connect helps the team. It does not propose replacing it.',
  whoTitle: 'For properties where WhatsApp is already part of the business.',
  whoTypes: ['Hostels', 'Small hotels', 'Inns', 'Holiday apartments', 'Aparthotels', 'Cabins', 'Villas', 'Rural stays', 'Other independent properties'],
  whoFit: ['Many repeated questions arrive.', 'WhatsApp is an important channel.', 'Conversations get lost.', 'Follow-up is manual.', 'Several people reply.', 'They want to join communication and booking.'],
  whenTitle: 'When it tends to make sense',
  when: [
    'You receive the same questions almost every day.',
    'Many people ask before they book.',
    'The team answers everything by hand.',
    'Conversations get lost.',
    'Interested people get no continuation.',
    'You want to point questions toward your booking channel.',
    'You want an automation layer, not a bot that does everything.',
  ],
  notTitle: 'What Andario Connect is not',
  not: [
    { title: 'Not only a chatbot', body: 'It is a communication layer inside the ecosystem.' },
    { title: 'Not a replacement for hospitality', body: 'What is complex can still need a person.' },
    { title: 'Not the Booking Engine', body: 'The engine manages availability, rates, inventory and reservations.' },
    { title: 'Not a booking guarantee', body: 'It can organize the journey. A booking depends on more factors.' },
    { title: 'Not spam', body: 'Messages have to be relevant and respect the channel.' },
    { title: 'Not an available AI assistant', body: 'That piece is a planned evolution.' },
    { title: 'Not automating everything', body: 'Automation is used where it helps. Judgment stays where it matters.' },
  ],
  processTitle: 'From scattered conversations to more structured communication.',
  process: [
    { title: 'Understand', body: 'Channels, questions, processes and friction.' },
    { title: 'Structure', body: 'Frequent questions, replies, flows and criteria.' },
    { title: 'Connect', body: 'The journey with the website and, when it applies, with the Booking Engine.' },
    { title: 'Automate', body: 'Only the automations that were agreed.' },
    { title: 'Test', body: 'Replies, paths, errors and exceptions.' },
    { title: 'Measure', body: 'Interactions and available events, without the text of the chats.' },
    { title: 'Evolve', body: 'We adjust the flows and review new capabilities.' },
  ],
  receiveTitle: 'A communication layer designed around the operation.',
  receive: [
    'Defined frequent questions',
    'A structure of replies',
    'Agreed conversation flows',
    'WhatsApp Business, according to the channel',
    'Capture of interest, if the flow allows it',
    'Guidance toward booking',
    'Confirmations and reminders, if they are in scope',
    'Follow-up',
    'Page measurement events, without personal data',
    'A basic operating guide',
  ],
  receiveNote: 'The final scope is defined by the needs and the capabilities available. It does not include an AI assistant or a booking inside the chat.',
  ecosystemTitle: 'Connect talks. The other pieces do something else.',
  ecosystemSteps: ['Google or social', 'Andario Web', 'WhatsApp', 'Andario Connect', 'Question or interest', 'Booking Engine', 'Reservation', 'Follow-up', 'Growth'],
  ecosystemNote: 'This is a reading of the ecosystem, not a required package. Each service is contracted separately.',
  lifecycleTitle: 'The life of a conversation',
  lifecycle: ['Discovery', 'Question', 'Reply', 'Interest', 'Guidance', 'Booking', 'Confirmation', 'Stay', 'Follow-up'],
  boundaryAutoTitle: 'Can be organized',
  boundaryAuto: ['Frequent questions', 'Basic information', 'Hours', 'Location', 'Reminders', 'Confirmations', 'Follow-up'],
  boundaryHumanTitle: 'Needs a person',
  boundaryHuman: ['Exceptions', 'Special cases', 'Complex changes', 'Sensitive situations', 'Commercial decisions'],
  boundaryNote: 'This split is a working guide. It is not an automatic classification.',
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal is the pioneer property of Andario Hospitality. We do not publish conversation volume, automation or bookings from its communication.',
  finalTitle: 'Make your conversations part of your digital strategy.',
  finalBody: 'Organize frequent questions, automate repetitive tasks and connect communication with your guest’s journey.',
  finalNote: 'Automate what repeats. Keep what is human where it matters.',
};
