import type { ContentPage, FaqItem } from '@/content/types';

export const contentFaqsEn: FaqItem[] = [
  {
    q: 'What is Andario Content?',
    a: 'The photography and content service for accommodations. It helps show and explain the property, its spaces, services, experiences and destination.',
  },
  {
    q: 'Does Andario take the photographs?',
    a: 'Production can be coordinated according to the city and the scope. There is not an in-house photography team in every city. If a third party shoots, they are not an Andario employee.',
  },
  {
    q: 'Is photography always included?',
    a: 'No. It is included only when it is part of that property’s scope.',
  },
  {
    q: 'Can you work with photographs I already have?',
    a: 'Yes. Organizing and preparing existing material can be part of the scope.',
  },
  {
    q: 'Do you write website copy?',
    a: 'Yes, according to what is agreed. The words explain the property. They do not promise a Google ranking.',
  },
  {
    q: 'Do you also create social content?',
    a: 'It can be included, adapted to each channel. That is not the same as running the accounts every day.',
  },
  {
    q: 'Do you create video?',
    a: 'Short video can be included, according to scope. Not every project includes it.',
  },
  {
    q: 'Do you create destination content?',
    a: 'It can be part of the service when the information is relevant and can be verified. Place details are not invented.',
  },
  {
    q: 'Do you manage social accounts on an ongoing basis?',
    a: 'That is not assumed. Posting and replying every day is a different scope and is defined separately, if it applies.',
  },
  {
    q: 'Can you organize the gallery?',
    a: 'Yes. Selection and order so the photos tell the property, rather than sitting in a loose folder.',
  },
  {
    q: 'Can you prepare images for the website?',
    a: 'Yes, according to scope: format, weight, size and alternative text when it is needed. We do not promise a specific speed without measuring it.',
  },
  {
    q: 'Does the content help SEO?',
    a: 'It can supply useful material for a visibility strategy. It does not guarantee a position on Google.',
  },
  {
    q: 'Does Andario Content include SEO?',
    a: 'Content can create material for Visibility. SEO and visibility work belongs to Andario Visibility.',
  },
  {
    q: 'What is the difference from Andario Web?',
    a: 'The website builds the structure of the site. Content produces and organizes the material the property communicates with.',
  },
  {
    q: 'What is the difference from Visibility?',
    a: 'Content creates and organizes material. Visibility works on the property’s ability to be found.',
  },
  {
    q: 'How does it relate to Connect?',
    a: 'The content can later be the base for replies and messages, when that piece exists and the scope allows it.',
  },
  {
    q: 'How does it relate to Booking Engine?',
    a: 'Content helps someone understand the property before they book. The engine manages the booking logic.',
  },
  {
    q: 'Do I need to contract every service?',
    a: 'No. They are contracted separately.',
  },
  {
    q: 'Can I start with Content alone?',
    a: 'Yes.',
  },
  {
    q: 'What do I need to start?',
    a: 'Property details, what you want to show, the material you already have and what is missing.',
  },
  {
    q: 'Can you work in any city?',
    a: 'Photography production depends on location and scope. A conversation does not require a shoot on site.',
  },
  {
    q: 'Does the content guarantee more bookings?',
    a: 'No. It can improve how the property is presented. A booking depends on more factors.',
  },
  {
    q: 'Can you create content on a recurring basis?',
    a: 'It can be defined if it is part of the proposal. It is not unlimited monthly production.',
  },
  {
    q: 'Can I use the content on several channels?',
    a: 'Yes, according to the rights, formats and scope that were agreed. The same file is not published unchanged everywhere.',
  },
  {
    q: 'How do I request information?',
    a: 'Through the contact form, WhatsApp or the buttons on this page. A conversation does not lock you into a contract.',
  },
];

const can = 'Can be used';
const scope = 'According to scope';

export const contentPageEn: ContentPage = {
  support:
    'Photographs, words and the way a property is presented shape how people imagine the stay before they book. Andario Content helps create useful, coherent material to show the property, its spaces, services, experiences and destination.',
  audienceLine: 'Content made for accommodations, not for posting because a calendar says so.',
  primaryCta: 'Improve my content',
  problemCta: 'Improve how my property looks',
  photoCta: 'I want to improve my photographs',
  scopeCta: 'Explore Andario Content',
  talkCta: 'Talk with Andario',
  whatsappCta: 'Write on WhatsApp',
  scopeLabel: 'The final scope is defined by what the property needs.',
  exampleLabel: 'Conceptual example. Not a client’s material and not a real photograph.',
  heroCaption: 'Photos, words and video meet in the experience a guest imagines before they arrive.',
  heroLayers: ['Property', 'Photos', 'Words', 'Video', 'Experience', 'Guest'],
  questions: [
    { q: 'What is the place really like?', a: 'Photographs of what exists.' },
    { q: 'What are the rooms or units like?', a: 'A gallery and information.' },
    { q: 'What will I find?', a: 'Words and real services.' },
    { q: 'What can I do there?', a: 'Experiences and destination, when they can be backed up.' },
    { q: 'Does the place fit me?', a: 'Clear information.' },
    { q: 'Can I trust it?', a: 'A coherent presentation.' },
  ],
  decisionSteps: ['Question', 'Content', 'Understanding', 'Trust', 'Decision'],
  decisionNote: 'Content helps someone imagine the stay. It does not decide the booking on its own.',
  whatTitle: 'What is Andario Content?',
  whatBody:
    'Andario Hospitality’s photography and content service. We build visual and editorial material to present the property, its spaces, services, experiences and destination. It is made for hospitality and travel, not for a generic brand.',
  whatNote: 'The aim is not to produce for its own sake. It is to create material that can be used coherently on the website and at other points of contact.',
  anatomyCaption: 'The property, the people and the destination are told with photography, words, video and a plan. No single piece is the whole service.',
  anatomyColumns: [
    { title: 'Property', points: ['Spaces', 'Services', 'Identity'] },
    { title: 'People', points: ['Experience', 'Clarity', 'Trust'] },
    { title: 'Destination', points: ['Context', 'Place', 'How to arrive'] },
  ],
  anatomyParts: ['Photography', 'Words', 'Video', 'Destination', 'Planning'],
  anatomyEquals: 'A content ecosystem',
  photoTitle: 'Photographs do more than show rooms. They help someone anticipate a stay.',
  photoBody: 'A hospitality photograph can help someone understand space, scale, atmosphere and detail. Services and experiences are shown only when the property actually has them.',
  photoCategories: [
    { title: 'Rooms or units', body: 'The place where people sleep, shown clearly.' },
    { title: 'Shared areas', body: 'How the property is lived in, if those areas exist.' },
    { title: 'Services', body: 'What the property really offers, without invented features.' },
    { title: 'Details', body: 'Elements that help the identity be recognized.' },
    { title: 'Experiences', body: 'Moments that can be shown when they apply.' },
    { title: 'Setting', body: 'The place around the property, when it helps and can be supported.' },
  ],
  photoNote: 'There is no fixed catalog of a pool, a restaurant or activities. What enters is what the property has.',
  coordinationTitle: 'Photography is coordinated. A crew in every city is not promised.',
  coordinationBody: 'According to location and scope, the work can include planning, a shot list, coordination, selection and preparation for publishing.',
  coordinationPoints: ['Planning', 'Shot list', 'Coordination', 'Selection', 'Organization', 'Ready to publish'],
  coordinationNote: 'If a third party shoots, they are not presented as Andario staff.',
  optimizeTitle: 'A good photograph also needs to be ready for the internet.',
  optimizeBody: 'Preparing an image can include format, weight, size, a useful name and alternative text when it is needed. Also its place in the gallery.',
  optimizeSteps: ['Source photo', 'Selection', 'Preparation', 'Website, social or gallery', 'Digital use'],
  optimizeNote: 'We do not claim a speed improvement without measuring it.',
  galleryTitle: 'A gallery should tell a story, not act as a folder of photos.',
  galleryBody: 'Order can help someone walk through the place: arrival, space, room, services, experience and destination. There is no single order for every property.',
  gallerySteps: ['Arrival', 'Space', 'Room', 'Services', 'Experience', 'Destination'],
  galleryNote: 'The sequence follows what the property can actually show.',
  copyTitle: 'Images show. Words explain.',
  copyBody: 'Copy can help say who the property is, what it offers, where it is and what is worth knowing before writing or booking.',
  copyPoints: ['Identity', 'Offer', 'Units', 'Services', 'Location', 'Experiences', 'Policies', 'Frequent questions', 'Destination'],
  copyPrinciple: 'People come first. Search enters when there is a visibility strategy, without a promised ranking.',
  genericLabel: 'Generic',
  genericExample: 'A comfortable room with excellent services.',
  usefulLabel: 'More useful',
  usefulExample: 'A private room meant for resting after a day in the destination.',
  videoTitle: 'Some experiences a photograph cannot quite tell.',
  videoBody: 'A short video can show atmosphere, a walk-through or a moment of the place. It is included only when the scope includes it.',
  videoPoints: ['A short clip', 'Atmosphere', 'A walk-through', 'A moment', 'Destination'],
  videoNote: 'Short video according to scope. It is not unlimited film production.',
  destinationTitle: 'A property does not exist apart from the place around it.',
  destinationBody: 'It can be useful to tell the destination, how to arrive and the context, when that information exists and can be checked.',
  destinationPoints: ['Destination', 'Setting', 'How to arrive', 'Activities that can be supported', 'Context'],
  destinationNote: 'Place information is not invented, and nothing is published that the property cannot stand behind.',
  socialTitle: 'One property, several points of contact.',
  socialBody: 'Central material can be adapted for the website, social channels and WhatsApp. Each format asks for a different cut.',
  socialChannels: ['Central content', 'Website', 'Instagram', 'Facebook', 'WhatsApp'],
  socialNote: 'The same file is not published unchanged on every platform.',
  editorialTitle: 'Publishing with a reason is different from publishing out of obligation.',
  editorialSteps: ['Goal', 'Theme', 'Format', 'Channel', 'Moment', 'Publication', 'Learning'],
  editorialCategories: ['Property', 'Services', 'Experiences', 'Destination', 'Recommendations', 'Questions', 'Stories', 'Season'],
  editorialNote: 'We do not build a generic calendar without knowing the property.',
  relations: [
    {
      title: 'Content feeds the digital home.',
      body: 'Andario Web builds the structure. Content helps fill it with material that represents the property.',
      steps: ['Andario Content', 'Photos, words and video', 'Andario Web', 'Presentation'],
      note: 'An Andario website is not required in order to work on content.',
      hrefLabel: 'Andario Web',
    },
    {
      title: 'Useful content is also part of visibility.',
      body: 'Words, destination and questions can feed Andario Visibility. Publishing does not guarantee a Google ranking.',
      steps: ['Content', 'Useful information', 'Intent', 'Visibility', 'Discovery'],
      note: 'Visibility is the SEO and visibility service. Content does not replace it.',
      hrefLabel: 'Andario Visibility',
    },
    {
      title: 'A good reply also needs content behind it.',
      body: 'Connect can later use the property’s information to guide a conversation, when that piece exists.',
      steps: ['A guest’s question', 'Connect', 'Content', 'A useful reply'],
      note: 'The example is conceptual. It does not claim that every chat already consults a content library.',
      hrefLabel: 'Andario Connect',
    },
    {
      title: 'Before booking, a guest needs clear information.',
      body: 'Content helps someone understand the place. Andario Booking Engine manages availability, rates and the reservation.',
      steps: ['Content', 'Information', 'Trust', 'Booking Engine', 'Reservation'],
      note: 'Content does not control the booking.',
      hrefLabel: 'Andario Booking Engine',
    },
    {
      title: 'Content can also learn from signals.',
      body: 'Andario Growth can later read interactions from the digital presence, if measurement exists. It does not read private conversations.',
      steps: ['Content', 'Publication', 'Interaction', 'Data', 'Growth', 'Learning'],
      note: 'We do not promise complete attribution for every piece.',
      hrefLabel: 'Andario Growth',
    },
  ],
  beforeLabel: 'Loose material',
  before: ['Mixed photos', 'Generic copy', 'A gallery without order', 'Isolated pieces', 'Improvised posts'],
  afterLabel: 'With a content line',
  after: ['Selected photographs', 'Useful words', 'A gallery with sense', 'Reusable material', 'An editorial plan', 'Destination context'],
  beforeNote: 'Conceptual example. Not every property starts this way.',
  matrixTitle: 'One piece can live in more than one place.',
  matrixCenter: 'Content',
  matrixAround: ['Website', 'Social', 'WhatsApp', 'Destination', 'Experiences'],
  matrixColumns: ['Website', 'Social', 'WhatsApp', 'Visibility'],
  matrixRows: [
    { name: 'Photographs', cells: [can, can, can, can] },
    { name: 'Words', cells: [can, can, can, can] },
    { name: 'Questions', cells: [can, can, can, can] },
    { name: 'Destination', cells: [can, can, can, can] },
    { name: 'Short video', cells: [can, can, scope, '—'] },
  ],
  matrixNote: 'This is a reading of possible reuse. It is not an automatic integration and not a promise to publish on every channel.',
  includesTitle: 'What it can include',
  includesIntro: 'Each piece is agreed. Not every project includes every activity.',
  whatLabel: 'What it is',
  purposeLabel: 'What it is for',
  exampleCardLabel: 'Example',
  groups: [
    { title: 'Photography coordination', what: 'A plan and coordination of production, according to city and scope.', purpose: 'Images of the real property.', example: 'A shot list of the units that actually exist.' },
    { title: 'Image preparation', what: 'Photos ready for the website and other channels.', purpose: 'They look right and weigh what they need to.', example: 'A selection with size and alternative text.' },
    { title: 'Website copy', what: 'Words that explain the property.', purpose: 'Someone understands the offer.', example: 'A unit description that says what it is for, not only that it is comfortable.' },
    { title: 'Social content', what: 'Adaptation to social formats.', purpose: 'A line, not an obligation to post.', example: 'A piece of the same space, cut for the channel.' },
    { title: 'Short video', what: 'A brief piece, if it is in scope.', purpose: 'Atmosphere or a walk-through when a photo is not enough.', example: 'A clip of the place, not unlimited production.' },
    { title: 'Destination content', what: 'Information about the place that can be checked.', purpose: 'Sit the property in its context.', example: 'How to arrive, if that detail can be supported.' },
    { title: 'Gallery preparation', what: 'Selection and order.', purpose: 'The visual visit makes sense.', example: 'From arrival to the room, according to what should be shown.' },
    { title: 'Editorial plan', what: 'Themes, formats and moments.', purpose: 'Publishing with a reason.', example: 'A seasonal line, not an empty calendar.' },
  ],
  notIncludedTitle: 'What is not included just because you start a conversation.',
  notIncludedBody: 'Content is defined by what that property needs. These pieces are not assumed.',
  notIncluded: [
    'A full photo shoot',
    'A large professional video',
    'Ongoing social management',
    'Unlimited monthly production',
    'Community management',
    'Aerial photography',
    'Production with models',
    'Travel',
    'An in-house film crew in every city',
    'A post every day',
  ],
  notIncludedNote: 'If one of them is needed, it enters the scope that is agreed.',
  processTitle: 'From the material you have to content ready to communicate.',
  process: [
    { title: 'Understand', body: 'Property, identity, audience, destination and goals.' },
    { title: 'Plan', body: 'What must be shown and what material is missing.' },
    { title: 'Produce or gather', body: 'Photography, words, video or other material, according to scope.' },
    { title: 'Select', body: 'We keep what is most useful.' },
    { title: 'Adapt', body: 'Formats for the website, social channels and others.' },
    { title: 'Deliver', body: 'The material is organized for use.' },
    { title: 'Evolve', body: 'It is adjusted from needs and the signals available.' },
  ],
  receiveTitle: 'Content ready to represent the property more clearly.',
  receive: [
    'A photo selection, if it is in scope',
    'Images prepared for publishing',
    'Words',
    'A gallery structure',
    'Social pieces, if they are agreed',
    'Short videos, if they are agreed',
    'Destination content that can be verified',
    'An editorial line',
    'Organized files',
    'Recommendations for use',
  ],
  receiveNote: 'The final scope is defined with the property. It is not unlimited production.',
  whoTitle: 'For properties that want to show more clearly what they really offer.',
  whoTypes: ['Hostels', 'Small hotels', 'Inns', 'Holiday apartments', 'Aparthotels', 'Cabins', 'Villas', 'Rural stays', 'Other independent properties'],
  whoFit: ['The photos no longer represent the place.', 'There is material, but no one knows which to use.', 'The website has little to show.', 'The units are poorly explained.', 'Social has no line.', 'The destination is not told.', 'There is a large archive and little order.', 'They want a base that can be reused.'],
  whenTitle: 'When it tends to make sense',
  when: [
    'The photographs no longer show the property as it is today.',
    'You have photos and do not know which to publish.',
    'The website has little visual material.',
    'Rooms or units are poorly explained.',
    'Social posts have no line.',
    'You want to show experiences and destination.',
    'You want a reusable content library.',
    'You want to join the material with the website, visibility and communication.',
  ],
  notTitle: 'What Andario Content is not',
  not: [
    { title: 'Not only photography', body: 'There can also be words, video, destination, a gallery and a plan.' },
    { title: 'Not posting for its own sake', body: 'Each piece has to help show or explain.' },
    { title: 'Not unlimited community management', body: 'Ongoing social management is defined separately, if it applies.' },
    { title: 'Not a booking guarantee', body: 'It helps communication. A booking depends on more factors.' },
    { title: 'Not a library of generic photos', body: 'The material has to be of that property.' },
    { title: 'Not unlimited photography', body: 'Production depends on the scope.' },
    { title: 'Not a replacement for Visibility', body: 'Content creates and organizes. Visibility works on being found.' },
    { title: 'Not a replacement for the website', body: 'The website is the structure. Content supplies the material.' },
  ],
  authenticTitle: 'Showing what really exists also builds trust.',
  authenticBody: 'The presentation can be attractive and still faithful to what a person will find.',
  authenticPoints: [
    'Do not misleadingly alter what matters',
    'Do not use another property’s photos as if they were yours',
    'Do not invent services',
    'Do not show spaces that do not exist',
    'Do not publish what the property cannot stand behind',
  ],
  journeyTitle: 'Content works mostly before arrival.',
  journeySteps: ['Before traveling', 'Discover', 'Imagine', 'Compare', 'Decide', 'Book', 'Arrive'],
  journeyNote: 'Content does not control every stage. It helps the place be understood in the digital experience.',
  assetTitle: 'A good piece can live in more than one place.',
  assetSteps: ['One piece', 'Website', 'Social', 'WhatsApp', 'Archive', 'Later uses'],
  assetNote: 'It is adapted to the channel. The same format is not duplicated everywhere.',
  ecosystemTitle: 'Content creates the material. The other pieces do something else.',
  ecosystemSteps: ['Digital Check', 'Understand', 'Content', 'Create material', 'Web', 'Present', 'Visibility', 'Be found', 'Connect', 'Communicate', 'Booking Engine', 'Book', 'Growth', 'Measure'],
  ecosystemNote: 'This is a reading of the ecosystem, not a required package.',
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal is the pioneer property of Andario Hospitality. We do not publish bookings, traffic or its photographs as a results case.',
  finalTitle: 'Let the property look and read the way it deserves.',
  finalBody: 'Tell us what material you have today, what you want to improve and how you want to present the property. We can help you build useful content for the website, digital channels and communication.',
  finalNote: 'No generic content. Material made for your property.',
};
