import type { DigitalCheckContent, FaqItem } from '@/content/types';

export const digitalCheckFaqsEn: FaqItem[] = [
  {
    q: 'What is Digital Check?',
    a: 'A structured diagnosis of your property’s digital presence. We review the main touchpoints and turn the findings into a prioritized roadmap.',
  },
  {
    q: 'What does Digital Check look at?',
    a: 'Google presence, the website, SEO, social profiles, WhatsApp, OTAs, the booking journey, content and photography, user experience, analytics, competitive context and how those pieces relate.',
  },
  {
    q: 'What do I receive at the end?',
    a: 'A reading of the current situation, findings, opportunities, priorities, a roadmap and next steps. It is more than a list of observations.',
  },
  {
    q: 'Do I need a website to do a Digital Check?',
    a: 'Not necessarily. The diagnosis looks at the current situation, including pieces that do not exist yet.',
  },
  {
    q: 'Do I have to contract other Andario services afterwards?',
    a: 'No. The diagnosis guides the decision. Later services are contracted separately, with Andario, with your team or with another provider.',
  },
  {
    q: 'Does Digital Check guarantee more bookings?',
    a: 'No. It does not guarantee bookings, revenue, traffic or a search ranking. It gives a clearer view of the situation and what to do first.',
  },
  {
    q: 'Does Digital Check include SEO?',
    a: 'It reviews SEO-related aspects inside the diagnosis. That does not, by itself, include a full SEO implementation.',
  },
  {
    q: 'Do you review Booking.com, Airbnb or other OTAs?',
    a: 'Yes, when they are part of the property’s presence and there is enough information to review them. We do not assume access the property has not provided.',
  },
  {
    q: 'Do you review WhatsApp?',
    a: 'Yes. We can look at how it works as a contact point in the digital journey.',
  },
  {
    q: 'What if I do not have Google Analytics?',
    a: 'That does not block the diagnosis. Missing measurement can itself be a finding and a recommendation.',
  },
  {
    q: 'Does the diagnosis include competitors?',
    a: 'It can consider comparable properties when enough relevant public information is available.',
  },
  {
    q: 'How long does it take?',
    a: 'We do not publish a fixed turnaround. Timing depends on the scope and the information available, and it is agreed when we start.',
  },
  {
    q: 'Can I request it if the property is still being built?',
    a: 'Yes, if there is enough information about what already exists and what is planned. Depth depends on that stage.',
  },
  {
    q: 'Can I implement the recommendations myself?',
    a: 'Yes. The roadmap is there so you can decide. Andario can support implementation when you ask for it.',
  },
  {
    q: 'How do I request a Digital Check?',
    a: 'Through Request a digital diagnosis or WhatsApp. The conversation does not require you to contract the other services.',
  },
];

export const digitalCheckEn: DigitalCheckContent = {
  support:
    'Before building new tools, we need to understand where you are. We review the property’s digital presence and turn the findings into a prioritized roadmap so you know what to improve first.',
  audienceLine: 'For hostels, small hotels, inns, holiday apartments, cabins and other independent accommodations.',
  primaryCta: 'Request a diagnosis',
  talkCta: 'Talk with Andario',
  knowCta: 'I want to understand my digital situation',
  startCta: 'Start my Digital Check',
  overviewCaption:
    'Google, the website, WhatsApp, OTAs, bookings and social profiles are looked at together. Digital Check turns them into a diagnosis and a roadmap.',
  overviewPieces: ['Google', 'Website', 'WhatsApp', 'OTAs', 'Bookings', 'Social'],
  overviewCore: 'Digital Check',
  overviewResult: ['Diagnosis', 'Priorities', 'Roadmap'],
  situations: [
    'I am on Google, but I do not know how visible I am.',
    'I have a website, but I do not know if it actually helps people take the next step.',
    'Enquiries arrive on WhatsApp, and everything is manual.',
    'I am on OTAs, but my own channel is unclear.',
    'I post on social profiles, but I do not know how that connects to bookings.',
    'I have tools, but I do not know what to improve first.',
  ],
  valueTitle: 'You do not need to start by building. You need to start by understanding.',
  valueBody: 'Digital Check sets a baseline. It turns scattered information into concrete priorities.',
  valueSteps: [
    'Where are we?',
    'What is working?',
    'What is failing or fragmented?',
    'What opportunities exist?',
    'What should happen first?',
    'What can wait?',
  ],
  valueClose: 'The result is a direction, not an endless list of problems.',
  whatTitle: 'What is Digital Check?',
  whatBody:
    'A structured diagnosis of your property’s digital presence. We review the main touchpoints, find opportunities and organize the findings by priority. The aim is to see what deserves attention first and which path makes sense.',
  mapCaption:
    'The diagnosis looks at the whole set: visibility, social, WhatsApp, website, booking, OTAs, analytics, SEO, content, photography, experience and context.',
  mapCenter: 'Your digital ecosystem',
  mapNodes: ['Google', 'Visibility', 'Social', 'WhatsApp', 'Website', 'Bookings', 'OTAs', 'Analytics', 'SEO', 'Content', 'Photography', 'Experience'],
  reviewsLabel: 'What we review',
  whyLabel: 'Why it matters',
  outcomeLabel: 'What can come out',
  areasTitle: 'What we analyze',
  areasIntro: 'Twelve pieces of the ecosystem. This is not only a website review.',
  areasNote: 'When a review needs access to an account or internal information, we ask for it. We do not assume that access.',
  areas: [
    {
      title: 'Google presence',
      reviews: ['Information a searcher can see', 'Consistency of public details', 'How the property is presented'],
      why: 'It is often one of the first places a guest can find you.',
      outcome: 'Opportunities to put that presence in order.',
    },
    {
      title: 'Website',
      reviews: ['Clarity', 'Structure', 'Content', 'Contact points'],
      why: 'The site can inform, build trust or slow the next step.',
      outcome: 'What on the site is worth improving, and what can wait.',
    },
    {
      title: 'SEO',
      reviews: ['Structure', 'Content', 'Metadata', 'Technical foundations'],
      why: 'It helps search engines understand the property.',
      outcome: 'SEO opportunities and priorities, not a full implementation.',
    },
    {
      title: 'Social profiles',
      reviews: ['Presence', 'Consistency', 'Information', 'Link to the rest of the journey'],
      why: 'Posting is not the same as connecting that presence to a decision.',
      outcome: 'How social fits with the rest of the presence.',
    },
    {
      title: 'WhatsApp',
      reviews: ['How easy it is to write', 'Information available', 'The contact experience'],
      why: 'It is often where the real questions arrive.',
      outcome: 'Whether contact helps or has become a manual process.',
    },
    {
      title: 'OTAs',
      reviews: ['Presence', 'Public information', 'Relationship with the direct channel'],
      why: 'OTAs can sit alongside a direct channel. The diagnosis does not ask you to leave them.',
      outcome: 'How that presence sits inside the wider strategy.',
    },
    {
      title: 'Booking journey',
      reviews: ['From interest to the attempt to book', 'Friction', 'Channels involved'],
      why: 'The problem is sometimes what happens after someone finds you.',
      outcome: 'Where the path breaks or gets complicated.',
    },
    {
      title: 'Content and photography',
      reviews: ['How the property is presented', 'Whether the content explains the offer'],
      why: 'A guest decides from what they understand and what they see.',
      outcome: 'What still needs to be said before producing more pieces.',
    },
    {
      title: 'User experience',
      reviews: ['Clarity', 'Navigation', 'Accessibility', 'Friction'],
      why: 'A confusing presence is hard to use, even when it exists.',
      outcome: 'What gets in the way, and what is already clear.',
    },
    {
      title: 'Analytics',
      reviews: ['Whether measurement tools exist', 'What behavior can be observed'],
      why: 'Without measurement, the next decisions are made in the dark.',
      outcome: 'What is not being measured. Analytics is not required to start.',
    },
    {
      title: 'Competitive context',
      reviews: ['Public information on comparable properties', 'Only when that information is enough'],
      why: 'It shows the surroundings. It is not a reason to copy another property.',
      outcome: 'Context, not an invented ranking.',
    },
    {
      title: 'Ecosystem',
      reviews: ['How the pieces relate', 'What is connected and what works apart'],
      why: 'The value appears when the whole set has a direction.',
      outcome: 'Where to start so the pieces stop working alone.',
    },
  ],
  areasCta: 'Request a diagnosis',
  methodTitle: 'How we turn your digital presence into a roadmap.',
  methodIntro: 'Five steps. The diagnosis does not end as a list of errors.',
  method: [
    { title: 'Context', body: 'We learn the property type, location, offer, goals and current situation.' },
    { title: 'Presence', body: 'We review the main digital touchpoints.' },
    { title: 'Findings', body: 'We separate what works, what is missing, what is fragmented and the opportunities.' },
    { title: 'Prioritization', body: 'We order the findings by importance and effort.' },
    { title: 'Roadmap', body: 'The actions become concrete and sequenced.' },
  ],
  methodCta: 'Start my Digital Check',
  matrixTitle: 'It does more than detect. It helps you prioritize.',
  matrixIntro: 'Impact and effort separate what is worth doing soon from what can be planned.',
  matrixExample: 'Illustrative examples. They are not findings from a real property.',
  matrixImpact: 'Impact',
  matrixEffort: 'Effort',
  matrixZones: [
    { title: 'Do soon', body: 'High impact and relatively low effort.' },
    { title: 'Priority', body: 'High impact and more effort.' },
    { title: 'Plan', body: 'Less immediate impact and low effort.' },
    { title: 'Evaluate', body: 'More effort and less clear impact for now.' },
  ],
  matrixPoints: ['Improve contact', 'Tidy Google information', 'Redesign the website', 'Measure conversions'],
  findingExample: 'Illustrative example. It is not a real finding.',
  finding: [
    { label: 'Finding', value: 'Contact information is hard to find.' },
    { label: 'Opportunity', value: 'Reduce the friction of getting in touch.' },
    { label: 'Priority', value: 'High' },
    { label: 'Action', value: 'Improve the call to action, contact and WhatsApp.' },
    { label: 'Next step', value: 'Implementation, if you choose to do it.' },
  ],
  receiveTitle: 'You do not receive only observations. You receive a direction.',
  receiveIntro: 'The deliverable is a diagnosis and a roadmap of priority actions.',
  receive: [
    { title: 'Diagnosis', body: 'An ordered reading of the current situation.' },
    { title: 'Findings', body: 'What works, what is missing and what can improve.' },
    { title: 'Opportunities', body: 'Where there is room to move forward.' },
    { title: 'Priorities', body: 'What is worth handling first.' },
    { title: 'Roadmap', body: 'Which actions could follow, and in what order.' },
    { title: 'Next steps', body: 'Which Andario solutions may fit, only when they do.' },
  ],
  receiveCta: 'I want to understand my digital situation',
  reportNote: 'Illustrative mockup. It is not a client report.',
  reportHeading: 'Digital diagnosis',
  reportRows: [
    { label: 'Google', value: 'Review' },
    { label: 'Website', value: 'High priority' },
    { label: 'SEO', value: 'Opportunity' },
    { label: 'WhatsApp', value: 'In place' },
    { label: 'Bookings', value: 'Priority' },
    { label: 'Analytics', value: 'Not measured' },
  ],
  reportPrioritiesTitle: 'Priorities',
  reportPriorities: ['Improve the web presence', 'Organize the contact path', 'Start measuring'],
  reportNextTitle: 'Next steps',
  reportNext: 'Website, then bookings, then measurement. Only if the diagnosis says so.',
  priorityTitle: 'How opportunities are ordered',
  priorityBody: 'We do not invent a score. We use categories.',
  priorityCriteria: ['Potential impact', 'Urgency', 'Effort', 'Dependency', 'Current maturity', 'Fit with your goals'],
  priorityLevels: ['High priority', 'Medium priority', 'Plan later', 'Future opportunity'],
  decisionsTitle: 'A useful diagnosis also helps you decide what not to do yet.',
  decisionsIntro: 'These are the questions the diagnosis can put in order.',
  decisions: [
    'Do I need a new website?',
    'Should I improve my Google presence first?',
    'Do I need a booking engine?',
    'Do I need to work on SEO?',
    'Is WhatsApp making contact easier?',
    'Do I need better content and photography?',
    'Am I measuring what happens?',
    'What should I do first?',
    'Which investment can wait?',
  ],
  pathTitle: 'The diagnosis can be the start. The decision is yours.',
  pathIntro:
    'It may show that the website, visibility, a direct booking channel, WhatsApp, content or measurement is the useful next piece.',
  pathClose: 'You do not need to contract every service.',
  pathServices: ['Andario Web', 'Visibility', 'Booking Engine', 'Connect', 'Content', 'Growth'],
  whoTitle: 'For properties that want to know where to start.',
  whoTypes: [
    'Hostels',
    'Small hotels',
    'Inns',
    'Holiday apartments',
    'Aparthotels',
    'Cabins',
    'Villas',
    'Rural stays',
    'Other independent accommodations',
  ],
  whenTitle: 'When it tends to help',
  when: [
    'You are starting to digitize the property.',
    'You have several channels and no integrated strategy.',
    'You have a website and do not know if it works.',
    'You want to build a direct channel.',
    'You depend heavily on OTAs.',
    'Many enquiries arrive on WhatsApp.',
    'You want to invest and do not know where.',
    'You are thinking of redesigning the website.',
    'You want to improve visibility.',
    'You want to measure what happens more clearly.',
  ],
  notTitle: 'What Digital Check is not',
  not: [
    { title: 'Not a guarantee of results', body: 'It does not promise bookings, revenue, traffic or a search ranking.' },
    { title: 'Not only a website audit', body: 'It looks at the digital ecosystem, not only the site.' },
    { title: 'Not an endless error list', body: 'The aim is to prioritize.' },
    { title: 'Not an obligation to buy more', body: 'Recommendations can be done with Andario, with your team or with other providers.' },
    { title: 'Not a replacement for specialist tools', body: 'If a specific access or fact is needed, we say so.' },
    { title: 'Not a financial audit', body: 'It does not review accounts or economic results.' },
  ],
  modelTitle: 'The first step of a longer path',
  model: ['Diagnosis', 'Strategy', 'Implementation', 'Measurement', 'Evolution'],
  modelClose:
    'Digital Check helps decide what the property needs and in which order. Strategy, implementation, measurement and evolution can follow.',
  finalTitle: 'Before investing in new tools, find out what your property actually needs.',
  finalBody:
    'Tell us how your digital presence works today. We will look at the context and help you see where it makes sense to start.',
  finalCta: 'Request a digital diagnosis',
  finalNote: 'No obligation to contract every service.',
};
