import type { FaqItem, GrowthContent } from '@/content/types';

export const growthFaqsEn: FaqItem[] = [
  {
    q: 'What is Andario Growth?',
    a: 'The measurement, analysis and optimization service. It helps read signals from the digital ecosystem so decisions have more context. It is not a dashboard and not a standalone tool install.',
  },
  {
    q: 'Does it guarantee more bookings or more revenue?',
    a: 'No. Measurement shows what can be observed. It does not promise bookings, revenue, growth or a return.',
  },
  {
    q: 'Does it guarantee a Google ranking?',
    a: 'No. Search Console helps observe search. It does not sell a position.',
  },
  {
    q: 'Is it the same as installing Google Analytics?',
    a: 'No. Analytics can be one source. Growth organizes what to watch, how to read it and which adjustment makes sense next.',
  },
  {
    q: 'Do I need to become an analyst?',
    a: 'No. The reading is translated into property questions: where people arrive, what they look at and what happens next.',
  },
  {
    q: 'Can every question be answered?',
    a: 'No. It depends on instrumentation and on the sources that are connected. If a figure does not exist, it is not invented.',
  },
  {
    q: 'What is Search Console?',
    a: 'A Google tool for seeing how a site appears in search and for technical notices. It is not a client ranking.',
  },
  {
    q: 'Do you measure WhatsApp conversations?',
    a: 'No. Clicks toward WhatsApp can be observed. Conversation text and personal data are not sent to analytics.',
  },
  {
    q: 'Do you measure bookings?',
    a: 'Process interactions and conversions can be observed when they are instrumented. Growth does not create the reservation. That lives in the Booking Engine, if the property uses it.',
  },
  {
    q: 'Is attribution complete?',
    a: 'No. Origin can be seen when the visit allows it. We do not promise the full path of every person.',
  },
  {
    q: 'Are Instagram or Facebook integrated?',
    a: 'They can appear as the source of a visit when that visit is identifiable. That is not a live integration with those platforms.',
  },
  {
    q: 'Does Growth run ad campaigns?',
    a: 'No. It can read a visit that arrives with a campaign mark, if one exists. It is not an advertising service.',
  },
  {
    q: 'What is the difference from Digital Check?',
    a: 'Digital Check diagnoses the situation. Growth measures what happens later, according to the sources available. The diagnosis is not required.',
  },
  {
    q: 'What is the difference from Visibility?',
    a: 'Visibility works on the base for being found. Growth observes search and behavior signals. Neither promises a ranking.',
  },
  {
    q: 'Do I need to contract every service?',
    a: 'No.',
  },
  {
    q: 'Can I contract Growth on its own?',
    a: 'Yes. It measures what already exists. Without a site or events, the scope is limited to what can be observed.',
  },
  {
    q: 'What do I receive?',
    a: 'According to scope: orderly measurement, a reading of the connected sources, reports and recommendations. Not an invented percentage.',
  },
  {
    q: 'How often are there reports?',
    a: 'That is agreed in the scope. There is no published calendar treated as an obligation.',
  },
  {
    q: 'What do I need to start?',
    a: 'The website if it exists, access to the tools when that access is needed, the channels you already use and the decisions you want to clarify.',
  },
  {
    q: 'How do I start?',
    a: 'With a conversation. It does not lock you into a contract.',
  },
];

export const growthEn: GrowthContent = {
  support:
    'Your website, Google, WhatsApp and bookings can leave signals. Andario Growth helps measure the interactions that matter, understand what is happening and turn those signals into opportunities to improve.',
  audienceLine: 'Measurement, analysis and optimization for your property’s digital ecosystem.',
  primaryCta: 'I want to measure more clearly',
  talkCta: 'Talk with Andario',
  whatsappCta: 'Write on WhatsApp',
  scopeLabel: 'What can be seen depends on instrumentation and on the sources that are connected.',
  exampleLabel: 'Conceptual diagram. These are not a property’s figures.',
  loop: ['Visits', 'Interactions', 'Conversions', 'Bookings', 'Data', 'Learning', 'Decision', 'Optimization'],
  loopNote: 'The cycle starts again. One measurement does not close the work or promise the next result.',
  hub: [
    { title: 'Measure', body: 'Choose the signals the property can use.' },
    { title: 'Understand', body: 'Move from loose numbers to a reading.' },
    { title: 'Improve', body: 'Prioritize a change and watch again.' },
  ],
  sources: ['Google', 'Instagram', 'Facebook', 'WhatsApp', 'Website', 'Bookings'],
  sourceNote: 'Visits can arrive from several places. The problem appears when nobody turns those signals into a decision.',
  guessLine: 'Without measurement, every change is a guess.',
  questionsTitle: 'You do not need more numbers. You need to know which ones matter.',
  questions: [
    'Where do people arrive from?',
    'Which pages do they open?',
    'Which content draws interaction?',
    'How many people click through to WhatsApp?',
    'Where does the journey break?',
    'How many interactions reach the booking process?',
    'Which channels leave an identifiable visit?',
    'Which action is worth adjusting?',
    'What are we not measuring yet?',
  ],
  questionsNote: 'Not every answer exists on day one. If the source is not connected, the question stays open.',
  whatTitle: 'What is Andario Growth?',
  whatBody:
    'Andario Hospitality’s measurement, analysis and optimization service. It structures a reading of the digital ecosystem so behavior, channels and relevant events are easier to understand. From that, opportunities can be seen and actions prioritized.',
  whatNote: 'Measure, understand, improve. The point is not to look at more data. It is to know what to do with it.',
  ecosystemCaption:
    'Growth does not replace Google, the website or the engine. It organizes a reading of the sources that exist so a decision is easier.',
  ecosystemColumns: [
    { title: 'Google', points: ['Search', 'Search Console', 'Origin, when it is identified'] },
    { title: 'Website', points: ['Analytics', 'Pages', 'Interactions'] },
    { title: 'Contact and booking', points: ['WhatsApp clicks', 'Form', 'Booking steps, if they are measured'] },
  ],
  measureTitle: 'What it can observe',
  measureIntro: 'Each group enters only when there is a source and an event. This is not an inventory already active for every property.',
  measureGroups: [
    { title: 'Discovery', items: ['Traffic', 'Searches', 'Sources', 'Channels', 'Landing pages'] },
    { title: 'Interaction', items: ['Pages', 'Journey', 'Clicks', 'Elements on the site'] },
    { title: 'Communication', items: ['WhatsApp clicks', 'Forms', 'Contacts'] },
    { title: 'Bookings', items: ['Start of the process', 'Availability, if the event exists', 'Steps', 'Measured conversions', 'Origin, when it is instrumented'] },
    { title: 'Content', items: ['Pages', 'Pieces', 'Interaction', 'Behavior'] },
  ],
  measureNote: 'We do not publish percentages or a universal drop-off. A figure appears when it is measured.',
  channelsTitle: 'Channels are read. They are not controlled from here.',
  channelsBody:
    'A visit can come from search, a social network, a link or a marked campaign. Growth helps distinguish those arrivals when the tool shows them. It does not run the networks or buy ads.',
  channels: [
    { title: 'Search', body: 'Search Console and Analytics, when there is access. Observing is not ranking.' },
    { title: 'Website', body: 'Pages and interactions on the property’s own site, if Analytics is configured.' },
    { title: 'WhatsApp', body: 'Clicks toward the channel. Not the text of the conversation.' },
    { title: 'Bookings', body: 'Process interactions when the engine and the events exist. Recording an origin is not a live integration.' },
    { title: 'Social', body: 'They can appear as the source of a visit. There is no live integration with Instagram or Facebook.' },
    { title: 'Campaigns', body: 'Only if the visit carries an identifiable mark. Growth is not an advertising service.' },
  ],
  channelsNote: 'Channel attribution is partial. We do not reconstruct every person’s full path.',
  includesTitle: 'What it can include',
  includesIntro: 'Scope is defined with the property and with the access that exists.',
  whatLabel: 'What it is',
  purposeLabel: 'What it is for',
  groups: [
    { title: 'Google Analytics', what: 'A reading of site visits and interactions.', purpose: 'See what happens after someone arrives.' },
    { title: 'Search Console', what: 'A reading of search appearance and technical notices.', purpose: 'Observe search without promising a rank.' },
    { title: 'Conversion events', what: 'Actions agreed for measurement: contact, WhatsApp, booking steps.', purpose: 'Tell a visit apart from a next step.' },
    { title: 'Site behavior', what: 'Pages and journeys that are available.', purpose: 'See where a person stays or continues.' },
    { title: 'WhatsApp clicks', what: 'The click, not the message.', purpose: 'Know that someone chose to write.' },
    { title: 'Booking interactions', what: 'Process events, if the engine exposes them.', purpose: 'Relate the visit to the booking without copying the engine’s logic.' },
    { title: 'Booking conversion', what: 'A completed reservation, when that event exists.', purpose: 'Count a fact, not promise the next one.' },
    { title: 'Channel attribution', what: 'The origin the tool can show.', purpose: 'Compare arrivals, without total attribution.' },
    { title: 'Reports and recommendations', what: 'A reading and a next adjustment.', purpose: 'Decide, rather than collect numbers.' },
  ],
  privacyTitle: 'What does not go to analytics',
  privacyPoints: ['Names', 'Email addresses', 'Phone numbers', 'Conversation text', 'Guest details'],
  privacyNote: 'Events are categories. They are not a file on the person.',
  relations: [
    {
      title: 'Before measuring, it sometimes helps to know where you are.',
      body: 'Digital Check can order priorities. Growth later measures what has been instrumented.',
      steps: ['Digital Check', 'Diagnosis', 'Growth', 'Reading'],
      note: 'The diagnosis is not required.',
      hrefLabel: 'Digital Check',
    },
    {
      title: 'The website is one of the sources.',
      body: 'Andario Web can leave the measurement base. Growth extends the reading. An Andario website is not required.',
      steps: ['Website', 'Events', 'Growth', 'Reading'],
      note: 'Without a site, what exists is what gets measured.',
      hrefLabel: 'Andario Web',
    },
    {
      title: 'Visibility also leaves signals.',
      body: 'Visibility works on the base for being found. Growth can observe search and behavior. Neither promises a ranking.',
      steps: ['Visibility', 'Signals', 'Growth', 'Adjustment'],
      note: 'There is no complete attribution for every search.',
      hrefLabel: 'Andario Visibility',
    },
    {
      title: 'The conversation is not read from the inside.',
      body: 'Connect organizes communication. Growth can see the click toward WhatsApp, not the chat.',
      steps: ['Connect', 'Click', 'Growth'],
      note: 'We do not analyze private messages.',
      hrefLabel: 'Andario Connect',
    },
    {
      title: 'Content can be observed, not guessed.',
      body: 'Content creates the material. Growth can see interaction with pages when that measurement exists.',
      steps: ['Content', 'Publication', 'Interaction', 'Growth'],
      note: 'A piece does not bring its own guaranteed result.',
      hrefLabel: 'Andario Content',
    },
    {
      title: 'The booking stays in the engine.',
      body: 'Booking Engine manages availability and the reservation. Growth can read process events if they are instrumented.',
      steps: ['Visit', 'Process', 'Booking Engine', 'Growth'],
      note: 'Measuring a booking does not create one.',
      hrefLabel: 'Andario Booking Engine',
    },
  ],
  processTitle: 'From signals to a decision.',
  process: [
    { title: 'Choose', body: 'Which property questions deserve a figure.' },
    { title: 'Connect', body: 'The sources and the access that exist.' },
    { title: 'Measure', body: 'Agreed events, without personal data.' },
    { title: 'Read', body: 'What is visible and what still cannot be seen.' },
    { title: 'Recommend', body: 'A concrete adjustment, not a decorative board.' },
    { title: 'Look again', body: 'The change is observed. It is not treated as finished.' },
  ],
  receiveTitle: 'What the property can receive',
  receive: [
    'An orderly measurement of what can already be seen',
    'Access to or a reading of Analytics and Search Console, according to permissions',
    'Contact, WhatsApp and booking events when they exist',
    'A reading of identifiable channels',
    'Reports according to scope',
    'Recommendations for what to adjust next',
  ],
  receiveNote: 'The deliverable depends on scope. It does not include promised growth or another property’s figures.',
  whoTitle: 'For properties that already generate signals and want to read them.',
  whoTypes: ['Hostels', 'Small hotels', 'Inns', 'Holiday apartments', 'Aparthotels', 'Cabins', 'Villas', 'Rural stays', 'Other independent properties'],
  whoFit: [
    'There are visits and it is unclear where they come from.',
    'The site exists and nobody reads what happens next.',
    'WhatsApp matters and only the chat is visible, not the click.',
    'There are bookings and they are not related to a channel.',
    'Changes are made by instinct.',
    'They want a measurement cycle, not a generic report.',
  ],
  notTitle: 'What Andario Growth is not',
  not: [
    { title: 'Not a dashboard', body: 'Numbers help when they help a decision.' },
    { title: 'Not installing a tool and leaving', body: 'The reading and the next adjustment are part of the service, according to scope.' },
    { title: 'Not a growth promise', body: 'There are no guaranteed bookings, revenue or return.' },
    { title: 'Not SEO', body: 'That is Visibility. Growth observes. It does not rank.' },
    { title: 'Not advertising', body: 'It does not buy traffic or run campaigns.' },
    { title: 'Not a replacement for the owner', body: 'The decision stays with the property, with more context.' },
    { title: 'Not a forecast', body: 'It reads what already happened in the connected sources.' },
  ],
  ecosystemTitle: 'Growth closes the reading. It does not require the rest.',
  ecosystemSteps: ['Digital Check', 'Understand', 'Web', 'Present', 'Visibility', 'Be found', 'Content', 'Show', 'Connect', 'Talk', 'Booking Engine', 'Book', 'Growth', 'Measure'],
  ecosystemNote: 'This is Growth’s place in the ecosystem. Each service is contracted separately.',
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal is the pioneer property of Andario Hospitality. We do not publish its traffic, bookings or conversions.',
  finalTitle: 'Give your property’s decisions more context.',
  finalBody: 'Tell us what you can already see and what you would like to understand. We can help you organize the measurement and choose what to do next.',
  finalNote: 'No promised growth. A reading of what the sources allow you to see.',
};
