import type { HomePageContent } from '@/content/types';

export const homePageEn: HomePageContent = {
  eyebrow: 'Andario Hospitality',
  h1: 'Your property deserves much more than simply being online.',
  support:
    'We build a digital strategy with you so the property has a professional presence, is easier to find, can strengthen its own booking channels and turn each digital interaction into part of one experience.',
  primaryCta: 'I want to improve my property',
  secondaryCta: 'See how',
  micro: 'For hostels, small hotels, inns, apart-hotels, cabins and independent accommodations.',
  heroAltH1: 'From being online to working digitally for your property.',
  heroAltSupport:
    'Strategy, technology and support to build your presence, improve visibility, connect conversations, make booking easier and understand what is working.',
  heroCenter: 'Your property',
  heroNodes: ['Visibility', 'Content', 'Web', 'Booking', 'Connect', 'Growth', 'Digital Check'],
  heroMobile: ['Digital Check', 'Web', 'Visibility', 'Content', 'Connect', 'Booking Engine', 'Growth'],
  heroCaption:
    'The property sits at the center. Visibility, content, website, communication, bookings, measurement and diagnosis relate around it. This is not a required order and not an automatic integration.',
  journeyTitle: 'Your guest’s experience starts long before arrival.',
  journeyBody:
    'Andario works with you on that digital path: from how people find you, to how they discover the property, talk with you, book and leave signals that can help you keep improving.',
  journeySteps: ['They find you', 'They get to know you', 'They write', 'They compare', 'They book', 'They arrive'],
  journeyMap: ['Google', 'Website', 'Content', 'WhatsApp', 'Booking Engine', 'Reservation', 'Growth'],
  journeyNote: 'This map explains the path. It does not mean every channel is integrated automatically.',
  memorySteps: ['Find', 'Know', 'Trust', 'Talk', 'Book', 'Return'],
  memoryNote: 'This is a way to read the digital ecosystem. Andario does not control every one of these steps.',
  problemTitle: 'Your property is already doing many things. Are they working together?',
  problemChannels: ['Google', 'Instagram', 'Facebook', 'WhatsApp', 'OTA', 'Website', 'Bookings', 'Photos', 'Content'],
  problemBody: [
    'You may already be present on several channels. You may get WhatsApp inquiries, keep social profiles, appear on Google or even have a website.',
    'When each part works on its own, the effort multiplies and the experience breaks into pieces.',
  ],
  problemClose: 'You do not need more channels. You need the ones you already have to work better together.',
  fragmentTitle: 'From separate pieces to a path with direction.',
  beforeLabel: 'Before',
  beforeItems: ['Website', 'Social', 'Google', 'WhatsApp', 'OTA', 'Bookings', 'Content', 'Photos'],
  beforeNote: 'Everything exists. It is just separate.',
  afterLabel: 'With a strategy',
  afterFlow: ['Web', 'Visibility', 'Content', 'Connect', 'Booking Engine', 'Growth'],
  afterNote: 'One strategy. One ecosystem. A path to evolve. Not an automatic integration of every channel.',
  visionTitle: 'Imagine your whole digital ecosystem starting to move in the same direction.',
  visionItems: [
    { title: 'Your website presents', body: 'The property in a professional way.' },
    { title: 'Google helps people find you', body: 'With a base of visibility and SEO. Not a promise of the top position.' },
    { title: 'Your content shows the experience', body: 'Spaces, services, the destination and what you offer.' },
    { title: 'WhatsApp keeps the conversation', body: 'With communication that is easier to follow.' },
    { title: 'Booking Engine makes the reservation easier', body: 'With our own technology for your booking channel.' },
    { title: 'Growth helps you understand what happens', body: 'By measuring the signals and interactions that are available.' },
  ],
  visionClose: 'That is what we want to build with you.',
  bookingTitle: 'Your property can have its own booking channel.',
  bookingSupport:
    'Andario Booking Engine is our own technology for managing availability, rates, guests and reservations from a direct channel.',
  bookingPhrase: 'More control over your own channel. Less dependence on manual processes.',
  bookingCta: 'Explore Andario Booking Engine',
  bookingBranches: [
    { title: 'Website', body: 'The starting channel you own, where a guest can check availability and book.' },
    { title: 'WhatsApp', body: 'It is for conversation. Booking inside the chat is not a live channel.' },
    { title: 'Other channels', body: 'A reservation can record where it came from. That is not a live integration.' },
  ],
  bookingResult: 'A reservation on your channel',
  bookingNote: 'The engine holds availability, rates, units, guests and reservations. It can coexist with OTAs. It does not replace them.',
  cardsTitle: 'We build the ecosystem around your property.',
  cardsSupport: 'Each solution answers a concrete need. You can start with one and grow when you are ready.',
  verbs: {
    'digital-check': 'Understand',
    'andario-web': 'Build',
    'andario-visibility': 'Be found',
    'andario-booking-engine': 'Book',
    'andario-connect': 'Communicate',
    'andario-content': 'Show',
    'andario-growth': 'Measure and evolve',
  },
  cards: {
    'digital-check': {
      category: 'Diagnosis and strategy',
      body: 'Understand what works, what is missing and what you should prioritize.',
      cta: 'Explore Digital Check',
    },
    'andario-web': {
      category: 'Digital presence',
      body: 'A professional website to present the property, the destination, the services, the experiences and the ways to get in touch.',
      cta: 'Explore Andario Web',
    },
    'andario-visibility': {
      category: 'SEO, Google and visibility',
      body: 'We work on technical, local and content foundations so the property can appear for relevant searches.',
      cta: 'Explore Andario Visibility',
    },
    'andario-booking-engine': {
      category: 'Direct bookings',
      body: 'Our own technology to manage availability, rates, guests and reservations from a channel you own.',
      cta: 'Explore Booking Engine',
    },
    'andario-connect': {
      category: 'Communication and automation',
      body: 'We connect WhatsApp and other conversation points with the commercial and booking journey, reducing repetitive tasks when automation applies.',
      cta: 'Explore Connect',
    },
    'andario-content': {
      category: 'Photography and content',
      body: 'We help present the property through photography, writing, video, destination content and an editorial plan, within the agreed scope.',
      cta: 'Explore Content',
    },
    'andario-growth': {
      category: 'Analytics and optimization',
      body: 'We measure interactions, channels, events and signals so available data can become useful information for decisions.',
      cta: 'Explore Growth',
    },
  },
  ownTech: 'Our own technology',
  solutionsCta: 'See all solutions',
  whereTitle: 'Not every property needs the same thing.',
  whereSupport:
    'The point is not to contract more tools. It is to start with the need that matters most for the business today. This is guidance, not a required recommendation.',
  scenarios: [
    {
      title: 'I am just starting',
      body: 'I need to build a professional digital presence.',
      cta: 'I want to start',
      placement: 'starting',
      services: ['digital-check', 'andario-web', 'andario-content'],
    },
    {
      title: 'I have a presence, but people do not find me',
      body: 'The priority is to appear for relevant searches.',
      cta: 'I want to improve my visibility',
      placement: 'visibility',
      services: ['digital-check', 'andario-visibility', 'andario-content'],
    },
    {
      title: 'I get inquiries, but everything is manual',
      body: 'Conversations and bookings still depend on loose processes.',
      cta: 'I want to organize my bookings',
      placement: 'bookings',
      services: ['andario-connect', 'andario-booking-engine', 'andario-web'],
    },
    {
      title: 'I have several disconnected channels',
      body: 'The pieces exist, but they do not form a path.',
      cta: 'I want to connect my ecosystem',
      placement: 'ecosystem',
      services: ['digital-check', 'andario-web', 'andario-connect', 'andario-booking-engine', 'andario-growth'],
    },
    {
      title: 'I already have a presence and want to improve it',
      body: 'I need to understand what is happening before choosing the next step.',
      cta: 'I want to measure and improve',
      placement: 'measure',
      services: ['andario-growth', 'andario-visibility', 'digital-check'],
    },
  ],
  adaptTitle: 'You do not need to do everything at once.',
  adaptBody:
    'Every property is in a different place. You can start with one concrete need and add solutions when the business is ready.',
  adaptClose: 'We do not want to sell you everything. We want to help you build what you actually need.',
  shiftTitle: 'From scattered effort to a strategy with direction.',
  shiftNote: 'This is a conceptual shift. It is not a promise of results.',
  beforeWord: 'Before',
  afterWord: 'After',
  shifts: [
    { before: 'A website without a strategy.', after: 'A digital presence aimed at the business.' },
    { before: 'Scattered inquiries.', after: 'Communication that is easier to follow.' },
    { before: 'Manual bookings.', after: 'A booking channel you own.' },
    { before: 'Data without context.', after: 'Information you can decide with.' },
  ],
  audienceTitle: 'Designed for people who make each property different.',
  audienceIntro: 'The focus is small and medium independent accommodations. There is no minimum size and no single format.',
  audiences: [
    { title: 'Hostels', body: 'A digital presence that fits a close operation with several units.' },
    { title: 'Small hotels', body: 'A channel you own, without the weight of a large platform.' },
    { title: 'Inns', body: 'The character of the place, told clearly before arrival.' },
    { title: 'Tourist apartments', body: 'Units, availability and a clearer way to inquire and book.' },
    { title: 'Cabins and villas', body: 'The destination and the stay, presented as an experience.' },
    { title: 'Tourism ventures', body: 'Start with what is needed today and grow later.' },
  ],
  audienceCta: 'See accommodations',
  processTitle: 'We do not digitalize for its own sake. We build what makes sense for your business.',
  process: [
    { title: 'Understand', body: 'What is happening?' },
    { title: 'Prioritize', body: 'What matters first?' },
    { title: 'Build', body: 'What do we need to implement?' },
    { title: 'Measure', body: 'What is going on?' },
    { title: 'Evolve', body: 'What can we improve?' },
  ],
  processClose: 'Your strategy is built around the business, not the other way around.',
  processCta: 'See how we work',
  trustTitle: 'Technology that does not complicate your day.',
  pillars: [
    { title: 'Specialization', body: 'We work with small and medium independent accommodations in mind.' },
    { title: 'Simplicity', body: 'Technology should be understandable and useful.' },
    { title: 'Our own technology', body: 'We build our own solutions, including Andario Booking Engine.' },
    { title: 'Support', body: 'It is not only about implementing. It is about understanding, measuring and evolving.' },
    {
      title: 'Transparency',
      body: 'We explain what we do, what each solution includes and which results we cannot guarantee.',
    },
  ],
  craftTitle: 'A digital strategy should not feel more complicated than the problem it is trying to solve.',
  craftItems: ['Clarity', 'Strategy', 'Technology', 'Support', 'Measurement'],
  craftClose: 'That is Andario Hospitality.',
  originTitle: 'We started in Colombia, with a Latin American outlook.',
  origin: [
    'Andario Hospitality exists to help small and medium independent accommodations professionalize their digital presence and build their own channels.',
    'We want to carry this from Colombia into Latin America, alongside properties that need accessible technology, strategy and support.',
  ],
  originCta: 'Meet Andario',
  casesTitle: 'Real stories. Real lessons.',
  casesPlace: 'BARUCH Hostal · Buritaca, Colombia',
  casesBody:
    'BARUCH is the pioneering property with which we are taking Andario Hospitality from the idea into real operation. We do not publish metrics, bookings or testimonials yet.',
  casesCta: 'See our cases',
  hopeTitle: 'It does not matter where your property is today. What matters is knowing the next step.',
  hopeBody:
    'Some properties are just starting. Others already have a website, social profiles, WhatsApp and a presence on several platforms. They do not all need the same thing. Our work is to understand your starting point and build from there.',
  hopeSteps: ['Today', 'Diagnosis', 'Priority', 'Implementation', 'Measurement', 'Evolution'],
  finalTitle: 'The next step for your property starts with a conversation.',
  finalBody:
    'Tell us where you are today, what concerns you and what you want to improve. We will look at the situation and help you see where to start.',
  finalPrimary: 'Request a digital diagnosis',
  finalSecondary: 'Talk with Andario',
  finalNote: 'No commitment. We will not sell you solutions you do not need.',
  faqs: [
    { q: 'Do I have to contract every solution?', a: 'No. You can contract only what your property needs now.' },
    { q: 'Where should I start?', a: 'If you are not sure what you need, Digital Check can help you identify priorities.' },
    { q: 'Can I contract only Booking Engine?', a: 'Yes, depending on the scope and the commercial conditions of the product.' },
    { q: 'Does Andario replace Booking.com?', a: 'No. Andario aims to strengthen your own channels and can coexist with OTAs.' },
    {
      q: 'Does Andario guarantee more bookings?',
      a: 'No. It provides strategy, technology and tools to build and improve the digital ecosystem. Results depend on many factors.',
    },
    { q: 'Can I start with only a website?', a: 'Yes.' },
    { q: 'Can I add solutions later?', a: 'Yes. The proposal is meant to grow when the property is ready.' },
    {
      q: 'Are the solutions connected?',
      a: 'They can form an ecosystem, depending on what you contract and which integrations are available. Not everything connects automatically.',
    },
    { q: 'Do you work with small properties?', a: 'Yes. The focus is small and medium independent accommodations.' },
    { q: 'How do I begin?', a: 'You can request a digital diagnosis or talk with Andario directly.' },
  ],
};
