import type { HomePageContent } from '@/content/types';

export const homePageEn: HomePageContent = {
  h1: 'Grow your property on the internet',
  support: 'We help you get a professional website, show up on Google, take direct bookings and look after your guests better.',
  trust: 'You do not need to know about technology. We walk with you, step by step.',
  primaryCta: 'I want to know where to start',
  secondaryCta: 'Talk with Andario',
  forLine: 'For hostels · small hotels · inns · cabins · tourist apartments · independent properties',
  heroAlt: 'City building with the Andario Hospitality mark on the facade, on an urban street.',
  heroBadge: 'Independent accommodation',
  checkAlt: 'A desk with a laptop showing the Andario Hospitality digital diagnosis, a presence checklist and a strategy summary.',
  checkNote: 'A conceptual sketch. Not a screenshot of the product.',
  checkItems: [
    { label: 'Website', tone: 'steady' },
    { label: 'Google', tone: 'steady' },
    { label: 'Bookings', tone: 'attention' },
    { label: 'WhatsApp', tone: 'attention' },
    { label: 'Content', tone: 'steady' },
    { label: 'Measurement', tone: 'attention' },
  ],
  knownAlt: 'Two people reviewing a laptop at a lodging reception, with a courtyard and plants behind them.',
  mockProperty: 'Patio House',
  mockDates: '12–15 Oct',
  mockGuests: '2 guests',
  mockUnit: 'Room available',
  mockPrice: 'Property rate',
  mockAction: 'Book',
  mockNote: 'Illustrative example. Not a screenshot of the product.',
  bookingAlt:
    'Illustrative Andario Booking Engine interface on a computer and a phone, with rooms and a sample reservation.',
  bridge: 'Having a digital presence is not the same as having a digital strategy.',
  situationsTitle: 'Where is your property today?',
  situations: [
    { title: 'I am just starting', body: 'Almost no digital presence, and I do not know where to begin.' },
    { title: 'I am online, but people do not find me', body: 'I have a presence, but very little visibility.' },
    { title: 'I get inquiries, but everything is manual', body: 'WhatsApp, calls and bookings are handled by hand.' },
    { title: 'My channels are disconnected', body: 'Website, OTAs, social media and WhatsApp do not talk to each other.' },
    { title: 'I have tools, but I do not know what works', body: 'I cannot see clearly what happens with visits, inquiries and bookings.' },
  ],
  situationClose: 'It does not matter where your property is today. What matters is the next step.',
  situationCta: 'Find out where to start',
  boardTitle: 'Digital diagnosis',
  boardStatus: 'Where your property stands today',
  boardAreas: 'Areas reviewed',
  boardOpportunities: 'Priority opportunities',
  boardNext: 'Next steps',
  opportunities: ['Direct bookings', 'WhatsApp conversations', 'Seeing what is happening'],
  nextSteps: ['Define the scope', 'Build a roadmap', 'Implement what matters first', 'Measure and adjust'],
  offerTitle: 'One system, not seven separate products',
  offerSupport: 'Digital Check shows where to start. The other solutions build only what your property needs.',
  cards: {
    'andario-web': {
      role: 'Build',
      title: 'A professional website',
      body: 'So guests can get to know your property, see what you offer and contact you or book.',
      cta: 'Explore Andario Web',
    },
    'andario-visibility': {
      role: 'Be found',
      title: 'Get found on Google',
      body: 'We work so your property has a stronger presence when people search for a place to stay.',
      cta: 'Explore Andario Visibility',
    },
    'andario-booking-engine': {
      role: 'Take bookings',
      title: 'Take bookings directly',
      body: 'We build a channel you own so guests can check availability and manage their bookings.',
      cta: 'Explore Andario Booking Engine',
    },
    'andario-connect': {
      role: 'Communicate',
      title: 'Look after guests better on WhatsApp',
      body: 'We help you organize conversations with guests and reply more easily.',
      cta: 'Explore Andario Connect',
    },
    'andario-content': {
      role: 'Show',
      title: 'Show your property better',
      body: 'Photos, writing and content that show the experience you offer.',
      cta: 'Explore Andario Content',
    },
    'andario-growth': {
      role: 'Measure and improve',
      title: 'See what is working',
      body: 'We help you understand which channels and actions are producing results.',
      cta: 'Explore Andario Growth',
    },
    'digital-check': {
      role: 'Understand',
      title: 'Find out where to start',
      body: 'We look at your situation and help you decide what to improve first.',
      cta: 'Explore Digital Check',
    },
  },
  solutionsCta: 'Explore our solutions',
  roadmapTitle: 'From diagnosis to action',
  roadmapIntro: 'First we understand. Then we build only what makes sense for your property.',
  roadmap: ['Diagnosis', 'Priorities', 'Roadmap', 'Implementation', 'Measurement', 'Evolution'],
  knownTitle: 'You know your property.\nWe help you with the technology.',
  knownBody: [
    'You do not need to become an expert in websites, Google, bookings or digital tools.',
    'Our work is to explain the options, help you choose what you actually need and stay with you through the process.',
  ],
  audienceTitle: 'Made for properties like yours',
  audiences: ['Hostels', 'Small hotels', 'Inns', 'Guesthouses', 'Cabins', 'Rural stays', 'Tourist apartments', 'Apart-hotels'],
  audienceCta: 'See accommodations',
  processCta: 'See how we work',
  differentiatorsTitle: 'Why work with Andario',
  differentiators: [
    { title: 'Focus', body: 'We work with places to stay, not with every kind of business.' },
    { title: 'Simplicity', body: 'We explain the options in plain language.' },
    { title: 'Our own technology', body: 'We build tools around how a property actually runs.' },
    { title: 'We stay with you', body: 'We do not disappear after the delivery.' },
    { title: 'Honesty', body: 'We say what is ready and what is still evolving.' },
  ],
  bookingTitle: 'Build your own booking channel.',
  booking: [
    'Your website introduces the property. Andario Booking Engine handles the reservation.',
    'The website is the live starting point. WhatsApp, Instagram, Facebook, Google and AI assistants are still evolving.',
  ],
  bookingCta: 'Explore Andario Booking Engine',
  bookingBranches: [
    { title: 'Your website', body: 'Where guests get to know the property and can ask or check.' },
    { title: 'WhatsApp', body: 'The channel they already use to write to you. We help organize that conversation.' },
    { title: 'Other platforms', body: 'They can keep working at the same time as the channel you own.' },
  ],
  bookingResult: 'A booking on your channel',
  bookingNote: 'Illustrative example. Not a screenshot of the product.',
  bookingOta: 'You do not need to leave the OTAs. You need a stronger channel of your own.',
  bookingPoints: ['Availability', 'Rates', 'Rooms or units', 'Guests', 'Reservations', 'Rules', 'Channel source', 'Administration'],
  finalTitle: 'Not sure where to start?',
  finalBody: ['Tell us where your property is today, what worries you and what you want to improve.'],
  finalPrimary: 'Request a digital diagnosis',
  finalSecondary: 'Talk with Andario',
  faqs: [
    {
      q: 'Do I need to know about technology?',
      a: 'No. You know your property. We explain the options and walk with you, step by step.',
    },
    {
      q: 'Do I have to contract every solution?',
      a: 'No. You can start with what the property needs now and add more later, if it makes sense.',
    },
    {
      q: 'Where should I start?',
      a: 'With a conversation. If you are not sure what to improve first, a diagnosis helps you see it.',
    },
    { q: 'Can I start with only a website?', a: 'Yes.' },
    {
      q: 'Does Andario replace Booking.com or other platforms?',
      a: 'No. You can keep using them and, at the same time, have your own channel for guests.',
    },
    {
      q: 'Do you guarantee more bookings?',
      a: 'No. We help you with a clearer presence, a website and a path to receive bookings. Results depend on many factors.',
    },
    { q: 'Do you work with small properties?', a: 'Yes. We work with hostels, small hotels, inns, cabins and other independent properties.' },
    { q: 'How do I begin?', a: 'You can request a diagnosis or write to us on WhatsApp.' },
  ],
};
