import type { HomePageContent } from '@/content/types';

export const homePageEn: HomePageContent = {
  h1: 'Grow your property on the internet',
  support: 'We help you get a professional website, show up on Google, take direct bookings and look after your guests better.',
  trust: 'You do not need to know about technology. We walk with you, step by step.',
  primaryCta: 'I want to know where to start',
  secondaryCta: 'Talk with Andario',
  forLine: 'For hostels · small hotels · inns · cabins · tourist apartments · independent properties',
  heroAlt: 'City building with the Andario Hospitality mark on the facade, on an urban street.',
  heroBadge: 'Independent accommodation',
  checkAlt: 'A desk with a laptop showing the Andario Hospitality digital diagnosis, a presence checklist and a strategy summary.',
  checkNote: 'A conceptual sketch. Not a screenshot of the product.',
  checkItems: [
    { label: 'Website', tone: 'steady' },
    { label: 'Google', tone: 'steady' },
    { label: 'Bookings', tone: 'attention' },
    { label: 'WhatsApp', tone: 'attention' },
    { label: 'Content', tone: 'steady' },
    { label: 'Measurement', tone: 'attention' },
  ],
  knownAlt: 'Two people reviewing a laptop at a lodging reception, with a courtyard and plants behind them.',
  mockProperty: 'Patio House',
  mockDates: '12–15 Oct',
  mockGuests: '2 guests',
  mockUnit: 'Room available',
  mockPrice: 'Property rate',
  mockAction: 'Book',
  mockNote: 'Illustrative example. Not a screenshot of the product.',
  problemTitle: 'Do you feel your property could sell more online?',
  problemIntro: 'Some of these may sound familiar.',
  problems: [
    'I have social media, but I do not know if it really helps.',
    'Most of my bookings come from Booking.com or other platforms.',
    'I do not have a professional website.',
    'Guests write to me on WhatsApp all the time.',
    'I want to show up better on Google.',
    'I do not know what I should improve first.',
  ],
  problemClose: 'You do not have to solve all of it at once.',
  problemNext: 'First we understand your situation and help you decide where to start.',
  problemCta: 'I want a diagnosis',
  offerTitle: 'What can we do for your property?',
  offerSupport: 'We help small and medium properties improve their presence, their bookings and the way they work online.',
  cards: {
    'andario-web': {
      title: 'A professional website',
      body: 'So guests can get to know your property, see what you offer and contact you or book.',
      cta: 'Explore Andario Web',
    },
    'andario-visibility': {
      title: 'Get found on Google',
      body: 'We work so your property has a stronger presence when people search for a place to stay.',
      cta: 'Explore Andario Visibility',
    },
    'andario-booking-engine': {
      title: 'Take bookings directly',
      body: 'We build a channel you own so guests can check availability and manage their bookings.',
      cta: 'Explore Andario Booking Engine',
    },
    'andario-connect': {
      title: 'Look after guests better on WhatsApp',
      body: 'We help you organize conversations with guests and reply more easily.',
      cta: 'Explore Andario Connect',
    },
    'andario-content': {
      title: 'Show your property better',
      body: 'Photos, writing and content that show the experience you offer.',
      cta: 'Explore Andario Content',
    },
    'andario-growth': {
      title: 'See what is working',
      body: 'We help you understand which channels and actions are producing results.',
      cta: 'Explore Andario Growth',
    },
    'digital-check': {
      title: 'Find out where to start',
      body: 'We look at your situation and help you decide what to improve first.',
      cta: 'Explore Digital Check',
    },
  },
  solutionsCta: 'See all solutions',
  paceTitle: 'You do not have to do everything at once',
  pace: [
    'Every property has different needs.',
    'First we understand where you are, what you want to improve and what can actually help.',
    'Then we build the path with you.',
  ],
  paceSteps: ['Understand', 'Prioritize', 'Improve', 'Measure', 'Keep growing'],
  knownTitle: 'You know your property.\nWe help you with the technology.',
  knownBody: [
    'You do not need to become an expert in websites, Google, bookings or digital tools.',
    'Our work is to explain the options, help you choose what you actually need and stay with you through the process.',
  ],
  audienceTitle: 'Made for properties like yours',
  audiences: ['Hostels', 'Small hotels', 'Inns', 'Guesthouses', 'Cabins', 'Rural stays', 'Tourist apartments', 'Apart-hotels'],
  audienceCta: 'See accommodations',
  processTitle: 'We start with what you need',
  process: [
    { title: 'We talk', body: 'You tell us how the property works today.' },
    { title: 'We look', body: 'We review your website, Google, social media, WhatsApp and bookings.' },
    { title: 'We recommend', body: 'We explain what is worth doing first.' },
    { title: 'We build it with you', body: 'We put in place the solutions you actually need.' },
    { title: 'We keep improving', body: 'We look at the results and look for new opportunities.' },
  ],
  processCta: 'See how we work',
  bookingTitle: 'Your property can have its own booking channel too',
  booking: [
    'You do not have to depend only on outside platforms.',
    'With Andario Booking Engine you can give guests a simple way to check availability and manage their bookings from your own channels.',
  ],
  bookingCta: 'Explore Andario Booking Engine',
  bookingBranches: [
    { title: 'Your website', body: 'Where guests get to know the property and can ask or check.' },
    { title: 'WhatsApp', body: 'The channel they already use to write to you. We help organize that conversation.' },
    { title: 'Other platforms', body: 'They can keep working at the same time as the channel you own.' },
  ],
  bookingResult: 'A booking on your channel',
  bookingNote: 'Booking.com and other platforms can stay. This channel is yours and it can sit alongside them.',
  pioneerTitle: 'We are starting with real properties',
  pioneer: [
    'BARUCH Hostal, in Buritaca, Magdalena, is our pioneering property.',
    'This project lets us test our solutions, learn and keep improving them in a real place to stay.',
  ],
  pioneerCta: 'See the project',
  finalTitle: 'Not sure where to start?',
  finalBody: ['Tell us how your property works today.', 'We help you see what you should improve first.'],
  finalPrimary: 'Request a digital diagnosis',
  finalSecondary: 'Talk on WhatsApp',
  faqs: [
    {
      q: 'Do I need to know about technology?',
      a: 'No. You know your property. We explain the options and walk with you, step by step.',
    },
    {
      q: 'Do I have to contract every solution?',
      a: 'No. You can start with what the property needs now and add more later, if it makes sense.',
    },
    {
      q: 'Where should I start?',
      a: 'With a conversation. If you are not sure what to improve first, a diagnosis helps you see it.',
    },
    { q: 'Can I start with only a website?', a: 'Yes.' },
    {
      q: 'Does Andario replace Booking.com or other platforms?',
      a: 'No. You can keep using them and, at the same time, have your own channel for guests.',
    },
    {
      q: 'Do you guarantee more bookings?',
      a: 'No. We help you with a clearer presence, a website and a path to receive bookings. Results depend on many factors.',
    },
    { q: 'Do you work with small properties?', a: 'Yes. We work with hostels, small hotels, inns, cabins and other independent properties.' },
    { q: 'How do I begin?', a: 'You can request a diagnosis or write to us on WhatsApp.' },
  ],
};
