import type { HowWeWorkPageContent } from '@/content/types';

export const howWeWorkPageEn: HowWeWorkPageContent = {
  eyebrow: 'How we work',
  h1: 'Before you digitalize your property, find out what it actually needs.',
  support:
    'You do not need to know about technology to begin. We look at how your online presence works today, spot where it can improve and help you decide what to do first.',
  primaryCta: 'Request a Digital Check',
  secondaryCta: 'Talk to Andario',
  micro: 'No commitment. First we understand your situation.',
  route: [
    'Your property',
    'Digital Check',
    'We see where you are',
    'We find opportunities',
    'We prioritize',
    'We build a roadmap',
    'We implement',
    'We measure',
    'We evolve',
  ],
  lostTitle: 'Not sure where to start?',
  lostBody:
    'That is common. A property can be on Instagram, WhatsApp, Booking.com and even have a website, and still not know what to improve first.',
  situations: [
    'I am online, but I do not know if it is working.',
    'I have social media, but people do not find me easily.',
    'I depend a lot on Booking.com or other platforms.',
    'I get many WhatsApp messages and still do the work by hand.',
    'I have a website, but I do not know if it helps the business.',
    'I want to improve, but I do not know what to do first.',
  ],
  lostClose: 'You do not have to fix everything at once.',
  lostMark: 'First we need to understand where you are.',
  checkLabel: 'First step',
  checkTitle: 'Digital Check: the digital assessment of your property.',
  checkBody:
    'Digital Check is a first look at your online presence. It shows how the property is working today, where it can improve and where it makes sense to start.',
  checkMark: 'This is not about selling you more tools. It is about understanding what you actually need.',
  reviewTitle: 'What do we review?',
  reviews: [
    { title: 'Your website', body: 'How the property is presented, and how easy it is for a visitor to understand it and get in touch.' },
    { title: 'Google and visibility', body: 'How easy it is to find the property when someone is looking for a place like yours.' },
    { title: 'Social media', body: 'How you are showing the property, and what role those channels play.' },
    { title: 'WhatsApp and communication', body: 'How you handle inquiries, and which parts of that work could be simpler.' },
    { title: 'OTAs and outside channels', body: 'How your booking channels work today, and what role they play.' },
    { title: 'The booking path', body: 'What happens from the moment someone shows interest until they book.' },
    { title: 'Content and images', body: 'How photos, words and content shape the way people see the property.' },
    { title: 'Measurement', body: 'What information you already have to see what is working and what needs attention.' },
    { title: 'The visitor experience', body: 'How easy it is to find information, make contact and move toward a booking.' },
  ],
  receiveTitle: 'What do you get after the Digital Check?',
  receive: [
    { title: 'Assessment', body: 'You see where your online presence stands today.' },
    { title: 'Findings', body: 'We identify what is working and where there is room to improve.' },
    { title: 'Priorities', body: 'We decide what should come first and what can wait.' },
    { title: 'Roadmap', body: 'We build a path that fits your goals.' },
    { title: 'Recommendations', body: 'We name which solutions can help, and why.' },
    { title: 'Next step', body: 'You decide what to implement, and when.' },
  ],
  receiveMark: 'A Digital Check does not lock you into every Andario solution.',
  receiveNote: 'The roadmap is built around your property, your goals and your priorities.',
  mapTitle: 'From knowing you need to improve to knowing what to do first.',
  mapBody: 'Often the hard part is not knowing that something should improve. It is not knowing where to start.',
  beforeLabel: 'Before',
  before: [
    'I have a lot to improve.',
    'I do not know what should come first.',
    'I do not know which tool I need.',
    'I do not know if my website is working.',
    'I do not know if I am using Google well.',
    'I do not know what is working.',
  ],
  afterLabel: 'After the Digital Check',
  after: [
    'I know where I stand.',
    'I understand the main opportunities.',
    'I know what to prioritize.',
    'I understand which solutions can help.',
    'I have a path for improvement.',
    'I know what the next step can be.',
  ],
  goalsTitle: 'Your goal shapes the path too.',
  goalsIntro: 'Not every property needs the same thing. These are possible paths, not a required package.',
  goals: [
    { title: 'I want more people to find my property.', services: ['andario-visibility', 'andario-web', 'andario-content'] },
    { title: 'I want a professional website.', services: ['andario-web'] },
    { title: 'I want to receive direct bookings.', services: ['andario-web', 'andario-booking-engine'] },
    { title: 'I want guest conversations to be easier to handle.', services: ['andario-connect'] },
    { title: 'I want to show the property more clearly.', services: ['andario-content'] },
    { title: 'I want to understand what is working.', services: ['andario-growth'] },
  ],
  unsure: "I'm not sure what I need. Start with Digital Check.",
  processTitle: 'How we work with you',
  process: [
    { title: 'We get to know the property', body: 'We learn how it works today and what you want to achieve.' },
    { title: 'We do your Digital Check', body: 'We review the online presence and look for opportunities.' },
    { title: 'We set priorities', body: 'We decide what is worth improving first.' },
    { title: 'We build with you', body: 'We implement the solutions you actually need.' },
    { title: 'We measure', body: 'We look at what is happening and what information is available.' },
    { title: 'We evolve', body: 'We learn from what was built and define the next steps.' },
  ],
  processClose: 'Your property sets the pace. We build the digital path with you.',
  paceTitle: 'You do not have to do everything at once.',
  paceBody: 'The property can start with one concrete need and move forward over time.',
  pace: ['Digital Check', 'One priority', 'One solution', 'Measurement', 'The next opportunity'],
  paceNote: 'The aim is not to fill you with tools. It is to build an online presence that makes sense for the business.',
  solutionsTitle: 'Depending on what we find, we can help in different areas.',
  solutionsBody: 'The order comes from the assessment and your goals. There is no required sequence.',
  solutions: [
    { id: 'digital-check', body: 'Find out where to start.' },
    { id: 'andario-web', body: 'Build a professional web presence.' },
    { id: 'andario-visibility', body: 'Work so the property can be found.' },
    { id: 'andario-content', body: 'Show the experience more clearly.' },
    { id: 'andario-connect', body: 'Organize guest communication.' },
    { id: 'andario-booking-engine', body: 'Build your own booking channel.' },
    { id: 'andario-growth', body: 'See what is working and what to improve.' },
  ],
  knownMark: 'You know your property.\nWe help you with the technology.',
  knownBody:
    'You do not need to become an expert in websites, Google, bookings or digital tools. You know the business. We bring strategy, technology and support.',
  beliefs: [
    'We do not start by selling. We start by understanding.',
    'We do not recommend what does not make sense.',
    'We do not promise results we cannot control.',
    'We do not believe in digitalizing for its own sake.',
    'We do believe in building step by step.',
  ],
  bookingTitle: 'When the property needs a stronger direct booking channel.',
  bookingBody: 'Andario Booking Engine is our own technology for managing availability, rates, guests and reservations from a direct channel.',
  bookingNote: 'It can sit alongside OTAs. You do not have to leave Booking.com or other platforms to build your own channel. It does not sync those platforms today.',
  bookingCta: 'Explore Booking Engine',
  pioneerTitle: 'BARUCH Hostal: our pioneering property.',
  pioneerBody:
    'BARUCH Hostal, in Buritaca, Magdalena, is the first property where we are putting this approach into practice and learning from a real case.',
  finalTitle: 'Not sure where to start?',
  finalBody:
    'Tell us how the property works today and what you want to achieve. We start by understanding the situation and, when it makes sense, we build an improvement roadmap with you.',
  finalNote: 'No commitment. First we understand. Then we recommend.',
  faqs: [
    {
      q: 'What is Digital Check?',
      a: 'It is the digital assessment of your property. We look at how your online presence works today and help you see where to start.',
    },
    {
      q: 'Do I have to contract Digital Check first?',
      a: 'Not necessarily. If you are not sure where to start, it is the recommended entry point. If you already have a concrete need, we can talk about that directly.',
    },
    {
      q: 'What do you review in a Digital Check?',
      a: 'Your website, how people find you, social media, WhatsApp, outside channels, the path to a booking, your content and the information you already have.',
    },
    {
      q: 'What do I receive after the assessment?',
      a: 'A reading of where you are, the findings, the priorities, a roadmap and a recommended next step. You decide what to implement.',
    },
    {
      q: 'Does the roadmap force me to contract every solution?',
      a: 'No. The roadmap is a recommendation based on the needs and goals of your property.',
    },
    {
      q: 'Can I start with only a website?',
      a: 'Yes. If that is the clear need, we can talk about Andario Web without contracting the rest.',
    },
    {
      q: 'Can I add Booking Engine later?',
      a: 'Yes. A direct booking channel can be added when the property is ready. It does not replace Booking.com, and it does not sync OTAs today.',
    },
    {
      q: 'Do I need technical knowledge?',
      a: 'No. You know the property. We help with the strategy and the technology.',
    },
    {
      q: 'Does Andario replace Booking.com?',
      a: 'No. You can keep using your platforms and, when it makes sense, also build a channel of your own.',
    },
    {
      q: 'How do I begin?',
      a: 'If you are not sure where to start, request a Digital Check. That is the starting point for understanding your situation and building a roadmap.',
    },
  ],
};
