import type { SolutionsHubContent } from '@/content/types';

export const solutionsHubEn: SolutionsHubContent = {
  eyebrow: 'Solutions for independent accommodations',
  h1: 'Digitalize your property, step by step.',
  support:
    'We help you build a professional website, get found on Google, receive direct bookings, communicate better with your guests, and understand what is actually working.',
  assist: "You don't have to do everything at once. We start with what your property actually needs.",
  primaryCta: 'I want to know where to start',
  secondaryCta: 'Talk to Andario',
  micro: 'No commitment. No unnecessary solutions.',
  problemTitle: 'Does any of this sound familiar?',
  problemIntro: 'Every property starts from a different place. The useful question is what to improve first.',
  problems: [
    'I post on social media, but I am not sure it brings bookings.',
    'My property does not show up on Google the way I wish it did.',
    'I do not have a professional website.',
    'Guests message me on WhatsApp and I still handle most of it by hand.',
    'I depend too much on outside platforms for bookings.',
    'I already use several tools, but I cannot tell what is working.',
  ],
  whereTitle: 'Where is your property today?',
  whereIntro: 'Not every property needs the same thing. Choose the situation closest to yours.',
  resultLabel: 'What you get',
  solutionLabel: 'Recommended solution',
  scenarios: [
    {
      title: 'I am just starting my online presence.',
      result: 'Get a clear starting point and decide what is worth building first.',
      cta: 'Explore Digital Check',
      placement: 'starting',
      service: 'digital-check',
    },
    {
      title: 'I have an online presence, but I want more people to find me.',
      result: 'Build a stronger base so the property can appear when someone searches for a place to stay.',
      cta: 'Explore Visibility',
      placement: 'visibility',
      service: 'andario-visibility',
    },
    {
      title: 'I want to receive direct bookings.',
      result: 'Build a channel you own so guests can check availability and book.',
      cta: 'Explore Booking Engine',
      placement: 'bookings',
      service: 'andario-booking-engine',
    },
    {
      title: 'I spend too much time on inquiries and repetitive tasks.',
      result: 'Organize guest conversations so replies take less of your day.',
      cta: 'Explore Connect',
      placement: 'connect',
      service: 'andario-connect',
    },
    {
      title: 'I have several tools, but I am not sure how to get more from them.',
      result: 'Look at what you already have before adding something new.',
      cta: 'Explore Digital Check',
      placement: 'tools',
      service: 'digital-check',
    },
    {
      title: 'I already have an online presence and I want to see what works.',
      result: 'Use the information you already have to decide what to improve.',
      cta: 'Explore Growth',
      placement: 'measure',
      service: 'andario-growth',
    },
  ],
  cardsTitle: 'Solutions for what your property needs today.',
  cardsSupport: 'You can start with one concrete solution and add others when it makes sense for the business.',
  cards: {
    'digital-check': {
      category: 'Digital assessment',
      problem: 'You are not sure what to improve first.',
      body: 'Get a clear view of your digital situation and a path of priorities.',
      cta: 'Explore Digital Check',
    },
    'andario-web': {
      category: 'Professional website',
      problem: 'You do not have a website that represents the property.',
      body: 'Present the property, build trust and make it easier for visitors to get in touch or book.',
      cta: 'Explore Andario Web',
    },
    'andario-visibility': {
      category: 'Google and visibility',
      problem: 'The property is online, but people cannot always find it.',
      body: 'Build a better base for showing up on relevant searches. Not a promise of a top ranking.',
      cta: 'Explore Visibility',
    },
    'andario-booking-engine': {
      category: 'Your own booking engine',
      problem: 'Many bookings still depend on manual work or outside platforms.',
      body: 'Build your own direct booking channel. Manage availability, rates, units, guests and reservations from one place.',
      cta: 'Explore Booking Engine',
    },
    'andario-connect': {
      category: 'WhatsApp and communication',
      problem: 'You spend too much time answering the same questions.',
      body: 'Organize guest communication and connect those conversations with the booking path.',
      cta: 'Explore Connect',
    },
    'andario-content': {
      category: 'Photography and content',
      problem: 'The property may be good, but you are not showing everything it offers.',
      body: 'Present your spaces, experiences and destination more clearly.',
      cta: 'Explore Content',
    },
    'andario-growth': {
      category: 'Measurement and improvement',
      problem: 'You do not know what is working.',
      body: 'Use the information you already have to see what to improve.',
      cta: 'Explore Growth',
    },
  },
  ownTech: 'Our own technology',
  paceTitle: 'You do not have to contract everything.',
  paceBody: 'The property can start with one concrete need. As it grows, you can add other solutions.',
  paths: [
    { need: "I'm not sure what I need", service: 'digital-check' },
    { need: "I don't have a website", service: 'andario-web' },
    { need: "People can't find me", service: 'andario-visibility' },
    { need: 'I want direct bookings', service: 'andario-booking-engine' },
    { need: 'I get too many inquiries', service: 'andario-connect' },
    { need: 'I need better content', service: 'andario-content' },
    { need: 'I want to measure', service: 'andario-growth' },
  ],
  paceCta: "I'm not sure where to start",
  bookingTitle: 'Your property can have its own booking channel too.',
  bookingSupport: 'Andario Booking Engine is our own technology for managing direct bookings.',
  bookingItems: ['Availability', 'Rates', 'Units', 'Guests', 'Reservations'],
  bookingNote: 'It can sit alongside Booking.com and other platforms. The aim is to strengthen your own channel, not to remove the others.',
  bookingCta: 'Explore Andario Booking Engine',
  processTitle: 'We walk with you, step by step.',
  processMark: 'You know your property. We help you with the technology.',
  processNote: 'You do not need to know about technology to begin.',
  process: ['We talk', 'We understand your situation', 'We prioritize', 'We propose', 'We implement', 'We measure', 'We evolve'],
  trustTitle: 'Why work with Andario?',
  pillars: [
    { title: 'Specialization', body: 'We think specifically about independent accommodations.' },
    { title: 'Simplicity', body: 'We make the technology understandable and useful.' },
    { title: 'Our own technology', body: 'We build our own solutions, including Andario Booking Engine.' },
    { title: 'Support', body: 'We do not hand over a tool and disappear.' },
    { title: 'Transparency', body: 'We explain what we do, what each solution includes and which results we cannot guarantee.' },
  ],
  pioneer: "BARUCH Hostal, in Buritaca, Colombia, is Andario Hospitality's pioneering property.",
  pioneerSoon: 'Coming soon: a case study.',
  finalTitle: 'Not sure where to start?',
  finalBody: 'Tell us how the property works today and what you would like to improve. We help you see the next step.',
  finalPrimary: 'Request a digital diagnosis',
  finalSecondary: 'Talk to Andario',
  finalNote: 'No commitment. No unnecessary solutions.',
  faqs: [
    { q: 'Do I have to contract every solution?', a: 'No. You can contract only what the property needs now.' },
    { q: 'Where should I start?', a: 'If you are not sure, Digital Check helps you see priorities. If you already know the need, you can start with that solution.' },
    { q: 'Can I contract only Booking Engine?', a: 'Yes, depending on the scope and the conditions of the product.' },
    { q: 'Does Andario replace Booking.com?', a: 'No. You can keep using outside platforms and have your own channel at the same time.' },
    { q: 'Can I start with only a website?', a: 'Yes.' },
    { q: 'Can I add other solutions later?', a: 'Yes. The idea is to move forward when the property is ready, not to contract everything on day one.' },
    { q: 'Do you work with small hostels?', a: 'Yes. We work with hostels, small hotels, inns, cabins and other independent properties.' },
    { q: 'Do I need to know about technology?', a: 'No. You know the property. We explain the options and stay with you.' },
    { q: 'Do you guarantee more bookings?', a: 'No. We help you with a clearer presence and a channel you own. Results depend on many factors.' },
    { q: 'How can I begin?', a: 'You can request a diagnosis or write to us on WhatsApp.' },
  ],
};
