import type { SolutionsHubContent } from '@/content/types';

export const solutionsHubEn: SolutionsHubContent = {
  eyebrow: 'Solutions for independent accommodations',
  h1: 'Everything your property needs to build a stronger digital presence.',
  support:
    'You do not need to solve everything at once. At Andario we connect strategy, digital presence, visibility, bookings, communication, content and measurement so you can build the ecosystem your property actually needs.',
  primaryCta: 'Request a digital diagnosis',
  secondaryCta: 'Explore the solutions',
  micro: 'You can start with a single solution and grow from there.',
  heroCenter: 'Property',
  heroNodes: ['Visibility', 'Content', 'Web', 'Booking', 'Connect', 'Growth', 'Digital Check'],
  heroMobile: ['Digital Check', 'Web', 'Visibility', 'Content', 'Connect', 'Booking Engine', 'Growth'],
  heroCaption:
    'The property sits at the center. Diagnosis, presence, visibility, content, communication, bookings and measurement relate around it. This is not a required order.',
  startTitle: 'You do not need to do everything. You need to start with what matters most.',
  startBody:
    'Every property is in a different place. Some need their first website. Others need to be found more easily, organize bookings, present the stay with more care, or understand what is working. That is why each solution can be contracted on its own and grow with you.',
  startSteps: ['Your situation', 'Your priorities', 'The right solution', 'Next step'],
  whereTitle: 'Where is your property today?',
  whereIntro: 'Choose the situation that feels closest. This is not a test. It is a way to see where you could start.',
  scenarios: [
    {
      title: 'I still do not have a solid digital presence.',
      cta: 'I want to start',
      placement: 'scenario-start',
      services: ['digital-check', 'andario-web', 'andario-content'],
    },
    {
      title: 'I have a digital presence, but people do not find me.',
      cta: 'I want to improve my visibility',
      placement: 'scenario-visibility',
      services: ['digital-check', 'andario-visibility', 'andario-content'],
    },
    {
      title: 'I get inquiries, but booking is still a manual process.',
      cta: 'I want to organize my bookings',
      placement: 'scenario-bookings',
      services: ['andario-booking-engine', 'andario-connect', 'andario-web'],
    },
    {
      title: 'I have several channels and everything is disconnected.',
      cta: 'I want to connect my ecosystem',
      placement: 'scenario-connect',
      services: ['andario-booking-engine', 'andario-connect', 'andario-growth', 'andario-web'],
    },
    {
      title: 'I already have tools, but I do not know what is working.',
      cta: 'I want to measure better',
      placement: 'scenario-measure',
      services: ['andario-growth', 'andario-visibility', 'digital-check'],
    },
  ],
  cardsTitle: 'An ecosystem built around your property.',
  cardsSupport:
    'Each solution answers a concrete need. Together they can form a connected digital ecosystem. Separately, each one can solve a specific need.',
  cards: {
    'digital-check': {
      category: 'Diagnosis and strategy',
      problem: 'You do not know what to improve first.',
      body: 'We review your digital presence to see what works, what is missing, what is disconnected and where it makes sense to start.',
      chain: 'Observe → Analyze → Prioritize',
      related: 'Often the starting point toward Web, Visibility and Content.',
      cta: 'Explore Digital Check',
    },
    'andario-web': {
      category: 'Digital presence',
      problem: 'Your property needs a home of its own on the internet.',
      body: 'We build a professional website to present the property, the destination, the services, the experiences and the ways to get in touch.',
      chain: 'Property → Website → Trust → Action',
      related: 'It draws on Content and can connect with Booking Engine.',
      cta: 'Explore Andario Web',
    },
    'andario-visibility': {
      category: 'SEO, Google and visibility',
      problem: 'Being online does not mean being found.',
      body: 'We work on technical, local and content foundations so the property can appear for relevant searches.',
      chain: 'Search → Google → Property',
      related: 'It builds on Web and Content. It does not promise the top position.',
      cta: 'Explore Andario Visibility',
    },
    'andario-booking-engine': {
      category: 'Direct bookings',
      problem: 'Bookings should not depend only on manual processes or external channels.',
      body: 'Our own technology to manage availability, rates, units, guests, reservations and booking logic from a channel you own.',
      chain: 'Availability → Rate → Reservation → Guest',
      related: 'The website is the starting direct channel. It can coexist with OTAs.',
      cta: 'Explore Andario Booking Engine',
    },
    'andario-connect': {
      category: 'Communication and automation',
      problem: 'Conversations are part of the booking journey too.',
      body: 'We connect WhatsApp and other conversation points with the commercial and booking journey, reducing repetitive tasks when automation applies.',
      chain: 'Inquiry → WhatsApp → Reply → Guidance',
      related: 'It complements Web and Booking Engine. Booking inside the chat is not a live channel.',
      cta: 'Explore Andario Connect',
    },
    'andario-content': {
      category: 'Photography and content',
      problem: 'The experience begins before arrival.',
      body: 'We help present the property through photography, writing, video, destination content and an editorial plan, within the agreed scope.',
      chain: 'Photos + Writing + Video + Destination → Content',
      related: 'It feeds Web and Visibility.',
      cta: 'Explore Andario Content',
    },
    'andario-growth': {
      category: 'Analytics and optimization',
      problem: 'Without measurement, every change can become a guess.',
      body: 'We measure interactions, channels, events and signals from the ecosystem so available data can become useful information for decisions.',
      chain: 'Measure → Understand → Improve',
      related: 'It reads signals from Web, Visibility and Booking Engine. It does not invent results.',
      cta: 'Explore Andario Growth',
    },
  },
  ownTech: 'Our own technology',
  bookingTitle: 'The technology that can become the center of your direct bookings.',
  bookingSupport:
    'Andario Booking Engine is built to help independent properties create and operate their own booking channel, with one logic for availability, rates, guests and reservations.',
  bookingBranches: [
    { title: 'Website', body: 'The starting channel you own, where a guest can check availability and book.' },
    { title: 'WhatsApp', body: 'It is for conversation. Booking inside the chat is a planned next step, not a live channel.' },
    { title: 'Other channels', body: 'A reservation can record where it came from. That is not a live integration.' },
  ],
  bookingResult: 'Central reservation',
  bookingNote:
    'The engine holds availability, rates, units, guests and reservations. It does not claim that Instagram, Facebook, Google or AI assistants are already connected.',
  bookingCta: 'Explore Andario Booking Engine',
  connectTitle: 'The solutions connect. Your property can too.',
  connectBody: 'You do not need to contract everything at once. You can start where there is a concrete need and grow from there.',
  connectFlow: [
    'Digital Check — understand',
    'Strategy',
    'Web — build',
    'Visibility — be found',
    'Content — show',
    'Connect — communicate',
    'Booking Engine — book',
    'Growth — measure and evolve',
  ],
  connectNote: 'This is a way to see how the pieces relate. It is not a required sequence: you can enter through any solution.',
  beforeTitle: 'From fragmentation to connection',
  beforeLabel: 'Before: separate channels',
  beforeItems: ['Google', 'Instagram', 'Facebook', 'WhatsApp', 'OTA', 'Website', 'Bookings'],
  afterLabel: 'With a strategy',
  afterFlow: ['Strategy', 'Web', 'Visibility', 'Content', 'Connect', 'Booking Engine', 'Growth'],
  afterNote: 'A strategy sets priorities. It does not mean every channel is integrated automatically.',
  hopeTitle: 'It does not matter where your property is today. What matters is knowing the next step.',
  hopeBody:
    'Some properties are just starting. Others already have a website, social profiles, WhatsApp and a presence on several platforms. They do not all need the same thing. Our work is to understand your starting point and build from there.',
  hopeSteps: ['Today', 'Next step', 'Improvement', 'Following step', 'Evolution'],
  chooseTitle: 'Where should you start?',
  chooseItems: [
    { need: 'If you do not know what you need', service: 'digital-check' },
    { need: 'If you do not have a professional website', service: 'andario-web' },
    { need: 'If people cannot find you', service: 'andario-visibility' },
    { need: 'If you want direct bookings', service: 'andario-booking-engine' },
    { need: 'If you handle many conversations by hand', service: 'andario-connect' },
    { need: 'If you need better photos and content', service: 'andario-content' },
    { need: 'If you already have a presence and want to measure', service: 'andario-growth' },
  ],
  chooseCta: 'I do not know where to start',
  matrixTitle: 'One need, one possible solution',
  matrix: [
    { need: 'I do not know where to start', service: 'digital-check' },
    { need: 'I need a website', service: 'andario-web' },
    { need: 'People cannot find me', service: 'andario-visibility' },
    { need: 'I want direct bookings', service: 'andario-booking-engine' },
    { need: 'I get many inquiries', service: 'andario-connect' },
    { need: 'I need better content', service: 'andario-content' },
    { need: 'I want to measure and improve', service: 'andario-growth' },
  ],
  adaptTitle: 'Andario fits the moment you are in.',
  adaptBody:
    'You can start with one concrete need and add solutions when the property is ready. The proposal does not begin by selling you everything. It begins by understanding what makes sense for the business.',
  journeyTitle: 'Your digital transformation can start with a conversation.',
  journeyNote: 'A conversation does not mean implementation starts immediately.',
  journey: [
    'We talk',
    'We understand your situation',
    'We set priorities',
    'We propose',
    'We implement',
    'We measure',
    'We evolve',
  ],
  trustTitle: 'Technology that does not complicate your day.',
  pillars: [
    { title: 'Specialization', body: 'We design with independent accommodations in mind.' },
    { title: 'Simplicity', body: 'We want the technology to be understandable and useful.' },
    { title: 'Our own technology', body: 'We build our own solutions, including Andario Booking Engine.' },
    { title: 'Support', body: 'We do not hand over a tool and disappear.' },
    {
      title: 'Transparency',
      body: 'We explain what we do, what each service includes and which results we cannot guarantee.',
    },
  ],
  craftTitle: 'A strategy should not feel more complicated than the problem it is trying to solve.',
  craftIntro: 'Clarity first. Then the tool that is actually needed.',
  craftPillars: [
    { title: 'Clarity', body: 'We name the situation before we propose a service.' },
    { title: 'Technology', body: 'We use our own tools when the property needs them.' },
    { title: 'Strategy', body: 'The order follows the business priority, not a fixed bundle.' },
    { title: 'Support', body: 'We stay close to implement and adjust.' },
    { title: 'Measurement', body: 'What can be observed is used to decide the next step.' },
  ],
  originTitle: 'We started in Colombia, with a Latin American outlook.',
  originBody:
    'Andario Hospitality exists to help small and medium independent accommodations professionalize their digital presence and build their own channels for growth.',
  pioneer: 'BARUCH Hostal — pioneering property of Andario Hospitality.',
  finalTitle: 'Your property can move forward. Let’s start by seeing where you are.',
  finalBody:
    'Tell us how your digital presence works today and what you want to improve. We will help you identify the next step that makes sense for the property.',
  finalPrimary: 'Request a digital diagnosis',
  finalSecondary: 'Talk with Andario',
  finalNote: 'No commitment. We will not sell you solutions you do not need.',
  faqs: [
    {
      q: 'Do I have to contract every solution?',
      a: 'No. You can contract only the ones that match what your property needs now.',
    },
    {
      q: 'Where should I start?',
      a: 'If you are not sure what you need, Digital Check can help you identify priorities.',
    },
    {
      q: 'Can I contract only the Booking Engine?',
      a: 'Yes, depending on the scope and the commercial conditions of the product.',
    },
    {
      q: 'Does Andario replace Booking.com?',
      a: 'No. Andario aims to strengthen your own channels and can coexist with OTAs.',
    },
    {
      q: 'Does Andario guarantee more bookings?',
      a: 'No. It provides strategy, technology and tools to build and improve the digital ecosystem. Results depend on many factors.',
    },
    {
      q: 'Can I start with only a website?',
      a: 'Yes.',
    },
    {
      q: 'Can I add other solutions later?',
      a: 'Yes. The proposal is designed to grow step by step.',
    },
    {
      q: 'Are the solutions connected?',
      a: 'They can form a connected ecosystem, depending on what you contract and which integrations are available.',
    },
    {
      q: 'Do you work with small hostels?',
      a: 'Yes. The focus is precisely small and medium independent accommodations.',
    },
    {
      q: 'How do I begin?',
      a: 'You can request a digital diagnosis or talk with Andario directly.',
    },
  ],
};
