import type { SolutionsHubContent } from '@/content/types';

export const solutionsHubEn: SolutionsHubContent = {
  eyebrow: 'Solutions for independent accommodations',
  h1: 'Digitalize your property, step by step.',
  support:
    'We help you build a professional website, get found on Google, receive direct bookings, communicate better with your guests, and understand what is actually working.',
  assist: "You don't have to do everything at once. We start with what your property actually needs.",
  primaryCta: 'I want to know where to start',
  secondaryCta: 'Talk to Andario',
  micro: 'No commitment. No unnecessary solutions.',
  heroAlt:
    'Visual path for digitalizing a property: website, visibility, guest care, direct bookings and measurement.',
  problemTitle: 'Does any of this sound familiar?',
  problemIntro: 'Not every property needs the same thing. Let’s see what is holding you back today.',
  problems: [
    'I do not have a professional website.',
    'My property does not show up on Google the way I wish it did.',
    'I get many WhatsApp inquiries and I still handle most of the process by hand.',
    'I depend too much on platforms like Booking.com or Airbnb to get bookings.',
    'I have social media, but I am not sure it really helps me get bookings.',
    'I already use several tools, but I cannot tell what is working.',
  ],
  whereTitle: 'Where is your property today?',
  whereIntro: 'Not every property needs the same thing. Choose the situation closest to yours.',
  resultLabel: 'Your next step',
  solutionLabel: 'Digital Check',
  whereAlt: 'A woman at the reception of a small lodging, with the Andario Hospitality name on the wall.',
  scenarios: [
    {
      title: 'I am just starting',
      summary: 'I want to build a professional presence online.',
      result: 'Before adding more tools, we look at where your property is today and what is worth improving first.',
      cta: 'Explore Digital Check',
      placement: 'starting',
      service: 'digital-check',
    },
    {
      title: 'I want people to find me',
      summary: 'I have a presence, but I need to be easier to find.',
      result: 'Before adding more tools, we look at where your property is today and what is worth improving first.',
      cta: 'Explore Digital Check',
      placement: 'visibility',
      service: 'digital-check',
    },
    {
      title: 'I want to take bookings directly',
      summary: 'I want to build my own booking channel.',
      result: 'Before adding more tools, we look at where your property is today and what is worth improving first.',
      cta: 'Explore Digital Check',
      placement: 'bookings',
      service: 'digital-check',
    },
    {
      title: 'I want to spend less time on repetitive tasks',
      summary: 'I get inquiries and I still handle much of the process by hand.',
      result: 'Before adding more tools, we look at where your property is today and what is worth improving first.',
      cta: 'Explore Digital Check',
      placement: 'connect',
      service: 'digital-check',
    },
    {
      title: 'I have tools, but I am not sure how to use them',
      summary: 'I am present on several channels and I need more clarity.',
      result: 'Before adding more tools, we look at where your property is today and what is worth improving first.',
      cta: 'Explore Digital Check',
      placement: 'tools',
      service: 'digital-check',
    },
    {
      title: 'I want to know what works',
      summary: 'I already have an online presence and I want to measure results.',
      result: 'Before adding more tools, we look at where your property is today and what is worth improving first.',
      cta: 'Explore Digital Check',
      placement: 'measure',
      service: 'digital-check',
    },
  ],
  cardsTitle: 'Solutions for every stage of your property',
  cardsSupport: 'Start with one concrete need and add more solutions as your business grows.',
  checkPrompt: 'Not sure where to start?',
  checkNote: 'You do not need to know which solution to contract. First we understand your property.',
  portfolioTitle: 'Solutions for your property',
  portfolioBody: 'You do not have to contract everything. You can start with one solution and add others when they make sense for your business.',
  unsureTitle: 'Not sure which one you need?',
  unsureBody: 'Tell us how your property works today and we will help you see where to start.',
  unsureCta: 'Request a digital diagnosis',
  cards: {
    'digital-check': {
      category: 'A digital diagnosis of your property',
      problem: 'You are not sure what to improve first.',
      body: 'We look at where you are, spot opportunities and decide what is worth improving first.',
      cta: 'Explore Digital Check',
    },
    'andario-web': {
      category: 'Professional website',
      problem: 'You do not have a website that represents the property.',
      body: 'A website that presents your property and makes it easy for visitors to see your spaces, services and ways to get in touch.',
      cta: 'Explore Andario Web',
    },
    'andario-visibility': {
      category: 'Google and visibility',
      problem: 'The property is online, but people cannot always find it.',
      body: 'We work on your property’s presence so it has a better chance of being found when people look for a place like yours.',
      cta: 'Explore Visibility',
    },
    'andario-booking-engine': {
      category: 'Your own booking engine',
      problem: 'Many bookings still depend on manual work or outside platforms.',
      body: 'Lets guests check availability and book directly through a channel you own.',
      cta: 'Explore Booking Engine',
    },
    'andario-connect': {
      category: 'WhatsApp and communication',
      problem: 'You spend too much time answering the same questions.',
      body: 'We help you organize inquiries and conversations with your guests.',
      cta: 'Explore Connect',
    },
    'andario-content': {
      category: 'Photography and content',
      problem: 'The property may be good, but you are not showing everything it offers.',
      body: 'Show your spaces, services and experiences more clearly, so your online presence matches what you actually offer.',
      cta: 'Explore Content',
    },
    'andario-growth': {
      category: 'Measurement and improvement',
      problem: 'You do not know what is working.',
      body: 'See what is working on your digital channels and where you can keep improving.',
      cta: 'Explore Growth',
    },
  },
  ownTech: 'Our own technology',
  paceEyebrow: 'Find your solution',
  paceTitle: 'You do not have to contract everything.',
  paceBody: 'Start with what your property needs today. You can add other solutions later, when they make sense for the business.',
  paths: [
    {
      need: "I'm not sure what my property needs.",
      support: 'I want to understand where I am and decide what is worth improving first.',
      service: 'digital-check',
    },
    {
      need: "I don't have a professional website.",
      support: 'I want to present the property, its services and ways to get in touch.',
      service: 'andario-web',
    },
    {
      need: 'I want to be easier to find on Google.',
      support: 'I want more people to find the property when they look for a place like ours.',
      service: 'andario-visibility',
    },
    {
      need: 'I want to take bookings directly.',
      support: 'I want guests to check availability and book on a channel I own.',
      service: 'andario-booking-engine',
    },
    {
      need: 'I spend too much time answering inquiries.',
      support: 'I want to organize communication with my guests.',
      service: 'andario-connect',
    },
    {
      need: 'I want to show the property more clearly.',
      support: 'I need photos and content that represent the spaces and experiences.',
      service: 'andario-content',
    },
    {
      need: 'I want to know what is working.',
      support: 'I want to measure results and see where I can improve.',
      service: 'andario-growth',
    },
  ],
  paceCloseTitle: 'Not sure where to start?',
  paceCloseBody: 'Tell us how your property works today and we will help you see what is worth improving first.',
  paceCta: 'Request a digital diagnosis',
  trustTitle: 'Why work with Andario?',
  trustSupport: 'We think about your business, not only the technology.',
  pillars: [
    { title: 'Specialization', body: 'We know what independent accommodations need.' },
    { title: 'Simplicity', body: 'You do not need to be a technology expert. We make it understandable and useful for your property.' },
    { title: 'Support', body: 'We do not leave you on your own after a solution is in place.' },
    { title: 'Our own technology', body: 'We build solutions such as Andario Booking Engine to strengthen the channels you own.' },
  ],
  trustNoteTitle: 'Transparency at every step.',
  trustNoteBody: 'We explain what each solution includes and what you can expect from it.',
  finalTitle: 'Not sure where to start?',
  finalBody: 'Tell us how the property works today and what you would like to improve. We help you see the next step.',
  finalPrimary: 'Request a digital diagnosis',
  finalSecondary: 'Talk to Andario',
  finalNote: 'No commitment. No unnecessary solutions.',
  faqs: [
    { q: 'Do I have to contract every solution?', a: 'No. You can contract only what the property needs now.' },
    { q: 'Where should I start?', a: 'If you are not sure, Digital Check helps you see priorities. If you already know the need, you can start with that solution.' },
    { q: 'Can I contract only Booking Engine?', a: 'Yes, depending on the scope and the conditions of the product.' },
    { q: 'Does Andario replace Booking.com?', a: 'No. You can keep using outside platforms and have your own channel at the same time.' },
    { q: 'Can I start with only a website?', a: 'Yes.' },
    { q: 'Can I add other solutions later?', a: 'Yes. The idea is to move forward when the property is ready, not to contract everything on day one.' },
    { q: 'Do you work with small hostels?', a: 'Yes. We work with hostels, small hotels, inns, cabins and other independent properties.' },
    { q: 'Do I need to know about technology?', a: 'No. You know the property. We explain the options and stay with you.' },
    { q: 'Do you guarantee more bookings?', a: 'No. We help you with a clearer presence and a channel you own. Results depend on many factors.' },
    { q: 'How can I begin?', a: 'You can request a diagnosis or write to us on WhatsApp.' },
  ],
};
