import type { FaqItem, VisibilityContent } from '@/content/types';

export const visibilityFaqsEn: FaqItem[] = [
  {
    q: 'What is Andario Visibility?',
    a: 'The SEO, Google and digital visibility service for independent accommodations. It works on the technical base, local presence and content so the property can be understood and found in relevant searches.',
  },
  {
    q: 'Do you guarantee the first place on Google?',
    a: 'No. Nobody can promise a fixed position. Results change and depend on many signals.',
  },
  {
    q: 'What can I expect, then?',
    a: 'Structured work on technical, local, content and measurement matters, according to scope. The aim is a stronger base, not a ranking for sale.',
  },
  {
    q: 'What is the difference between technical SEO and local SEO?',
    a: 'Technical SEO helps the site be discovered and understood. Local SEO connects the property with its place, its information and the searches of people who travel.',
  },
  {
    q: 'Do you work with Google Search Console?',
    a: 'Yes, when it is part of the agreed scope: setup and a reading of what the tool shows about the site.',
  },
  {
    q: 'What is Search Console?',
    a: 'A Google tool for seeing how a site appears in search and for spotting technical issues. It is not a ranking and not a client report.',
  },
  {
    q: 'Do I need a website?',
    a: 'Not in order to talk. A site of your own is often an important base, but it is not required to start the conversation.',
  },
  {
    q: 'Can I contract Visibility if I already have a website?',
    a: 'Yes. The work can sit on a site that already exists.',
  },
  {
    q: 'Can I contract Visibility without Andario Web?',
    a: 'Yes. Services are contracted separately.',
  },
  {
    q: 'How does it relate to Digital Check?',
    a: 'Digital Check diagnoses and orders priorities. Visibility works on the visibility areas that are defined. The diagnosis is not required.',
  },
  {
    q: 'Do you work on the Google business profile?',
    a: 'It can be part of local presence work, according to scope. We do not claim actions that have not been agreed.',
  },
  {
    q: 'Do you create content?',
    a: 'We can identify opportunities and organize useful information. A wider production of copy, photos or video belongs to Andario Content, if you contract it.',
  },
  {
    q: 'Do you work with keywords?',
    a: 'Yes, as part of search intent and content structure. It is not about repeating terms.',
  },
  {
    q: 'How long does it take to improve rankings?',
    a: 'There is no guaranteed timeline. SEO depends on many signals and is observed over time. We do not promise a date or a position.',
  },
  {
    q: 'Does Visibility create bookings?',
    a: 'Not directly. It works on discovery. A booking may continue on the website, WhatsApp or the Booking Engine, and it depends on more than visibility.',
  },
  {
    q: 'Can I keep using Booking.com or Airbnb?',
    a: 'Yes. Visibility does not ask you to leave OTAs.',
  },
  {
    q: 'What do I need to start?',
    a: 'Property details, the website if it exists, digital profiles, location, goals and access to tools when that access is needed.',
  },
  {
    q: 'How do I know what to improve first?',
    a: 'Digital Check can help set priorities. A specific Visibility scope can also be defined without that diagnosis.',
  },
  {
    q: 'Do I need to contract every Andario service?',
    a: 'No.',
  },
  {
    q: 'How do I start?',
    a: 'With a conversation or, if you prefer, with Digital Check. Neither requires you to contract the rest.',
  },
];

export const visibilityEn: VisibilityContent = {
  support:
    'A professional digital presence still needs visibility. We work on technical SEO, local SEO, structure, content and search opportunities so your property is easier to understand and can be found by people looking for what you offer.',
  audienceLine: 'No promised rankings. A measurable digital strategy.',
  primaryCta: 'Improve my visibility',
  problemCta: 'I want to improve my visibility',
  talkCta: 'Talk with Andario',
  reviewCta: 'Review my digital presence',
  infoCta: 'Request information',
  whatsappCta: 'Write on WhatsApp',
  scopeLabel: 'Scope is defined by the property’s situation.',
  exampleLabel: 'Conceptual example. Not a real case and not a search volume.',
  heroCaption:
    'A person searches for a kind of stay. Google shows pieces of information. The property can offer a next step. This is not a real result.',
  heroQuery: 'hostel in a destination',
  problems: [
    { title: 'Information that is hard to find', body: 'Someone searching does not quickly reach a clear explanation.' },
    { title: 'A website without structure', body: 'The content exists, but it is hard to understand.' },
    { title: 'A weak local presence', body: 'The place and the property details are incomplete or poorly connected.' },
    { title: 'Content without a clear question', body: 'Things are published without answering what someone needs to know.' },
    { title: 'Inconsistent information', body: 'The website, profiles and other platforms do not say the same thing.' },
    { title: 'Nothing to measure', body: 'Without data it is harder to see what happens after someone finds the property.' },
  ],
  systemTitle: 'Digital visibility is a system, not a button.',
  systemParts: ['Structure', 'Content', 'Local context', 'Relevance', 'Experience', 'Measurement'],
  systemEquals: 'A visibility base',
  systemNote: 'No single piece guarantees a ranking. We work on the set.',
  chain: ['Be found', 'Be relevant', 'Be understandable', 'Be useful', 'Make the next step easier'],
  whatTitle: 'What is Andario Visibility?',
  whatBody:
    'Andario Hospitality’s SEO, Google and digital visibility service. We work on technical structure, local presence, property information and content opportunities so search engines can understand the property and people can find useful information.',
  whatNote: 'We do not promise a specific position on Google. We build a solid, measurable digital base.',
  technicalTitle: 'First, we make the site technically understandable.',
  technicalBody: 'A search engine needs to discover, crawl and understand the content. That does not guarantee a rank.',
  technicalDo: ['Architecture', 'Headings', 'Metadata', 'URLs', 'Sitemap', 'Canonical', 'Indexing', 'Internal links', 'Performance', 'Structured data when it helps'],
  technicalWhy: 'Without that base, useful content can exist and still be hard for a search engine to read.',
  localTitle: 'Your property is not “on the internet”. It is in a real place.',
  localBody:
    'People looking for a stay often combine destination, area, property type, services and what they want to do. Local SEO strengthens the link between the property, its place and useful information.',
  localSteps: ['Someone searches for a place', 'Location comes into view', 'The property is recognized', 'Local information is there', 'They can continue toward contact'],
  localNote: 'We do not guarantee map placement or the first results.',
  googleTitle: 'Google needs to understand who you are, where you are and what you offer.',
  googleBody:
    'Search engines use many signals. Results change, competition changes and the searcher’s intent matters. The technical work is a base, not control over Google.',
  googleParts: [
    { title: 'Who', body: 'The property and its information.' },
    { title: 'Where', body: 'The place and consistent details.' },
    { title: 'What you offer', body: 'Services, units and useful content.' },
  ],
  googleNote: 'This is not Google’s full algorithm.',
  consoleTitle: 'Search Console helps you observe. It does not promise.',
  consoleBody:
    'It is a Google tool for seeing how the site appears in search and for spotting indexing or technical issues, when access is part of the scope.',
  consoleRows: ['Queries', 'Impressions', 'Clicks', 'Pages', 'Technical notices', 'Opportunities'],
  contentTitle: 'The point is not to publish more. It is to answer better.',
  contentBody:
    'Useful content answers real questions: where it is, what it offers, how to arrive, what kind of stay it is, which services it has and what to know before writing or booking.',
  contentSteps: ['Search', 'Intent', 'Question', 'Useful content', 'Trust', 'Next step'],
  intentTitle: 'Intent matters more than repeating a word.',
  intentIntro: 'These phrases show kinds of need. They are not volumes and not a property’s results.',
  intents: [
    { query: 'hostel in a destination', intent: 'Find a place to stay.' },
    { query: 'what to do in the destination', intent: 'Discover the place.' },
    { query: 'hostel near…', intent: 'Locate the property.' },
    { query: 'hostel rooms', intent: 'Compare options.' },
  ],
  intentNote: 'We do not state how many people search for each phrase.',
  destinationTitle: 'The destination is part of visibility too.',
  destinationBody:
    'Context can include the place, how to arrive, the surroundings and experiences, when that information exists and is in scope. Andario Content can extend the production.',
  destinationPoints: ['Destination', 'Location', 'How to arrive', 'Surroundings', 'Experiences', 'Useful information'],
  ecosystemCaption: 'Technical work, local presence and content meet in useful information. No piece promises a ranking.',
  ecosystemColumns: [
    { title: 'Technical', points: ['Indexing', 'Structure', 'Sitemap'] },
    { title: 'Local', points: ['Place', 'Google', 'Consistent details'] },
    { title: 'Content', points: ['Intent', 'Questions', 'Usefulness'] },
  ],
  discoveryTitle: 'Being found is the start. The experience continues on the site.',
  discoverySteps: ['Search', 'Discovery', 'Website', 'Information', 'Trust', 'WhatsApp or booking', 'Booking Engine'],
  discoveryNote:
    'Visibility works on discovery. The website presents. Connect can organize the conversation. The engine manages the booking. Not every search becomes a reservation.',
  includesTitle: 'What it can include',
  includesIntro: 'Each piece is agreed. Not every project includes every activity.',
  whatLabel: 'What we do',
  purposeLabel: 'What it is for',
  groups: [
    { title: 'Technical and on-page SEO', what: 'Structure, headings, metadata and technical foundations.', purpose: 'Help the site be discovered and understood.' },
    { title: 'Local SEO', what: 'Location, context and the property’s presence.', purpose: 'Connect the accommodation with the place it is in.' },
    { title: 'Search Console', what: 'Setup and reading, according to access and scope.', purpose: 'Observe search appearance and technical notices.' },
    { title: 'Sitemap', what: 'A map of the site’s addresses.', purpose: 'Make pages easier to discover.' },
    { title: 'Structured data', what: 'Markup when it helps and fits.', purpose: 'Describe the property more explicitly.' },
    { title: 'Internal links', what: 'Connections between related content.', purpose: 'Let information be followed with sense.' },
    { title: 'Google presence', what: 'A review of the public information available.', purpose: 'Reduce incomplete or conflicting details.' },
    { title: 'Content and destination', what: 'Opportunities for useful information about the property and its context.', purpose: 'Answer real questions, not fill pages.' },
    { title: 'Search intent', what: 'Questions and needs the content can address.', purpose: 'Decide what deserves an answer.' },
  ],
  matrixTitle: 'Visibility joins several dimensions.',
  matrixCenter: 'Visibility',
  matrixPoints: ['People', 'Useful content', 'Technical work', 'Local context', 'Measurement'],
  matrixNote: 'The diagram shows relationships. It is not a score.',
  processTitle: 'From understanding the problem to building a base.',
  process: [
    { title: 'Review', body: 'Presence, site, Google, structure and opportunities.' },
    { title: 'Prioritize', body: 'Which actions make sense for this property.' },
    { title: 'Optimize', body: 'We implement the improvements that were agreed.' },
    { title: 'Measure', body: 'We look at the signals and data that are available.' },
    { title: 'Evolve', body: 'We adjust from what is learned. It is not a closed ranking.' },
  ],
  receiveTitle: 'What the property can receive',
  receive: [
    'A reading of the situation',
    'Prioritized opportunities',
    'Agreed technical improvements',
    'A clearer structure',
    'Content recommendations',
    'Local presence work',
    'Search Console, if it is in scope',
    'A sitemap and structured data when they fit',
    'A base for measurement',
  ],
  receiveNote: 'The deliverable depends on the defined scope. It does not include a Google position.',
  structureTitle: 'A conceptual example of structure',
  structureBefore: ['Home', 'Rooms', 'Contact', 'A generic paragraph'],
  structureAfter: ['Where we are', 'How to arrive', 'Rooms', 'Services', 'Experiences', 'Questions', 'Contact', 'Book'],
  finding: [
    { label: 'Finding', value: 'The location is hard to understand.' },
    { label: 'Opportunity', value: 'Strengthen the local context.' },
    { label: 'Action', value: 'Improve content and structure.' },
    { label: 'Measurement', value: 'Watch behavior and search, without promising a rank.' },
  ],
  webTitle: 'Visibility leans on a digital home.',
  webBody: 'Andario Web organizes the information. Visibility works to strengthen the chance of finding it. One does not replace the other.',
  webNote: 'An Andario website is not required in order to talk about visibility.',
  checkTitle: 'Before optimizing, it helps to know where you are.',
  checkBody: 'Digital Check can show what deserves attention first. Visibility then works on the visibility areas that are defined.',
  checkNote: 'The diagnosis is not a required step.',
  bookingTitle: 'Finding a guest is only part of the journey.',
  bookingBody: 'Visibility does not check availability or create bookings. That lives in Andario Booking Engine, if the property uses it.',
  growthTitle: 'Visibility also needs measurement.',
  growthBody: 'Visibility leaves work and signals. Andario Growth can extend the reading later. We do not promise complete attribution.',
  whoTitle: 'For properties that do not want to rely only on people who already know them.',
  whoTypes: ['Hostels', 'Small hotels', 'Inns', 'Holiday apartments', 'Aparthotels', 'Cabins', 'Villas', 'Rural stays', 'Other independent accommodations'],
  whoFit: ['There is a website, but the offer is hard to grasp.', 'The presence is scattered.', 'The SEO base is thin.', 'Local information is incomplete.', 'They want a direct channel.', 'They want to measure more clearly.'],
  whenTitle: 'When it tends to make sense',
  when: [
    'The website does not clearly explain what you offer.',
    'The local presence is incomplete.',
    'Content does not answer real questions.',
    'You do not know what potential guests search for.',
    'You do not know how the property appears on Google.',
    'You want an SEO base.',
    'You want to connect visibility, the website and booking.',
  ],
  notTitle: 'What Andario Visibility is not',
  not: [
    { title: 'Not a first-place guarantee', body: 'Google decides with many signals, and results change.' },
    { title: 'Not a ranking you can buy', body: 'We do not sell a position on Google.' },
    { title: 'Not publishing without a reason', body: 'Content has to answer a need.' },
    { title: 'Not only keywords', body: 'There is also structure, technique, place, content and experience.' },
    { title: 'Not an ads campaign', body: 'This is organic visibility. Paid advertising is different, and the two can coexist.' },
    { title: 'Not a booking guarantee', body: 'It can help discovery. A booking depends on more factors.' },
    { title: 'Not always a one-time job', body: 'Watching, measuring and adjusting can continue with the goals.' },
  ],
  adsTitle: 'Organic visibility and advertising are not the same.',
  adsIntro: 'They can coexist. Andario Visibility is not an advertising service.',
  organicTitle: 'Organic visibility',
  organicPoints: ['SEO', 'Structural work', 'Content', 'Results that are not guaranteed', 'Progressive building'],
  paidTitle: 'Advertising',
  paidPoints: ['Ads', 'Ad spend', 'Campaigns', 'Visibility tied to budget', 'Campaigns that can be switched on'],
  adsNote: 'We do not say one is better. We explain that they are different paths.',
  pioneerTitle: 'BARUCH Hostal',
  pioneerBody: 'BARUCH Hostal is the pioneer property of Andario Hospitality. We do not publish traffic, rankings or bookings from its presence.',
  finalTitle: 'Make your digital presence easier to find and understand.',
  finalBody: 'Tell us how the property appears online today and what you want to improve. We can help you see opportunities and decide where to start.',
  finalNote: 'No promised rankings. A clear, measurable strategy.',
};
